project:
  type: book
  output-dir: _book

  resources: 
    - "images/"
    - "practice_datasets/"
    - "custom_functions/"
  
book:
  title: "PSYC 7014: Graduate Statistics 1"
  reader-mode: true

  page-footer: 
    left: |
      Written by <a href="https://tehrandav.is">Tehran Davis</a> of PSYC 7014.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: "images/cover.png"
  favicon: "images/favicon.png"
  site-url: https://tehrandav.is/
  chapters:
    - index.qmd

    - part: "Part 1: INTRO to R"
      chapters:
        - week00/0_1-getting_started.qmd
        - week00/0_2-resources.qmd
        - week01/1_1-Rmarkdown_basics.qmd
        - week01/1_2-objects_assignment_functions.qmd
        - week01/1_3-install_packages.qmd
        - week01/1_4-loading_data.qmd
        - week01/1_5-leveling-up.qmd
    
    - part: "Part 2: DESCRIBING & VISUALIZING DATA"
      chapters:
        - week02/2_1-structure_data.qmd
        - week02/2_2-central_tendency.qmd
        - week02/2_3-summary_tables.qmd
        - week03/3_1-basic_ggplot.qmd
        - week03/3_2-more_adv_ggplot.qmd
        - week02/2_4-means_other_models.qmd

    - part: "Part 3: DISTRIBUTIONS and NHST"
      chapters:
        - week04/4_1-the_normal_distribution.qmd
        - week04/4_2-building_intuitions_about_probability_and_nhst.qmd
        - week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.qmd
        - week04/4_4-more_examples.qmd
        - week04/4_5-bias_variance.qmd

    - part: "Part 4: MODELING w/ CONTINUOUS PREDICTORS"
      chapters: 
        - week05/5_2_correlations.qmd
        - week05/5_3_regressions.qmd
        - week05/5_4_plotting.qmd
        - week05/5_5_diagnostics.qmd
        - week05/5_6_example_report.qmd

    - part: "Part 5: T-TESTS"
      chapters: 
        - week06/6_1_t-test.qmd
        - week06/6_2_t-test-null-model.qmd
        - week06/6_3_t-test-lm.qmd

    - part: "Part 6: Power & Effect Size"
      chapters: 
        - week07/7_1-effect_size.qmd
        - week07/7_2-power.qmd
        - week07/7_3-power_es_sig_tests.qmd
        - week07/7_4-simulating_power.qmd
    
    - part: "Part 7: One-way ANOVA"
      chapters: 
        - week08/8_1-one-way-anova.qmd
        - week08/8_2-anova-regression.qmd
        - week09/9_1-posthocs.qmd
        - week09/9_2-planned_contrasts.qmd
      
    - part: "Part 8: Factorial ANOVA"
      chapters: 
        - week10/10_1-main_effects.qmd
        - week10/10_2-factorial_w_post_hocs.qmd
        - week10/10_3-advanced_example_and_apa.qmd
    
    - part: "Part 9: Repeated Measures ANOVA"
      chapters: 
        - week12/12_1-afex_ANOVA.qmd
        - week12/12_2-repeated_measures_anova.qmd       
        - week12/12_3-factorial_rma.qmd       
        - week12/12_4-sphericity.qmd       
        - week12/12_5-spss_rma.qmd

    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-overflow: wrap
    code-line-numbers: false
    code-link: true
    code-tools: 
      source: true
      toggle: false

    author-meta: "Tehran Davis"
    callout-appearance: simple


editor: visual


            
    