<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>tehrandav.is - Factorial ANOVA - Post hoc analysis of Main effects</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating nav-fixed">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">tehrandav.is</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="https://tehrandav.is">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Factorial ANOVA - Post hoc analysis of Main effects</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../walkthroughs.html" class="sidebar-item-text sidebar-link">PSYC 7014</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">TOPIC 1 INTRO to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_1-Rmarkdown_basics.html" class="sidebar-item-text sidebar-link">Rmarkdown Basics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_2-objects_assignment_functions.html" class="sidebar-item-text sidebar-link">Objects, assignment, and functions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_3-install_packages.html" class="sidebar-item-text sidebar-link">Installing and loading an <code>R</code> package</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_4-loading_data.html" class="sidebar-item-text sidebar-link">Loading in Data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_5-leveling-up.html" class="sidebar-item-text sidebar-link">Leveling-up</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">TOPIC 2: DESCRIPTIVE STATS and CENTRAL TENDENCY</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_1-structure_data.html" class="sidebar-item-text sidebar-link">The structure of your data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_2-central_tendency.html" class="sidebar-item-text sidebar-link">Measures of central tendency</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_3-summary_tables.html" class="sidebar-item-text sidebar-link">Creating summary tables</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_4-means_other_models.html" class="sidebar-item-text sidebar-link">Means and other models</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">TOPIC 3: DATA VISUALIZATION</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_1-basic_ggplot.html" class="sidebar-item-text sidebar-link">Basic ggplotting</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_2-more_adv_ggplot.html" class="sidebar-item-text sidebar-link">More advanced ggPlots</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">TOPIC 4: DISTRIBUTIONS and NHST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link">The normal distribution</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_2-building_intuitions_about_probability_and_nhst.html" class="sidebar-item-text sidebar-link">Building intuitions about probability and NHST</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.html" class="sidebar-item-text sidebar-link">Sampling distributions and seeing the logic of NHST</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_4-more_examples.html" class="sidebar-item-text sidebar-link">More examples of distributions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_5-bias_variance.html" class="sidebar-item-text sidebar-link">Bias in sample variance estimates</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">TOPIC 5: CORRELATION AND REGRESSION</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link">The normal distribution</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_2_correlations.html" class="sidebar-item-text sidebar-link">Correlations</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_3_regressions.html" class="sidebar-item-text sidebar-link">Regression, pt.&nbsp;1: Running the model</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_4_plotting.html" class="sidebar-item-text sidebar-link">Plotting regression data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_5_diagnostics.html" class="sidebar-item-text sidebar-link">Regression model diagnostics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_6_example_report.html" class="sidebar-item-text sidebar-link">Example Report</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">TOPIC 6: T-TESTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_1_t-test.html" class="sidebar-item-text sidebar-link">Testing differences in means / t-test</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_2_t-test-null-model.html" class="sidebar-item-text sidebar-link">Thinking about nothing (aka the null)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_3_t-test-lm.html" class="sidebar-item-text sidebar-link">t-test? It’s just a linear model</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">TOPIC 7: POWER &amp; EFFECT SIZES</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_1-effect_size.html" class="sidebar-item-text sidebar-link">Effect Size</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_2-power.html" class="sidebar-item-text sidebar-link">Power</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_3-power_es_sig_tests.html" class="sidebar-item-text sidebar-link">Power, Effect sizes, and Significance testing</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_4-simulating_power.html" class="sidebar-item-text sidebar-link">Simulating Power!!!</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">TOPIC 8: INTRO to ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_1-one-way-anova.html" class="sidebar-item-text sidebar-link">The One-way ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_2-anova-regression.html" class="sidebar-item-text sidebar-link">ANOVA and Regression</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">TOPIC 9: ANOVA: CONTRASTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_1-posthocs.html" class="sidebar-item-text sidebar-link">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_2-planned_contrasts.html" class="sidebar-item-text sidebar-link">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">TOPIC 10: ANOVA: FACTORIAL ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_1-main_effects.html" class="sidebar-item-text sidebar-link">Factorial ANOVA - The omnibus ANOVA and Main effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_2-factorial_w_post_hocs.html" class="sidebar-item-text sidebar-link active">Factorial ANOVA - Post hoc analysis of Main effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_3-advanced_example_and_apa.html" class="sidebar-item-text sidebar-link">Template for Analysis &amp; APA Style</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">TOPIC 11: ANOVA + INTERACTIONS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week11/11_1-interactions.html" class="sidebar-item-text sidebar-link">Analysis of Variance: the Factorial ANOVA - Interactions &amp; Simple Effects ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week11/11_2-higher_order_anova.html" class="sidebar-item-text sidebar-link">Dealing with Higher Order Factorial ANOVA</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">TOPIC 12: WITHIN SUBJECTS / REPEATED MEASURES ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_1-afex_ANOVA.html" class="sidebar-item-text sidebar-link">afex is for ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_2-repeated_measures_anova.html" class="sidebar-item-text sidebar-link">Within Subjects / Repeated Measures ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_3-factorial_rma.html" class="sidebar-item-text sidebar-link">Factorial RM-ANOVA and simple effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_4-sphericity.html" class="sidebar-item-text sidebar-link">Sphericity: Variances and Co-Variances</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_5-spss_rma.html" class="sidebar-item-text sidebar-link">Running a RM-ANOVA in SPSS</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">TOPIC 13: MIXED ANOVA (BS + WS)</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week13/13_1-mixed_effects_anova.html" class="sidebar-item-text sidebar-link">Mixed-effects ANOVA (BS + WS)</a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#example-a-2-3-anova" id="toc-example-a-2-3-anova" class="nav-link active" data-scroll-target="#example-a-2-3-anova">Example: A 2 × 3 ANOVA</a>
  <ul class="collapse">
<li><a href="#building-the-anova-model" id="toc-building-the-anova-model" class="nav-link" data-scroll-target="#building-the-anova-model">Building the ANOVA model</a></li>
  <li><a href="#testing-assumptions" id="toc-testing-assumptions" class="nav-link" data-scroll-target="#testing-assumptions">Testing assumptions</a></li>
  <li><a href="#visual" id="toc-visual" class="nav-link" data-scroll-target="#visual">visual</a></li>
  <li><a href="#interaction-plot" id="toc-interaction-plot" class="nav-link" data-scroll-target="#interaction-plot">Interaction plot</a></li>
  <li><a href="#testing-the-anova" id="toc-testing-the-anova" class="nav-link" data-scroll-target="#testing-the-anova">Testing the ANOVA</a></li>
  </ul>
</li>
  <li><a href="#post-hoc-analysis" id="toc-post-hoc-analysis" class="nav-link" data-scroll-target="#post-hoc-analysis">post hoc analysis</a></li>
  <li><a href="#what-about-planned-contrasts" id="toc-what-about-planned-contrasts" class="nav-link" data-scroll-target="#what-about-planned-contrasts">What about planned contrasts?</a></li>
  <li>
<a href="#more-examples-a-3-3-anova" id="toc-more-examples-a-3-3-anova" class="nav-link" data-scroll-target="#more-examples-a-3-3-anova">More examples: a 3 × 3 ANOVA</a>
  <ul class="collapse">
<li><a href="#interaction-plot-1" id="toc-interaction-plot-1" class="nav-link" data-scroll-target="#interaction-plot-1">Interaction plot</a></li>
  <li><a href="#anova-model" id="toc-anova-model" class="nav-link" data-scroll-target="#anova-model">ANOVA model</a></li>
  </ul>
</li>
  <li>
<a href="#post-hoc-analysis-1" id="toc-post-hoc-analysis-1" class="nav-link" data-scroll-target="#post-hoc-analysis-1">Post-hoc analysis</a>
  <ul class="collapse">
<li><a href="#task" id="toc-task" class="nav-link" data-scroll-target="#task">Task</a></li>
  <li><a href="#smkgrp" id="toc-smkgrp" class="nav-link" data-scroll-target="#smkgrp">Smkgrp</a></li>
  </ul>
</li>
  <li><a href="#example-write-up" id="toc-example-write-up" class="nav-link" data-scroll-target="#example-write-up">Example write up</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">Factorial ANOVA - Post hoc analysis of Main effects</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>In the last walkthrough, analyzed a 2×2 ANOVA focusing on our main effects. Because each of our factors only had two levels, there was no need to follow up on significant main effects with pairwise post hoc analysis. In this walkthough we will take a look at examples where our main effects have 3 or more levels, and demand a post-hoc analysis. For now, let’s try another example. First let’s bring in the necessary packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(psych, tidyverse, cowplot, emmeans, ez)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="example-a-2-3-anova" class="level2"><h2 class="anchored" data-anchor-id="example-a-2-3-anova">Example: A 2 × 3 ANOVA</h2>
<p>Thirty-six college students were randomly assigned to 3 groups (N=12). Students in each group were asked to watch and take notes on a 50 min lecture. One week later all students were tested on the content of their lectures, and their <code>scores</code> were compared. Groups differed by the lecture’s subject matter, where:</p>
<ul>
<li>
<strong>1</strong> = Physics lecture</li>
<li>
<strong>2</strong> = Social Science lecture</li>
<li>
<strong>3</strong> = History lecture</li>
</ul>
<p>The lectures were presented in two manners</p>
<ul>
<li><p><strong>1 =</strong> via computer</p></li>
<li><p><strong>2</strong> = standard method, lecturer in a lecture hall</p></li>
</ul>
<p>The researchers hypothesized that students that learned the material in the standard lecture would perform better than those that learned via computer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>dataset_no_inter <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/tehrandavis/graduate_statistics/main/practice_datasets/factorial_ANOVA_dataset_no_interactions.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 36 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Lecture, Presentation
dbl (2): Score, PartID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>dataset_no_inter<span class="sc">$</span>Lecture <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset_no_inter<span class="sc">$</span>Lecture, <span class="st">"1"</span><span class="ot">=</span><span class="st">"Phys"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"Soc"</span>,<span class="st">"3"</span><span class="ot">=</span><span class="st">"Hist"</span>)</span>
<span id="cb4-2"><a href="#cb4-2"></a></span>
<span id="cb4-3"><a href="#cb4-3"></a>dataset_no_inter<span class="sc">$</span>Presentation <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset_no_inter<span class="sc">$</span>Presentation, <span class="st">"1"</span><span class="ot">=</span><span class="st">"Comp"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"Stand"</span>)</span>
<span id="cb4-4"><a href="#cb4-4"></a></span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="fu">summary</span>(dataset_no_inter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Lecture   Presentation     Score           PartID     
 Phys:12   Comp :18     Min.   :18.00   Min.   : 1.00  
 Soc :12   Stand:18     1st Qu.:26.75   1st Qu.: 9.75  
 Hist:12                Median :35.50   Median :18.50  
                        Mean   :35.44   Mean   :18.50  
                        3rd Qu.:42.50   3rd Qu.:27.25  
                        Max.   :53.00   Max.   :36.00  </code></pre>
</div>
</div>
<section id="building-the-anova-model" class="level3"><h3 class="anchored" data-anchor-id="building-the-anova-model">Building the ANOVA model</h3>
<p>I’m going to use <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>aov_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score<span class="sc">~</span>Presentation <span class="sc">+</span> Lecture, <span class="at">data =</span> dataset_no_inter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="testing-assumptions" class="level3"><h3 class="anchored" data-anchor-id="testing-assumptions">Testing assumptions</h3>
</section><section id="visual" class="level3"><h3 class="anchored" data-anchor-id="visual">visual</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_model</span>(<span class="at">panel=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_normality</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.887).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_homogeneity</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Variances differ between groups (Bartlett Test, p = 0.040).</code></pre>
</div>
</div>
<p>The model checks both for normality of residuals but fails homogeneity of variance. Following upon given the robustness of ANOVA (3x rule):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>dataset_no_inter <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="fu">group_by</span>(Lecture, Presentation) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Score),</span>
<span id="cb12-4"><a href="#cb12-4"></a>            <span class="at">var =</span> <span class="fu">var</span>(Score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Lecture'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
# Groups:   Lecture [3]
  Lecture Presentation  mean    var
  &lt;fct&gt;   &lt;fct&gt;        &lt;dbl&gt;  &lt;dbl&gt;
1 Phys    Comp          46    48.8 
2 Phys    Stand         34   121.  
3 Soc     Comp          40    23.2 
4 Soc     Stand         23.7   7.47
5 Hist    Comp          38    19.2 
6 Hist    Stand         31   106.  </code></pre>
</div>
</div>
<p>Potential issues, but moving on.</p>
</section><section id="interaction-plot" class="level3"><h3 class="anchored" data-anchor-id="interaction-plot">Interaction plot</h3>
<p>Let’s plot the data. You’ll note in this plot I’m adding some code to get it into better APA shape. More on this in the next walkthrough. For now just focus on content.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># setting original parameters</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>p <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> dataset_no_inter, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Lecture,<span class="at">y=</span>Score,<span class="at">group=</span>Presentation))</span>
<span id="cb15-3"><a href="#cb15-3"></a></span>
<span id="cb15-4"><a href="#cb15-4"></a><span class="co"># making a basic line plot</span></span>
<span id="cb15-5"><a href="#cb15-5"></a>line_p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>,<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">size=</span><span class="fl">0.75</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">25</span>), <span class="fu">aes</span>(<span class="at">shape=</span>Presentation)) <span class="sc">+</span> </span>
<span id="cb15-6"><a href="#cb15-6"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">25</span>), <span class="fu">aes</span>(<span class="at">linetype=</span>Presentation))</span>
<span id="cb15-7"><a href="#cb15-7"></a></span>
<span id="cb15-8"><a href="#cb15-8"></a><span class="co"># adding APA elements</span></span>
<span id="cb15-9"><a href="#cb15-9"></a>line_p <span class="ot">&lt;-</span> line_p <span class="sc">+</span> <span class="fu">theme</span>(</span>
<span id="cb15-10"><a href="#cb15-10"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">lineheight =</span> .<span class="dv">55</span>),</span>
<span id="cb15-11"><a href="#cb15-11"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb15-12"><a href="#cb15-12"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb15-13"><a href="#cb15-13"></a>    <span class="at">legend.position =</span> <span class="fu">c</span>(.<span class="dv">75</span>,.<span class="dv">9</span>)) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14"></a>  <span class="fu">xlab</span>(<span class="st">"Lecture type"</span>) <span class="sc">+</span> </span>
<span id="cb15-15"><a href="#cb15-15"></a>  <span class="fu">ylab</span> (<span class="st">"Performance score"</span>) <span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16"></a>  <span class="fu">theme</span>(<span class="at">plot.margin=</span><span class="fu">unit</span>(<span class="fu">c</span>(.<span class="dv">25</span>,.<span class="dv">25</span>,.<span class="dv">25</span>,.<span class="dv">25</span>),<span class="st">"in"</span>)) <span class="sc">+</span> </span>
<span id="cb15-17"><a href="#cb15-17"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb15-18"><a href="#cb15-18"></a></span>
<span id="cb15-19"><a href="#cb15-19"></a><span class="fu">show</span>(line_p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="10_2-factorial_w_post_hocs_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="testing-the-anova" class="level3"><h3 class="anchored" data-anchor-id="testing-the-anova">Testing the ANOVA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>aov_model <span class="sc">%&gt;%</span> sjstats<span class="sc">::</span><span class="fu">anova_stats</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="fu">select</span>(<span class="st">"term"</span>,<span class="st">"df"</span>,<span class="st">"statistic"</span>,<span class="st">"p.value"</span>,<span class="st">"partial.etasq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>term         | df | statistic | p.value | partial.etasq
-------------------------------------------------------
Presentation |  1 |    22.670 |  &lt; .001 |         0.415
Lecture      |  2 |     3.779 |   0.034 |         0.191
Residuals    | 32 |           |         |              </code></pre>
</div>
</div>
</section></section><section id="post-hoc-analysis" class="level2"><h2 class="anchored" data-anchor-id="post-hoc-analysis">post hoc analysis</h2>
<p>Admittedly, moving on to this step will ultimately be qualified by the presence of interactions (next week). For now, note that if you don’t have an interaction, you may simply proceed to run post-hoc analyses on any significant main effects in the manner you would with a One-way ANOVA. Easy, peasy, right. One thing to note, you need to make the appropriate multiple comparison corrections. For example, returning to our data with no interaction, we need to test for differences in both the <code>Lecture</code> and <code>Presentation</code> main effects.</p>
<ul>
<li><p>Presentation: This one is easy. We only have two levels of <code>Presentation</code>, so the omnibus <span class="math inline">\(F\)</span> test tells us that our two groups are different. Nothing else to do here other than note which mean (Computer v. Standard) is greater than the other.</p></li>
<li><p>Lecture: We have three levels of lecture, so were are going to need to run a post-hoc analysis. In this case, we may call upon our old standbys, Tukey and Bonferroni.</p></li>
</ul>
<p><strong>Just as last week, we can use <code>emmeans()</code> to run our post-hoc tests.</strong></p>
<p>For example, to run a Tukey, you need call your ANOVA model. For the sake of clarity let’s rebuild the ANOVA model and save it to <code>aov_model</code> and then run <code>emmeans()</code></p>
<p>Here I’m saving it to the object <code>aov_model</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>aov_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score<span class="sc">~</span>Presentation <span class="sc">+</span> Lecture, <span class="at">data =</span> dataset_no_inter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From here you may call upon the <code>emmeans()</code> function to derive your posthocs. By itself, <code>emmeans</code> produces the means by levels of the IV(s) listed in its <code>spec=</code> argument. It takes the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> model as a first argument, and the IVs of interest as the second.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># input your model into the emmeans,</span></span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="co"># interested in Lecture</span></span>
<span id="cb19-3"><a href="#cb19-3"></a></span>
<span id="cb19-4"><a href="#cb19-4"></a><span class="fu">emmeans</span>(aov_model,<span class="at">specs =</span> <span class="sc">~</span>Lecture)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Lecture emmean   SE df lower.CL upper.CL
 Phys      40.0 2.14 32     35.6     44.4
 Soc       31.8 2.14 32     27.5     36.2
 Hist      34.5 2.14 32     30.1     38.9

Results are averaged over the levels of: Presentation 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<p><code>emmeans()</code> alone gives us the estimated marginal means for each of our levels, to run a post-hoc comparison we then pipe it into <code><a href="https://rdrr.io/r/graphics/pairs.html">pairs()</a></code> and include the <code>p value</code> adjustment that we would like to make. allows another method for making contrasts (planned and posthoc). If you want to perform a Tukey test follow this procedure you can simply pipe the previous (or save to an object and submit) to <code><a href="https://rdrr.io/r/graphics/pairs.html">pairs()</a></code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">emmeans</span>(aov_model,<span class="at">specs =</span> <span class="sc">~</span>Lecture) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"tukey"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    estimate   SE df t.ratio p.value
 Phys - Soc      8.17 3.03 32   2.696  0.0291
 Phys - Hist     5.50 3.03 32   1.815  0.1807
 Soc - Hist     -2.67 3.03 32  -0.880  0.6565

Results are averaged over the levels of: Presentation 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>In this case it appears that our Tukey does reveal differences between means, when performance of those getting Physical Science Lectures is greater than both History and Social, but Social and History are not difference from one another.</p>
<p>Note that you may call other p-value adjustments using these methods:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">emmeans</span>(aov_model,<span class="at">specs =</span> <span class="sc">~</span>Lecture) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    estimate   SE df t.ratio p.value
 Phys - Soc      8.17 3.03 32   2.696  0.0333
 Phys - Hist     5.50 3.03 32   1.815  0.2365
 Soc - Hist     -2.67 3.03 32  -0.880  1.0000

Results are averaged over the levels of: Presentation 
P value adjustment: bonferroni method for 3 tests </code></pre>
</div>
</div>
</section><section id="what-about-planned-contrasts" class="level2"><h2 class="anchored" data-anchor-id="what-about-planned-contrasts">What about planned contrasts?</h2>
<p>You need to be careful when running planned contrasts in factorial ANOVA. In general I would recommend only running planned contrasts on a single main effect, or a planned contrast on the effects of one of your factors at a single level of your other (though you still need to proceed with caution here).</p>
<p>For example, using the data from the last section, I would only run a planned contrast related to the main effect of <code>Lecture Type</code>, or a contrast of <code>Lecture Type</code> means only in <code>Computer presentation</code> conditions (or <code>Standard presentation</code>). DO NOT, I repeat DO NOT run contrasts that go across levels of your other factors. Well, truthfully, you can do whatever you want, but you may find that your ability to meaningfully interpret your results in such cases is extremely limited.</p>
<p>We can run planned contrasts using <code>emmeans()</code> as well. In this case, we need to specify the contrasts.</p>
<p>First we need to obtain the <code>emmeans()</code> of the model including all cells (all factors). Using <code>aov.model</code> from the previous example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture<span class="sc">+</span>Presentation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Lecture Presentation emmean   SE df lower.CL upper.CL
 Phys    Comp           45.9 2.47 32     40.9     50.9
 Soc     Comp           37.7 2.47 32     32.7     42.8
 Hist    Comp           40.4 2.47 32     35.4     45.4
 Phys    Stand          34.1 2.47 32     29.1     39.1
 Soc     Stand          25.9 2.47 32     20.9     31.0
 Hist    Stand          28.6 2.47 32     23.6     33.6

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>OK. From here let’s build two custom contrasts. First, let’s do the <code>Lecture</code> contrast on the main effect. In this case let’s assume I want to contrast <code>Phys</code> with the combined other two conditions. Using the output above, I identify which rows contain <code>Phys</code> and I ensure that the summation of those rows is 1. In this case there are two rows, the first and the fourth, and each gets <code>0.5</code>. My remaining conditions must also equal <code>-1</code>. In this case there are four, so each is <code>-0.25</code>. Following the output above, then my contrast matrix is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>lecture_contrast <span class="ot">&lt;-</span> <span class="fu">list</span>( <span class="st">"Phys v. Soc + Hist"</span> <span class="ot">=</span> <span class="fu">c</span>(.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>,.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From here I simply call <code>contrast()</code> with my contrast matrix as an argument. So the entire pipe goes from:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(lecture_contrast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE df t.ratio p.value
 Phys v. Soc + Hist     6.83 2.62 32   2.604  0.0138</code></pre>
</div>
</div>
<p>Assuming I wanted to perform a set of orthogonal contrasts:</p>
<ul>
<li><p>Phys v. Soc and Hist and</p></li>
<li><p>Soc v Hist</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="co"># build the contrast matrix</span></span>
<span id="cb30-2"><a href="#cb30-2"></a>contrast_matrix <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"Phys v. Soc + Hist"</span> <span class="ot">=</span> <span class="fu">c</span>(.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>,.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>),</span>
<span id="cb30-3"><a href="#cb30-3"></a>                        <span class="st">"Soc v Hist"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span>.<span class="dv">5</span>, .<span class="dv">5</span>, <span class="dv">0</span>, <span class="sc">-</span>.<span class="dv">5</span>, .<span class="dv">5</span>)</span>
<span id="cb30-4"><a href="#cb30-4"></a>                        )</span>
<span id="cb30-5"><a href="#cb30-5"></a></span>
<span id="cb30-6"><a href="#cb30-6"></a><span class="co"># run the contrasts</span></span>
<span id="cb30-7"><a href="#cb30-7"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE df t.ratio p.value
 Phys v. Soc + Hist     6.83 2.62 32   2.604  0.0138
 Soc v Hist             2.67 3.03 32   0.880  0.3853</code></pre>
</div>
</div>
<p>In both cases, my p-values are unadjusted. I can add an adjustment to the <code>contrast()</code> argument like so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="co"># tukey is most common</span></span>
<span id="cb32-2"><a href="#cb32-2"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Note: adjust = "tukey" was changed to "sidak"
because "tukey" is only appropriate for one set of pairwise comparisons</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE df t.ratio p.value
 Phys v. Soc + Hist     6.83 2.62 32   2.604  0.0275
 Soc v Hist             2.67 3.03 32   0.880  0.6222

P value adjustment: sidak method for 2 tests </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># or bonferroni is most conservative</span></span>
<span id="cb35-2"><a href="#cb35-2"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE df t.ratio p.value
 Phys v. Soc + Hist     6.83 2.62 32   2.604  0.0277
 Soc v Hist             2.67 3.03 32   0.880  0.7706

P value adjustment: bonferroni method for 2 tests </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="co"># or holm is more liberal</span></span>
<span id="cb37-2"><a href="#cb37-2"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix, <span class="at">adjust =</span> <span class="st">"holm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE df t.ratio p.value
 Phys v. Soc + Hist     6.83 2.62 32   2.604  0.0277
 Soc v Hist             2.67 3.03 32   0.880  0.3853

P value adjustment: holm method for 2 tests </code></pre>
</div>
</div>
</section><section id="more-examples-a-3-3-anova" class="level2"><h2 class="anchored" data-anchor-id="more-examples-a-3-3-anova">More examples: a 3 × 3 ANOVA</h2>
<p>In the previous example we focused in the 2 × 3 scenario for ease. Let’s look at how we might deal with a 3 × 3 example. Let’s use our dataset from the previous walkthrough involving a 3 (Smoking group) by 3 (Task) design. Let’s run another example using this data. Let’s use this as a chance to brush up on creating APA visualizations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Sec13-5.dat"</span>, </span>
<span id="cb39-2"><a href="#cb39-2"></a>                      <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">escape_double =</span> <span class="cn">FALSE</span>, </span>
<span id="cb39-3"><a href="#cb39-3"></a>                      <span class="at">trim_ws =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 135 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
dbl (4): Task, Smkgrp, score, covar

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>dataset<span class="sc">$</span>PartID <span class="ot">&lt;-</span> <span class="fu">seq_along</span>(dataset<span class="sc">$</span>score)</span>
<span id="cb41-2"><a href="#cb41-2"></a>dataset<span class="sc">$</span>Task <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Task, </span>
<span id="cb41-3"><a href="#cb41-3"></a>                              <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Pattern Recognition"</span>, </span>
<span id="cb41-4"><a href="#cb41-4"></a>                              <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Cognitive"</span>, </span>
<span id="cb41-5"><a href="#cb41-5"></a>                              <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Driving Simulation"</span>) </span>
<span id="cb41-6"><a href="#cb41-6"></a>dataset<span class="sc">$</span>Smkgrp <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Smkgrp, </span>
<span id="cb41-7"><a href="#cb41-7"></a>                                <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Nonsmoking"</span>, </span>
<span id="cb41-8"><a href="#cb41-8"></a>                                <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Delayed"</span>, </span>
<span id="cb41-9"><a href="#cb41-9"></a>                                <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Active"</span>)</span>
<span id="cb41-10"><a href="#cb41-10"></a></span>
<span id="cb41-11"><a href="#cb41-11"></a>dataset</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 135 × 5
   Task                Smkgrp score covar PartID
   &lt;fct&gt;               &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;int&gt;
 1 Pattern Recognition Active     9   107      1
 2 Pattern Recognition Active     8   133      2
 3 Pattern Recognition Active    12   123      3
 4 Pattern Recognition Active    10    94      4
 5 Pattern Recognition Active     7    83      5
 6 Pattern Recognition Active    10    86      6
 7 Pattern Recognition Active     9   112      7
 8 Pattern Recognition Active    11   117      8
 9 Pattern Recognition Active     8   130      9
10 Pattern Recognition Active    10   111     10
# ℹ 125 more rows</code></pre>
</div>
</div>
<section id="interaction-plot-1" class="level3"><h3 class="anchored" data-anchor-id="interaction-plot-1">Interaction plot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="co"># line plot</span></span>
<span id="cb43-2"><a href="#cb43-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dataset, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Smkgrp,<span class="at">y=</span>score,<span class="at">group=</span>Task)) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>,</span>
<span id="cb43-4"><a href="#cb43-4"></a>               <span class="at">fun.data =</span> <span class="st">"mean_cl_normal"</span>, </span>
<span id="cb43-5"><a href="#cb43-5"></a>               <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">5</span>)) <span class="sc">+</span> </span>
<span id="cb43-6"><a href="#cb43-6"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"line"</span>, </span>
<span id="cb43-7"><a href="#cb43-7"></a>               <span class="at">fun =</span> <span class="st">"mean"</span>, </span>
<span id="cb43-8"><a href="#cb43-8"></a>               <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">5</span>), </span>
<span id="cb43-9"><a href="#cb43-9"></a>               <span class="fu">aes</span>(<span class="at">linetype=</span>Task)) <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10"></a>  <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="10_2-factorial_w_post_hocs_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Before continuing it might be useful to get a feel for whats going on in the dataset. In this case, both the performance on the Cognitive and Driving simulation tasks seems to be impacted by the degree of smoking. However the Pattern recognition task does not appear to be affected.</p>
<p>Another way of viewing this is that scores on the Cognitive task tended to be greater than the other two Task conditions. Let’s hold onto our impressions of the data and move on.</p>
</section><section id="anova-model" class="level3"><h3 class="anchored" data-anchor-id="anova-model">ANOVA model</h3>
<p>As before we can build our ANOVA model and test it against the requisite assumptions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>aov_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score<span class="sc">~</span>Smkgrp<span class="sc">+</span>Task,<span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_model</span>(<span class="at">panel=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_normality</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p &lt; .001).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_homogeneity</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Variances differ between groups (Bartlett Test, p = 0.000).</code></pre>
</div>
</div>
<p>As in the last walkthrough we’ll ignore the issues with our assumption checks</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>aov_model <span class="sc">%&gt;%</span> sjstats<span class="sc">::</span><span class="fu">anova_stats</span>() <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"term"</span>,<span class="st">"df"</span>,<span class="st">"statistic"</span>,<span class="st">"p.value"</span>,<span class="st">"partial.etasq"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>term      |  df | statistic | p.value | partial.etasq
-----------------------------------------------------
Smkgrp    |   2 |     7.935 |   0.001 |         0.109
Task      |   2 |   125.398 |  &lt; .001 |         0.659
Residuals | 130 |           |         |              </code></pre>
</div>
</div>
<p>Here we have significant main effects for <code>Smkgrp</code> and <code>Task</code>. We’ll need to run seperate post-hoc analyses for each of our observed effects (given that both factors have 3 levels). Before moving on, I would recommend writing out the main points of this table to refer to later in your write up.</p>
<blockquote class="blockquote">
<ul>
<li><p>main effect for Task, <span class="math inline">\(F\)</span> (2, 130) = 125.40, <span class="math inline">\(p\)</span> &lt; .001, <span class="math inline">\(n_p^2\)</span> = .66.</p></li>
<li><p>main effect for Smoking Group, <span class="math inline">\(F\)</span> (2, 130) = 7.94, <span class="math inline">\(p\)</span> = .001, <span class="math inline">\(n_p^2\)</span> = .11</p></li>
</ul>
</blockquote>
</section></section><section id="post-hoc-analysis-1" class="level2"><h2 class="anchored" data-anchor-id="post-hoc-analysis-1">Post-hoc analysis</h2>
<section id="task" class="level3"><h3 class="anchored" data-anchor-id="task">Task</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>main_effect_Task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(aov_model, <span class="sc">~</span>Task) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"tukey"</span>)</span>
<span id="cb52-2"><a href="#cb52-2"></a></span>
<span id="cb52-3"><a href="#cb52-3"></a>main_effect_Task</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                 estimate   SE  df t.ratio p.value
 Pattern Recognition - Cognitive            -29.13 2.25 130 -12.927  &lt;.0001
 Pattern Recognition - Driving Simulation     3.29 2.25 130   1.459  0.3139
 Cognitive - Driving Simulation              32.42 2.25 130  14.386  &lt;.0001

Results are averaged over the levels of: Smkgrp 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>The results confirm that overall, Cognitive task performance was greater than the other two conditions. To get the descriptive stats for these contrasts, we can use <code>summarySE</code>, only specifying <code>Task</code> as our grouping viariable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a>Rmisc<span class="sc">::</span><span class="fu">summarySE</span>(<span class="at">data =</span> dataset, <span class="at">measurevar =</span> <span class="st">"score"</span>, <span class="at">groupvars =</span> <span class="st">"Task"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Task  N     score        sd        se       ci
1 Pattern Recognition 45  9.644444  4.513392 0.6728168 1.355973
2           Cognitive 45 38.777778 18.055330 2.6915297 5.424422
3  Driving Simulation 45  6.355556  5.701497 0.8499290 1.712919</code></pre>
</div>
</div>
</section><section id="smkgrp" class="level3"><h3 class="anchored" data-anchor-id="smkgrp">Smkgrp</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a>main_effect_Smkgrp <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(aov_model, <span class="sc">~</span>Smkgrp) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"tukey"</span>)</span>
<span id="cb56-2"><a href="#cb56-2"></a></span>
<span id="cb56-3"><a href="#cb56-3"></a>main_effect_Smkgrp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast             estimate   SE  df t.ratio p.value
 Nonsmoking - Delayed     3.69 2.25 130   1.637  0.2339
 Nonsmoking - Active      8.93 2.25 130   3.964  0.0004
 Delayed - Active         5.24 2.25 130   2.327  0.0556

Results are averaged over the levels of: Task 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>and to get these descriptive stats, we run <code>summarySE</code> using only <code>Smkgrp</code> as our grouping variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a>Rmisc<span class="sc">::</span><span class="fu">summarySE</span>(<span class="at">data =</span> dataset, <span class="at">measurevar =</span> <span class="st">"score"</span>, <span class="at">groupvars =</span> <span class="st">"Smkgrp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Smkgrp  N    score       sd       se       ci
1 Nonsmoking 45 22.46667 20.36218 3.035414 6.117475
2    Delayed 45 18.77778 19.35892 2.885857 5.816063
3     Active 45 13.53333 14.13024 2.106412 4.245194</code></pre>
</div>
</div>
</section></section><section id="example-write-up" class="level2"><h2 class="anchored" data-anchor-id="example-write-up">Example write up</h2>
<p>Let’s use this space to provide an example write-up for our factorial ANOVA. To do this I need to refer back to values I generated in my ANOVA table, my post-hoc tests, and my descriptive statistics above.</p>
<blockquote class="blockquote">
<p>To test our hypothesis we ran a 3 (Task) × 3 (Smoking Group) ANOVA on cognitive performance scores. Our ANOVA revealed a significant main effect for Task, <span class="math inline">\(F\)</span> (2, 130) = 125.40, <span class="math inline">\(p\)</span> &lt; .001, <span class="math inline">\(n_p^2\)</span> = .66. Post hoc analysis of Task revealed that participants scored higher in the Cognitive group (<span class="math inline">\(M±SE\)</span> = 38.78 ± 2.69) than the Pattern Recognition (9.64 ± 0.67 ) and Driving Simulator (6.36 ± 0.84) groups (<span class="math inline">\(ps\)</span> &lt; .05).</p>
<p>Our analysis also revealed a main effect for Smoking Group, <span class="math inline">\(F\)</span> (2, 130) = 7.94, <span class="math inline">\(p\)</span> = .001, <span class="math inline">\(n_p^2\)</span> = .11. Post hoc analysis of Smoking Group revealed participants scored higher in the Nonsmoking group than the Active group (<span class="math inline">\(p\)</span> &lt; .05). No other statistically significant group differences were observed.</p>
</blockquote>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb60" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb60-1"><a href="#cb60-1"></a><span class="co">---</span></span>
<span id="cb60-2"><a href="#cb60-2"></a><span class="an">title:</span><span class="co"> 'Factorial ANOVA - Post hoc analysis of Main effects'</span></span>
<span id="cb60-3"><a href="#cb60-3"></a><span class="co">---</span></span>
<span id="cb60-4"><a href="#cb60-4"></a></span>
<span id="cb60-5"><a href="#cb60-5"></a>In the last walkthrough, analyzed a 2×2 ANOVA focusing on our main effects. Because each of our factors only had two levels, there was no need to follow up on significant main effects with pairwise post hoc analysis. In this walkthough we will take a look at examples where our main effects have 3 or more levels, and demand a post-hoc analysis. For now, let's try another example. First let's bring in the necessary packages:</span>
<span id="cb60-6"><a href="#cb60-6"></a></span>
<span id="cb60-9"><a href="#cb60-9"></a><span class="in">```{r}</span></span>
<span id="cb60-10"><a href="#cb60-10"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(psych, tidyverse, cowplot, emmeans, ez)</span>
<span id="cb60-11"><a href="#cb60-11"></a><span class="in">```</span></span>
<span id="cb60-12"><a href="#cb60-12"></a></span>
<span id="cb60-13"><a href="#cb60-13"></a><span class="fu">## Example: A 2 × 3 ANOVA</span></span>
<span id="cb60-14"><a href="#cb60-14"></a></span>
<span id="cb60-15"><a href="#cb60-15"></a>Thirty-six college students were randomly assigned to 3 groups (N=12). Students in each group were asked to watch and take notes on a 50 min lecture. One week later all students were tested on the content of their lectures, and their <span class="in">`scores`</span> were compared. Groups differed by the lecture's subject matter, where:</span>
<span id="cb60-16"><a href="#cb60-16"></a></span>
<span id="cb60-17"><a href="#cb60-17"></a><span class="ss">-   </span>**1** = Physics lecture</span>
<span id="cb60-18"><a href="#cb60-18"></a><span class="ss">-   </span>**2** = Social Science lecture</span>
<span id="cb60-19"><a href="#cb60-19"></a><span class="ss">-   </span>**3** = History lecture</span>
<span id="cb60-20"><a href="#cb60-20"></a></span>
<span id="cb60-21"><a href="#cb60-21"></a>The lectures were presented in two manners</span>
<span id="cb60-22"><a href="#cb60-22"></a></span>
<span id="cb60-23"><a href="#cb60-23"></a><span class="ss">-   </span>**1 =** via computer</span>
<span id="cb60-24"><a href="#cb60-24"></a></span>
<span id="cb60-25"><a href="#cb60-25"></a><span class="ss">-   </span>**2** = standard method, lecturer in a lecture hall</span>
<span id="cb60-26"><a href="#cb60-26"></a></span>
<span id="cb60-27"><a href="#cb60-27"></a>The researchers hypothesized that students that learned the material in the standard lecture would perform better than those that learned via computer.</span>
<span id="cb60-28"><a href="#cb60-28"></a></span>
<span id="cb60-31"><a href="#cb60-31"></a><span class="in">```{r}</span></span>
<span id="cb60-32"><a href="#cb60-32"></a>dataset_no_inter <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/tehrandavis/graduate_statistics/main/practice_datasets/factorial_ANOVA_dataset_no_interactions.csv"</span>)</span>
<span id="cb60-33"><a href="#cb60-33"></a></span>
<span id="cb60-34"><a href="#cb60-34"></a>dataset_no_inter<span class="sc">$</span>Lecture <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset_no_inter<span class="sc">$</span>Lecture, <span class="st">"1"</span><span class="ot">=</span><span class="st">"Phys"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"Soc"</span>,<span class="st">"3"</span><span class="ot">=</span><span class="st">"Hist"</span>)</span>
<span id="cb60-35"><a href="#cb60-35"></a></span>
<span id="cb60-36"><a href="#cb60-36"></a>dataset_no_inter<span class="sc">$</span>Presentation <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset_no_inter<span class="sc">$</span>Presentation, <span class="st">"1"</span><span class="ot">=</span><span class="st">"Comp"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"Stand"</span>)</span>
<span id="cb60-37"><a href="#cb60-37"></a></span>
<span id="cb60-38"><a href="#cb60-38"></a><span class="fu">summary</span>(dataset_no_inter)</span>
<span id="cb60-39"><a href="#cb60-39"></a><span class="in">```</span></span>
<span id="cb60-40"><a href="#cb60-40"></a></span>
<span id="cb60-41"><a href="#cb60-41"></a><span class="fu">### Building the ANOVA model</span></span>
<span id="cb60-42"><a href="#cb60-42"></a></span>
<span id="cb60-43"><a href="#cb60-43"></a>I'm going to use <span class="in">`lm()`</span>.</span>
<span id="cb60-44"><a href="#cb60-44"></a></span>
<span id="cb60-47"><a href="#cb60-47"></a><span class="in">```{r}</span></span>
<span id="cb60-48"><a href="#cb60-48"></a>aov_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score<span class="sc">~</span>Presentation <span class="sc">+</span> Lecture, <span class="at">data =</span> dataset_no_inter)</span>
<span id="cb60-49"><a href="#cb60-49"></a><span class="in">```</span></span>
<span id="cb60-50"><a href="#cb60-50"></a></span>
<span id="cb60-51"><a href="#cb60-51"></a><span class="fu">### Testing assumptions</span></span>
<span id="cb60-52"><a href="#cb60-52"></a></span>
<span id="cb60-53"><a href="#cb60-53"></a><span class="fu">### visual</span></span>
<span id="cb60-54"><a href="#cb60-54"></a></span>
<span id="cb60-57"><a href="#cb60-57"></a><span class="in">```{r}</span></span>
<span id="cb60-58"><a href="#cb60-58"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_model</span>(<span class="at">panel=</span><span class="cn">FALSE</span>)</span>
<span id="cb60-59"><a href="#cb60-59"></a><span class="in">```</span></span>
<span id="cb60-60"><a href="#cb60-60"></a></span>
<span id="cb60-63"><a href="#cb60-63"></a><span class="in">```{r}</span></span>
<span id="cb60-64"><a href="#cb60-64"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_normality</span>()</span>
<span id="cb60-65"><a href="#cb60-65"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_homogeneity</span>()</span>
<span id="cb60-66"><a href="#cb60-66"></a><span class="in">```</span></span>
<span id="cb60-67"><a href="#cb60-67"></a></span>
<span id="cb60-68"><a href="#cb60-68"></a>The model checks both for normality of residuals but fails homogeneity of variance. Following upon given the robustness of ANOVA (3x rule):</span>
<span id="cb60-69"><a href="#cb60-69"></a></span>
<span id="cb60-72"><a href="#cb60-72"></a><span class="in">```{r}</span></span>
<span id="cb60-73"><a href="#cb60-73"></a>dataset_no_inter <span class="sc">%&gt;%</span> </span>
<span id="cb60-74"><a href="#cb60-74"></a>  <span class="fu">group_by</span>(Lecture, Presentation) <span class="sc">%&gt;%</span></span>
<span id="cb60-75"><a href="#cb60-75"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Score),</span>
<span id="cb60-76"><a href="#cb60-76"></a>            <span class="at">var =</span> <span class="fu">var</span>(Score))</span>
<span id="cb60-77"><a href="#cb60-77"></a><span class="in">```</span></span>
<span id="cb60-78"><a href="#cb60-78"></a></span>
<span id="cb60-79"><a href="#cb60-79"></a>Potential issues, but moving on.</span>
<span id="cb60-80"><a href="#cb60-80"></a></span>
<span id="cb60-81"><a href="#cb60-81"></a><span class="fu">### Interaction plot</span></span>
<span id="cb60-82"><a href="#cb60-82"></a></span>
<span id="cb60-83"><a href="#cb60-83"></a>Let's plot the data. You'll note in this plot I'm adding some code to get it into better APA shape. More on this in the next walkthrough. For now just focus on content.</span>
<span id="cb60-84"><a href="#cb60-84"></a></span>
<span id="cb60-87"><a href="#cb60-87"></a><span class="in">```{r}</span></span>
<span id="cb60-88"><a href="#cb60-88"></a><span class="co"># setting original parameters</span></span>
<span id="cb60-89"><a href="#cb60-89"></a>p <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> dataset_no_inter, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Lecture,<span class="at">y=</span>Score,<span class="at">group=</span>Presentation))</span>
<span id="cb60-90"><a href="#cb60-90"></a></span>
<span id="cb60-91"><a href="#cb60-91"></a><span class="co"># making a basic line plot</span></span>
<span id="cb60-92"><a href="#cb60-92"></a>line_p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>,<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">size=</span><span class="fl">0.75</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">25</span>), <span class="fu">aes</span>(<span class="at">shape=</span>Presentation)) <span class="sc">+</span> </span>
<span id="cb60-93"><a href="#cb60-93"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">25</span>), <span class="fu">aes</span>(<span class="at">linetype=</span>Presentation))</span>
<span id="cb60-94"><a href="#cb60-94"></a></span>
<span id="cb60-95"><a href="#cb60-95"></a><span class="co"># adding APA elements</span></span>
<span id="cb60-96"><a href="#cb60-96"></a>line_p <span class="ot">&lt;-</span> line_p <span class="sc">+</span> <span class="fu">theme</span>(</span>
<span id="cb60-97"><a href="#cb60-97"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">lineheight =</span> .<span class="dv">55</span>),</span>
<span id="cb60-98"><a href="#cb60-98"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb60-99"><a href="#cb60-99"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb60-100"><a href="#cb60-100"></a>    <span class="at">legend.position =</span> <span class="fu">c</span>(.<span class="dv">75</span>,.<span class="dv">9</span>)) <span class="sc">+</span></span>
<span id="cb60-101"><a href="#cb60-101"></a>  <span class="fu">xlab</span>(<span class="st">"Lecture type"</span>) <span class="sc">+</span> </span>
<span id="cb60-102"><a href="#cb60-102"></a>  <span class="fu">ylab</span> (<span class="st">"Performance score"</span>) <span class="sc">+</span></span>
<span id="cb60-103"><a href="#cb60-103"></a>  <span class="fu">theme</span>(<span class="at">plot.margin=</span><span class="fu">unit</span>(<span class="fu">c</span>(.<span class="dv">25</span>,.<span class="dv">25</span>,.<span class="dv">25</span>,.<span class="dv">25</span>),<span class="st">"in"</span>)) <span class="sc">+</span> </span>
<span id="cb60-104"><a href="#cb60-104"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb60-105"><a href="#cb60-105"></a></span>
<span id="cb60-106"><a href="#cb60-106"></a><span class="fu">show</span>(line_p)</span>
<span id="cb60-107"><a href="#cb60-107"></a><span class="in">```</span></span>
<span id="cb60-108"><a href="#cb60-108"></a></span>
<span id="cb60-109"><a href="#cb60-109"></a><span class="fu">### Testing the ANOVA</span></span>
<span id="cb60-110"><a href="#cb60-110"></a></span>
<span id="cb60-113"><a href="#cb60-113"></a><span class="in">```{r}</span></span>
<span id="cb60-114"><a href="#cb60-114"></a>aov_model <span class="sc">%&gt;%</span> sjstats<span class="sc">::</span><span class="fu">anova_stats</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb60-115"><a href="#cb60-115"></a>  <span class="fu">select</span>(<span class="st">"term"</span>,<span class="st">"df"</span>,<span class="st">"statistic"</span>,<span class="st">"p.value"</span>,<span class="st">"partial.etasq"</span>)</span>
<span id="cb60-116"><a href="#cb60-116"></a><span class="in">```</span></span>
<span id="cb60-117"><a href="#cb60-117"></a></span>
<span id="cb60-118"><a href="#cb60-118"></a><span class="fu">## post hoc analysis</span></span>
<span id="cb60-119"><a href="#cb60-119"></a></span>
<span id="cb60-120"><a href="#cb60-120"></a>Admittedly, moving on to this step will ultimately be qualified by the presence of interactions (next week). For now, note that if you don't have an interaction, you may simply proceed to run post-hoc analyses on any significant main effects in the manner you would with a One-way ANOVA. Easy, peasy, right. One thing to note, you need to make the appropriate multiple comparison corrections. For example, returning to our data with no interaction, we need to test for differences in both the <span class="in">`Lecture`</span> and <span class="in">`Presentation`</span> main effects.</span>
<span id="cb60-121"><a href="#cb60-121"></a></span>
<span id="cb60-122"><a href="#cb60-122"></a><span class="ss">-   </span>Presentation: This one is easy. We only have two levels of <span class="in">`Presentation`</span>, so the omnibus $F$ test tells us that our two groups are different. Nothing else to do here other than note which mean (Computer v. Standard) is greater than the other.</span>
<span id="cb60-123"><a href="#cb60-123"></a></span>
<span id="cb60-124"><a href="#cb60-124"></a><span class="ss">-   </span>Lecture: We have three levels of lecture, so were are going to need to run a post-hoc analysis. In this case, we may call upon our old standbys, Tukey and Bonferroni.</span>
<span id="cb60-125"><a href="#cb60-125"></a></span>
<span id="cb60-126"><a href="#cb60-126"></a>**Just as last week, we can use `emmeans()` to run our post-hoc tests.**</span>
<span id="cb60-127"><a href="#cb60-127"></a></span>
<span id="cb60-128"><a href="#cb60-128"></a>For example, to run a Tukey, you need call your ANOVA model. For the sake of clarity let's rebuild the ANOVA model and save it to <span class="in">`aov_model`</span> and then run <span class="in">`emmeans()`</span></span>
<span id="cb60-129"><a href="#cb60-129"></a></span>
<span id="cb60-130"><a href="#cb60-130"></a>Here I'm saving it to the object <span class="in">`aov_model`</span>:</span>
<span id="cb60-131"><a href="#cb60-131"></a></span>
<span id="cb60-134"><a href="#cb60-134"></a><span class="in">```{r}</span></span>
<span id="cb60-135"><a href="#cb60-135"></a>aov_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score<span class="sc">~</span>Presentation <span class="sc">+</span> Lecture, <span class="at">data =</span> dataset_no_inter)</span>
<span id="cb60-136"><a href="#cb60-136"></a><span class="in">```</span></span>
<span id="cb60-137"><a href="#cb60-137"></a></span>
<span id="cb60-138"><a href="#cb60-138"></a>From here you may call upon the <span class="in">`emmeans()`</span> function to derive your posthocs. By itself, <span class="in">`emmeans`</span> produces the means by levels of the IV(s) listed in its <span class="in">`spec=`</span> argument. It takes the <span class="in">`lm()`</span> model as a first argument, and the IVs of interest as the second.</span>
<span id="cb60-139"><a href="#cb60-139"></a></span>
<span id="cb60-142"><a href="#cb60-142"></a><span class="in">```{r}</span></span>
<span id="cb60-143"><a href="#cb60-143"></a><span class="co"># input your model into the emmeans,</span></span>
<span id="cb60-144"><a href="#cb60-144"></a><span class="co"># interested in Lecture</span></span>
<span id="cb60-145"><a href="#cb60-145"></a></span>
<span id="cb60-146"><a href="#cb60-146"></a><span class="fu">emmeans</span>(aov_model,<span class="at">specs =</span> <span class="sc">~</span>Lecture)</span>
<span id="cb60-147"><a href="#cb60-147"></a><span class="in">```</span></span>
<span id="cb60-148"><a href="#cb60-148"></a></span>
<span id="cb60-149"><a href="#cb60-149"></a><span class="in">`emmeans()`</span> alone gives us the estimated marginal means for each of our levels, to run a post-hoc comparison we then pipe it into <span class="in">`pairs()`</span> and include the <span class="in">`p value`</span> adjustment that we would like to make. allows another method for making contrasts (planned and posthoc). If you want to perform a Tukey test follow this procedure you can simply pipe the previous (or save to an object and submit) to <span class="in">`pairs()`</span>:</span>
<span id="cb60-150"><a href="#cb60-150"></a></span>
<span id="cb60-153"><a href="#cb60-153"></a><span class="in">```{r}</span></span>
<span id="cb60-154"><a href="#cb60-154"></a><span class="fu">emmeans</span>(aov_model,<span class="at">specs =</span> <span class="sc">~</span>Lecture) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"tukey"</span>) </span>
<span id="cb60-155"><a href="#cb60-155"></a><span class="in">```</span></span>
<span id="cb60-156"><a href="#cb60-156"></a></span>
<span id="cb60-157"><a href="#cb60-157"></a>In this case it appears that our Tukey does reveal differences between means, when performance of those getting Physical Science Lectures is greater than both History and Social, but Social and History are not difference from one another.</span>
<span id="cb60-158"><a href="#cb60-158"></a></span>
<span id="cb60-159"><a href="#cb60-159"></a>Note that you may call other p-value adjustments using these methods:</span>
<span id="cb60-160"><a href="#cb60-160"></a></span>
<span id="cb60-163"><a href="#cb60-163"></a><span class="in">```{r}</span></span>
<span id="cb60-164"><a href="#cb60-164"></a><span class="fu">emmeans</span>(aov_model,<span class="at">specs =</span> <span class="sc">~</span>Lecture) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"bonferroni"</span>)</span>
<span id="cb60-165"><a href="#cb60-165"></a><span class="in">```</span></span>
<span id="cb60-166"><a href="#cb60-166"></a></span>
<span id="cb60-167"><a href="#cb60-167"></a><span class="fu">## What about planned contrasts?</span></span>
<span id="cb60-168"><a href="#cb60-168"></a></span>
<span id="cb60-169"><a href="#cb60-169"></a>You need to be careful when running planned contrasts in factorial ANOVA. In general I would recommend only running planned contrasts on a single main effect, or a planned contrast on the effects of one of your factors at a single level of your other (though you still need to proceed with caution here).</span>
<span id="cb60-170"><a href="#cb60-170"></a></span>
<span id="cb60-171"><a href="#cb60-171"></a>For example, using the data from the last section, I would only run a planned contrast related to the main effect of <span class="in">`Lecture Type`</span>, or a contrast of <span class="in">`Lecture Type`</span> means only in <span class="in">`Computer presentation`</span> conditions (or <span class="in">`Standard presentation`</span>). DO NOT, I repeat DO NOT run contrasts that go across levels of your other factors. Well, truthfully, you can do whatever you want, but you may find that your ability to meaningfully interpret your results in such cases is extremely limited.</span>
<span id="cb60-172"><a href="#cb60-172"></a></span>
<span id="cb60-173"><a href="#cb60-173"></a>We can run planned contrasts using <span class="in">`emmeans()`</span> as well. In this case, we need to specify the contrasts.</span>
<span id="cb60-174"><a href="#cb60-174"></a></span>
<span id="cb60-175"><a href="#cb60-175"></a>First we need to obtain the <span class="in">`emmeans()`</span> of the model including all cells (all factors). Using <span class="in">`aov.model`</span> from the previous example:</span>
<span id="cb60-176"><a href="#cb60-176"></a></span>
<span id="cb60-179"><a href="#cb60-179"></a><span class="in">```{r}</span></span>
<span id="cb60-180"><a href="#cb60-180"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture<span class="sc">+</span>Presentation)</span>
<span id="cb60-181"><a href="#cb60-181"></a><span class="in">```</span></span>
<span id="cb60-182"><a href="#cb60-182"></a></span>
<span id="cb60-183"><a href="#cb60-183"></a>OK. From here let's build two custom contrasts. First, let's do the <span class="in">`Lecture`</span> contrast on the main effect. In this case let's assume I want to contrast <span class="in">`Phys`</span> with the combined other two conditions. Using the output above, I identify which rows contain <span class="in">`Phys`</span> and I ensure that the summation of those rows is 1. In this case there are two rows, the first and the fourth, and each gets <span class="in">`0.5`</span>. My remaining conditions must also equal <span class="in">`-1`</span>. In this case there are four, so each is <span class="in">`-0.25`</span>. Following the output above, then my contrast matrix is:</span>
<span id="cb60-184"><a href="#cb60-184"></a></span>
<span id="cb60-187"><a href="#cb60-187"></a><span class="in">```{r}</span></span>
<span id="cb60-188"><a href="#cb60-188"></a>lecture_contrast <span class="ot">&lt;-</span> <span class="fu">list</span>( <span class="st">"Phys v. Soc + Hist"</span> <span class="ot">=</span> <span class="fu">c</span>(.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>,.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>))</span>
<span id="cb60-189"><a href="#cb60-189"></a><span class="in">```</span></span>
<span id="cb60-190"><a href="#cb60-190"></a></span>
<span id="cb60-191"><a href="#cb60-191"></a>From here I simply call <span class="in">`contrast()`</span> with my contrast matrix as an argument. So the entire pipe goes from:</span>
<span id="cb60-192"><a href="#cb60-192"></a></span>
<span id="cb60-195"><a href="#cb60-195"></a><span class="in">```{r}</span></span>
<span id="cb60-196"><a href="#cb60-196"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(lecture_contrast)</span>
<span id="cb60-197"><a href="#cb60-197"></a><span class="in">```</span></span>
<span id="cb60-198"><a href="#cb60-198"></a></span>
<span id="cb60-199"><a href="#cb60-199"></a>Assuming I wanted to perform a set of orthogonal contrasts:</span>
<span id="cb60-200"><a href="#cb60-200"></a></span>
<span id="cb60-201"><a href="#cb60-201"></a><span class="ss">-   </span>Phys v. Soc and Hist and</span>
<span id="cb60-202"><a href="#cb60-202"></a></span>
<span id="cb60-203"><a href="#cb60-203"></a><span class="ss">-   </span>Soc v Hist</span>
<span id="cb60-204"><a href="#cb60-204"></a></span>
<span id="cb60-207"><a href="#cb60-207"></a><span class="in">```{r}</span></span>
<span id="cb60-208"><a href="#cb60-208"></a><span class="co"># build the contrast matrix</span></span>
<span id="cb60-209"><a href="#cb60-209"></a>contrast_matrix <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"Phys v. Soc + Hist"</span> <span class="ot">=</span> <span class="fu">c</span>(.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>,.<span class="dv">5</span>,<span class="sc">-</span>.<span class="dv">25</span>,<span class="sc">-</span>.<span class="dv">25</span>),</span>
<span id="cb60-210"><a href="#cb60-210"></a>                        <span class="st">"Soc v Hist"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span>.<span class="dv">5</span>, .<span class="dv">5</span>, <span class="dv">0</span>, <span class="sc">-</span>.<span class="dv">5</span>, .<span class="dv">5</span>)</span>
<span id="cb60-211"><a href="#cb60-211"></a>                        )</span>
<span id="cb60-212"><a href="#cb60-212"></a></span>
<span id="cb60-213"><a href="#cb60-213"></a><span class="co"># run the contrasts</span></span>
<span id="cb60-214"><a href="#cb60-214"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix)</span>
<span id="cb60-215"><a href="#cb60-215"></a><span class="in">```</span></span>
<span id="cb60-216"><a href="#cb60-216"></a></span>
<span id="cb60-217"><a href="#cb60-217"></a>In both cases, my p-values are unadjusted. I can add an adjustment to the <span class="in">`contrast()`</span> argument like so:</span>
<span id="cb60-218"><a href="#cb60-218"></a></span>
<span id="cb60-221"><a href="#cb60-221"></a><span class="in">```{r}</span></span>
<span id="cb60-222"><a href="#cb60-222"></a><span class="co"># tukey is most common</span></span>
<span id="cb60-223"><a href="#cb60-223"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb60-224"><a href="#cb60-224"></a></span>
<span id="cb60-225"><a href="#cb60-225"></a><span class="co"># or bonferroni is most conservative</span></span>
<span id="cb60-226"><a href="#cb60-226"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb60-227"><a href="#cb60-227"></a></span>
<span id="cb60-228"><a href="#cb60-228"></a><span class="co"># or holm is more liberal</span></span>
<span id="cb60-229"><a href="#cb60-229"></a><span class="fu">emmeans</span>(aov_model, <span class="at">specs =</span> <span class="sc">~</span>Lecture <span class="sc">+</span> Presentation) <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(contrast_matrix, <span class="at">adjust =</span> <span class="st">"holm"</span>)</span>
<span id="cb60-230"><a href="#cb60-230"></a><span class="in">```</span></span>
<span id="cb60-231"><a href="#cb60-231"></a></span>
<span id="cb60-232"><a href="#cb60-232"></a><span class="fu">## More examples: a 3 × 3 ANOVA</span></span>
<span id="cb60-233"><a href="#cb60-233"></a></span>
<span id="cb60-234"><a href="#cb60-234"></a>In the previous example we focused in the 2 × 3 scenario for ease. Let's look at how we might deal with a 3 × 3 example. Let's use our dataset from the previous walkthrough involving a 3 (Smoking group) by 3 (Task) design. Let's run another example using this data. Let's use this as a chance to brush up on creating APA visualizations:</span>
<span id="cb60-235"><a href="#cb60-235"></a></span>
<span id="cb60-238"><a href="#cb60-238"></a><span class="in">```{r}</span></span>
<span id="cb60-239"><a href="#cb60-239"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Sec13-5.dat"</span>, </span>
<span id="cb60-240"><a href="#cb60-240"></a>                      <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">escape_double =</span> <span class="cn">FALSE</span>, </span>
<span id="cb60-241"><a href="#cb60-241"></a>                      <span class="at">trim_ws =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-242"><a href="#cb60-242"></a>dataset<span class="sc">$</span>PartID <span class="ot">&lt;-</span> <span class="fu">seq_along</span>(dataset<span class="sc">$</span>score)</span>
<span id="cb60-243"><a href="#cb60-243"></a>dataset<span class="sc">$</span>Task <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Task, </span>
<span id="cb60-244"><a href="#cb60-244"></a>                              <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Pattern Recognition"</span>, </span>
<span id="cb60-245"><a href="#cb60-245"></a>                              <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Cognitive"</span>, </span>
<span id="cb60-246"><a href="#cb60-246"></a>                              <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Driving Simulation"</span>) </span>
<span id="cb60-247"><a href="#cb60-247"></a>dataset<span class="sc">$</span>Smkgrp <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Smkgrp, </span>
<span id="cb60-248"><a href="#cb60-248"></a>                                <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Nonsmoking"</span>, </span>
<span id="cb60-249"><a href="#cb60-249"></a>                                <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Delayed"</span>, </span>
<span id="cb60-250"><a href="#cb60-250"></a>                                <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Active"</span>)</span>
<span id="cb60-251"><a href="#cb60-251"></a></span>
<span id="cb60-252"><a href="#cb60-252"></a>dataset</span>
<span id="cb60-253"><a href="#cb60-253"></a><span class="in">```</span></span>
<span id="cb60-254"><a href="#cb60-254"></a></span>
<span id="cb60-255"><a href="#cb60-255"></a><span class="fu">### Interaction plot</span></span>
<span id="cb60-256"><a href="#cb60-256"></a></span>
<span id="cb60-259"><a href="#cb60-259"></a><span class="in">```{r}</span></span>
<span id="cb60-260"><a href="#cb60-260"></a><span class="co"># line plot</span></span>
<span id="cb60-261"><a href="#cb60-261"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dataset, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Smkgrp,<span class="at">y=</span>score,<span class="at">group=</span>Task)) <span class="sc">+</span></span>
<span id="cb60-262"><a href="#cb60-262"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>,</span>
<span id="cb60-263"><a href="#cb60-263"></a>               <span class="at">fun.data =</span> <span class="st">"mean_cl_normal"</span>, </span>
<span id="cb60-264"><a href="#cb60-264"></a>               <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">5</span>)) <span class="sc">+</span> </span>
<span id="cb60-265"><a href="#cb60-265"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">"line"</span>, </span>
<span id="cb60-266"><a href="#cb60-266"></a>               <span class="at">fun =</span> <span class="st">"mean"</span>, </span>
<span id="cb60-267"><a href="#cb60-267"></a>               <span class="at">position=</span><span class="fu">position_dodge</span>(.<span class="dv">5</span>), </span>
<span id="cb60-268"><a href="#cb60-268"></a>               <span class="fu">aes</span>(<span class="at">linetype=</span>Task)) <span class="sc">+</span></span>
<span id="cb60-269"><a href="#cb60-269"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb60-270"><a href="#cb60-270"></a><span class="in">```</span></span>
<span id="cb60-271"><a href="#cb60-271"></a></span>
<span id="cb60-272"><a href="#cb60-272"></a>Before continuing it might be useful to get a feel for whats going on in the dataset. In this case, both the performance on the Cognitive and Driving simulation tasks seems to be impacted by the degree of smoking. However the Pattern recognition task does not appear to be affected.</span>
<span id="cb60-273"><a href="#cb60-273"></a></span>
<span id="cb60-274"><a href="#cb60-274"></a>Another way of viewing this is that scores on the Cognitive task tended to be greater than the other two Task conditions. Let's hold onto our impressions of the data and move on.</span>
<span id="cb60-275"><a href="#cb60-275"></a></span>
<span id="cb60-276"><a href="#cb60-276"></a><span class="fu">### ANOVA model</span></span>
<span id="cb60-277"><a href="#cb60-277"></a></span>
<span id="cb60-278"><a href="#cb60-278"></a>As before we can build our ANOVA model and test it against the requisite assumptions:</span>
<span id="cb60-279"><a href="#cb60-279"></a></span>
<span id="cb60-282"><a href="#cb60-282"></a><span class="in">```{r}</span></span>
<span id="cb60-283"><a href="#cb60-283"></a>aov_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score<span class="sc">~</span>Smkgrp<span class="sc">+</span>Task,<span class="at">data =</span> dataset)</span>
<span id="cb60-284"><a href="#cb60-284"></a><span class="in">```</span></span>
<span id="cb60-285"><a href="#cb60-285"></a></span>
<span id="cb60-288"><a href="#cb60-288"></a><span class="in">```{r}</span></span>
<span id="cb60-289"><a href="#cb60-289"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_model</span>(<span class="at">panel=</span>F)</span>
<span id="cb60-290"><a href="#cb60-290"></a><span class="in">```</span></span>
<span id="cb60-291"><a href="#cb60-291"></a></span>
<span id="cb60-294"><a href="#cb60-294"></a><span class="in">```{r}</span></span>
<span id="cb60-295"><a href="#cb60-295"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_normality</span>()</span>
<span id="cb60-296"><a href="#cb60-296"></a>aov_model <span class="sc">%&gt;%</span> performance<span class="sc">::</span><span class="fu">check_homogeneity</span>()</span>
<span id="cb60-297"><a href="#cb60-297"></a><span class="in">```</span></span>
<span id="cb60-298"><a href="#cb60-298"></a></span>
<span id="cb60-299"><a href="#cb60-299"></a>As in the last walkthrough we'll ignore the issues with our assumption checks</span>
<span id="cb60-300"><a href="#cb60-300"></a></span>
<span id="cb60-303"><a href="#cb60-303"></a><span class="in">```{r}</span></span>
<span id="cb60-304"><a href="#cb60-304"></a>aov_model <span class="sc">%&gt;%</span> sjstats<span class="sc">::</span><span class="fu">anova_stats</span>() <span class="sc">%&gt;%</span></span>
<span id="cb60-305"><a href="#cb60-305"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"term"</span>,<span class="st">"df"</span>,<span class="st">"statistic"</span>,<span class="st">"p.value"</span>,<span class="st">"partial.etasq"</span>))</span>
<span id="cb60-306"><a href="#cb60-306"></a><span class="in">```</span></span>
<span id="cb60-307"><a href="#cb60-307"></a></span>
<span id="cb60-308"><a href="#cb60-308"></a>Here we have significant main effects for <span class="in">`Smkgrp`</span> and <span class="in">`Task`</span>. We'll need to run seperate post-hoc analyses for each of our observed effects (given that both factors have 3 levels). Before moving on, I would recommend writing out the main points of this table to refer to later in your write up.</span>
<span id="cb60-309"><a href="#cb60-309"></a></span>
<span id="cb60-310"><a href="#cb60-310"></a><span class="at">&gt; -   main effect for Task, $F$ (2, 130) = 125.40, $p$ </span><span class="sc">\&lt;</span><span class="at"> .001, $n_p^2$ = .66.</span></span>
<span id="cb60-311"><a href="#cb60-311"></a><span class="at">&gt;</span></span>
<span id="cb60-312"><a href="#cb60-312"></a><span class="at">&gt; -   main effect for Smoking Group, $F$ (2, 130) = 7.94, $p$ = .001, $n_p^2$ = .11</span></span>
<span id="cb60-313"><a href="#cb60-313"></a></span>
<span id="cb60-314"><a href="#cb60-314"></a><span class="fu">## Post-hoc analysis</span></span>
<span id="cb60-315"><a href="#cb60-315"></a></span>
<span id="cb60-316"><a href="#cb60-316"></a><span class="fu">### Task</span></span>
<span id="cb60-317"><a href="#cb60-317"></a></span>
<span id="cb60-320"><a href="#cb60-320"></a><span class="in">```{r}</span></span>
<span id="cb60-321"><a href="#cb60-321"></a>main_effect_Task <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(aov_model, <span class="sc">~</span>Task) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"tukey"</span>)</span>
<span id="cb60-322"><a href="#cb60-322"></a></span>
<span id="cb60-323"><a href="#cb60-323"></a>main_effect_Task</span>
<span id="cb60-324"><a href="#cb60-324"></a><span class="in">```</span></span>
<span id="cb60-325"><a href="#cb60-325"></a></span>
<span id="cb60-326"><a href="#cb60-326"></a>The results confirm that overall, Cognitive task performance was greater than the other two conditions. To get the descriptive stats for these contrasts, we can use <span class="in">`summarySE`</span>, only specifying <span class="in">`Task`</span> as our grouping viariable:</span>
<span id="cb60-327"><a href="#cb60-327"></a></span>
<span id="cb60-330"><a href="#cb60-330"></a><span class="in">```{r}</span></span>
<span id="cb60-331"><a href="#cb60-331"></a>Rmisc<span class="sc">::</span><span class="fu">summarySE</span>(<span class="at">data =</span> dataset, <span class="at">measurevar =</span> <span class="st">"score"</span>, <span class="at">groupvars =</span> <span class="st">"Task"</span>)</span>
<span id="cb60-332"><a href="#cb60-332"></a><span class="in">```</span></span>
<span id="cb60-333"><a href="#cb60-333"></a></span>
<span id="cb60-334"><a href="#cb60-334"></a><span class="fu">### Smkgrp</span></span>
<span id="cb60-335"><a href="#cb60-335"></a></span>
<span id="cb60-338"><a href="#cb60-338"></a><span class="in">```{r}</span></span>
<span id="cb60-339"><a href="#cb60-339"></a>main_effect_Smkgrp <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(aov_model, <span class="sc">~</span>Smkgrp) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"tukey"</span>)</span>
<span id="cb60-340"><a href="#cb60-340"></a></span>
<span id="cb60-341"><a href="#cb60-341"></a>main_effect_Smkgrp</span>
<span id="cb60-342"><a href="#cb60-342"></a><span class="in">```</span></span>
<span id="cb60-343"><a href="#cb60-343"></a></span>
<span id="cb60-344"><a href="#cb60-344"></a>and to get these descriptive stats, we run <span class="in">`summarySE`</span> using only <span class="in">`Smkgrp`</span> as our grouping variable:</span>
<span id="cb60-345"><a href="#cb60-345"></a></span>
<span id="cb60-348"><a href="#cb60-348"></a><span class="in">```{r}</span></span>
<span id="cb60-349"><a href="#cb60-349"></a>Rmisc<span class="sc">::</span><span class="fu">summarySE</span>(<span class="at">data =</span> dataset, <span class="at">measurevar =</span> <span class="st">"score"</span>, <span class="at">groupvars =</span> <span class="st">"Smkgrp"</span>)</span>
<span id="cb60-350"><a href="#cb60-350"></a><span class="in">```</span></span>
<span id="cb60-351"><a href="#cb60-351"></a></span>
<span id="cb60-352"><a href="#cb60-352"></a><span class="fu">## Example write up</span></span>
<span id="cb60-353"><a href="#cb60-353"></a></span>
<span id="cb60-354"><a href="#cb60-354"></a>Let's use this space to provide an example write-up for our factorial ANOVA. To do this I need to refer back to values I generated in my ANOVA table, my post-hoc tests, and my descriptive statistics above.</span>
<span id="cb60-355"><a href="#cb60-355"></a></span>
<span id="cb60-356"><a href="#cb60-356"></a><span class="at">&gt; To test our hypothesis we ran a 3 (Task) × 3 (Smoking Group) ANOVA on cognitive performance scores. Our ANOVA revealed a significant main effect for Task, $F$ (2, 130) = 125.40, $p$ </span><span class="sc">\&lt;</span><span class="at"> .001, $n_p^2$ = .66. Post hoc analysis of Task revealed that participants scored higher in the Cognitive group ($M±SE$ = 38.78 ± 2.69) than the Pattern Recognition (9.64 ± 0.67 ) and Driving Simulator (6.36 ± 0.84) groups ($ps$ </span><span class="sc">\&lt;</span><span class="at"> .05).</span></span>
<span id="cb60-357"><a href="#cb60-357"></a><span class="at">&gt;</span></span>
<span id="cb60-358"><a href="#cb60-358"></a><span class="at">&gt; Our analysis also revealed a main effect for Smoking Group, $F$ (2, 130) = 7.94, $p$ = .001, $n_p^2$ = .11. Post hoc analysis of Smoking Group revealed participants scored higher in the Nonsmoking group than the Active group ($p$ </span><span class="sc">\&lt;</span><span class="at"> .05). No other statistically significant group differences were observed.</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>