<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Tehran Davis">
<title>PSYC 7014: Graduate Statistics 1 - 21&nbsp; Regression, pt.&nbsp;1: Running the model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../week05/5_4_plotting.html" rel="next">
<link href="../week05/5_2_correlations.html" rel="prev">
<link href="../images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regression, pt.&nbsp;1: Running the model</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">PSYC 7014: Graduate Statistics 1</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Graduate Statistics Walkthroughs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part 1: INTRO to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_1-getting_started.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting started</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_2-resources.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Links to resources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_1-Rmarkdown_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Rmarkdown Basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_2-objects_assignment_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Objects, assignment, and functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_3-install_packages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Installing and loading an <code>R</code> package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_4-loading_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Loading in Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_5-leveling-up.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Leveling-up</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part 2: DESCRIBING &amp; VISUALIZING DATA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_1-structure_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The structure of your data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_2-central_tendency.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Measures of central tendency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_3-summary_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Creating summary tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_1-basic_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Basic ggplotting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_2-more_adv_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">More advanced ggPlots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_4-means_other_models.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Means and other models</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part 3: DISTRIBUTIONS and NHST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The normal distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_2-building_intuitions_about_probability_and_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Building intuitions about probability and NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Sampling distributions and seeing the logic of NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_4-more_examples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">More examples of distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_5-bias_variance.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Bias in sample variance estimates</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Part 4: MODELING w/ CONTINUOUS PREDICTORS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_2_correlations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_3_regressions.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regression, pt.&nbsp;1: Running the model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_4_plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Plotting regression data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_5_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Regression model diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_6_example_report.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Example Report</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Part 5: T-TESTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_1_t-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing differences in means / t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_2_t-test-null-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Thinking about nothing (aka the null)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_3_t-test-lm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">t-test? It’s just a linear model</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Part 6: Power &amp; Effect Size</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_1-effect_size.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Effect Size</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_2-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_3-power_es_sig_tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Power, Effect sizes, and Significance testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_4-simulating_power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Simulating Power!!!</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Part 7: One-way ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_1-one-way-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">The One-way ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_2-anova-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">ANOVA and Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_1-posthocs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_2-planned_contrasts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">Part 8: Factorial ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_1-main_effects.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Factorial ANOVA - The omnibus ANOVA and Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_2-factorial_w_post_hocs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Factorial ANOVA - Post hoc analysis of Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_3-advanced_example_and_apa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Template for Analysis &amp; APA Style</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Part 9: Repeated Measures ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_1-afex_ANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">afex is for ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_2-repeated_measures_anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Within Subjects / Repeated Measures ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_3-factorial_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Factorial RM-ANOVA and simple effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_4-sphericity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Sphericity: Variances and Co-Variances</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_5-spss_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Running a RM-ANOVA in SPSS</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#fitting-the-data-to-a-model" id="toc-fitting-the-data-to-a-model" class="nav-link active" data-scroll-target="#fitting-the-data-to-a-model"><span class="toc-section-number">21.1</span>  Fitting the data to a model</a></li>
  <li><a href="#the-relationship-btw-stress-and-health" id="toc-the-relationship-btw-stress-and-health" class="nav-link" data-scroll-target="#the-relationship-btw-stress-and-health"><span class="toc-section-number">21.2</span>  The Relationship b/tw Stress and Health</a></li>
  <li>
<a href="#linear-models-in-r" id="toc-linear-models-in-r" class="nav-link" data-scroll-target="#linear-models-in-r"><span class="toc-section-number">21.3</span>  Linear models in R</a>
  <ul class="collapse">
<li><a href="#attributes-of-class-lm" id="toc-attributes-of-class-lm" class="nav-link" data-scroll-target="#attributes-of-class-lm"><span class="toc-section-number">21.3.1</span>  Attributes of class <code>lm</code>:</a></li>
  <li><a href="#testing-the-residuals" id="toc-testing-the-residuals" class="nav-link" data-scroll-target="#testing-the-residuals"><span class="toc-section-number">21.3.2</span>  Testing the residuals</a></li>
  <li><a href="#using-your-lm-object-with-other-functions" id="toc-using-your-lm-object-with-other-functions" class="nav-link" data-scroll-target="#using-your-lm-object-with-other-functions"><span class="toc-section-number">21.3.3</span>  Using your <code>lm</code> object with other functions</a></li>
  </ul>
</li>
  <li><a href="#a-note-on-degrees-of-freedom-of-our-model" id="toc-a-note-on-degrees-of-freedom-of-our-model" class="nav-link" data-scroll-target="#a-note-on-degrees-of-freedom-of-our-model"><span class="toc-section-number">21.4</span>  A note on degrees of freedom of our model</a></li>
  <li><a href="#interpreting-the-output" id="toc-interpreting-the-output" class="nav-link" data-scroll-target="#interpreting-the-output"><span class="toc-section-number">21.5</span>  Interpreting the output</a></li>
  <li><a href="#the-coeff.-of-determination-as-index-of-explanatory-value" id="toc-the-coeff.-of-determination-as-index-of-explanatory-value" class="nav-link" data-scroll-target="#the-coeff.-of-determination-as-index-of-explanatory-value"><span class="toc-section-number">21.6</span>  The coeff. of determination as index of explanatory value</a></li>
  <li>
<a href="#write-up-and-presentation" id="toc-write-up-and-presentation" class="nav-link" data-scroll-target="#write-up-and-presentation"><span class="toc-section-number">21.7</span>  Write up and presentation</a>
  <ul class="collapse">
<li><a href="#reporting-standardized-beta" id="toc-reporting-standardized-beta" class="nav-link" data-scroll-target="#reporting-standardized-beta"><span class="toc-section-number">21.7.1</span>  Reporting standardized <span class="math inline">\(\beta\)</span></a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">
<span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regression, pt.&nbsp;1: Running the model</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>Please note that this walkthrough assumes that you have the following packages installed and loaded in R:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">car</span>, <span class="co"># qqPlot function</span></span>
<span>               <span class="va">cowplot</span>, <span class="co"># apa plotting</span></span>
<span>               <span class="va">tidyverse</span>, <span class="co"># tidyverse goodness</span></span>
<span>               <span class="va">psych</span>, <span class="co"># descriptive stats</span></span>
<span>               <span class="va">lm.beta</span>, <span class="co"># getting a standard coefficient</span></span>
<span>               <span class="va">broom</span>, <span class="co"># tidy lm output</span></span>
<span>               <span class="va">olsrr</span> <span class="co"># testing heteroscadicity.</span></span>
<span>               <span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="fitting-the-data-to-a-model" class="level2" data-number="21.1"><h2 data-number="21.1" class="anchored" data-anchor-id="fitting-the-data-to-a-model">
<span class="header-section-number">21.1</span> Fitting the data to a model</h2>
<p>As social scientists, we are not only concerned with observation, but also with explanation. Measures of correlation provide us with the former; we use regression methods to build models in service of the latter. Again both the assigned texts provide excellent overviews of regression, so I won’t repeat much of what they say here.</p>
<p>For the purposes of this vignette (and this course) we will limit ourselves to linear regression, that is describing a line that best fits our data. By “fit” we mean a line than when compared to our observed data minimizes our squared residuals.</p>
</section><section id="the-relationship-btw-stress-and-health" class="level2" data-number="21.2"><h2 data-number="21.2" class="anchored" data-anchor-id="the-relationship-btw-stress-and-health">
<span class="header-section-number">21.2</span> The Relationship b/tw Stress and Health</h2>
<p>Let’s revisit our data from the first walk-through:</p>
<blockquote class="blockquote">
<p>Wagner, Compas, and Howell (1988) investigated the relationship between stress and mental health in first-year college students. Using a scale they developed to measure the frequency, perceived importance, and desirability of recent life events, they created a measure of negative events weighted by the reported frequency and the respondent’s subjective estimate of the impact of each event. This served as their measure of the subject’s perceived social and environmental stress. They also asked students to complete the Hopkins Symptom Checklist, assessing the presence or absence of 57 psychological symptoms.</p>
</blockquote>
<p>This data can be accessed directly from this <a href="https://www.uvm.edu/~statdhtx/methods8/">companion website</a> for Howell’s stats textbook.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stress_data</span> <span class="op">&lt;-</span> <span class="fu">read_table</span><span class="op">(</span><span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab9-2.dat"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  ID = col_double(),
  Stress = col_double(),
  Symptoms = col_double(),
  lnSymptoms = col_double()
)</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">stress_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           vars   n  mean    sd median trimmed   mad   min    max  range skew
ID            1 107 54.00 31.03  54.00   54.00 40.03  1.00 107.00 106.00 0.00
Stress        2 107 21.29 12.49  20.00   20.49 11.86  1.00  58.00  57.00 0.62
Symptoms      3 107 90.33 18.81  88.00   88.87 17.79 58.00 147.00  89.00 0.74
lnSymptoms    4 107  4.48  0.20   4.48    4.48  0.19  4.06   4.99   0.93 0.21
           kurtosis   se
ID            -1.23 3.00
Stress        -0.19 1.21
Symptoms       0.45 1.82
lnSymptoms    -0.28 0.02</code></pre>
</div>
</div>
<p>To perform a linear regression we may call upon the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function. This function uses formula notation <code>outcome variable ~ predictor variable(s)</code>. A simple regression has a single predictor. More often in our analyses we are concerned with the relative effects of multiple predictors, but this is multiple regression and saved for the Spring course. Here, we may be interested in the degree to which perceived <strong>Stress</strong> contributes to the number of <strong>lnSymptons</strong>, or using formula terminology: “How do lnSymptoms (outcome) vary as a function of Stress (predictor)”. This is represented in R as <code>stress_data$lnSymptoms~stress_data$Stress</code></p>
</section><section id="linear-models-in-r" class="level2" data-number="21.3"><h2 data-number="21.3" class="anchored" data-anchor-id="linear-models-in-r">
<span class="header-section-number">21.3</span> Linear models in R</h2>
<p>Let’s run the model we introduced in the last section. Note that instead of specifying the data frame for each variable, I can place it in the <code>data=</code> argument.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lnSymptoms</span><span class="op">~</span><span class="va">Stress</span>,data <span class="op">=</span> <span class="va">stress_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnSymptoms ~ Stress, data = stress_data)

Coefficients:
(Intercept)       Stress  
   4.300537     0.008565  </code></pre>
</div>
</div>
<p>This output gives us our <code>intercept</code> and <code>slope</code> coefficients. That said, theirs more lurking behind this output. The resulting output of the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function is an <code>object</code> with the class <code>lm</code>. This simply means that R understands that this object is storing a linear model. Hiding behind this spartan output is a multitude of info that may be accessed via its <code>attributes</code> or it may be thrown into other functions for additional info and analysis. <strong>My tip… GET IN THE HABIT OF SAVING (ASSIGNING) YOUR MODELS</strong>. In this case let’s assign the model we just ran to <code>stress_symptoms_model</code></p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stress_symptoms_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lnSymptoms</span><span class="op">~</span><span class="va">Stress</span>,data <span class="op">=</span> <span class="va">stress_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="attributes-of-class-lm" class="level3" data-number="21.3.1"><h3 data-number="21.3.1" class="anchored" data-anchor-id="attributes-of-class-lm">
<span class="header-section-number">21.3.1</span> Attributes of class <code>lm</code>:</h3>
<p>As I mentioned above, <code>lm</code> objects contain various attributes that may be accessed using the names convention, <code>$nameOfAttribute</code>.</p>
<p>For example, returning to the <code>stress_symptoms_model</code> object we created above, we may get a glimpse of its attributes by:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/attributes.html">attributes</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$names
 [1] "coefficients"  "residuals"     "effects"       "rank"         
 [5] "fitted.values" "assign"        "qr"            "df.residual"  
 [9] "xlevels"       "call"          "terms"         "model"        

$class
[1] "lm"</code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stress_symptoms_model</span><span class="op">$</span><span class="va">residuals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           1            2            3            4            5            6 
 0.037639323  0.011508729  0.004407164 -0.223337657  0.278938976  0.262339353 
           7            8            9           10           11           12 
-0.216226628  0.008264362 -0.193462063  0.204051115  0.133337343 -0.155679251 
          13           14           15           16           17           18 
-0.045884469  0.028334551 -0.155679251 -0.254621647 -0.137363093  0.016773551 
          19           20           21           22           23           24 
 0.357607907  0.243820353 -0.282917628  0.033932947 -0.064990034  0.407257917 
          25           26           27           28           29           30 
 0.003404758  0.021897739  0.035071937  0.189244294  0.108281966 -0.013123706 
          31           32           33           34           35           36 
-0.234484836  0.219322294 -0.176332459 -0.030854449 -0.183458251  0.262268521 
          37           38           39           40           41           42 
-0.239353647 -0.046311261  0.101345155 -0.107814044 -0.140097291 -0.370393063 
          43           44           45           46           47           48 
 0.021897739  0.166111353  0.126967897  0.032561729  0.073479541  0.006251511 
          49           50           51           52           53           54 
-0.160091093 -0.033866242 -0.089593420  0.110316333  0.082044343 -0.038040440 
          55           56           57           58           59           60 
-0.009426726 -0.070215895  0.026507135 -0.206792222 -0.215357024 -0.055546449 
          61           62           63           64           65           66 
-0.291503706 -0.136643865  0.003404758  0.126759115 -0.043850103  0.088591947 
          67           68           69           70           71           72 
 0.140416947 -0.274251885  0.356359125 -0.034559647  0.004783570 -0.172322132 
          73           74           75           76           77           78 
-0.163087291  0.006961956  0.306215758 -0.100953836 -0.017485657  0.066205125 
          79           80           81           82           83           84 
-0.029852044  0.100660511 -0.239370083 -0.066710063 -0.070121261 -0.134714420 
          85           86           87           88           89           90 
 0.278938976  0.092780353  0.251559956 -0.428892905  0.105060560  0.039027343 
          91           92           93           94           95           96 
 0.054768927  0.350241155 -0.170835232 -0.025250034  0.053197164  0.031945917 
          97           98           99          100          101          102 
-0.175912826 -0.011625261  0.058350768  0.233516155  0.338095135 -0.055170044 
         103          104          105          106          107 
-0.308985677  0.228080145  0.052651115  0.076727164  0.042924729 </code></pre>
</div>
</div>
<p>This command tells us the names of several attributes (values) that are stored in <code>stress_symptoms_model</code>. Typically we are interested in the <code>$coefficients</code>, <code>fitted.values</code> (aka <em>predicted values</em>), and <code>$residuals</code>. Recall that in our model <code>fitted.values</code> are the predicted values of <strong>lnSymptoms</strong> for each value of <strong>Stress</strong>, that is those values that fall along the line of best fit. <code>residuals</code> are the difference between our observed values of <strong>lnSymptoms</strong> and those predicted by the model. Mathematically <code>stress_symptoms_model$residuals</code> is equivalent to:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stress_data</span><span class="op">$</span><span class="va">lnSymptoms</span> <span class="op">-</span> <span class="va">stress_symptoms_model</span><span class="op">$</span><span class="va">fitted.values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="testing-the-residuals" class="level3" data-number="21.3.2"><h3 data-number="21.3.2" class="anchored" data-anchor-id="testing-the-residuals">
<span class="header-section-number">21.3.2</span> Testing the residuals</h3>
<p>An important assumption test for our model is that the residuals are normally distributed. In fact some argue that this is more important than than having normal distributions in the raw data itself. Quickly, we can test this using the regular methods:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">$</span><span class="va">residuals</span>,breaks <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span>
<span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/qqPlot.html">qqPlot</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu">show</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Question: Run a Shapiro-Wilkes test on our <code>stress_symptoms_model</code> residuals. How do we feel about the residuals here?</strong></p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># test the stress_symptoms_model residulas</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll return to diagnosing your regression model for violations of your assumptions (normality &amp; heteroscadicity) in an an upcoming walkthrough. For now, I just wanted to use this as an example of extracting values from your model.</p>
</section><section id="using-your-lm-object-with-other-functions" class="level3" data-number="21.3.3"><h3 data-number="21.3.3" class="anchored" data-anchor-id="using-your-lm-object-with-other-functions">
<span class="header-section-number">21.3.3</span> Using your <code>lm</code> object with other functions</h3>
<p>As I mentioned above you may also use <code>lm</code> objects with other functions. For example, for our model <code>stress_symptoms_model</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnSymptoms ~ Stress, data = stress_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42889 -0.13568  0.00478  0.09672  0.40726 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.300537   0.033088 129.974  &lt; 2e-16 ***
Stress      0.008565   0.001342   6.382 4.83e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1726 on 105 degrees of freedom
Multiple R-squared:  0.2795,    Adjusted R-squared:  0.2726 
F-statistic: 40.73 on 1 and 105 DF,  p-value: 4.827e-09</code></pre>
</div>
</div>
<p>provides us with info about the coefficients, their standard error, <em>t</em>-scores, and corresponding p-values (Pr&gt;|t|). It also provides us with our <span class="math inline">\(r^2\)</span> and adjusted <span class="math inline">\(r_{adj}^2\)</span> (which corresponds to our <span class="math inline">\(r\)</span> and <span class="math inline">\(r_{adj}\)</span> from above).</p>
<p>Coincidentally we can also call the individual attributes of this summary as well:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/attributes.html">attributes</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$names
 [1] "call"          "terms"         "residuals"     "coefficients" 
 [5] "aliased"       "sigma"         "df"            "r.squared"    
 [9] "adj.r.squared" "fstatistic"    "cov.unscaled" 

$class
[1] "summary.lm"</code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error    t value      Pr(&gt;|t|)
(Intercept) 4.300536618 0.033087547 129.974478 8.085268e-118
Stress      0.008564802 0.001342063   6.381819  4.827486e-09</code></pre>
</div>
</div>
<p>For what it’s worth, Bodo Winter (optional text) is a fan of using the <code>tidy</code> function from the <code>broom</code> package to clean up the output. I prefer <code>summary</code> but can understand the desire for clean and to the point output.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">broom</span><span class="op">)</span></span>
<span><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  4.30      0.0331     130.   8.09e-118
2 Stress       0.00856   0.00134      6.38 4.83e-  9</code></pre>
</div>
</div>
</section></section><section id="a-note-on-degrees-of-freedom-of-our-model" class="level2" data-number="21.4"><h2 data-number="21.4" class="anchored" data-anchor-id="a-note-on-degrees-of-freedom-of-our-model">
<span class="header-section-number">21.4</span> A note on degrees of freedom of our model</h2>
<p>The general equation for calculating the requisite degrees of freedom of a model is <span class="math inline">\(n-k\)</span> where <span class="math inline">\(n\)</span> is the number of observations (or later conditions) and <span class="math inline">\(k\)</span> is the number of parameters that are required to be known for the calculation.</p>
<p>Recall how we calculate variance / standard deviation. We take the sum of the squared deviations from the <em>mean</em> <span class="math inline">\(\sum(X-\bar{X})\)</span> and divide by <span class="math inline">\((n-1)\)</span>. Remember that we are subtracting that 1 because in order to calculate the variance we must keep one thing constant, the <strong>mean</strong>. In this case the <strong>mean</strong> is our parameter that must be known in order to calculate the variance.</p>
<p>We can now ask the question “what must be known in order to derive the line of best fit?”, or more simply what must one know in order to create a particular line. We must know <strong>both</strong> the line’s <strong>slope</strong> and its <strong>intercept</strong>. Knowing slope alone leads to the indeterminism presented in Fig A (identical slopes, infinitely-many intercepts), intercept alone leads to indeterminism presented in Fig B (identical intercept, infinitely-many slopes). We need <strong>both</strong> to define a particular line. Just like the <strong>mean</strong> above, these are the two parameters that must be <em>locked-in</em> to derive our model.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="5_3_regressions_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>A simple way of restating this is that your model degrees of freedom are the: <span class="math display">\[number \space of \space observations -  number \space of \space predictors\]</span></p>
<p>where at least one of your predictors is used as a constant (the intercept) and the remainder provide your <span class="math inline">\(\beta\)</span> coefficients.</p>
<p>For simple regression we have 1 predictor and 1 constant so our degrees of freedom are <span class="math inline">\(n-k\)</span>; where <span class="math inline">\(k=2\)</span>. However, in your future <strong>there be be dragons</strong>… models that may have multiple predictors and multiple intercepts (multiple regression, mixed effects / multi-level models, etc). Indeed, using <code>df</code> may not even make much sense in such cases, and there are arguments about how to even calculate them in the first place.</p>
</section><section id="interpreting-the-output" class="level2" data-number="21.5"><h2 data-number="21.5" class="anchored" data-anchor-id="interpreting-the-output">
<span class="header-section-number">21.5</span> Interpreting the output</h2>
<p>With our plot in hand, we can return to our <code>summary(stress_symptoms_model)</code> output:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnSymptoms ~ Stress, data = stress_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42889 -0.13568  0.00478  0.09672  0.40726 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.300537   0.033088 129.974  &lt; 2e-16 ***
Stress      0.008565   0.001342   6.382 4.83e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1726 on 105 degrees of freedom
Multiple R-squared:  0.2795,    Adjusted R-squared:  0.2726 
F-statistic: 40.73 on 1 and 105 DF,  p-value: 4.827e-09</code></pre>
</div>
</div>
<ul>
<li><p><strong>Call</strong>: tells us the formula we originally input for this model</p></li>
<li><p><strong>Residuals</strong>: descriptive stats of the residuals</p></li>
<li><p><strong>Coefficients</strong>: provides the estimated values, standard error of the estimates, and NHST of the intercept and beta coefficient. In both cases the null hypothesis is Estimate = 0. Again for the intercept this may or may not be useful. For example you might use it to test whether people who haven’t had a single drink of alcohol have no depression at all. The test of <code>beta</code> tests against the null hypothesis of zero correlation (relationship). All tests are conducted provided the t-value on <span class="math inline">\(n-k\)</span> degrees of freedom (see next bullet point)</p></li>
<li><p><strong>Residual standard error</strong>: This is calculated by first getting the sum of the squared residuals and dividing that number by the degrees of freedom of the model. In this case the df equals the number of total observations (107) minus the number of parameters (<span class="math inline">\(k\)</span>) that were calculated by the model in order to generate the predicted values (2). This may be interpreted as a measure of goodness of fit of the model, and perhaps more importantly its predictive value. This value is closely tied to Cohen Chapter 10 “The Variance of the Estimate”, but rather than the denominator being <span class="math inline">\(N\)</span>, it is the degrees of freedom for the model. In this way it speaks more directly to the model itself.</p></li>
<li><p><strong>Multiple R-squared</strong> and <strong>Adjusted R-squared</strong>: The <strong>coefficient of determination</strong> calculated from <span class="math inline">\(r\)</span> or <span class="math inline">\(r_{adj}\)</span>. <span class="math inline">\(r^2\)</span> tells us the degree to which our model accounts for observed variance in the observed outcomes. On was to think about this is, to what degree does variation in our predictor explain the observed variation in our outcomes. More on this below.</p></li>
<li><p>Finally, this output gives is the resulting <span class="math inline">\(F\)</span>-ratio and corresponding <span class="math inline">\(df\)</span> for an <span class="math inline">\(F\)</span>-test. This is a significance test for our <span class="math inline">\(r^2\)</span>. Does our model explain a significant amount of the variance?</p></li>
</ul></section><section id="the-coeff.-of-determination-as-index-of-explanatory-value" class="level2" data-number="21.6"><h2 data-number="21.6" class="anchored" data-anchor-id="the-coeff.-of-determination-as-index-of-explanatory-value">
<span class="header-section-number">21.6</span> The coeff. of determination as index of explanatory value</h2>
<p>Here we may turn to a (a little bit longer than expected) digression involving J.S. Mill and <em>exact</em> and <em>inexact</em> sciences. One philosophical conceit is that we can never really empirically observe causes, but only effects. That is, I can never truly observe that one billiard ball <em>caused</em> another to move, I can only say with a high degree of certainty that I observed the first billiard ball striking the second and subsequently the second moved at a particular velocity. In order to deal with this epistemological crisis (how can you really ever know anything!!!) we build explanatory models. The degree to which our model is able to account for the range of our previous observations tells us how useful our model parameters (predictors) are in explaining a phenomenon in question.</p>
<p>For example, to explain what I observe about the contact and subsequent motion of billiard balls I might build a model that takes into account the mass and velocity (speed and direction) of the first ball, the mass and velocity of the second ball and the point and angle of contact. Presuming I use these as predictors, I can account with varying degrees of success the heading and direction of the balls, or the <em>outcome</em>. In fact, in this example, I’m likely to be very successful in describing most, <strong>but not all</strong> observed outcomes. That is, there are some variations in the outcomes that just using these parameters does not result in a successful account. I can refine my <em>billiard contact model</em> to include things like the friction caused from the felt, the force of gravity, the angle of the table top, etc., and it’s likely the case that with each new predictor my model becomes better. However at some point I begin to reach diminishing returns (see over-fitting next semester).</p>
<p>This is why physics <em>appears</em> to be an exact science (well, mechanical physics at least). They’ve had centuries to develop and refine their models about the mechanical workings of our very local corner of the universe to the point that these models are able to account for a very high degree of variation in observed phenomena. These models typically have a very high <span class="math inline">\(r^2\)</span> and as such tend to have high predictive value. Which is why with some understanding of gravitational force, mass, and a few simple calculations, high school students all over country are able to do <a href="https://www.youtube.com/watch?v=46CJmWlxfck">this</a> in their physics lab.</p>
<p>Indeed within some disciplines having an <span class="math inline">\(r^2\)</span> &lt; .9 means you model isn’t good enough. Typically this is the case when the phenomenon under observation is not complex (hope that doesn’t offend). As you move away from physics and chemistry (or at least the low complexity phenomena under each discipline), the explanatory value of models tends to decrease. Us folks in the social sciences, we are moving into inexact-science-land. Weather patterns, economies, ecosystems, and human behaviors are highly complex; in many cases in inordinate number of contributing factors may be present in an observed outcome. As a result degree of variation that these models may account for is typically diminished, especially in the social sciences. For example depending on the phenomena and sub-discipline, an <span class="math inline">\(r^2\)</span> of .3 might mean you’re cooking with gas! In fact, for some phenomena, a reported <span class="math inline">\(r^2\)</span> that is too high might be a cause for suspicion (“they weren’t so much cooking with gas so much as they were cooking the books”).</p>
<p>As a final note, its typically poor practice to get a significant <span class="math inline">\(r^2\)</span> and just stop there. Remember, this is just a claim that your model accounts for significantly more variation than 0%. If you were to have a model that accounted for 6% (<span class="math inline">\(r^2 = .06\)</span>) of the variance but was significant (<span class="math inline">\(p&lt;.05\)</span>), you need to ask yourself whether that model is useful at all. It certainly has very little predictive value (I wouldn’t bet my life… or even a few bills on it predicting a future outcome), and its true explanatory value is quite questionable.</p>
<p><img src="https://imgs.xkcd.com/comics/linear_regression.png" class="img-fluid"></p>
<p>For what it’s worth, this isn’t just a joke. I can point to a paper from my field that was published in a very prominent journal (**cough Psych Science) that reported just this… a <span class="math inline">\(r^2\)</span> of about .08.</p>
</section><section id="write-up-and-presentation" class="level2" data-number="21.7"><h2 data-number="21.7" class="anchored" data-anchor-id="write-up-and-presentation">
<span class="header-section-number">21.7</span> Write up and presentation</h2>
<p>Our obtained results can be reported in several different ways. However, typically it’s best practice to report both the <span class="math inline">\(beta\)</span> (<span class="math inline">\(b\)</span>) coefficient with corresponding <span class="math inline">\(t-test\)</span>; as well as the general statistics about the model including the <span class="math inline">\(r^2\)</span> and corresponding <span class="math inline">\(F-test\)</span>. Prior to any reporting of the stats, you also need to articulate the structure of the model.</p>
<p>I think a good template to start from is:</p>
<blockquote class="blockquote">
<p>“[Clearly restate the alternative hypothesis identifying operationalized variables]. To test this hypothesis the data were [what type of analysis?] with [what is your dv] as the outcome and [what is your predictor] as our predictor. The resulting model was significant, <span class="math inline">\(r^2\)</span>=0.XX; <span class="math inline">\(F\)</span>(df1,df2)=F-ratio, <span class="math inline">\(p\)</span>=p-value and revealed a significant relationship between the [covariables], <span class="math inline">\(b\)</span>=XX; <span class="math inline">\(t\)</span>(df)=XX, <span class="math inline">\(p\)</span>=XX$.”</p>
</blockquote>
<p>Returning to our <code>stress_symptoms_model</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnSymptoms ~ Stress, data = stress_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42889 -0.13568  0.00478  0.09672  0.40726 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.300537   0.033088 129.974  &lt; 2e-16 ***
Stress      0.008565   0.001342   6.382 4.83e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1726 on 105 degrees of freedom
Multiple R-squared:  0.2795,    Adjusted R-squared:  0.2726 
F-statistic: 40.73 on 1 and 105 DF,  p-value: 4.827e-09</code></pre>
</div>
</div>
<p>For example, with this data you may report it as:</p>
<blockquote class="blockquote">
<p>“We hypothesized that increases in self-reported measures of Stress would correspond to increases in the number of self-reported symptoms. Given that our Symptoms data showed a significant violation of the normality assumption, we transformed these scores using a log-transformation (lnSymptoms). To test this hypothesis the data were submitted to a simple linear regression with lnSymptoms as the outcome and Stress as our predictor. The resulting model was significant, <span class="math inline">\(r^2\)</span>=.28; <span class="math inline">\(F\)</span>(1,105)=40.73, <span class="math inline">\(p\)</span>&lt;.001, and revealed a significant positive relationship between the Stress and Symptoms, <span class="math inline">\(b\)</span>=.008; <span class="math inline">\(t\)</span>(105)=6.38, <span class="math inline">\(p\)</span>&lt;.001.”</p>
</blockquote>
<section id="reporting-standardized-beta" class="level3" data-number="21.7.1"><h3 data-number="21.7.1" class="anchored" data-anchor-id="reporting-standardized-beta">
<span class="header-section-number">21.7.1</span> Reporting standardized <span class="math inline">\(\beta\)</span>
</h3>
<p>That said, in many circles it’s typical practice to report the <em>standardized</em> <span class="math inline">\(beta\)</span> coefficients (<span class="math inline">\(\beta\)</span>). These are the <span class="math inline">\(beta\)</span> coefficients we would have obtained if we had initially converted both our <em>Stress</em> and <em>lnSymptom</em> values to <span class="math inline">\(z\)</span>-scores, and then ran the model using those <span class="math inline">\(z\)</span>-scores. For example, let’s add z-transformed values for both to our original dataframe</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stress_data</span> <span class="op">&lt;-</span> <span class="va">stress_data</span> <span class="op">%&gt;%</span> <span class="fu">mutate</span><span class="op">(</span>z_Stress <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">Stress</span><span class="op">)</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>,</span>
<span>                                      z_lnSymptoms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">lnSymptoms</span><span class="op">)</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now run the model (piping to a tidy output)</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">z_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">z_lnSymptoms</span> <span class="op">~</span> <span class="va">z_Stress</span>, data <span class="op">=</span> <span class="va">stress_data</span><span class="op">)</span></span>
<span><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">z_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term         estimate std.error statistic       p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;
1 (Intercept) -7.07e-16    0.0824 -8.58e-15 1.00         
2 z_Stress     5.29e- 1    0.0828  6.38e+ 0 0.00000000483</code></pre>
</div>
</div>
<p>That said, you don’t <strong>NEED</strong> to do the z-transform by hand. We can retroactively obtain these coefficients from raw values by using the <code>lm.beta()</code> function from the <code>lm.beta</code> package (duplicate names, confusing I know). We can then input our model into the <code>lm.beta()</code> function and get the summary of those results. The new column <strong>std_estimate</strong> is reported in addition to the <strong>estimate</strong>:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">lm.beta</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># this is the raw data model you ran earlier</span></span>
<span><span class="va">stress_symptoms_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lnSymptoms</span> <span class="op">~</span> <span class="va">Stress</span>, data <span class="op">=</span> <span class="va">stress_data</span><span class="op">)</span></span>
<span><span class="fu">lm.beta</span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  term        estimate std_estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  4.30          NA       0.0331     130.   8.09e-118
2 Stress       0.00856        0.529   0.00134      6.38 4.83e-  9</code></pre>
</div>
</div>
<p>Note that if you are using <code>summary</code> rather than <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code> then the <code>lm.beta</code> output looks like this:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lm.beta</span><span class="op">(</span><span class="va">stress_symptoms_model</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnSymptoms ~ Stress, data = stress_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42889 -0.13568  0.00478  0.09672  0.40726 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.300537           NA   0.033088 129.974  &lt; 2e-16 ***
Stress      0.008565     0.528656   0.001342   6.382 4.83e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1726 on 105 degrees of freedom
Multiple R-squared:  0.2795,    Adjusted R-squared:  0.2726 
F-statistic: 40.73 on 1 and 105 DF,  p-value: 4.827e-09</code></pre>
</div>
</div>
<p>So amending the example reporting paragraph above:</p>
<blockquote class="blockquote">
<p>The resulting model was significant, <span class="math inline">\(r^2\)</span>=.28; <span class="math inline">\(F\)</span>(1,105)=40.73, <span class="math inline">\(p\)</span>&lt;.001, and revealed a significant positive relationship between the Stress and Symptoms, <span class="math inline">\(\beta =.528\)</span>; <span class="math inline">\(t(105)=6.38\)</span>, <span class="math inline">\(p&lt;.001\)</span>.”</p>
</blockquote>
<p>Coincidentally you may have noticed that this <span class="math inline">\(\beta\)</span> value is the correlation that we established in the previous walkthrough! Quickly:</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">stress_data</span><span class="op">$</span><span class="va">Stress</span>, <span class="va">stress_data</span><span class="op">$</span><span class="va">lnSymptoms</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5286565</code></pre>
</div>
</div>
<p>As explained by Barry Cohen (in his useful textbook that I didn’t have you buy…):</p>
<blockquote class="blockquote">
<p>if you have already tested the Pearson’s <span class="math inline">\(r\)</span> against zero, there is no need to test the corresponding <span class="math inline">\(b\)</span>, as the <span class="math inline">\(t\)</span> values will be exactly the same (except for rounding error) for both tests”. More, a test on <span class="math inline">\(b\)</span> is equivalent to a test on <span class="math inline">\(r\)</span> in the one-predictor case. If it is true that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are related, then it must also be true that <span class="math inline">\(Y\)</span> varies with <span class="math inline">\(X\)</span>—that is, that the slope is nonzero. This suggests that a test on <span class="math inline">\(b\)</span> (beta coefficient) will produce the same answer as a test on <span class="math inline">\(r\)</span>, and we could dispense with a test for <span class="math inline">\(b\)</span> altogether.</p>
</blockquote>
<p>The reverse is also true. In the single predictor case, if one has a test of <span class="math inline">\(b\)</span> this obviates the need to run an independent test of <span class="math inline">\(r\)</span>. The output of <code>lm</code> provides us with a simple test that gives us the significance of the beta coefficient, <span class="math inline">\(b\)</span>.</p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../week05/5_2_correlations.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../week05/5_4_plotting.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Plotting regression data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb38" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Regression, pt. 1: Running the model"</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>Please note that this walkthrough assumes that you have the following packages installed and loaded in R:</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(car, <span class="co"># qqPlot function</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>               cowplot, <span class="co"># apa plotting</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>               tidyverse, <span class="co"># tidyverse goodness</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>               psych, <span class="co"># descriptive stats</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>               lm.beta, <span class="co"># getting a standard coefficient</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>               broom, <span class="co"># tidy lm output</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>               olsrr <span class="co"># testing heteroscadicity.</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>               ) </span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fitting the data to a model</span></span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>As social scientists, we are not only concerned with observation, but also with explanation. Measures of correlation provide us with the former; we use regression methods to build models in service of the latter. Again both the assigned texts provide excellent overviews of regression, so I won't repeat much of what they say here.</span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>For the purposes of this vignette (and this course) we will limit ourselves to linear regression, that is describing a line that best fits our data. By "fit" we mean a line than when compared to our observed data minimizes our squared residuals.</span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Relationship b/tw Stress and Health</span></span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a>Let's revisit our data from the first walk-through:</span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Wagner, Compas, and Howell (1988) investigated the relationship between stress and mental health in first-year college students. Using a scale they developed to measure the frequency, perceived importance, and desirability of recent life events, they created a measure of negative events weighted by the reported frequency and the respondent's subjective estimate of the impact of each event. This served as their measure of the subject's perceived social and environmental stress. They also asked students to complete the Hopkins Symptom Checklist, assessing the presence or absence of 57 psychological symptoms.</span></span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>This data can be accessed directly from this <span class="co">[</span><span class="ot">companion website</span><span class="co">](https://www.uvm.edu/~statdhtx/methods8/)</span> for Howell's stats textbook.</span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a>stress_data <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab9-2.dat"</span>)</span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(stress_data)</span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a>To perform a linear regression we may call upon the <span class="in">`lm()`</span> function. This function uses formula notation <span class="in">`outcome variable ~ predictor variable(s)`</span>. A simple regression has a single predictor. More often in our analyses we are concerned with the relative effects of multiple predictors, but this is multiple regression and saved for the Spring course. Here, we may be interested in the degree to which perceived **Stress** contributes to the number of **lnSymptons**, or using formula terminology: "How do lnSymptoms (outcome) vary as a function of Stress (predictor)". This is represented in R as <span class="in">`stress_data$lnSymptoms~stress_data$Stress`</span></span>
<span id="cb38-43"><a href="#cb38-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-44"><a href="#cb38-44" aria-hidden="true" tabindex="-1"></a><span class="fu">## Linear models in R</span></span>
<span id="cb38-45"><a href="#cb38-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-46"><a href="#cb38-46" aria-hidden="true" tabindex="-1"></a>Let's run the model we introduced in the last section. Note that instead of specifying the data frame for each variable, I can place it in the <span class="in">`data=`</span> argument.</span>
<span id="cb38-47"><a href="#cb38-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-48"><a href="#cb38-48" aria-hidden="true" tabindex="-1"></a><span class="in">```{r warning = FALSE}</span></span>
<span id="cb38-49"><a href="#cb38-49" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(lnSymptoms<span class="sc">~</span>Stress,<span class="at">data =</span> stress_data)</span>
<span id="cb38-50"><a href="#cb38-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-51"><a href="#cb38-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-52"><a href="#cb38-52" aria-hidden="true" tabindex="-1"></a>This output gives us our <span class="in">`intercept`</span> and <span class="in">`slope`</span> coefficients. That said, theirs more lurking behind this output. The resulting output of the <span class="in">`lm()`</span> function is an <span class="in">`object`</span> with the class <span class="in">`lm`</span>. This simply means that R understands that this object is storing a linear model. Hiding behind this spartan output is a multitude of info that may be accessed via its <span class="in">`attributes`</span> or it may be thrown into other functions for additional info and analysis. **My tip... GET IN THE HABIT OF SAVING (ASSIGNING) YOUR MODELS**. In this case let's assign the model we just ran to <span class="in">`stress_symptoms_model`</span></span>
<span id="cb38-53"><a href="#cb38-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-56"><a href="#cb38-56" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-57"><a href="#cb38-57" aria-hidden="true" tabindex="-1"></a>stress_symptoms_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(lnSymptoms<span class="sc">~</span>Stress,<span class="at">data =</span> stress_data)</span>
<span id="cb38-58"><a href="#cb38-58" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-59"><a href="#cb38-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-60"><a href="#cb38-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### Attributes of class `lm`:</span></span>
<span id="cb38-61"><a href="#cb38-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-62"><a href="#cb38-62" aria-hidden="true" tabindex="-1"></a>As I mentioned above, <span class="in">`lm`</span> objects contain various attributes that may be accessed using the names convention, <span class="in">`$nameOfAttribute`</span>.</span>
<span id="cb38-63"><a href="#cb38-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-64"><a href="#cb38-64" aria-hidden="true" tabindex="-1"></a>For example, returning to the <span class="in">`stress_symptoms_model`</span> object we created above, we may get a glimpse of its attributes by:</span>
<span id="cb38-65"><a href="#cb38-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-66"><a href="#cb38-66" aria-hidden="true" tabindex="-1"></a><span class="in">```{r warning = FALSE}</span></span>
<span id="cb38-67"><a href="#cb38-67" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(stress_symptoms_model)</span>
<span id="cb38-68"><a href="#cb38-68" aria-hidden="true" tabindex="-1"></a>stress_symptoms_model<span class="sc">$</span>residuals</span>
<span id="cb38-69"><a href="#cb38-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-70"><a href="#cb38-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-71"><a href="#cb38-71" aria-hidden="true" tabindex="-1"></a>This command tells us the names of several attributes (values) that are stored in <span class="in">`stress_symptoms_model`</span>. Typically we are interested in the <span class="in">`$coefficients`</span>, <span class="in">`fitted.values`</span> (aka *predicted values*), and `$residuals`. Recall that in our model `fitted.values` are the predicted values of **lnSymptoms** for each value of **Stress**, that is those values that fall along the line of best fit. `residuals` are the difference between our observed values of **lnSymptoms** and those predicted by the model. Mathematically <span class="in">`stress_symptoms_model$residuals`</span> is equivalent to:</span>
<span id="cb38-72"><a href="#cb38-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-73"><a href="#cb38-73" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eval=FALSE}</span></span>
<span id="cb38-74"><a href="#cb38-74" aria-hidden="true" tabindex="-1"></a>stress_data<span class="sc">$</span>lnSymptoms <span class="sc">-</span> stress_symptoms_model<span class="sc">$</span>fitted.values</span>
<span id="cb38-75"><a href="#cb38-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-76"><a href="#cb38-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-77"><a href="#cb38-77" aria-hidden="true" tabindex="-1"></a><span class="fu">### Testing the residuals</span></span>
<span id="cb38-78"><a href="#cb38-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-79"><a href="#cb38-79" aria-hidden="true" tabindex="-1"></a>An important assumption test for our model is that the residuals are normally distributed. In fact some argue that this is more important than than having normal distributions in the raw data itself. Quickly, we can test this using the regular methods:</span>
<span id="cb38-80"><a href="#cb38-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-81"><a href="#cb38-81" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eval=FALSE}</span></span>
<span id="cb38-82"><a href="#cb38-82" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(stress_symptoms_model<span class="sc">$</span>residuals,<span class="at">breaks =</span> <span class="dv">10</span>)</span>
<span id="cb38-83"><a href="#cb38-83" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(stress_symptoms_model<span class="sc">$</span>residuals) <span class="sc">%&gt;%</span> <span class="fu">show</span>()</span>
<span id="cb38-84"><a href="#cb38-84" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(stress_symptoms_model<span class="sc">$</span>residuals)</span>
<span id="cb38-85"><a href="#cb38-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-86"><a href="#cb38-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-87"><a href="#cb38-87" aria-hidden="true" tabindex="-1"></a>**Question: Run a Shapiro-Wilkes test on our `stress_symptoms_model` residuals. How do we feel about the residuals here?**</span>
<span id="cb38-88"><a href="#cb38-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-91"><a href="#cb38-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-92"><a href="#cb38-92" aria-hidden="true" tabindex="-1"></a><span class="co"># test the stress_symptoms_model residulas</span></span>
<span id="cb38-93"><a href="#cb38-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-94"><a href="#cb38-94" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-95"><a href="#cb38-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-96"><a href="#cb38-96" aria-hidden="true" tabindex="-1"></a>We'll return to diagnosing your regression model for violations of your assumptions (normality &amp; heteroscadicity) in an an upcoming walkthrough. For now, I just wanted to use this as an example of extracting values from your model.</span>
<span id="cb38-97"><a href="#cb38-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-98"><a href="#cb38-98" aria-hidden="true" tabindex="-1"></a><span class="fu">### Using your `lm` object with other functions</span></span>
<span id="cb38-99"><a href="#cb38-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-100"><a href="#cb38-100" aria-hidden="true" tabindex="-1"></a>As I mentioned above you may also use <span class="in">`lm`</span> objects with other functions. For example, for our model <span class="in">`stress_symptoms_model`</span>:</span>
<span id="cb38-101"><a href="#cb38-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-102"><a href="#cb38-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eval=TRUE}</span></span>
<span id="cb38-103"><a href="#cb38-103" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stress_symptoms_model)</span>
<span id="cb38-104"><a href="#cb38-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-105"><a href="#cb38-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-106"><a href="#cb38-106" aria-hidden="true" tabindex="-1"></a>provides us with info about the coefficients, their standard error, *t*-scores, and corresponding p-values (Pr<span class="sc">\&gt;</span>\|t\|). It also provides us with our $r^2$ and adjusted $r_{adj}^2$ (which corresponds to our $r$ and $r_{adj}$ from above).</span>
<span id="cb38-107"><a href="#cb38-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-108"><a href="#cb38-108" aria-hidden="true" tabindex="-1"></a>Coincidentally we can also call the individual attributes of this summary as well:</span>
<span id="cb38-109"><a href="#cb38-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-110"><a href="#cb38-110" aria-hidden="true" tabindex="-1"></a><span class="in">```{r warning = FALSE}</span></span>
<span id="cb38-111"><a href="#cb38-111" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stress_symptoms_model) <span class="sc">%&gt;%</span> <span class="fu">attributes</span>()</span>
<span id="cb38-112"><a href="#cb38-112" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stress_symptoms_model)<span class="sc">$</span>coefficients</span>
<span id="cb38-113"><a href="#cb38-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-114"><a href="#cb38-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-115"><a href="#cb38-115" aria-hidden="true" tabindex="-1"></a>For what it's worth, Bodo Winter (optional text) is a fan of using the <span class="in">`tidy`</span> function from the <span class="in">`broom`</span> package to clean up the output. I prefer <span class="in">`summary`</span> but can understand the desire for clean and to the point output.</span>
<span id="cb38-116"><a href="#cb38-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-119"><a href="#cb38-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-120"><a href="#cb38-120" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(broom)</span>
<span id="cb38-121"><a href="#cb38-121" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(stress_symptoms_model)</span>
<span id="cb38-122"><a href="#cb38-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-123"><a href="#cb38-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-124"><a href="#cb38-124" aria-hidden="true" tabindex="-1"></a><span class="fu">## A note on degrees of freedom of our model</span></span>
<span id="cb38-125"><a href="#cb38-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-126"><a href="#cb38-126" aria-hidden="true" tabindex="-1"></a>The general equation for calculating the requisite degrees of freedom of a model is $n-k$ where $n$ is the number of observations (or later conditions) and $k$ is the number of parameters that are required to be known for the calculation.</span>
<span id="cb38-127"><a href="#cb38-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-128"><a href="#cb38-128" aria-hidden="true" tabindex="-1"></a>Recall how we calculate variance / standard deviation. We take the sum of the squared deviations from the *mean* $\sum(X-\bar{X})$ and divide by $(n-1)$. Remember that we are subtracting that 1 because in order to calculate the variance we must keep one thing constant, the **mean**. In this case the **mean** is our parameter that must be known in order to calculate the variance.</span>
<span id="cb38-129"><a href="#cb38-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-130"><a href="#cb38-130" aria-hidden="true" tabindex="-1"></a>We can now ask the question "what must be known in order to derive the line of best fit?", or more simply what must one know in order to create a particular line. We must know **both** the line's **slope** and its **intercept**. Knowing slope alone leads to the indeterminism presented in Fig A (identical slopes, infinitely-many intercepts), intercept alone leads to indeterminism presented in Fig B (identical intercept, infinitely-many slopes). We need **both** to define a particular line. Just like the **mean** above, these are the two parameters that must be *locked-in* to derive our model.</span>
<span id="cb38-131"><a href="#cb38-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-132"><a href="#cb38-132" aria-hidden="true" tabindex="-1"></a><span class="in">```{r echo=FALSE, fig.height=4, fig.width=8}</span></span>
<span id="cb38-133"><a href="#cb38-133" aria-hidden="true" tabindex="-1"></a>figA <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb38-134"><a href="#cb38-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"y-intercept"</span>)<span class="sc">+</span></span>
<span id="cb38-135"><a href="#cb38-135" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>))<span class="sc">+</span><span class="fu">ylim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>))<span class="sc">+</span></span>
<span id="cb38-136"><a href="#cb38-136" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-137"><a href="#cb38-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-138"><a href="#cb38-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">3</span>), <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-139"><a href="#cb38-139" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>), <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-140"><a href="#cb38-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">9</span>), <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-141"><a href="#cb38-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">3</span>), <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-142"><a href="#cb38-142" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">6</span>), <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-143"><a href="#cb38-143" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">9</span>), <span class="at">slope=</span><span class="dv">1</span>)</span>
<span id="cb38-144"><a href="#cb38-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-145"><a href="#cb38-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-146"><a href="#cb38-146" aria-hidden="true" tabindex="-1"></a>figB <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb38-147"><a href="#cb38-147" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"y-intercept"</span>)<span class="sc">+</span></span>
<span id="cb38-148"><a href="#cb38-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>))<span class="sc">+</span><span class="fu">ylim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>))<span class="sc">+</span></span>
<span id="cb38-149"><a href="#cb38-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-150"><a href="#cb38-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span><span class="sc">-</span><span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb38-151"><a href="#cb38-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span><span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-152"><a href="#cb38-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span><span class="sc">-</span>.<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb38-153"><a href="#cb38-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span><span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb38-154"><a href="#cb38-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span>.<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb38-155"><a href="#cb38-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-156"><a href="#cb38-156" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">slope=</span><span class="fl">1.5</span>)</span>
<span id="cb38-157"><a href="#cb38-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-158"><a href="#cb38-158" aria-hidden="true" tabindex="-1"></a>cowplot<span class="sc">::</span><span class="fu">plot_grid</span>(figA,figB, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>))</span>
<span id="cb38-159"><a href="#cb38-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-160"><a href="#cb38-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-161"><a href="#cb38-161" aria-hidden="true" tabindex="-1"></a>A simple way of restating this is that your model degrees of freedom are the: $$number \space of \space observations -  number \space of \space predictors$$</span>
<span id="cb38-162"><a href="#cb38-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-163"><a href="#cb38-163" aria-hidden="true" tabindex="-1"></a>where at least one of your predictors is used as a constant (the intercept) and the remainder provide your $\beta$ coefficients.</span>
<span id="cb38-164"><a href="#cb38-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-165"><a href="#cb38-165" aria-hidden="true" tabindex="-1"></a>For simple regression we have 1 predictor and 1 constant so our degrees of freedom are $n-k$; where $k=2$. However, in your future **there be be dragons**... models that may have multiple predictors and multiple intercepts (multiple regression, mixed effects / multi-level models, etc). Indeed, using <span class="in">`df`</span> may not even make much sense in such cases, and there are arguments about how to even calculate them in the first place.</span>
<span id="cb38-166"><a href="#cb38-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-167"><a href="#cb38-167" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpreting the output</span></span>
<span id="cb38-168"><a href="#cb38-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-169"><a href="#cb38-169" aria-hidden="true" tabindex="-1"></a>With our plot in hand, we can return to our <span class="in">`summary(stress_symptoms_model)`</span> output:</span>
<span id="cb38-170"><a href="#cb38-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-173"><a href="#cb38-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-174"><a href="#cb38-174" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stress_symptoms_model)</span>
<span id="cb38-175"><a href="#cb38-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-176"><a href="#cb38-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-177"><a href="#cb38-177" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Call**: tells us the formula we originally input for this model</span>
<span id="cb38-178"><a href="#cb38-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-179"><a href="#cb38-179" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Residuals**: descriptive stats of the residuals</span>
<span id="cb38-180"><a href="#cb38-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-181"><a href="#cb38-181" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Coefficients**: provides the estimated values, standard error of the estimates, and NHST of the intercept and beta coefficient. In both cases the null hypothesis is Estimate = 0. Again for the intercept this may or may not be useful. For example you might use it to test whether people who haven't had a single drink of alcohol have no depression at all. The test of <span class="in">`beta`</span> tests against the null hypothesis of zero correlation (relationship). All tests are conducted provided the t-value on $n-k$ degrees of freedom (see next bullet point)</span>
<span id="cb38-182"><a href="#cb38-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-183"><a href="#cb38-183" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Residual standard error**: This is calculated by first getting the sum of the squared residuals and dividing that number by the degrees of freedom of the model. In this case the df equals the number of total observations (107) minus the number of parameters ($k$) that were calculated by the model in order to generate the predicted values (2). This may be interpreted as a measure of goodness of fit of the model, and perhaps more importantly its predictive value. This value is closely tied to Cohen Chapter 10 "The Variance of the Estimate", but rather than the denominator being $N$, it is the degrees of freedom for the model. In this way it speaks more directly to the model itself.</span>
<span id="cb38-184"><a href="#cb38-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-185"><a href="#cb38-185" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Multiple R-squared** and **Adjusted R-squared**: The **coefficient of determination** calculated from $r$ or $r_{adj}$. $r^2$ tells us the degree to which our model accounts for observed variance in the observed outcomes. On was to think about this is, to what degree does variation in our predictor explain the observed variation in our outcomes. More on this below.</span>
<span id="cb38-186"><a href="#cb38-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-187"><a href="#cb38-187" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Finally, this output gives is the resulting $F$-ratio and corresponding $df$ for an $F$-test. This is a significance test for our $r^2$. Does our model explain a significant amount of the variance?</span>
<span id="cb38-188"><a href="#cb38-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-189"><a href="#cb38-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## The coeff. of determination as index of explanatory value</span></span>
<span id="cb38-190"><a href="#cb38-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-191"><a href="#cb38-191" aria-hidden="true" tabindex="-1"></a>Here we may turn to a (a little bit longer than expected) digression involving J.S. Mill and *exact* and *inexact* sciences. One philosophical conceit is that we can never really empirically observe causes, but only effects. That is, I can never truly observe that one billiard ball *caused* another to move, I can only say with a high degree of certainty that I observed the first billiard ball striking the second and subsequently the second moved at a particular velocity. In order to deal with this epistemological crisis (how can you really ever know anything!!!) we build explanatory models. The degree to which our model is able to account for the range of our previous observations tells us how useful our model parameters (predictors) are in explaining a phenomenon in question.</span>
<span id="cb38-192"><a href="#cb38-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-193"><a href="#cb38-193" aria-hidden="true" tabindex="-1"></a>For example, to explain what I observe about the contact and subsequent motion of billiard balls I might build a model that takes into account the mass and velocity (speed and direction) of the first ball, the mass and velocity of the second ball and the point and angle of contact. Presuming I use these as predictors, I can account with varying degrees of success the heading and direction of the balls, or the *outcome*. In fact, in this example, I'm likely to be very successful in describing most, **but not all** observed outcomes. That is, there are some variations in the outcomes that just using these parameters does not result in a successful account. I can refine my *billiard contact model* to include things like the friction caused from the felt, the force of gravity, the angle of the table top, etc., and it's likely the case that with each new predictor my model becomes better. However at some point I begin to reach diminishing returns (see over-fitting next semester).</span>
<span id="cb38-194"><a href="#cb38-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-195"><a href="#cb38-195" aria-hidden="true" tabindex="-1"></a>This is why physics *appears* to be an exact science (well, mechanical physics at least). They've had centuries to develop and refine their models about the mechanical workings of our very local corner of the universe to the point that these models are able to account for a very high degree of variation in observed phenomena. These models typically have a very high $r^2$ and as such tend to have high predictive value. Which is why with some understanding of gravitational force, mass, and a few simple calculations, high school students all over country are able to do <span class="co">[</span><span class="ot">this</span><span class="co">](https://www.youtube.com/watch?v=46CJmWlxfck)</span> in their physics lab.</span>
<span id="cb38-196"><a href="#cb38-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-197"><a href="#cb38-197" aria-hidden="true" tabindex="-1"></a>Indeed within some disciplines having an $r^2$ <span class="sc">\&lt;</span> .9 means you model isn't good enough. Typically this is the case when the phenomenon under observation is not complex (hope that doesn't offend). As you move away from physics and chemistry (or at least the low complexity phenomena under each discipline), the explanatory value of models tends to decrease. Us folks in the social sciences, we are moving into inexact-science-land. Weather patterns, economies, ecosystems, and human behaviors are highly complex; in many cases in inordinate number of contributing factors may be present in an observed outcome. As a result degree of variation that these models may account for is typically diminished, especially in the social sciences. For example depending on the phenomena and sub-discipline, an $r^2$ of .3 might mean you're cooking with gas! In fact, for some phenomena, a reported $r^2$ that is too high might be a cause for suspicion ("they weren't so much cooking with gas so much as they were cooking the books").</span>
<span id="cb38-198"><a href="#cb38-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-199"><a href="#cb38-199" aria-hidden="true" tabindex="-1"></a>As a final note, its typically poor practice to get a significant $r^2$ and just stop there. Remember, this is just a claim that your model accounts for significantly more variation than 0%. If you were to have a model that accounted for 6% ($r^2 = .06$) of the variance but was significant ($p&lt;.05$), you need to ask yourself whether that model is useful at all. It certainly has very little predictive value (I wouldn't bet my life... or even a few bills on it predicting a future outcome), and its true explanatory value is quite questionable.</span>
<span id="cb38-200"><a href="#cb38-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-201"><a href="#cb38-201" aria-hidden="true" tabindex="-1"></a><span class="al">![](https://imgs.xkcd.com/comics/linear_regression.png)</span></span>
<span id="cb38-202"><a href="#cb38-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-203"><a href="#cb38-203" aria-hidden="true" tabindex="-1"></a>For what it's worth, this isn't just a joke. I can point to a paper from my field that was published in a very prominent journal (<span class="sc">\*\*</span>cough Psych Science) that reported just this... a $r^2$ of about .08.</span>
<span id="cb38-204"><a href="#cb38-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-205"><a href="#cb38-205" aria-hidden="true" tabindex="-1"></a><span class="fu">## Write up and presentation</span></span>
<span id="cb38-206"><a href="#cb38-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-207"><a href="#cb38-207" aria-hidden="true" tabindex="-1"></a>Our obtained results can be reported in several different ways. However, typically it's best practice to report both the $beta$ ($b$) coefficient with corresponding $t-test$; as well as the general statistics about the model including the $r^2$ and corresponding $F-test$. Prior to any reporting of the stats, you also need to articulate the structure of the model.</span>
<span id="cb38-208"><a href="#cb38-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-209"><a href="#cb38-209" aria-hidden="true" tabindex="-1"></a>I think a good template to start from is:</span>
<span id="cb38-210"><a href="#cb38-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-211"><a href="#cb38-211" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; "</span><span class="sc">\[</span><span class="at">Clearly restate the alternative hypothesis identifying operationalized variables</span><span class="sc">\]</span><span class="at">. To test this hypothesis the data were </span><span class="sc">\[</span><span class="at">what type of analysis?</span><span class="sc">\]</span><span class="at"> with </span><span class="sc">\[</span><span class="at">what is your dv</span><span class="sc">\]</span><span class="at"> as the outcome and </span><span class="sc">\[</span><span class="at">what is your predictor</span><span class="sc">\]</span><span class="at"> as our predictor. The resulting model was significant, $r^2$=0.XX; $F$(df1,df2)=F-ratio, $p$=p-value and revealed a significant relationship between the </span><span class="sc">\[</span><span class="at">covariables</span><span class="sc">\]</span><span class="at">, $b$=XX; $t$(df)=XX, $p$=XX\$."</span></span>
<span id="cb38-212"><a href="#cb38-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-213"><a href="#cb38-213" aria-hidden="true" tabindex="-1"></a>Returning to our <span class="in">`stress_symptoms_model`</span>:</span>
<span id="cb38-214"><a href="#cb38-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-217"><a href="#cb38-217" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-218"><a href="#cb38-218" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stress_symptoms_model)</span>
<span id="cb38-219"><a href="#cb38-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-220"><a href="#cb38-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-221"><a href="#cb38-221" aria-hidden="true" tabindex="-1"></a>For example, with this data you may report it as:</span>
<span id="cb38-222"><a href="#cb38-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-223"><a href="#cb38-223" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; "We hypothesized that increases in self-reported measures of Stress would correspond to increases in the number of self-reported symptoms. Given that our Symptoms data showed a significant violation of the normality assumption, we transformed these scores using a log-transformation (lnSymptoms). To test this hypothesis the data were submitted to a simple linear regression with lnSymptoms as the outcome and Stress as our predictor. The resulting model was significant, $r^2$=.28; $F$(1,105)=40.73, $p$</span><span class="sc">\&lt;</span><span class="at">.001, and revealed a significant positive relationship between the Stress and Symptoms, $b$=.008; $t$(105)=6.38, $p$</span><span class="sc">\&lt;</span><span class="at">.001."</span></span>
<span id="cb38-224"><a href="#cb38-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-225"><a href="#cb38-225" aria-hidden="true" tabindex="-1"></a><span class="fu">### Reporting standardized $\beta$</span></span>
<span id="cb38-226"><a href="#cb38-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-227"><a href="#cb38-227" aria-hidden="true" tabindex="-1"></a>That said, in many circles it's typical practice to report the *standardized* $beta$ coefficients ($\beta$). These are the $beta$ coefficients we would have obtained if we had initially converted both our *Stress* and *lnSymptom* values to $z$-scores, and then ran the model using those $z$-scores. For example, let's add z-transformed values for both to our original dataframe</span>
<span id="cb38-228"><a href="#cb38-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-231"><a href="#cb38-231" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-232"><a href="#cb38-232" aria-hidden="true" tabindex="-1"></a>stress_data <span class="ot">&lt;-</span> stress_data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">z_Stress =</span> <span class="fu">scale</span>(Stress)[,<span class="dv">1</span>],</span>
<span id="cb38-233"><a href="#cb38-233" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">z_lnSymptoms =</span> <span class="fu">scale</span>(lnSymptoms)[,<span class="dv">1</span>])</span>
<span id="cb38-234"><a href="#cb38-234" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-235"><a href="#cb38-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-236"><a href="#cb38-236" aria-hidden="true" tabindex="-1"></a>And now run the model (piping to a tidy output)</span>
<span id="cb38-237"><a href="#cb38-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-240"><a href="#cb38-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-241"><a href="#cb38-241" aria-hidden="true" tabindex="-1"></a>z_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(z_lnSymptoms <span class="sc">~</span> z_Stress, <span class="at">data =</span> stress_data)</span>
<span id="cb38-242"><a href="#cb38-242" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(z_model)</span>
<span id="cb38-243"><a href="#cb38-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-244"><a href="#cb38-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-245"><a href="#cb38-245" aria-hidden="true" tabindex="-1"></a>That said, you don't **NEED** to do the z-transform by hand. We can retroactively obtain these coefficients from raw values by using the `lm.beta()` function from the `lm.beta` package (duplicate names, confusing I know). We can then input our model into the `lm.beta()` function and get the summary of those results. The new column **std_estimate** is reported in addition to the **estimate**:</span>
<span id="cb38-246"><a href="#cb38-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-249"><a href="#cb38-249" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-250"><a href="#cb38-250" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(lm.beta)</span>
<span id="cb38-251"><a href="#cb38-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-252"><a href="#cb38-252" aria-hidden="true" tabindex="-1"></a><span class="co"># this is the raw data model you ran earlier</span></span>
<span id="cb38-253"><a href="#cb38-253" aria-hidden="true" tabindex="-1"></a>stress_symptoms_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(lnSymptoms <span class="sc">~</span> Stress, <span class="at">data =</span> stress_data)</span>
<span id="cb38-254"><a href="#cb38-254" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.beta</span>(stress_symptoms_model) <span class="sc">%&gt;%</span> broom<span class="sc">::</span><span class="fu">tidy</span>()</span>
<span id="cb38-255"><a href="#cb38-255" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-256"><a href="#cb38-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-257"><a href="#cb38-257" aria-hidden="true" tabindex="-1"></a>Note that if you are using <span class="in">`summary`</span> rather than <span class="in">`broom::tidy()`</span> then the <span class="in">`lm.beta`</span> output looks like this:</span>
<span id="cb38-258"><a href="#cb38-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-261"><a href="#cb38-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-262"><a href="#cb38-262" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.beta</span>(stress_symptoms_model) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb38-263"><a href="#cb38-263" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-264"><a href="#cb38-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-265"><a href="#cb38-265" aria-hidden="true" tabindex="-1"></a>So amending the example reporting paragraph above:</span>
<span id="cb38-266"><a href="#cb38-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-267"><a href="#cb38-267" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The resulting model was significant, $r^2$=.28; $F$(1,105)=40.73, $p$</span><span class="sc">\&lt;</span><span class="at">.001, and revealed a significant positive relationship between the Stress and Symptoms, $\beta =.528$; $t(105)=6.38$, $p&lt;.001$."</span></span>
<span id="cb38-268"><a href="#cb38-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-269"><a href="#cb38-269" aria-hidden="true" tabindex="-1"></a>Coincidentally you may have noticed that this $\beta$ value is the correlation that we established in the previous walkthrough! Quickly:</span>
<span id="cb38-270"><a href="#cb38-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-273"><a href="#cb38-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-274"><a href="#cb38-274" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(stress_data<span class="sc">$</span>Stress, stress_data<span class="sc">$</span>lnSymptoms)</span>
<span id="cb38-275"><a href="#cb38-275" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-276"><a href="#cb38-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-277"><a href="#cb38-277" aria-hidden="true" tabindex="-1"></a>As explained by Barry Cohen (in his useful textbook that I didn't have you buy...):</span>
<span id="cb38-278"><a href="#cb38-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-279"><a href="#cb38-279" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; if you have already tested the Pearson's $r$ against zero, there is no need to test the corresponding $b$, as the $t$ values will be exactly the same (except for rounding error) for both tests". More, a test on $b$ is equivalent to a test on $r$ in the one-predictor case. If it is true that $X$ and $Y$ are related, then it must also be true that $Y$ varies with $X$---that is, that the slope is nonzero. This suggests that a test on $b$ (beta coefficient) will produce the same answer as a test on $r$, and we could dispense with a test for $b$ altogether.</span></span>
<span id="cb38-280"><a href="#cb38-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-281"><a href="#cb38-281" aria-hidden="true" tabindex="-1"></a>The reverse is also true. In the single predictor case, if one has a test of $b$ this obviates the need to run an independent test of $r$. The output of <span class="in">`lm`</span> provides us with a simple test that gives us the significance of the beta coefficient, $b$.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Written by <a href="https://tehrandav.is">Tehran Davis</a> of PSYC 7014.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>