<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>tehrandav.is - More examples of distributions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-sidebar floating nav-fixed">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">tehrandav.is</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="https://tehrandav.is">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">More examples of distributions</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./walkthroughs.html" class="sidebar-item-text sidebar-link">PSYC 7014</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">TOPIC 1 INTRO to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week01/1_1-Rmarkdown_basics.html" class="sidebar-item-text sidebar-link">Rmarkdown Basics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week01/1_2-objects_assignment_functions.html" class="sidebar-item-text sidebar-link">Objects, assignment, and functions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week01/1_3-install_packages.html" class="sidebar-item-text sidebar-link">Installing and loading an <code>R</code> package</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week01/1_4-loading_data.html" class="sidebar-item-text sidebar-link">Loading in Data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week01/1_5-leveling-up.html" class="sidebar-item-text sidebar-link">Leveling-up</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">TOPIC 2: DESCRIPTIVE STATS and CENTRAL TENDENCY</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week02/2_1-structure_data.html" class="sidebar-item-text sidebar-link">The structure of your data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week02/2_2-central_tendency.html" class="sidebar-item-text sidebar-link">Measures of central tendency</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week02/2_3-summary_tables.html" class="sidebar-item-text sidebar-link">Creating summary tables</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week02/2_4-means_other_models.html" class="sidebar-item-text sidebar-link">Means and other models</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">TOPIC 3: DATA VISUALIZATION</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week03/3_1-basic_ggplot.html" class="sidebar-item-text sidebar-link">Basic ggplotting</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week03/3_2-more_adv_ggplot.html" class="sidebar-item-text sidebar-link">More advanced ggPlots</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">TOPIC 4: DISTRIBUTIONS and NHST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week04/4_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link">The normal distribution</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week04/4_2-building_intuitions_about_probability_and_nhst.html" class="sidebar-item-text sidebar-link">Building intuitions about probability and NHST</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.html" class="sidebar-item-text sidebar-link">Sampling distributions and seeing the logic of NHST</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week04/4_4-more_examples.html" class="sidebar-item-text sidebar-link">More examples of distributions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week04/4_5-bias_variance.html" class="sidebar-item-text sidebar-link">Bias in sample variance estimates</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">TOPIC 5: CORRELATION AND REGRESSION</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05/5_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link">The normal distribution</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05/5_2_correlations.html" class="sidebar-item-text sidebar-link">Correlations</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05/5_3_regressions.html" class="sidebar-item-text sidebar-link">Regression, pt.&nbsp;1: Running the model</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05/5_4_plotting.html" class="sidebar-item-text sidebar-link">Plotting regression data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05/5_5_diagnostics.html" class="sidebar-item-text sidebar-link">Regression model diagnostics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05/5_6_example_report.html" class="sidebar-item-text sidebar-link">Example Report</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">TOPIC 6: T-TESTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week06/6_1_t-test.html" class="sidebar-item-text sidebar-link">Testing differences in means / t-test</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week06/6_2_t-test-null-model.html" class="sidebar-item-text sidebar-link">Thinking about nothing (aka the null)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week06/6_3_t-test-lm.html" class="sidebar-item-text sidebar-link">t-test? It’s just a linear model</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">TOPIC 7: POWER &amp; EFFECT SIZES</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week07/7_1-effect_size.html" class="sidebar-item-text sidebar-link">Effect Size</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week07/7_2-power.html" class="sidebar-item-text sidebar-link">Power</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week07/7_3-power_es_sig_tests.html" class="sidebar-item-text sidebar-link">Power, Effect sizes, and Significance testing</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week07/7_4-simulating_power.html" class="sidebar-item-text sidebar-link">Simulating Power!!!</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">TOPIC 8: INTRO to ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week08/8_1-one-way-anova.html" class="sidebar-item-text sidebar-link">The One-way ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week08/8_2-anova-regression.html" class="sidebar-item-text sidebar-link">ANOVA and Regression</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">TOPIC 9: ANOVA: CONTRASTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week09/9_1-posthocs.html" class="sidebar-item-text sidebar-link">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week09/9_2-planned_contrasts.html" class="sidebar-item-text sidebar-link">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">TOPIC 10: ANOVA: FACTORIAL ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week10/10_1-main_effects.html" class="sidebar-item-text sidebar-link">Factorial ANOVA - The omnibus ANOVA and Main effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week10/10_2-factorial_w_post_hocs.html" class="sidebar-item-text sidebar-link">Factorial ANOVA - Post hoc analysis of Main effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week10/10_3-advanced_example_and_apa.html" class="sidebar-item-text sidebar-link">Template for Analysis &amp; APA Style</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">TOPIC 11: ANOVA + INTERACTIONS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week11/11_1-interactions.html" class="sidebar-item-text sidebar-link">Analysis of Variance: the Factorial ANOVA - Interactions &amp; Simple Effects ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week11/11_2-higher_order_anova.html" class="sidebar-item-text sidebar-link">Dealing with Higher Order Factorial ANOVA</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">TOPIC 12: WITHIN SUBJECTS / REPEATED MEASURES ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week12/12_1-afex_ANOVA.html" class="sidebar-item-text sidebar-link">afex is for ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week12/12_2-repeated_measures_anova.html" class="sidebar-item-text sidebar-link">Within Subjects / Repeated Measures ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week12/12_3-factorial_rma.html" class="sidebar-item-text sidebar-link">Factorial RM-ANOVA and simple effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week12/12_4-sphericity.html" class="sidebar-item-text sidebar-link">Sphericity: Variances and Co-Variances</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week12/12_5-spss_rma.html" class="sidebar-item-text sidebar-link">Running a RM-ANOVA in SPSS</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">TOPIC 13: MIXED ANOVA (BS + WS)</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week13/13_1-mixed_effects_anova.html" class="sidebar-item-text sidebar-link">Mixed-effects ANOVA (BS + WS)</a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#distributions" id="toc-distributions" class="nav-link active" data-scroll-target="#distributions">Distributions</a>
  <ul class="collapse">
<li><a href="#population-distribution" id="toc-population-distribution" class="nav-link" data-scroll-target="#population-distribution">Population distribution</a></li>
  <li><a href="#sample" id="toc-sample" class="nav-link" data-scroll-target="#sample">Sample</a></li>
  <li><a href="#sampling-distribution" id="toc-sampling-distribution" class="nav-link" data-scroll-target="#sampling-distribution">Sampling Distribution</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">More examples of distributions</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="distributions" class="level1"><h1>Distributions</h1>
<p>This week you’ve encountered the notion of the distribution, which is just a way of describing all of the scores in a given set. We typically describe distributions in terms of tallies. For example if we were looking at the distribution of heights in a given group, the distribution would describe the number of individuals within that group that were a certain height (or more likely within a range of heights). I like to focus on distributions as having three different classifications.</p>
<ul>
<li><p>population: the distribution of all scores of EVERYONE in an entire population, you almost NEVER have access to this.</p></li>
<li><p>sample: the empirically observed distribution of scores from a selected group (sample) within a population (this is what we typically have access to as scientists)</p></li>
<li><p>and, theoretical: a distribution that is derived from certain principles or assumptions by logical and mathematical reasoning, as opposed to one derived from real-world data obtained by empirical research (see APA). For example the normal distribution, Poisson distribution, the F-distribution, etc.</p></li>
</ul>
<p>In this walkthrough we are going to use <code>R</code> to visualize the relationship between three types of distributions that are going to be particularly relevant for you this week:</p>
<section id="population-distribution" class="level2"><h2 class="anchored" data-anchor-id="population-distribution">Population distribution</h2>
<p>We’re just extrapolate to play around with some numbers from this website: https://ourworldindata.org/human-height. According to this website the average height of men in North America (from 1996) is about 177 cm, with a standard deviation of 7.49. Height, it turns out is normally distributed.</p>
<p>Let’s just assume those numbers hold for the US. There are about 151 million men in the US. On my machine it would takes <code>R</code> about 10 secs to generate a distribution of 151 million heights with the above criteria, but it also eats up about 1.2 GB of RAM. Given that not everyone has 32GB of RAM laying around on their laptops, let’s just create a population of 1 million men (depending on your machine this might take a few seconds:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>population_heights <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000000</span>, <span class="at">mean =</span> <span class="dv">177</span>,<span class="at">sd =</span> <span class="fl">7.49</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Congrats, in a matter of seconds you’ve created a population of 1 million heights! Before doing so, let’s turn this into a data frame / tibble containing columns for person and their corresponding height:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2"></a>person_id <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000000</span></span>
<span id="cb2-3"><a href="#cb2-3"></a></span>
<span id="cb2-4"><a href="#cb2-4"></a>pop_mens_heights <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">person =</span> person_id,</span>
<span id="cb2-5"><a href="#cb2-5"></a>                      <span class="at">height =</span> population_heights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a look at this distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(cowplot)</span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> pop_mens_heights,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>height)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">1000000</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="4_4-more_examples_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>And getting our summary stats for this population</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(psych)</span>
<span id="cb4-2"><a href="#cb4-2"></a>psych<span class="sc">::</span><span class="fu">describe</span>(pop_mens_heights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vars     n     mean        sd   median  trimmed      mad    min
person    1 1e+06 500000.5 288675.28 500000.5 500000.5 370650.0   1.00
height    2 1e+06    177.0      7.49    177.0    177.0      7.5 137.77
             max     range skew kurtosis     se
person 1000000.0 999999.00    0     -1.2 288.68
height     214.1     76.33    0      0.0   0.01</code></pre>
</div>
</div>
</section><section id="sample" class="level2"><h2 class="anchored" data-anchor-id="sample">Sample</h2>
<p>Of course we don’t have time or money to go around getting the height of 1 million men. Instead we get a sample of 25 from our population, <code>pop_men_heights</code>.</p>
<p>We can do this by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># get a sample of heights</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>sample_mens_heights <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights, <span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb6-3"><a href="#cb6-3"></a>sample_mens_heights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 2
   person height
    &lt;int&gt;  &lt;dbl&gt;
 1 114883   187.
 2 140272   169.
 3 237481   159.
 4 811253   181.
 5 462344   166.
 6 657291   175.
 7 311193   177.
 8 643017   180.
 9 348107   164.
10 113025   179.
# ℹ 15 more rows</code></pre>
</div>
</div>
<p>Now, let’s take a look at the distribution and the summary stats of our sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># histogram</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sample_mens_heights,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>height)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">25</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="4_4-more_examples_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># summary stats</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample_mens_heights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vars  n      mean        sd    median   trimmed       mad     min
person    1 25 411220.32 317849.75 348107.00 404184.67 437233.57 1068.00
height    2 25    177.32      9.33    177.57    177.14      9.65  158.87
             max     range skew kurtosis       se
person 907985.00 906917.00 0.19    -1.65 63569.95
height    196.17     37.29 0.16    -0.68     1.87</code></pre>
</div>
</div>
<p>Two things:</p>
<p>First, related to <code>R</code>, your histogram and summary stats are likely different from mine. This is because <code>sample_n()</code> pulls a random sample. If you resample the data using <code>sample_n()</code> you’re going to get different numbers every time around. FWIW, <strong>this is also true when we are getting our samples in research</strong>. To ensure that our numbers are identical we need to set the seed—set the manner <code>R</code> “randomly” (nothing in a computer is truly random) selects its sample. For example, if we rerun our sample using this code, our numbers will match:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># setting the seed to 2021</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="fu">set.seed</span>(<span class="dv">2021</span>)</span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="co"># get a sample of heights</span></span>
<span id="cb11-5"><a href="#cb11-5"></a>sample_mens_heights <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights, <span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb11-6"><a href="#cb11-6"></a></span>
<span id="cb11-7"><a href="#cb11-7"></a><span class="co"># histogram</span></span>
<span id="cb11-8"><a href="#cb11-8"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sample_mens_heights,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>height)) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">25</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb11-10"><a href="#cb11-10"></a>  <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="4_4-more_examples_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="co"># summary stats</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample_mens_heights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vars  n      mean        sd   median  trimmed       mad      min
person    1 25 589528.52 282701.81 643236.0 602575.9 364602.47 66630.00
height    2 25    180.66      7.19    181.7    180.7      6.39   163.64
             max     range  skew kurtosis       se
person 976624.00 909994.00 -0.30    -1.23 56540.36
height    194.79     31.15 -0.15    -0.05     1.44</code></pre>
</div>
</div>
<p>Second, tied to the conceptual material (and related to the discussion above), you’ll note that the distribution of heights in your sample is not identical to the population. This will be true for any sample that you take—the sample statistics are not identical to the population statistics. What we hope is that they are close enough that our sample approximates the population within a certain tolerance. More, no two samples are going to be exactly alike:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">set.seed</span>(<span class="dv">2021</span>)</span>
<span id="cb14-2"><a href="#cb14-2"></a>sample1 <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights,<span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb14-3"><a href="#cb14-3"></a>sample2 <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights,<span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb14-4"><a href="#cb14-4"></a></span>
<span id="cb14-5"><a href="#cb14-5"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vars  n      mean        sd   median  trimmed       mad      min
person    1 25 589528.52 282701.81 643236.0 602575.9 364602.47 66630.00
height    2 25    180.66      7.19    181.7    180.7      6.39   163.64
             max     range  skew kurtosis       se
person 976624.00 909994.00 -0.30    -1.23 56540.36
height    194.79     31.15 -0.15    -0.05     1.44</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vars  n      mean        sd   median   trimmed       mad      min    max
person    1 25 428057.16 308820.34 353637.0 415141.71 360989.38 14244.00 967537
height    2 25    177.56      7.36    178.7    177.77      8.35   162.28    189
           range  skew kurtosis       se
person 953293.00  0.38    -1.30 61764.07
height     26.72 -0.25    -0.96     1.47</code></pre>
</div>
</div>
<p>The fact that summary statistics vary from sample to sample, leads us to our next kind of distribution… the sampling distribution.</p>
</section><section id="sampling-distribution" class="level2"><h2 class="anchored" data-anchor-id="sampling-distribution">Sampling Distribution</h2>
<p>The sampling distribution is a distribution built by the sampling and resampling of a population. A sampling distribution of a statistic shows every possible result that statistic can take in every possible sample from a population and how often each result happens. In practice, the generic characteristics of a sampling distribution are theoretical. That is they are developed by applying some small amount of observation to establish fundamental, and ultimately abstract principles. As an example, the <strong>normal distribution</strong> is a theoretical distribution that states that for any (approximately) randomly occurring measurement, such as height, a given percentage of scores should fall within specific ranges from the mean. Indeed, we’ve already generated a normal distribution in this walkthrough when we created our population. The function <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> generates a normal distribution of <code>n</code> scores, data with a prescribed <code>mean</code> and <code>sd</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span> <span class="fu">hist</span>(., <span class="at">main =</span> <span class="st">"Randomly generated normal distribution"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="4_4-more_examples_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Returning to the Sampling Distribution, one claim is that if we were to sample and resample a population to infinity, the <strong>Sampling Distribution of Means</strong> (i.e.&nbsp;the distribution of those sample means) would be normal. More the the mean of this Sampling Distribution of Means should be identical to the population mean (177.0).</p>
<p>Obviously we can’t get an infinite number of samples, so this assumption / claim is based on underlying mathematical principles and formalisms. BUT… one of the nice things about computers is that while we can’t go to infinity, we can perform a really high number of samples. Let’s generate a sampling distribution of means by taking one-hundred-thousand different samples from our population of men, where each sample is 25 men</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># imagine taking a hundred thousand different samples...</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>number_of_samples <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb19-3"><a href="#cb19-3"></a></span>
<span id="cb19-4"><a href="#cb19-4"></a><span class="co"># where each sample is 25 men</span></span>
<span id="cb19-5"><a href="#cb19-5"></a>N <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb19-6"><a href="#cb19-6"></a></span>
<span id="cb19-7"><a href="#cb19-7"></a>sampling_dist_means <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">num =</span> <span class="dv">1</span><span class="sc">:</span>number_of_samples) <span class="sc">%&gt;%</span> </span>
<span id="cb19-8"><a href="#cb19-8"></a>    <span class="fu">group_by</span>(num) <span class="sc">%&gt;%</span> </span>
<span id="cb19-9"><a href="#cb19-9"></a>  <span class="co"># using sample for a vector, rather than sample_n for a data frame (tibble)</span></span>
<span id="cb19-10"><a href="#cb19-10"></a>    <span class="fu">mutate</span>(<span class="at">sample_means =</span> <span class="fu">mean</span>(<span class="fu">sample</span>(pop_mens_heights<span class="sc">$</span>height, <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb19-11"><a href="#cb19-11"></a>           )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at our sampling distribution of means:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># histogram</span></span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sampling_dist_means,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>sample_means)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">10000</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb20-4"><a href="#cb20-4"></a>  <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="4_4-more_examples_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># summary stats</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sampling_dist_means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             vars     n    mean       sd   median trimmed      mad    min
num             1 1e+05 50000.5 28867.66 50000.50 50000.5 37065.00   1.00
sample_means    2 1e+05   177.0     1.49   177.01   177.0     1.49 170.07
                   max    range skew kurtosis    se
num          100000.00 99999.00    0     -1.2 91.29
sample_means    183.65    13.59    0      0.0  0.00</code></pre>
</div>
</div>
<p>Look at that!</p>
<p>One last bit with the <strong>Sampling Distribution of Means</strong>. The standard deviation of the <strong>Sampling Distribution of Means</strong> is known as the <strong>standard error</strong>. You may have likely encountered this term before as a measure of confidence of the mean of your sample as it relates to the true mean of the population. When working with a given sample, standard error is approximated as the standard deviation of the sample divided-by the square root of the number of scores…</p>
<p><span class="math display">\[\frac{standard\space deviation}{N}\]</span> For example the standard error for this single sample is <span class="math inline">\(7.54/\sqrt{25}\)</span> or 7.54/5 or 1.51. Note that <code><a href="https://rdrr.io/pkg/psych/man/describe.html">psych::describe()</a></code> produces the <code>se</code> at the send of its table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">set.seed</span>(<span class="dv">2021</span>)</span>
<span id="cb23-2"><a href="#cb23-2"></a><span class="fu">sample_n</span>(pop_mens_heights,<span class="at">size =</span> <span class="dv">25</span>) <span class="sc">%&gt;%</span> psych<span class="sc">::</span><span class="fu">describe</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vars  n      mean        sd   median  trimmed       mad      min
person    1 25 589528.52 282701.81 643236.0 602575.9 364602.47 66630.00
height    2 25    180.66      7.19    181.7    180.7      6.39   163.64
             max     range  skew kurtosis       se
person 976624.00 909994.00 -0.30    -1.23 56540.36
height    194.79     31.15 -0.15    -0.05     1.44</code></pre>
</div>
</div>
<p>In this case the standard error of the sample (1.51) is pretty close to the standard deviation of the sampling distribution (1.49). Given that we are dividing by <span class="math inline">\(\sqrt{N}\)</span> it should be apparent that the standard error decreases as we increase or sample size. Thus, with increase sample size we are more confident that a given sample accurately represents the whole population.</p>
<p>Try rerunning the code, but this time with sample sizes of 5, 50, and 500. What happens to your distributions and your measures of central tendency?</p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb25" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb25-1"><a href="#cb25-1"></a><span class="co">---</span></span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="an">title:</span><span class="co"> "More examples of distributions"</span></span>
<span id="cb25-3"><a href="#cb25-3"></a><span class="co">---</span></span>
<span id="cb25-4"><a href="#cb25-4"></a></span>
<span id="cb25-5"><a href="#cb25-5"></a><span class="fu"># Distributions</span></span>
<span id="cb25-6"><a href="#cb25-6"></a></span>
<span id="cb25-7"><a href="#cb25-7"></a>This week you've encountered the notion of the distribution, which is just a way of describing all of the scores in a given set. We typically describe distributions in terms of tallies. For example if we were looking at the distribution of heights in a given group, the distribution would describe the number of individuals within that group that were a certain height (or more likely within a range of heights). I like to focus on distributions as having three different classifications.</span>
<span id="cb25-8"><a href="#cb25-8"></a></span>
<span id="cb25-9"><a href="#cb25-9"></a><span class="ss">-   </span>population: the distribution of all scores of EVERYONE in an entire population, you almost NEVER have access to this.</span>
<span id="cb25-10"><a href="#cb25-10"></a></span>
<span id="cb25-11"><a href="#cb25-11"></a><span class="ss">-   </span>sample: the empirically observed distribution of scores from a selected group (sample) within a population (this is what we typically have access to as scientists)</span>
<span id="cb25-12"><a href="#cb25-12"></a></span>
<span id="cb25-13"><a href="#cb25-13"></a><span class="ss">-   </span>and, theoretical: a distribution that is derived from certain principles or assumptions by logical and mathematical reasoning, as opposed to one derived from real-world data obtained by empirical research (see APA). For example the normal distribution, Poisson distribution, the F-distribution, etc.</span>
<span id="cb25-14"><a href="#cb25-14"></a></span>
<span id="cb25-15"><a href="#cb25-15"></a>In this walkthrough we are going to use <span class="in">`R`</span> to visualize the relationship between three types of distributions that are going to be particularly relevant for you this week:</span>
<span id="cb25-16"><a href="#cb25-16"></a></span>
<span id="cb25-17"><a href="#cb25-17"></a><span class="fu">## Population distribution</span></span>
<span id="cb25-18"><a href="#cb25-18"></a></span>
<span id="cb25-19"><a href="#cb25-19"></a>We're just extrapolate to play around with some numbers from this website: https://ourworldindata.org/human-height. According to this website the average height of men in North America (from 1996) is about 177 cm, with a standard deviation of 7.49. Height, it turns out is normally distributed.</span>
<span id="cb25-20"><a href="#cb25-20"></a></span>
<span id="cb25-21"><a href="#cb25-21"></a>Let's just assume those numbers hold for the US. There are about 151 million men in the US. On my machine it would takes <span class="in">`R`</span> about 10 secs to generate a distribution of 151 million heights with the above criteria, but it also eats up about 1.2 GB of RAM. Given that not everyone has 32GB of RAM laying around on their laptops, let's just create a population of 1 million men (depending on your machine this might take a few seconds:</span>
<span id="cb25-22"><a href="#cb25-22"></a></span>
<span id="cb25-25"><a href="#cb25-25"></a><span class="in">```{r}</span></span>
<span id="cb25-26"><a href="#cb25-26"></a>population_heights <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000000</span>, <span class="at">mean =</span> <span class="dv">177</span>,<span class="at">sd =</span> <span class="fl">7.49</span>)</span>
<span id="cb25-27"><a href="#cb25-27"></a><span class="in">```</span></span>
<span id="cb25-28"><a href="#cb25-28"></a></span>
<span id="cb25-29"><a href="#cb25-29"></a>Congrats, in a matter of seconds you've created a population of 1 million heights! Before doing so, let's turn this into a data frame / tibble containing columns for person and their corresponding height:</span>
<span id="cb25-30"><a href="#cb25-30"></a></span>
<span id="cb25-33"><a href="#cb25-33"></a><span class="in">```{r}</span></span>
<span id="cb25-34"><a href="#cb25-34"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse)</span>
<span id="cb25-35"><a href="#cb25-35"></a>person_id <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000000</span></span>
<span id="cb25-36"><a href="#cb25-36"></a></span>
<span id="cb25-37"><a href="#cb25-37"></a>pop_mens_heights <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">person =</span> person_id,</span>
<span id="cb25-38"><a href="#cb25-38"></a>                      <span class="at">height =</span> population_heights)</span>
<span id="cb25-39"><a href="#cb25-39"></a><span class="in">```</span></span>
<span id="cb25-40"><a href="#cb25-40"></a></span>
<span id="cb25-41"><a href="#cb25-41"></a>Let's take a look at this distribution.</span>
<span id="cb25-42"><a href="#cb25-42"></a></span>
<span id="cb25-45"><a href="#cb25-45"></a><span class="in">```{r}</span></span>
<span id="cb25-46"><a href="#cb25-46"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(cowplot)</span>
<span id="cb25-47"><a href="#cb25-47"></a><span class="fu">ggplot</span>(<span class="at">data =</span> pop_mens_heights,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>height)) <span class="sc">+</span></span>
<span id="cb25-48"><a href="#cb25-48"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">1000000</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb25-49"><a href="#cb25-49"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb25-50"><a href="#cb25-50"></a><span class="in">```</span></span>
<span id="cb25-51"><a href="#cb25-51"></a></span>
<span id="cb25-52"><a href="#cb25-52"></a>And getting our summary stats for this population</span>
<span id="cb25-53"><a href="#cb25-53"></a></span>
<span id="cb25-56"><a href="#cb25-56"></a><span class="in">```{r}</span></span>
<span id="cb25-57"><a href="#cb25-57"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(psych)</span>
<span id="cb25-58"><a href="#cb25-58"></a>psych<span class="sc">::</span><span class="fu">describe</span>(pop_mens_heights)</span>
<span id="cb25-59"><a href="#cb25-59"></a><span class="in">```</span></span>
<span id="cb25-60"><a href="#cb25-60"></a></span>
<span id="cb25-61"><a href="#cb25-61"></a><span class="fu">## Sample</span></span>
<span id="cb25-62"><a href="#cb25-62"></a></span>
<span id="cb25-63"><a href="#cb25-63"></a>Of course we don't have time or money to go around getting the height of 1 million men. Instead we get a sample of 25 from our population, <span class="in">`pop_men_heights`</span>.</span>
<span id="cb25-64"><a href="#cb25-64"></a></span>
<span id="cb25-65"><a href="#cb25-65"></a>We can do this by:</span>
<span id="cb25-66"><a href="#cb25-66"></a></span>
<span id="cb25-69"><a href="#cb25-69"></a><span class="in">```{r}</span></span>
<span id="cb25-70"><a href="#cb25-70"></a><span class="co"># get a sample of heights</span></span>
<span id="cb25-71"><a href="#cb25-71"></a>sample_mens_heights <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights, <span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb25-72"><a href="#cb25-72"></a>sample_mens_heights</span>
<span id="cb25-73"><a href="#cb25-73"></a><span class="in">```</span></span>
<span id="cb25-74"><a href="#cb25-74"></a></span>
<span id="cb25-75"><a href="#cb25-75"></a>Now, let's take a look at the distribution and the summary stats of our sample:</span>
<span id="cb25-76"><a href="#cb25-76"></a></span>
<span id="cb25-79"><a href="#cb25-79"></a><span class="in">```{r}</span></span>
<span id="cb25-80"><a href="#cb25-80"></a><span class="co"># histogram</span></span>
<span id="cb25-81"><a href="#cb25-81"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sample_mens_heights,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>height)) <span class="sc">+</span></span>
<span id="cb25-82"><a href="#cb25-82"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">25</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb25-83"><a href="#cb25-83"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb25-84"><a href="#cb25-84"></a></span>
<span id="cb25-85"><a href="#cb25-85"></a><span class="co"># summary stats</span></span>
<span id="cb25-86"><a href="#cb25-86"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample_mens_heights)</span>
<span id="cb25-87"><a href="#cb25-87"></a><span class="in">```</span></span>
<span id="cb25-88"><a href="#cb25-88"></a></span>
<span id="cb25-89"><a href="#cb25-89"></a>Two things:</span>
<span id="cb25-90"><a href="#cb25-90"></a></span>
<span id="cb25-91"><a href="#cb25-91"></a>First, related to <span class="in">`R`</span>, your histogram and summary stats are likely different from mine. This is because <span class="in">`sample_n()`</span> pulls a random sample. If you resample the data using <span class="in">`sample_n()`</span> you're going to get different numbers every time around. FWIW, **this is also true when we are getting our samples in research**. To ensure that our numbers are identical we need to set the seed---set the manner <span class="in">`R`</span> "randomly" (nothing in a computer is truly random) selects its sample. For example, if we rerun our sample using this code, our numbers will match:</span>
<span id="cb25-92"><a href="#cb25-92"></a></span>
<span id="cb25-95"><a href="#cb25-95"></a><span class="in">```{r}</span></span>
<span id="cb25-96"><a href="#cb25-96"></a><span class="co"># setting the seed to 2021</span></span>
<span id="cb25-97"><a href="#cb25-97"></a><span class="fu">set.seed</span>(<span class="dv">2021</span>)</span>
<span id="cb25-98"><a href="#cb25-98"></a></span>
<span id="cb25-99"><a href="#cb25-99"></a><span class="co"># get a sample of heights</span></span>
<span id="cb25-100"><a href="#cb25-100"></a>sample_mens_heights <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights, <span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb25-101"><a href="#cb25-101"></a></span>
<span id="cb25-102"><a href="#cb25-102"></a><span class="co"># histogram</span></span>
<span id="cb25-103"><a href="#cb25-103"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sample_mens_heights,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>height)) <span class="sc">+</span></span>
<span id="cb25-104"><a href="#cb25-104"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">25</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb25-105"><a href="#cb25-105"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb25-106"><a href="#cb25-106"></a></span>
<span id="cb25-107"><a href="#cb25-107"></a><span class="co"># summary stats</span></span>
<span id="cb25-108"><a href="#cb25-108"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample_mens_heights)</span>
<span id="cb25-109"><a href="#cb25-109"></a><span class="in">```</span></span>
<span id="cb25-110"><a href="#cb25-110"></a></span>
<span id="cb25-111"><a href="#cb25-111"></a>Second, tied to the conceptual material (and related to the discussion above), you'll note that the distribution of heights in your sample is not identical to the population. This will be true for any sample that you take---the sample statistics are not identical to the population statistics. What we hope is that they are close enough that our sample approximates the population within a certain tolerance. More, no two samples are going to be exactly alike:</span>
<span id="cb25-112"><a href="#cb25-112"></a></span>
<span id="cb25-115"><a href="#cb25-115"></a><span class="in">```{r}</span></span>
<span id="cb25-116"><a href="#cb25-116"></a><span class="fu">set.seed</span>(<span class="dv">2021</span>)</span>
<span id="cb25-117"><a href="#cb25-117"></a>sample1 <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights,<span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb25-118"><a href="#cb25-118"></a>sample2 <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(pop_mens_heights,<span class="at">size =</span> <span class="dv">25</span>)</span>
<span id="cb25-119"><a href="#cb25-119"></a></span>
<span id="cb25-120"><a href="#cb25-120"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample1)</span>
<span id="cb25-121"><a href="#cb25-121"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sample2)</span>
<span id="cb25-122"><a href="#cb25-122"></a><span class="in">```</span></span>
<span id="cb25-123"><a href="#cb25-123"></a></span>
<span id="cb25-124"><a href="#cb25-124"></a>The fact that summary statistics vary from sample to sample, leads us to our next kind of distribution... the sampling distribution.</span>
<span id="cb25-125"><a href="#cb25-125"></a></span>
<span id="cb25-126"><a href="#cb25-126"></a><span class="fu">## Sampling Distribution</span></span>
<span id="cb25-127"><a href="#cb25-127"></a></span>
<span id="cb25-128"><a href="#cb25-128"></a>The sampling distribution is a distribution built by the sampling and resampling of a population. A sampling distribution of a statistic shows every possible result that statistic can take in every possible sample from a population and how often each result happens. In practice, the generic characteristics of a sampling distribution are theoretical. That is they are developed by applying some small amount of observation to establish fundamental, and ultimately abstract principles. As an example, the **normal distribution** is a theoretical distribution that states that for any (approximately) randomly occurring measurement, such as height, a given percentage of scores should fall within specific ranges from the mean. Indeed, we've already generated a normal distribution in this walkthrough when we created our population. The function <span class="in">`rnorm()`</span> generates a normal distribution of <span class="in">`n`</span> scores, data with a prescribed <span class="in">`mean`</span> and <span class="in">`sd`</span>:</span>
<span id="cb25-129"><a href="#cb25-129"></a></span>
<span id="cb25-132"><a href="#cb25-132"></a><span class="in">```{r}</span></span>
<span id="cb25-133"><a href="#cb25-133"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span> <span class="fu">hist</span>(., <span class="at">main =</span> <span class="st">"Randomly generated normal distribution"</span>)</span>
<span id="cb25-134"><a href="#cb25-134"></a><span class="in">```</span></span>
<span id="cb25-135"><a href="#cb25-135"></a></span>
<span id="cb25-136"><a href="#cb25-136"></a>Returning to the Sampling Distribution, one claim is that if we were to sample and resample a population to infinity, the **Sampling Distribution of Means** (i.e. the distribution of those sample means) would be normal. More the the mean of this Sampling Distribution of Means should be identical to the population mean (177.0).</span>
<span id="cb25-137"><a href="#cb25-137"></a></span>
<span id="cb25-138"><a href="#cb25-138"></a>Obviously we can't get an infinite number of samples, so this assumption / claim is based on underlying mathematical principles and formalisms. BUT... one of the nice things about computers is that while we can't go to infinity, we can perform a really high number of samples. Let's generate a sampling distribution of means by taking one-hundred-thousand different samples from our population of men, where each sample is 25 men</span>
<span id="cb25-139"><a href="#cb25-139"></a></span>
<span id="cb25-142"><a href="#cb25-142"></a><span class="in">```{r}</span></span>
<span id="cb25-143"><a href="#cb25-143"></a><span class="co"># imagine taking a hundred thousand different samples...</span></span>
<span id="cb25-144"><a href="#cb25-144"></a>number_of_samples <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb25-145"><a href="#cb25-145"></a></span>
<span id="cb25-146"><a href="#cb25-146"></a><span class="co"># where each sample is 25 men</span></span>
<span id="cb25-147"><a href="#cb25-147"></a>N <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb25-148"><a href="#cb25-148"></a></span>
<span id="cb25-149"><a href="#cb25-149"></a>sampling_dist_means <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">num =</span> <span class="dv">1</span><span class="sc">:</span>number_of_samples) <span class="sc">%&gt;%</span> </span>
<span id="cb25-150"><a href="#cb25-150"></a>    <span class="fu">group_by</span>(num) <span class="sc">%&gt;%</span> </span>
<span id="cb25-151"><a href="#cb25-151"></a>  <span class="co"># using sample for a vector, rather than sample_n for a data frame (tibble)</span></span>
<span id="cb25-152"><a href="#cb25-152"></a>    <span class="fu">mutate</span>(<span class="at">sample_means =</span> <span class="fu">mean</span>(<span class="fu">sample</span>(pop_mens_heights<span class="sc">$</span>height, <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb25-153"><a href="#cb25-153"></a>           )</span>
<span id="cb25-154"><a href="#cb25-154"></a><span class="in">```</span></span>
<span id="cb25-155"><a href="#cb25-155"></a></span>
<span id="cb25-156"><a href="#cb25-156"></a>Let's look at our sampling distribution of means:</span>
<span id="cb25-157"><a href="#cb25-157"></a></span>
<span id="cb25-160"><a href="#cb25-160"></a><span class="in">```{r}</span></span>
<span id="cb25-161"><a href="#cb25-161"></a><span class="co"># histogram</span></span>
<span id="cb25-162"><a href="#cb25-162"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sampling_dist_means,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>sample_means)) <span class="sc">+</span></span>
<span id="cb25-163"><a href="#cb25-163"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="fu">sqrt</span>(<span class="dv">10000</span>)) <span class="sc">+</span> <span class="co"># ideal # of bins = sqrt of N</span></span>
<span id="cb25-164"><a href="#cb25-164"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb25-165"><a href="#cb25-165"></a></span>
<span id="cb25-166"><a href="#cb25-166"></a><span class="co"># summary stats</span></span>
<span id="cb25-167"><a href="#cb25-167"></a>psych<span class="sc">::</span><span class="fu">describe</span>(sampling_dist_means)</span>
<span id="cb25-168"><a href="#cb25-168"></a><span class="in">```</span></span>
<span id="cb25-169"><a href="#cb25-169"></a></span>
<span id="cb25-170"><a href="#cb25-170"></a>Look at that!</span>
<span id="cb25-171"><a href="#cb25-171"></a></span>
<span id="cb25-172"><a href="#cb25-172"></a>One last bit with the **Sampling Distribution of Means**. The standard deviation of the **Sampling Distribution of Means** is known as the **standard error**. You may have likely encountered this term before as a measure of confidence of the mean of your sample as it relates to the true mean of the population. When working with a given sample, standard error is approximated as the standard deviation of the sample divided-by the square root of the number of scores...</span>
<span id="cb25-173"><a href="#cb25-173"></a></span>
<span id="cb25-174"><a href="#cb25-174"></a>$$\frac{standard\space deviation}{N}$$ For example the standard error for this single sample is $7.54/\sqrt{25}$ or 7.54/5 or 1.51. Note that <span class="in">`psych::describe()`</span> produces the <span class="in">`se`</span> at the send of its table:</span>
<span id="cb25-175"><a href="#cb25-175"></a></span>
<span id="cb25-178"><a href="#cb25-178"></a><span class="in">```{r}</span></span>
<span id="cb25-179"><a href="#cb25-179"></a><span class="fu">set.seed</span>(<span class="dv">2021</span>)</span>
<span id="cb25-180"><a href="#cb25-180"></a><span class="fu">sample_n</span>(pop_mens_heights,<span class="at">size =</span> <span class="dv">25</span>) <span class="sc">%&gt;%</span> psych<span class="sc">::</span><span class="fu">describe</span>()</span>
<span id="cb25-181"><a href="#cb25-181"></a><span class="in">```</span></span>
<span id="cb25-182"><a href="#cb25-182"></a></span>
<span id="cb25-183"><a href="#cb25-183"></a>In this case the standard error of the sample (1.51) is pretty close to the standard deviation of the sampling distribution (1.49). Given that we are dividing by $\sqrt{N}$ it should be apparent that the standard error decreases as we increase or sample size. Thus, with increase sample size we are more confident that a given sample accurately represents the whole population.</span>
<span id="cb25-184"><a href="#cb25-184"></a></span>
<span id="cb25-185"><a href="#cb25-185"></a>Try rerunning the code, but this time with sample sizes of 5, 50, and 500. What happens to your distributions and your measures of central tendency?</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>