<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Tehran Davis">
<title>PSYC 7014: Graduate Statistics 1 - 34&nbsp; Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../week09/9_2-planned_contrasts.html" rel="next">
<link href="../week08/8_2-anova-regression.html" rel="prev">
<link href="../images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">PSYC 7014: Graduate Statistics 1</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Graduate Statistics Walkthroughs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part 1: INTRO to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_1-getting_started.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting started</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_2-resources.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Links to resources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_1-Rmarkdown_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Rmarkdown Basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_2-objects_assignment_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Objects, assignment, and functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_3-install_packages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Installing and loading an <code>R</code> package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_4-loading_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Loading in Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_5-leveling-up.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Leveling-up</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part 2: DESCRIBING &amp; VISUALIZING DATA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_1-structure_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The structure of your data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_2-central_tendency.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Measures of central tendency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_3-summary_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Creating summary tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_1-basic_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Basic ggplotting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_2-more_adv_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">More advanced ggPlots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_4-means_other_models.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Means and other models</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part 3: DISTRIBUTIONS and NHST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The normal distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_2-building_intuitions_about_probability_and_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Building intuitions about probability and NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Sampling distributions and seeing the logic of NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_4-more_examples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">More examples of distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_5-bias_variance.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Bias in sample variance estimates</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Part 4: MODELING w/ CONTINUOUS PREDICTORS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_2_correlations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_3_regressions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regression, pt.&nbsp;1: Running the model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_4_plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Plotting regression data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_5_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Regression model diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_6_example_report.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Example Report</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Part 5: T-TESTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_1_t-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing differences in means / t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_2_t-test-null-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Thinking about nothing (aka the null)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_3_t-test-lm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">t-test? It’s just a linear model</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Part 6: Power &amp; Effect Size</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_1-effect_size.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Effect Size</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_2-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_3-power_es_sig_tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Power, Effect sizes, and Significance testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_4-simulating_power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Simulating Power!!!</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Part 7: One-way ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_1-one-way-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">The One-way ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_2-anova-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">ANOVA and Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_1-posthocs.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_2-planned_contrasts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">Part 8: Factorial ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_1-main_effects.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Factorial ANOVA - The omnibus ANOVA and Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_2-factorial_w_post_hocs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Factorial ANOVA - Post hoc analysis of Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_3-advanced_example_and_apa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Template for Analysis &amp; APA Style</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Part 9: Repeated Measures ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_1-afex_ANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">afex is for ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_2-repeated_measures_anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Within Subjects / Repeated Measures ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_3-factorial_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Factorial RM-ANOVA and simple effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_4-sphericity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Sphericity: Variances and Co-Variances</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_5-spss_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Running a RM-ANOVA in SPSS</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#tldr-steps-for-running-a-posthoc-test-of-means" id="toc-tldr-steps-for-running-a-posthoc-test-of-means" class="nav-link active" data-scroll-target="#tldr-steps-for-running-a-posthoc-test-of-means"><span class="toc-section-number">34.1</span>  TLDR; Steps for running a posthoc test of means</a></li>
  <li><a href="#comparing-means-in-the-anova-model" id="toc-comparing-means-in-the-anova-model" class="nav-link" data-scroll-target="#comparing-means-in-the-anova-model"><span class="toc-section-number">34.2</span>  Comparing means in the ANOVA model</a></li>
  <li><a href="#the-data-siegels-1975-study-on-the-effects-of-morphine" id="toc-the-data-siegels-1975-study-on-the-effects-of-morphine" class="nav-link" data-scroll-target="#the-data-siegels-1975-study-on-the-effects-of-morphine"><span class="toc-section-number">34.3</span>  The data: Siegel’s 1975 study on the effects of morphine</a></li>
  <li><a href="#running-the-one-way-anova" id="toc-running-the-one-way-anova" class="nav-link" data-scroll-target="#running-the-one-way-anova"><span class="toc-section-number">34.4</span>  Running the One-way ANOVA</a></li>
  <li>
<a href="#post-hoc-tests" id="toc-post-hoc-tests" class="nav-link" data-scroll-target="#post-hoc-tests"><span class="toc-section-number">34.5</span>  Post-hoc tests</a>
  <ul class="collapse">
<li><a href="#bonferonni-dunn-and-holm-tests" id="toc-bonferonni-dunn-and-holm-tests" class="nav-link" data-scroll-target="#bonferonni-dunn-and-holm-tests"><span class="toc-section-number">34.5.1</span>  Bonferonni-Dunn and Holm tests</a></li>
  <li><a href="#bonferroni-example-pairwise.t.test" id="toc-bonferroni-example-pairwise.t.test" class="nav-link" data-scroll-target="#bonferroni-example-pairwise.t.test"><span class="toc-section-number">34.5.2</span>  Bonferroni example (pairwise.t.test())</a></li>
  <li><a href="#holm-example-pairwise.t.test" id="toc-holm-example-pairwise.t.test" class="nav-link" data-scroll-target="#holm-example-pairwise.t.test"><span class="toc-section-number">34.5.3</span>  Holm example (pairwise.t.test())</a></li>
  </ul>
</li>
  <li>
<a href="#tukey-hsd-and-regwq-tests" id="toc-tukey-hsd-and-regwq-tests" class="nav-link" data-scroll-target="#tukey-hsd-and-regwq-tests"><span class="toc-section-number">34.6</span>  Tukey HSD and REGWQ tests</a>
  <ul class="collapse">
<li><a href="#tukey-hsd-example-agricolae" id="toc-tukey-hsd-example-agricolae" class="nav-link" data-scroll-target="#tukey-hsd-example-agricolae"><span class="toc-section-number">34.6.1</span>  Tukey HSD example (agricolae)</a></li>
  <li><a href="#regwq-example-agricolae" id="toc-regwq-example-agricolae" class="nav-link" data-scroll-target="#regwq-example-agricolae"><span class="toc-section-number">34.6.2</span>  REGWQ example (agricolae)</a></li>
  </ul>
</li>
  <li>
<a href="#using-estimated-marginal-means-emmeans" id="toc-using-estimated-marginal-means-emmeans" class="nav-link" data-scroll-target="#using-estimated-marginal-means-emmeans"><span class="toc-section-number">35</span>  Using estimated marginal means, <code>emmeans()</code></a>
  <ul class="collapse">
<li><a href="#alternative-to-cld" id="toc-alternative-to-cld" class="nav-link" data-scroll-target="#alternative-to-cld"><span class="toc-section-number">35.1</span>  Alternative to CLD()</a></li>
  <li><a href="#effect-sizes" id="toc-effect-sizes" class="nav-link" data-scroll-target="#effect-sizes"><span class="toc-section-number">35.2</span>  Effect sizes</a></li>
  <li><a href="#reporting-and-anova-with-post-hoc-analyses." id="toc-reporting-and-anova-with-post-hoc-analyses." class="nav-link" data-scroll-target="#reporting-and-anova-with-post-hoc-analyses."><span class="toc-section-number">35.3</span>  Reporting and ANOVA with post hoc analyses.</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">
<span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="tldr-steps-for-running-a-posthoc-test-of-means" class="level2" data-number="34.1"><h2 data-number="34.1" class="anchored" data-anchor-id="tldr-steps-for-running-a-posthoc-test-of-means">
<span class="header-section-number">34.1</span> TLDR; Steps for running a posthoc test of means</h2>
<p>This walkthrough requires the following to be installed / loaded in <code>R</code></p>
<ol type="1">
<li>Be sure that the column that contains your IV is indeed being treated as a factor. If it is <code>levels(IV)</code> will list your levels, also the column containing the IV will contain <code>&lt;fct&gt;</code>.</li>
<li>build an ANOVA model using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>, or <code>afex()</code> (output to lm)</li>
<li>run your post-hoc comparisions using the p.adjustment of your choice (tukey, holm, bonferroni)</li>
</ol>
<p>Example (I recommend running this line-by-line)</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Preliminaries</span></span>
<span><span class="co">## load in data</span></span>
<span><span class="va">dataset</span> <span class="op">&lt;-</span> <span class="fu">read_table2</span><span class="op">(</span><span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `read_table2()` was deprecated in readr 2.0.0.
ℹ Please use `read_table()` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  ID = col_character(),
  Group = col_double(),
  Time = col_double()
)</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Step 1</span></span>
<span><span class="co">## check data, identify columns</span></span>
<span><span class="va">dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 3
   ID    Group  Time
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 01        1     3
 2 02        1     5
 3 03        1     1
 4 04        1     8
 5 05        1     1
 6 06        1     1
 7 07        1     4
 8 08        1     9
 9 09        2     2
10 10        2    12
# ℹ 30 more rows</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Group is numerically coded. Fixing this and turning to a factor</span></span>
<span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span> <span class="op">&lt;-</span> <span class="fu">recode_factor</span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>, <span class="st">"1"</span><span class="op">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="op">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="op">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="op">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="op">=</span><span class="st">"McM"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Step 2: Run the model</span></span>
<span><span class="va">model_aov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Time</span><span class="op">~</span><span class="va">Group</span>, data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Step 3: Test the model for significant F-value</span></span>
<span><span class="va">model_aov</span> <span class="op">%&gt;%</span> <span class="fu">sjstats</span><span class="fu">::</span><span class="fu"><a href="https://strengejacke.github.io/sjstats/reference/anova_stats.html">anova_stats</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>term      | df |    sumsq |  meansq | statistic | p.value | etasq | partial.etasq | omegasq | partial.omegasq | epsilonsq | cohens.f | power
--------------------------------------------------------------------------------------------------------------------------------------------
Group     |  4 | 3497.600 | 874.400 |    27.325 |  &lt; .001 | 0.757 |         0.757 |   0.725 |           0.725 |     0.730 |    1.767 |     1
Residuals | 35 | 1120.000 |  32.000 |           |         |       |               |         |                 |           |          |      </code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Step 4: post-hoc analysis in this example "tukey", but could also be "bonf" or "holm"</span></span>
<span><span class="fu">emmeans</span><span class="op">(</span>object <span class="op">=</span> <span class="va">model_aov</span>,specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span>, adjust<span class="op">=</span><span class="st">"tukey"</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df t.ratio p.value
 MS - MM        -6 2.83 35  -2.121  0.2340
 MS - SS        -7 2.83 35  -2.475  0.1198
 MS - SM       -20 2.83 35  -7.071  &lt;.0001
 MS - McM      -25 2.83 35  -8.839  &lt;.0001
 MM - SS        -1 2.83 35  -0.354  0.9965
 MM - SM       -14 2.83 35  -4.950  0.0002
 MM - McM      -19 2.83 35  -6.718  &lt;.0001
 SS - SM       -13 2.83 35  -4.596  0.0005
 SS - McM      -18 2.83 35  -6.364  &lt;.0001
 SM - McM       -5 2.83 35  -1.768  0.4078

P value adjustment: tukey method for comparing a family of 5 estimates </code></pre>
</div>
</div>
</section><section id="comparing-means-in-the-anova-model" class="level2" data-number="34.2"><h2 data-number="34.2" class="anchored" data-anchor-id="comparing-means-in-the-anova-model">
<span class="header-section-number">34.2</span> Comparing means in the ANOVA model</h2>
<p>In AoV, part 1, introduced the One-Way ANOVA. ANOVA is useful when we are comparing 3 or more group means such that the null hypothesis is:</p>
<p><span class="math display">\[\mu_1=\mu_2=\mu_3...=\mu_n\]</span>.</p>
<p>In this case, if a single mean is revealed to be significantly different from the others, then the null is rejected. However, rejecting the null only tells us that at least one mean was different from the others; it does not tell us which one or how many. For example with just three means, it could be the case that:</p>
<ul>
<li><span class="math inline">\(\mu_1≠\mu_2=\mu_3\)</span></li>
<li><span class="math inline">\(\mu_1=\mu_2≠\mu_3\)</span></li>
<li><span class="math inline">\(\mu_1=\mu_3≠\mu_2\)</span></li>
<li><span class="math inline">\(\mu_1≠\mu_2≠\mu_3\)</span></li>
</ul>
<p>Simply getting a significant <em>F</em>-value does not tell us this at all. In order to suss out any differences in our groups we are going to need to make direct comparisons between them.</p>
<p>Enter multiple contrasts. Multiple contrasts are a way of testing the potential inequalities between group means like those above. As always, both Navarro and Poldrack do wonderful jobs of laying out the mathematics and logic of multiple comparisons. As with Part 1 I focus on practical implementation and spend some time focusing a bit on potential landmines and theoretical concerns as I see them.</p>
<p>This vignette assumes that you have the following packages installed and loaded in R:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># use pacman to check, install, and load necessary packages</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">agricolae</span>,</span>
<span>               <span class="va">cowplot</span>, </span>
<span>               <span class="va">tidyverse</span>, </span>
<span>               <span class="va">emmeans</span>,</span>
<span>               <span class="va">multcomp</span>,</span>
<span>               <span class="va">psych</span>,</span>
<span>               <span class="va">sjstats</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="the-data-siegels-1975-study-on-the-effects-of-morphine" class="level2" data-number="34.3"><h2 data-number="34.3" class="anchored" data-anchor-id="the-data-siegels-1975-study-on-the-effects-of-morphine">
<span class="header-section-number">34.3</span> The data: Siegel’s 1975 study on the effects of morphine</h2>
<p>To start, lets download Siegel’s (1975) data set on Morphine Tolerance. This data set can be found on the web. Before diving into the data, check a description of the experiment in the <strong>Siegel_summary.pdf</strong> file in the walkthroughs folder. When you are done, come back a we’ll work on analyzing this data.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># grab data from online location:</span></span>
<span><span class="va">dataset</span> <span class="op">&lt;-</span> <span class="fu">read_table2</span><span class="op">(</span><span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  ID = col_character(),
  Group = col_double(),
  Time = col_double()
)</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># convert dataset$Group number codes to named factor levels:</span></span>
<span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span> <span class="op">&lt;-</span> <span class="fu">recode_factor</span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>, <span class="st">"1"</span><span class="op">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="op">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="op">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="op">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="op">=</span><span class="st">"McM"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># get descriptive stats for this data by Group</span></span>
<span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.by.html">describeBy</a></span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Time</span>,<span class="va">dataset</span><span class="op">$</span><span class="va">Group</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Descriptive statistics by group 
group: MS
   vars n mean   sd median trimmed  mad min max range skew kurtosis   se
X1    1 8    4 3.16    3.5       4 3.71   1   9     8 0.43    -1.59 1.12
------------------------------------------------------------ 
group: MM
   vars n mean   sd median trimmed  mad min max range skew kurtosis   se
X1    1 8   10 5.13   10.5      10 4.45   2  19    17 0.15    -0.99 1.81
------------------------------------------------------------ 
group: SS
   vars n mean   sd median trimmed  mad min max range skew kurtosis   se
X1    1 8   11 6.72   10.5      11 8.15   3  21    18 0.23    -1.69 2.38
------------------------------------------------------------ 
group: SM
   vars n mean   sd median trimmed  mad min max range skew kurtosis   se
X1    1 8   24 6.37     23      24 5.93  17  36    19 0.59    -1.07 2.25
------------------------------------------------------------ 
group: McM
   vars n mean   sd median trimmed  mad min max range skew kurtosis   se
X1    1 8   29 6.16   28.5      29 5.93  20  40    20 0.28    -1.07 2.18</code></pre>
</div>
</div>
<p>And a quick peek at this data:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dataset</span>,<span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">Group</span>,y<span class="op">=</span><span class="va">Time</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="va">mean</span>, geom <span class="op">=</span> <span class="st">"bar"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="va">mean_se</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, <span class="fu">aes</span><span class="op">(</span>width<span class="op">=</span><span class="fl">.25</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">expand_limits</span><span class="op">(</span>y<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">35</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="9_1-posthocs_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="running-the-one-way-anova" class="level2" data-number="34.4"><h2 data-number="34.4" class="anchored" data-anchor-id="running-the-one-way-anova">
<span class="header-section-number">34.4</span> Running the One-way ANOVA</h2>
<p>Now that our data is properly coded we can run our omnibus ANOVA. My own personal preference is to run the ANOVA using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. This makes like a lot easier when dealing with contrasts, especially if you decide to employ the method that Field suggests in his guide. FWIW, I typically use another method as seen below, but I’ll talk a little bit about why I prefer it to Fields method. That said, recall from Part 1 that using the <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> function gives you the same result. Depending on which you choose, you can use the <code>summary(morphine_mdl)</code> or <code>anova(morphine_mdl)</code> to switch back and forth to get the info that you desire:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># running the ANOVA using lm:</span></span>
<span><span class="va">morphine_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">Time</span><span class="op">~</span><span class="va">Group</span>,data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></span>
<span><span class="co"># using the anova() function to display as ANOVA table</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">morphine_mdl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Time
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Group      4 3497.6   874.4  27.325 2.443e-10 ***
Residuals 35 1120.0    32.0                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># full anova output (preferred)</span></span>
<span><span class="fu">sjstats</span><span class="fu">::</span><span class="fu"><a href="https://strengejacke.github.io/sjstats/reference/anova_stats.html">anova_stats</a></span><span class="op">(</span><span class="va">morphine_mdl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>term      | df |    sumsq |  meansq | statistic | p.value | etasq | partial.etasq | omegasq | partial.omegasq | epsilonsq | cohens.f | power
--------------------------------------------------------------------------------------------------------------------------------------------
Group     |  4 | 3497.600 | 874.400 |    27.325 |  &lt; .001 | 0.757 |         0.757 |   0.725 |           0.725 |     0.730 |    1.767 |     1
Residuals | 35 | 1120.000 |  32.000 |           |         |       |               |         |                 |           |          |      </code></pre>
</div>
</div>
<p>So we see here that we have: <span class="math inline">\(F(4,35)=27.33,p&lt;.001,\eta_p^2=.75\)</span></p>
<p>Remember again that the <strong>only</strong> thing that the omnibus ANOVA tells us is that there is an inequality in our means. In this respect, the omnibus begs more questions than it answers—which means are different from which. In order to get this answer we need to run direct comparisons between our means. There are two ways of going about this, we can either <em>(1)</em> plan beforehand what differences in means are especially relevant for us and focus on those, or <em>(2)</em> take a look at all potential differences without any specified predictions. In Case 1, we are performing <strong>planned contrasts</strong>; in Case 2, we use <strong>post hoc</strong> tests. More often than not, you will see researchers analyzing differences in means using post hoc tests—that is they run the ANOVA, find that it is significant, and run a battery of pairwise comparisons. It is sometimes the case that of that battery of comparisons, only a select few are actually theoretically relevant. However, if there is a theory-driven case to be made that you are predicting differences between a few select means in your data, then there is an argument to be made that you should run your planned contrasts independent of your ANOVA. That is, you are technically only permitted to run post-hoc tests if your ANOVA is significant (you can only go looking for differences in means if your ANOVA tells you that they exist), whereas planned contrasts can be run regardless of the outcome of the omnibus ANOVA (indeed, some argue that they obviate the need to run the omnibus ANOVA altogether).</p>
<p>My guess is that most of you have experience with post-hoc tests. They are more commonly performed tend to be touched upon in introductory stats courses. So we will spend a little time on these first before proceeding to a more in depth treatment of planned contrasts.</p>
</section><section id="post-hoc-tests" class="level2" data-number="34.5"><h2 data-number="34.5" class="anchored" data-anchor-id="post-hoc-tests">
<span class="header-section-number">34.5</span> Post-hoc tests</h2>
<p><strong>We use a post-hoc test when we want to test for differences in means that we have not explicitly predicted prior to conducting our experiment</strong>. As a result, whenever we perform a post-hoc test, we need to adjust our critical p-values to correct for inflation of Type 1 error. Recall from earlier discussions that the odds of committing a Type 1 error (falsely rejecting the null) is <span class="math inline">\(1-(1-\alpha)^c\)</span> where <span class="math inline">\(\alpha\)</span> is you critical p-value and <span class="math inline">\(c\)</span> is the number of comparisons that are to be performed. Typically we keep this at .05, so when conducting a single test, the likelihood of committing a Type 1 error is: <span class="math inline">\(1-(1-.05)^1=1-0.95^1=0.05\)</span></p>
<p>However as we increase the number of comparisons, assuming an <span class="math inline">\(\alpha\)</span> of 0.05:</p>
<ul>
<li>2 comparisons = <span class="math inline">\(1-.95^2=0.0975\)</span>
</li>
<li>3 comparisons = <span class="math inline">\(1-.95^3=0.1426\)</span>
</li>
<li>4 comparisons = <span class="math inline">\(1-.95^4=0.1855\)</span>
</li>
<li>5 comparisons = <span class="math inline">\(1-.95^5=0.2262\)</span>
</li>
</ul>
<p>Obviously, we need to control for this. The post-hoc methods that were introduced this week are all similar in that they involve comparing two means (<em>a la t</em>-test) but differ in how the error is controlled. For example a Bonferroni-Dunn correction (which is often used as a post-hoc correction, although initially intended for correcting planned comparisons) adjusts for this by partitioning the significance (by diving your original alpha by the number of comparisons). A popular variant of this method, the Holm test, is a multistage test. It proceeds by ordering the obtained <em>t</em>-values from smallest to largest. We then evaluate the largest <em>t</em> according to the Bonferroni-Dunn correction <span class="math inline">\(\alpha/c\)</span>. Each subsequent comparison <em>t</em> value, <span class="math inline">\(n\)</span> is evaluated against the correction <span class="math inline">\(\alpha/(c-n)\)</span>. Please note I mention the these two methods with post-hoc analyses, although in true they are intended for planned comparisons. However, in instances in which the number of comparisons is relatively small, I’ve often seen them employed as post-hocs.</p>
<p>So how many comparisons is relatively small? I’d suggest best form is to use the above methods when you have 5 or fewer comparisons, meaning that your critical <span class="math inline">\(\alpha\)</span> is .01. That said, with a post hoc test, you really do not have a choice in the number of comparisons you can make, you need to test for all possible comparisons on the IV. Why? well if not you are simply cherry picking your data. For example it would be poor form to take a look at our data like so:</p>
<p>Plot:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">dataset</span>,<span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">Group</span>,y<span class="op">=</span><span class="va">Time</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.y <span class="op">=</span> <span class="va">mean</span>, geom <span class="op">=</span> <span class="st">"bar"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="va">mean_se</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, <span class="fu">aes</span><span class="op">(</span>width<span class="op">=</span><span class="fl">.25</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">expand_limits</span><span class="op">(</span>y<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">35</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
ℹ Please use the `fun` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="9_1-posthocs_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>and then decide that you <em>only</em> want to compare ‘McM’ to ‘MS’ because that’s where you see the greatest differences. Or that you simply want to take a look at “MM” and “SS” <em>without considering the rest</em>.</p>
<p>Since you did not plan for or explicitly predict these differences from the outset, you are simply banking on what I like to say might be a “historical accident”, that you simply stumbled into these results. As such, it’s deemed as proper for to test <em>all</em> contingencies.</p>
<p>In the case above there are <span class="math inline">\((5!)/(2!)(5-2)!\)</span> = 10 combinations. If we were to run a Bonferroni correction in this case or critical <span class="math inline">\(p\)</span> would need to be <span class="math inline">\(.05/10=.005\)</span> which is an extremely conservative value, and thus dramatically inflates the likelihood of Type II error. In cases like this, Tukey’s HSD is the traditionally preferred method, as it takes into account the characteristics of your data (in particular the standard error of the distribution) when calculating the critical <span class="math inline">\(p\)</span> value. As such in cases where many post-hoc, pairwise comparisons are made, Tukey’s HSD is less conservative than a Bonferroni adjustment.</p>
<p>One final method that is becoming more <em>en vogue</em> is the Ryan, Einot, Gabriel, Welsch method (REGWQ). Whereas Tukey’s method holds the critical <span class="math inline">\(p\)</span> constant for all comparisons (at the loss of power) the REGWQ allows for an adjustment for the number of comparisons. It is currently being promoted as the most desirable post-hoc method.</p>
<section id="bonferonni-dunn-and-holm-tests" class="level3" data-number="34.5.1"><h3 data-number="34.5.1" class="anchored" data-anchor-id="bonferonni-dunn-and-holm-tests">
<span class="header-section-number">34.5.1</span> Bonferonni-Dunn and Holm tests</h3>
<p>In <code>R</code> there are several ways in which we can call post hoc corrections. For example we can call the Bonferonni and Holm adjustments using <code><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test()</a></code> function from the <code>base</code> package (already installed). The <code><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test()</a></code> method asks you to input:</p>
<ul>
<li>
<code>x</code> = your DV</li>
<li>
<code>g</code> = your grouping factor</li>
<li>
<code>p.adjust.method</code> = the name of your desired correction in string format</li>
</ul>
<p>First let’s run the <code>pairwise.t.tests</code> with no adjustment (akin to uncorrected <span class="math inline">\(p\)</span> values):</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Time</span>, g <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>,p.adjust.method <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  dataset$Time and dataset$Group 

    MS      MM      SS      SM   
MM  0.041   -       -       -    
SS  0.018   0.726   -       -    
SM  3.1e-08 1.9e-05 5.4e-05 -    
McM 1.9e-10 8.9e-08 2.6e-07 0.086

P value adjustment method: none </code></pre>
</div>
</div>
<p>You see above that we get a cross-matrix containing the <span class="math inline">\(p\)</span> values for each cross pair (row × column). Remember this is something we would never do in a post hoc (no corrections) but I wanted to first run this to illustrate a point. Now let’s run the the Bonferroni and Holm corrections:</p>
</section><section id="bonferroni-example-pairwise.t.test" class="level3" data-number="34.5.2"><h3 data-number="34.5.2" class="anchored" data-anchor-id="bonferroni-example-pairwise.t.test">
<span class="header-section-number">34.5.2</span> Bonferroni example (pairwise.t.test())</h3>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Time</span>, g <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>,p.adjust.method <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  dataset$Time and dataset$Group 

    MS      MM      SS      SM     
MM  0.41051 -       -       -      
SS  0.18319 1.00000 -       -      
SM  3.1e-07 0.00019 0.00054 -      
McM 1.9e-09 8.9e-07 2.6e-06 0.85818

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>You’ll note that the <code>p-values</code> displayed here are 10x the p-values from the uncorrected matrix. To demonstrate this:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">uncorrected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Time</span>, g <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>,p.adjust.method <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span>
<span><span class="va">bonf_corrected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Time</span>, g <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>,p.adjust.method <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">bonf_corrected</span><span class="op">$</span><span class="va">p.value</span><span class="op">/</span><span class="va">uncorrected</span><span class="op">$</span><span class="va">p.value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    MS        MM SS SM
MM  10        NA NA NA
SS  10  1.377801 NA NA
SM  10 10.000000 10 NA
McM 10 10.000000 10 10</code></pre>
</div>
</div>
<ul>
<li>note that the <code>1.378</code> value is the result of p being capped at <span class="math inline">\(p=1\)</span> in the Bonferroni corrected comparison.</li>
</ul>
<p>Remember from a few paragraphs back that there are 10 possible combinations so the Bonferonni test would need to divide the critical alpha by 10. What this means is that anytime you perform a correction, <code>R</code> actually adjusts the <span class="math inline">\(p\)</span> values for you; therefore you may interpret the output against your original (familywise) <span class="math inline">\(\alpha\)</span>. So here, any values that are still less than .05 after the corrections are significant.</p>
<p>Moving on…</p>
</section><section id="holm-example-pairwise.t.test" class="level3" data-number="34.5.3"><h3 data-number="34.5.3" class="anchored" data-anchor-id="holm-example-pairwise.t.test">
<span class="header-section-number">34.5.3</span> Holm example (pairwise.t.test())</h3>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.t.test.html">pairwise.t.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Time</span>, g <span class="op">=</span> <span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>,p.adjust.method <span class="op">=</span> <span class="st">"holm"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  dataset$Time and dataset$Group 

    MS      MM      SS      SM     
MM  0.12315 -       -       -      
SS  0.07327 0.72579 -       -      
SM  2.8e-07 0.00011 0.00027 -      
McM 1.9e-09 7.1e-07 1.8e-06 0.17164

P value adjustment method: holm </code></pre>
</div>
</div>
</section></section><section id="tukey-hsd-and-regwq-tests" class="level2" data-number="34.6"><h2 data-number="34.6" class="anchored" data-anchor-id="tukey-hsd-and-regwq-tests">
<span class="header-section-number">34.6</span> Tukey HSD and REGWQ tests</h2>
<p>In order to run Tukey’s HSD and REGWQ methods we call upon the <code>agricolae</code> package. In this case, we need to input our <code>lm() model</code> into the function, as well as identify our “treatment” (in this case our “Group” factor). For example:</p>
<section id="tukey-hsd-example-agricolae" class="level3" data-number="34.6.1"><h3 data-number="34.6.1" class="anchored" data-anchor-id="tukey-hsd-example-agricolae">
<span class="header-section-number">34.6.1</span> Tukey HSD example (agricolae)</h3>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">morphine_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Time</span><span class="op">~</span><span class="va">Group</span>,data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span> <span class="co"># from above</span></span>
<span><span class="fu">agricolae</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/agricolae/man/HSD.test.html">HSD.test</a></span><span class="op">(</span><span class="va">morphine_mdl</span>,trt <span class="op">=</span> <span class="st">"Group"</span>,group <span class="op">=</span> <span class="cn">T</span>,console <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: morphine_mdl ~ "Group"

HSD Test for Time 

Mean Square Error:  32 

Group,  means

    Time      std r Min Max
McM   29 6.164414 8  20  40
MM    10 5.126960 8   2  19
MS     4 3.162278 8   1   9
SM    24 6.369571 8  17  36
SS    11 6.718843 8   3  21

Alpha: 0.05 ; DF Error: 35 
Critical Value of Studentized Range: 4.065949 

Minimun Significant Difference: 8.131899 

Treatments with the same letter are not significantly different.

    Time groups
McM   29      a
SM    24      a
SS    11      b
MM    10      b
MS     4      b</code></pre>
</div>
</div>
<p>Note that the <code>group</code> and <code>console</code> arguments pertain to the output. You typically will want to keep console set to <code>TRUE</code> as that simply prints the output of your test. The <code>group</code> argument controls how the output is presented. Above we set it to <code>TRUE.</code> This results in an output that groups the treatment means into subsets where treatments with the same letter are not significantly different from one another, known as <em>compact letter displays</em>. For example, <em>a</em>s are not significantly different from each other, <em>b</em>s are not significantly different from each other, <strong>but</strong> <em>a</em>s are different from <em>b</em>s. Conversely if you wanted to see each comparison you can set this to <code>FALSE</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">agricolae</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/agricolae/man/HSD.test.html">HSD.test</a></span><span class="op">(</span><span class="va">morphine_mdl</span>,trt <span class="op">=</span> <span class="st">"Group"</span>,group <span class="op">=</span> <span class="cn">FALSE</span>,console <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: morphine_mdl ~ "Group"

HSD Test for Time 

Mean Square Error:  32 

Group,  means

    Time      std r Min Max
McM   29 6.164414 8  20  40
MM    10 5.126960 8   2  19
MS     4 3.162278 8   1   9
SM    24 6.369571 8  17  36
SS    11 6.718843 8   3  21

Alpha: 0.05 ; DF Error: 35 
Critical Value of Studentized Range: 4.065949 

Comparison between treatments means

         difference pvalue signif.        LCL        UCL
McM - MM         19 0.0000     ***  10.868101  27.131899
McM - MS         25 0.0000     ***  16.868101  33.131899
McM - SM          5 0.4078          -3.131899  13.131899
McM - SS         18 0.0000     ***   9.868101  26.131899
MM - MS           6 0.2340          -2.131899  14.131899
MM - SM         -14 0.0002     *** -22.131899  -5.868101
MM - SS          -1 0.9965          -9.131899   7.131899
MS - SM         -20 0.0000     *** -28.131899 -11.868101
MS - SS          -7 0.1198         -15.131899   1.131899
SM - SS          13 0.0005     ***   4.868101  21.131899</code></pre>
</div>
</div>
<p>Finally, if you do decide to group (<code>group=TRUE</code>), you can take the outcome of this function and use it to generate a nice group plot. This is useful for quick visual inspection.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">agricolae</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/agricolae/man/HSD.test.html">HSD.test</a></span><span class="op">(</span><span class="va">morphine_mdl</span>,trt <span class="op">=</span> <span class="st">"Group"</span>,group <span class="op">=</span> <span class="cn">T</span>,console <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: morphine_mdl ~ "Group"

HSD Test for Time 

Mean Square Error:  32 

Group,  means

    Time      std r Min Max
McM   29 6.164414 8  20  40
MM    10 5.126960 8   2  19
MS     4 3.162278 8   1   9
SM    24 6.369571 8  17  36
SS    11 6.718843 8   3  21

Alpha: 0.05 ; DF Error: 35 
Critical Value of Studentized Range: 4.065949 

Minimun Significant Difference: 8.131899 

Treatments with the same letter are not significantly different.

    Time groups
McM   29      a
SM    24      a
SS    11      b
MM    10      b
MS     4      b</code></pre>
</div>
<div class="cell-output-display">
<p><img src="9_1-posthocs_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="regwq-example-agricolae" class="level3" data-number="34.6.2"><h3 data-number="34.6.2" class="anchored" data-anchor-id="regwq-example-agricolae">
<span class="header-section-number">34.6.2</span> REGWQ example (agricolae)</h3>
<p>The same applies to REGW, using the <code>REGW.test()</code> function (with <code>group=F</code>, I’m showing all of the comparisons):</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">agricolae</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/agricolae/man/REGW.test.html">REGW.test</a></span><span class="op">(</span><span class="va">morphine_mdl</span>,trt <span class="op">=</span> <span class="st">"Group"</span>,group <span class="op">=</span> <span class="cn">F</span>,console <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: morphine_mdl ~ "Group"

Ryan, Einot and Gabriel and Welsch multiple range test
for Time 

Mean Square Error:  32 

Group,  means

    Time      std r Min Max
McM   29 6.164414 8  20  40
MM    10 5.126960 8   2  19
MS     4 3.162278 8   1   9
SM    24 6.369571 8  17  36
SS    11 6.718843 8   3  21

Comparison between treatments means

         difference pvalue signif.         LCL        UCL
McM - MM         19 0.0000     ***  12.1234674  25.876533
McM - MS         25 0.0000     ***  17.4611210  32.538879
McM - SM          5 0.3056          -2.6279930  12.627993
McM - SS         18 0.0000     ***   9.8681013  26.131899
MM - MS           6 0.0995       .  -0.8765326  12.876533
MM - SM         -14 0.0001     *** -21.5388790  -6.461121
MM - SS          -1 0.9846          -8.6279930   6.627993
MS - SM         -20 0.0000     *** -26.8765326 -13.123467
MS - SS          -7 0.0771       . -14.5388790   0.538879
SM - SS          13 0.0001     ***   6.1234674  19.876533</code></pre>
</div>
</div>
<p>Compact letter displays are nice (SPSS generates them, too), but as seems to always be the case, there is some controversy as to whether we should use them. Taken from this vignette:</p>
<blockquote class="blockquote">
<p>CLD displays promote visually the idea that two means that are “not significantly different” are to be judged as being equal; and that is a very wrong interpretation. In addition, they draw an artificial “bright line” between P values on either side of alpha, even ones that are very close.</p>
</blockquote>
</section></section><section id="using-estimated-marginal-means-emmeans" class="level1" data-number="35"><h1 data-number="35">
<span class="header-section-number">35</span> Using estimated marginal means, <code>emmeans()</code>
</h1>
<p>In previous years I would have stopped here and left you with the impression that you may need to call different packages depending on what post-hoc (or later, contrast) you intend to run. While this is perfectly acceptable, more and more I am using the estimated marginal means (package) to perform just about all of my post hoc analyses and contrasts. From the <code>emmeans</code> vignette <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html#EMMdef">(link)</a>:</p>
<blockquote class="blockquote">
<p>Estimated marginal means are based on a model – not directly on data. The basis for them is what we call the reference grid for a given model. To obtain the reference grid, consider all the predictors in the model.</p>
</blockquote>
<p>(The notion of a reference grid will become more apparent when we more into factorial ANOVA For now, let’s just focus on practical implementation).</p>
<p>I typically use this framework as it allows for a higher level of flexibility in analyzing contrasts while still being unified. We’ll see just how far we can go in the upcoming weeks. For now, let’s use the <code>emmeans</code> package to perform our post-hoc analyses from above.</p>
<p>We start by throwing our model into the <code>emmeans()</code> function, specifying our test as a function of our comparison. We also need to tell <code>R</code> what adjustment (correction) we desire. To remind ourselves, our model is:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">morphine_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">Time</span><span class="op">~</span><span class="va">Group</span>,data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For a <code>pairwise</code> test with a <code>bonferroni</code> correction we need to specify what factor (or predictor or IV) we are running our pairwise comparisons on (<code>spec =</code>), and that we are <code>adjusting</code> by using the bonferonni (<code>bonf</code>). This takes the general form:</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">emmeans</span><span class="op">(</span><span class="va">morphine_mdl</span>, specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span>adjust<span class="op">=</span><span class="st">"bonf"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df t.ratio p.value
 MS - MM        -6 2.83 35  -2.121  0.4105
 MS - SS        -7 2.83 35  -2.475  0.1832
 MS - SM       -20 2.83 35  -7.071  &lt;.0001
 MS - McM      -25 2.83 35  -8.839  &lt;.0001
 MM - SS        -1 2.83 35  -0.354  1.0000
 MM - SM       -14 2.83 35  -4.950  0.0002
 MM - McM      -19 2.83 35  -6.718  &lt;.0001
 SS - SM       -13 2.83 35  -4.596  0.0005
 SS - McM      -18 2.83 35  -6.364  &lt;.0001
 SM - McM       -5 2.83 35  -1.768  0.8582

P value adjustment: bonferroni method for 10 tests </code></pre>
</div>
</div>
<p><code>emmeans</code> also allows us to run a pairwise Tukey test:</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">emmeans</span><span class="op">(</span><span class="va">morphine_mdl</span>, specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span>adjust <span class="op">=</span> <span class="st">"tukey"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df t.ratio p.value
 MS - MM        -6 2.83 35  -2.121  0.2340
 MS - SS        -7 2.83 35  -2.475  0.1198
 MS - SM       -20 2.83 35  -7.071  &lt;.0001
 MS - McM      -25 2.83 35  -8.839  &lt;.0001
 MM - SS        -1 2.83 35  -0.354  0.9965
 MM - SM       -14 2.83 35  -4.950  0.0002
 MM - McM      -19 2.83 35  -6.718  &lt;.0001
 SS - SM       -13 2.83 35  -4.596  0.0005
 SS - McM      -18 2.83 35  -6.364  &lt;.0001
 SM - McM       -5 2.83 35  -1.768  0.4078

P value adjustment: tukey method for comparing a family of 5 estimates </code></pre>
</div>
</div>
<section id="alternative-to-cld" class="level2" data-number="35.1"><h2 data-number="35.1" class="anchored" data-anchor-id="alternative-to-cld">
<span class="header-section-number">35.1</span> Alternative to CLD()</h2>
<p>One thing to note, the curator of the <code>emmeans()</code> package is not a fan of <code>cld</code> (Compact Letter Displays) and instead has created <code>pwpp</code> as a visualization tool.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">emmeans</span><span class="op">(</span><span class="va">morphine_mdl</span>, specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu">pwpp</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="9_1-posthocs_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can visit <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html">this vignette</a> to get a feel for what is at issue here.</p>
</section><section id="effect-sizes" class="level2" data-number="35.2"><h2 data-number="35.2" class="anchored" data-anchor-id="effect-sizes">
<span class="header-section-number">35.2</span> Effect sizes</h2>
<p>Typically when reporting the effect size of the difference between two means we use Cohen’s <span class="math inline">\(d\)</span>. However, calculating Cohen’s $d$ in a posthoc contrast is slightly more involved than the method used for a regular t-test. This is because with a regular t-test you only have 2 means from 2 samples that you have collected. In the case of pairwise contrasts in ANOVA, while you are only comparing two means, those means are nested within a larger group (e.g., when comparing MS and MM, we still need to account for the fact that we also collected samples from SS, SM, and McM). That is, you need to understand the difference between the two means <strong>in the context of the entire model.</strong></p>
<p>Simply put, in our calculations we need to account for the influence of all of our collected groups. This is done by placing the contrasted difference in the context of the Root Mean Square Error, or the square root of the Mean Square Error of the residuals in our ANOVA model. Recall that typically Cohen’s <span class="math inline">\(d\)</span> is the <strong>difference between the two means</strong> divided by their <strong>pooled standard deviation</strong>. Here, <span class="math inline">\(d\)</span> is the <strong>difference between the two means</strong> divided by <strong><em>sigma, or the estimated standard deviation of the errors of the linear model.</em></strong></p>
<p>To do this we’re going to need two things from the original model. Let’s take a look at the model summary:</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">morphine_mdl</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Time ~ Group, data = dataset)

Residuals:
   Min     1Q Median     3Q    Max 
 -9.00  -3.25   0.00   3.00  12.00 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    4.000      2.000   2.000   0.0533 .  
GroupMM        6.000      2.828   2.121   0.0411 *  
GroupSS        7.000      2.828   2.475   0.0183 *  
GroupSM       20.000      2.828   7.071 3.09e-08 ***
GroupMcM      25.000      2.828   8.839 1.93e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.657 on 35 degrees of freedom
Multiple R-squared:  0.7574,    Adjusted R-squared:  0.7297 
F-statistic: 27.32 on 4 and 35 DF,  p-value: 2.443e-10</code></pre>
</div>
</div>
<p>The values line that is important to us is the <code>Residual standard error ___ on __ degrees of freedom</code>—in this case the values <strong>5.657</strong> and <strong>35</strong> respectively.</p>
<p>Assuming you have run your comparisons using <code>emmeans()</code> you can calculate your effect sizes for each comparison using <code><a href="https://rdrr.io/pkg/emmeans/man/eff_size.html">emmeans::eff_size()</a></code>.</p>
<p><code>eff_size()</code> takes three arguments:</p>
<ul>
<li>the emmeans object</li>
<li>the estimated standard deviation of the errors of the linear model, <code>sigma</code>
</li>
<li>the residual degrees of freedom from the model, <code>df.residual</code>
</li>
</ul>
<p>The functions <code><a href="https://rdrr.io/r/stats/sigma.html">sigma()</a></code> and <code><a href="https://rdrr.io/r/stats/df.residual.html">df.residual()</a></code> allow us to get this information directly from the model. A typical call would look something like this</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># save your contrasts to an object</span></span>
<span><span class="va">mdl_contrasts</span> <span class="op">&lt;-</span> <span class="fu">emmeans</span><span class="op">(</span><span class="va">morphine_mdl</span>, specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># use the saved object in the following function</span></span>
<span><span class="fu">eff_size</span><span class="op">(</span><span class="va">mdl_contrasts</span>,sigma <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sigma.html">sigma</a></span><span class="op">(</span><span class="va">morphine_mdl</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/df.residual.html">df.residual</a></span><span class="op">(</span><span class="va">morphine_mdl</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast effect.size    SE df lower.CL upper.CL
 MS - MM       -1.061 0.516 35    -2.11  -0.0135
 MS - SS       -1.237 0.521 35    -2.30  -0.1789
 MS - SM       -3.536 0.655 35    -4.86  -2.2065
 MS - McM      -4.419 0.727 35    -5.90  -2.9428
 MM - SS       -0.177 0.500 35    -1.19   0.8392
 MM - SM       -2.475 0.581 35    -3.65  -1.2955
 MM - McM      -3.359 0.641 35    -4.66  -2.0570
 SS - SM       -2.298 0.570 35    -3.46  -1.1400
 SS - McM      -3.182 0.628 35    -4.46  -1.9067
 SM - McM      -0.884 0.511 35    -1.92   0.1536

sigma used for effect sizes: 5.657 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>That said, there is some debate as to whether this is the most appropriate way to calculate posthoc effect sizes, or whether posthoc effect sizes are in general a proper thing to calculate. I’ve personally never had a reviewer ask for one, <strong>BUT</strong> if I had to provide on I would use this method.</p>
<p>FWIW, this won’t be the last time that we need to call back to the original (omnibus) ANOVA when conducting posthoc tests. Things get a little messier next week!</p>
</section><section id="reporting-and-anova-with-post-hoc-analyses." class="level2" data-number="35.3"><h2 data-number="35.3" class="anchored" data-anchor-id="reporting-and-anova-with-post-hoc-analyses.">
<span class="header-section-number">35.3</span> Reporting and ANOVA with post hoc analyses.</h2>
<p>In your report, you need to include information for the main ANOVA as well as information related to</p>
<ul>
<li>the omnibus ANOVA</li>
<li>a statement on what multiple comparisons were run and how corrected</li>
<li>note which comparisons were significant.</li>
</ul>
<p>If we work off of our last example, you’ll note that there are quite a few comparisons that we could discuss (10 in fact). In cases like these you could either put this information into a formatted table, or simply highlight a few that are especially relevant. For example, looking at the <code>emmeans()</code> outcome as well as the <code>CLD</code> plot from <code><a href="https://rdrr.io/pkg/agricolae/man/HSD.test.html">agricolae::HSD.test</a></code> we see that McM and SM (a’s) in the CLD plot are both significantly greater than the remain conditions (b’s). Based on this I would write something like:</p>
<p>… Our ANOVA revealed a significant effect for Morphine treatment group, <em>F</em>(4, 35) = 27.325, <em>p</em> &lt; .001. Tukey pairwise comparisons revealed that the mean tolerance times for the both the SM (<span class="math inline">\(M±SD\)</span>: 24.00 ± 6.37) and McM (29.00 ± 6.16) groups were greater than the remaining three groups (<span class="math inline">\(ps\)</span> &lt; .05), but not different from one another. The mean times for the remaining three conditions were not significantly different from one another, <span class="math inline">\(ps &gt; .05\)</span> (see Figure 1)</p>
<ul>
<li>assuming Figure 1 is a camera ready plot you’ve created in <code>ggplot()</code>. Any of the barplots in this walkthrough will suffice.</li>
</ul>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../week08/8_2-anova-regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">ANOVA and Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../week09/9_2-planned_contrasts.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb48" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Multiple comparisons in One-way ANOVA, pt. 1: post hoc tests"</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## TLDR; Steps for running a posthoc test of means</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>This walkthrough requires the following to be installed / loaded in <span class="in">`R`</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="in">```{r message=FALSE, warning=FALSE, include=FALSE}</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="co"># use pacman to check, install, and load necessary packages</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(agricolae,</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>               cowplot, </span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>               tidyverse, </span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>               emmeans,</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>               multcomp,</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>               psych,</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>               sjstats,</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>               pwr)</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Be sure that the column that contains your IV is indeed being treated as a factor. If it is <span class="in">`levels(IV)`</span> will list your levels, also the column containing the IV will contain <span class="in">`&lt;fct&gt;`</span>.</span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>build an ANOVA model using <span class="in">`lm()`</span>, <span class="in">`aov()`</span>, or <span class="in">`afex()`</span> (output to lm)</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>run your post-hoc comparisions using the p.adjustment of your choice (tukey, holm, bonferroni)</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>Example (I recommend running this line-by-line)</span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Preliminaries</span></span>
<span id="cb48-31"><a href="#cb48-31" aria-hidden="true" tabindex="-1"></a><span class="do">## load in data</span></span>
<span id="cb48-32"><a href="#cb48-32" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_table2</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span>)</span>
<span id="cb48-33"><a href="#cb48-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-34"><a href="#cb48-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1</span></span>
<span id="cb48-35"><a href="#cb48-35" aria-hidden="true" tabindex="-1"></a><span class="do">## check data, identify columns</span></span>
<span id="cb48-36"><a href="#cb48-36" aria-hidden="true" tabindex="-1"></a>dataset</span>
<span id="cb48-37"><a href="#cb48-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-38"><a href="#cb48-38" aria-hidden="true" tabindex="-1"></a><span class="do">## Group is numerically coded. Fixing this and turning to a factor</span></span>
<span id="cb48-39"><a href="#cb48-39" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Group, <span class="st">"1"</span><span class="ot">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="ot">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="ot">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="ot">=</span><span class="st">"McM"</span>)</span>
<span id="cb48-40"><a href="#cb48-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-41"><a href="#cb48-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Run the model</span></span>
<span id="cb48-42"><a href="#cb48-42" aria-hidden="true" tabindex="-1"></a>model_aov <span class="ot">&lt;-</span> <span class="fu">lm</span>(Time<span class="sc">~</span>Group, <span class="at">data =</span> dataset)</span>
<span id="cb48-43"><a href="#cb48-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-44"><a href="#cb48-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Test the model for significant F-value</span></span>
<span id="cb48-45"><a href="#cb48-45" aria-hidden="true" tabindex="-1"></a>model_aov <span class="sc">%&gt;%</span> sjstats<span class="sc">::</span><span class="fu">anova_stats</span>()</span>
<span id="cb48-46"><a href="#cb48-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-47"><a href="#cb48-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: post-hoc analysis in this example "tukey", but could also be "bonf" or "holm"</span></span>
<span id="cb48-48"><a href="#cb48-48" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(<span class="at">object =</span> model_aov,<span class="at">specs =</span> <span class="sc">~</span>Group, <span class="at">adjust=</span><span class="st">"tukey"</span>) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>()</span>
<span id="cb48-49"><a href="#cb48-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-50"><a href="#cb48-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-51"><a href="#cb48-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## Comparing means in the ANOVA model</span></span>
<span id="cb48-52"><a href="#cb48-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-53"><a href="#cb48-53" aria-hidden="true" tabindex="-1"></a>In AoV, part 1, introduced the One-Way ANOVA. ANOVA is useful when we are comparing 3 or more group means such that the null hypothesis is:</span>
<span id="cb48-54"><a href="#cb48-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-55"><a href="#cb48-55" aria-hidden="true" tabindex="-1"></a>$$\mu_1=\mu_2=\mu_3...=\mu_n$$.</span>
<span id="cb48-56"><a href="#cb48-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-57"><a href="#cb48-57" aria-hidden="true" tabindex="-1"></a>In this case, if a single mean is revealed to be significantly different from the others, then the null is rejected. However, rejecting the null only tells us that at least one mean was different from the others; it does not tell us which one or how many. For example with just three means, it could be the case that:</span>
<span id="cb48-58"><a href="#cb48-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-59"><a href="#cb48-59" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\mu_1≠\mu_2=\mu_3$</span>
<span id="cb48-60"><a href="#cb48-60" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\mu_1=\mu_2≠\mu_3$</span>
<span id="cb48-61"><a href="#cb48-61" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\mu_1=\mu_3≠\mu_2$</span>
<span id="cb48-62"><a href="#cb48-62" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\mu_1≠\mu_2≠\mu_3$</span>
<span id="cb48-63"><a href="#cb48-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-64"><a href="#cb48-64" aria-hidden="true" tabindex="-1"></a>Simply getting a significant *F*-value does not tell us this at all. In order to suss out any differences in our groups we are going to need to make direct comparisons between them.</span>
<span id="cb48-65"><a href="#cb48-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-66"><a href="#cb48-66" aria-hidden="true" tabindex="-1"></a>Enter multiple contrasts. Multiple contrasts are a way of testing the potential inequalities between group means like those above. As always, both Navarro and Poldrack do wonderful jobs of laying out the mathematics and logic of multiple comparisons. As with Part 1 I focus on practical implementation and spend some time focusing a bit on potential landmines and theoretical concerns as I see them.</span>
<span id="cb48-67"><a href="#cb48-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-68"><a href="#cb48-68" aria-hidden="true" tabindex="-1"></a>This vignette assumes that you have the following packages installed and loaded in R:</span>
<span id="cb48-69"><a href="#cb48-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-70"><a href="#cb48-70" aria-hidden="true" tabindex="-1"></a><span class="in">```{r warning = FALSE, message=FALSE}</span></span>
<span id="cb48-71"><a href="#cb48-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-72"><a href="#cb48-72" aria-hidden="true" tabindex="-1"></a><span class="co"># use pacman to check, install, and load necessary packages</span></span>
<span id="cb48-73"><a href="#cb48-73" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(agricolae,</span>
<span id="cb48-74"><a href="#cb48-74" aria-hidden="true" tabindex="-1"></a>               cowplot, </span>
<span id="cb48-75"><a href="#cb48-75" aria-hidden="true" tabindex="-1"></a>               tidyverse, </span>
<span id="cb48-76"><a href="#cb48-76" aria-hidden="true" tabindex="-1"></a>               emmeans,</span>
<span id="cb48-77"><a href="#cb48-77" aria-hidden="true" tabindex="-1"></a>               multcomp,</span>
<span id="cb48-78"><a href="#cb48-78" aria-hidden="true" tabindex="-1"></a>               psych,</span>
<span id="cb48-79"><a href="#cb48-79" aria-hidden="true" tabindex="-1"></a>               sjstats)</span>
<span id="cb48-80"><a href="#cb48-80" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-81"><a href="#cb48-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-82"><a href="#cb48-82" aria-hidden="true" tabindex="-1"></a><span class="fu">## The data: Siegel's 1975 study on the effects of morphine</span></span>
<span id="cb48-83"><a href="#cb48-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-84"><a href="#cb48-84" aria-hidden="true" tabindex="-1"></a>To start, lets download Siegel's (1975) data set on Morphine Tolerance. This data set can be found on the web. Before diving into the data, check a description of the experiment in the **Siegel_summary.pdf** file in the walkthroughs folder. When you are done, come back a we'll work on analyzing this data.</span>
<span id="cb48-85"><a href="#cb48-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-86"><a href="#cb48-86" aria-hidden="true" tabindex="-1"></a><span class="in">```{r downloading the dataset}</span></span>
<span id="cb48-87"><a href="#cb48-87" aria-hidden="true" tabindex="-1"></a><span class="co"># grab data from online location:</span></span>
<span id="cb48-88"><a href="#cb48-88" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_table2</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span>)</span>
<span id="cb48-89"><a href="#cb48-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-90"><a href="#cb48-90" aria-hidden="true" tabindex="-1"></a><span class="co"># convert dataset$Group number codes to named factor levels:</span></span>
<span id="cb48-91"><a href="#cb48-91" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Group, <span class="st">"1"</span><span class="ot">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="ot">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="ot">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="ot">=</span><span class="st">"McM"</span>)</span>
<span id="cb48-92"><a href="#cb48-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-93"><a href="#cb48-93" aria-hidden="true" tabindex="-1"></a><span class="co"># get descriptive stats for this data by Group</span></span>
<span id="cb48-94"><a href="#cb48-94" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describeBy</span>(dataset<span class="sc">$</span>Time,dataset<span class="sc">$</span>Group)</span>
<span id="cb48-95"><a href="#cb48-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-96"><a href="#cb48-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-97"><a href="#cb48-97" aria-hidden="true" tabindex="-1"></a>And a quick peek at this data:</span>
<span id="cb48-98"><a href="#cb48-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-101"><a href="#cb48-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-102"><a href="#cb48-102" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dataset,<span class="fu">aes</span>(<span class="at">x=</span>Group,<span class="at">y=</span>Time)) <span class="sc">+</span></span>
<span id="cb48-103"><a href="#cb48-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb48-104"><a href="#cb48-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="fu">aes</span>(<span class="at">width=</span>.<span class="dv">25</span>)) <span class="sc">+</span></span>
<span id="cb48-105"><a href="#cb48-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">35</span>)) <span class="sc">+</span> <span class="fu">theme_cowplot</span>()</span>
<span id="cb48-106"><a href="#cb48-106" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-107"><a href="#cb48-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-108"><a href="#cb48-108" aria-hidden="true" tabindex="-1"></a><span class="fu">## Running the One-way ANOVA</span></span>
<span id="cb48-109"><a href="#cb48-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-110"><a href="#cb48-110" aria-hidden="true" tabindex="-1"></a>Now that our data is properly coded we can run our omnibus ANOVA. My own personal preference is to run the ANOVA using <span class="in">`lm()`</span>. This makes like a lot easier when dealing with contrasts, especially if you decide to employ the method that Field suggests in his guide. FWIW, I typically use another method as seen below, but I'll talk a little bit about why I prefer it to Fields method. That said, recall from Part 1 that using the <span class="in">`aov()`</span> function gives you the same result. Depending on which you choose, you can use the <span class="in">`summary(morphine_mdl)`</span> or <span class="in">`anova(morphine_mdl)`</span> to switch back and forth to get the info that you desire:</span>
<span id="cb48-111"><a href="#cb48-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-114"><a href="#cb48-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-115"><a href="#cb48-115" aria-hidden="true" tabindex="-1"></a><span class="co"># running the ANOVA using lm:</span></span>
<span id="cb48-116"><a href="#cb48-116" aria-hidden="true" tabindex="-1"></a>morphine_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Time<span class="sc">~</span>Group,<span class="at">data =</span> dataset)</span>
<span id="cb48-117"><a href="#cb48-117" aria-hidden="true" tabindex="-1"></a><span class="co"># using the anova() function to display as ANOVA table</span></span>
<span id="cb48-118"><a href="#cb48-118" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(morphine_mdl)</span>
<span id="cb48-119"><a href="#cb48-119" aria-hidden="true" tabindex="-1"></a><span class="co"># full anova output (preferred)</span></span>
<span id="cb48-120"><a href="#cb48-120" aria-hidden="true" tabindex="-1"></a>sjstats<span class="sc">::</span><span class="fu">anova_stats</span>(morphine_mdl)</span>
<span id="cb48-121"><a href="#cb48-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-122"><a href="#cb48-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-123"><a href="#cb48-123" aria-hidden="true" tabindex="-1"></a>So we see here that we have: $F(4,35)=27.33,p&lt;.001,\eta_p^2=.75$</span>
<span id="cb48-124"><a href="#cb48-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-125"><a href="#cb48-125" aria-hidden="true" tabindex="-1"></a>Remember again that the **only** thing that the omnibus ANOVA tells us is that there is an inequality in our means. In this respect, the omnibus begs more questions than it answers---which means are different from which. In order to get this answer we need to run direct comparisons between our means. There are two ways of going about this, we can either *(1)* plan beforehand what differences in means are especially relevant for us and focus on those, or *(2)* take a look at all potential differences without any specified predictions. In Case 1, we are performing **planned contrasts**; in Case 2, we use **post hoc** tests. More often than not, you will see researchers analyzing differences in means using post hoc tests---that is they run the ANOVA, find that it is significant, and run a battery of pairwise comparisons. It is sometimes the case that of that battery of comparisons, only a select few are actually theoretically relevant. However, if there is a theory-driven case to be made that you are predicting differences between a few select means in your data, then there is an argument to be made that you should run your planned contrasts independent of your ANOVA. That is, you are technically only permitted to run post-hoc tests if your ANOVA is significant (you can only go looking for differences in means if your ANOVA tells you that they exist), whereas planned contrasts can be run regardless of the outcome of the omnibus ANOVA (indeed, some argue that they obviate the need to run the omnibus ANOVA altogether).</span>
<span id="cb48-126"><a href="#cb48-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-127"><a href="#cb48-127" aria-hidden="true" tabindex="-1"></a>My guess is that most of you have experience with post-hoc tests. They are more commonly performed tend to be touched upon in introductory stats courses. So we will spend a little time on these first before proceeding to a more in depth treatment of planned contrasts.</span>
<span id="cb48-128"><a href="#cb48-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-129"><a href="#cb48-129" aria-hidden="true" tabindex="-1"></a><span class="fu">## Post-hoc tests</span></span>
<span id="cb48-130"><a href="#cb48-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-131"><a href="#cb48-131" aria-hidden="true" tabindex="-1"></a>**We use a post-hoc test when we want to test for differences in means that we have not explicitly predicted prior to conducting our experiment**. As a result, whenever we perform a post-hoc test, we need to adjust our critical p-values to correct for inflation of Type 1 error. Recall from earlier discussions that the odds of committing a Type 1 error (falsely rejecting the null) is $1-(1-\alpha)^c$ where $\alpha$ is you critical p-value and $c$ is the number of comparisons that are to be performed. Typically we keep this at .05, so when conducting a single test, the likelihood of committing a Type 1 error is: $1-(1-.05)^1=1-0.95^1=0.05$</span>
<span id="cb48-132"><a href="#cb48-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-133"><a href="#cb48-133" aria-hidden="true" tabindex="-1"></a>However as we increase the number of comparisons, assuming an $\alpha$ of 0.05:</span>
<span id="cb48-134"><a href="#cb48-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-135"><a href="#cb48-135" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>2 comparisons = $1-.95^2=0.0975$</span>
<span id="cb48-136"><a href="#cb48-136" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>3 comparisons = $1-.95^3=0.1426$</span>
<span id="cb48-137"><a href="#cb48-137" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>4 comparisons = $1-.95^4=0.1855$</span>
<span id="cb48-138"><a href="#cb48-138" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>5 comparisons = $1-.95^5=0.2262$</span>
<span id="cb48-139"><a href="#cb48-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-140"><a href="#cb48-140" aria-hidden="true" tabindex="-1"></a>Obviously, we need to control for this. The post-hoc methods that were introduced this week are all similar in that they involve comparing two means (*a la t*-test) but differ in how the error is controlled. For example a Bonferroni-Dunn correction (which is often used as a post-hoc correction, although initially intended for correcting planned comparisons) adjusts for this by partitioning the significance (by diving your original alpha by the number of comparisons). A popular variant of this method, the Holm test, is a multistage test. It proceeds by ordering the obtained *t*-values from smallest to largest. We then evaluate the largest *t* according to the Bonferroni-Dunn correction $\alpha/c$. Each subsequent comparison *t* value, $n$ is evaluated against the correction $\alpha/(c-n)$. Please note I mention the these two methods with post-hoc analyses, although in true they are intended for planned comparisons. However, in instances in which the number of comparisons is relatively small, I've often seen them employed as post-hocs.</span>
<span id="cb48-141"><a href="#cb48-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-142"><a href="#cb48-142" aria-hidden="true" tabindex="-1"></a>So how many comparisons is relatively small? I'd suggest best form is to use the above methods when you have 5 or fewer comparisons, meaning that your critical $\alpha$ is .01. That said, with a post hoc test, you really do not have a choice in the number of comparisons you can make, you need to test for all possible comparisons on the IV. Why? well if not you are simply cherry picking your data. For example it would be poor form to take a look at our data like so:</span>
<span id="cb48-143"><a href="#cb48-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-144"><a href="#cb48-144" aria-hidden="true" tabindex="-1"></a>Plot:</span>
<span id="cb48-145"><a href="#cb48-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-148"><a href="#cb48-148" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-149"><a href="#cb48-149" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dataset,<span class="fu">aes</span>(<span class="at">x=</span>Group,<span class="at">y=</span>Time)) <span class="sc">+</span></span>
<span id="cb48-150"><a href="#cb48-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb48-151"><a href="#cb48-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="fu">aes</span>(<span class="at">width=</span>.<span class="dv">25</span>)) <span class="sc">+</span></span>
<span id="cb48-152"><a href="#cb48-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">35</span>)) <span class="sc">+</span> </span>
<span id="cb48-153"><a href="#cb48-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb48-154"><a href="#cb48-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-155"><a href="#cb48-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-156"><a href="#cb48-156" aria-hidden="true" tabindex="-1"></a>and then decide that you *only* want to compare 'McM' to 'MS' because that's where you see the greatest differences. Or that you simply want to take a look at "MM" and "SS" *without considering the rest*.</span>
<span id="cb48-157"><a href="#cb48-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-158"><a href="#cb48-158" aria-hidden="true" tabindex="-1"></a>Since you did not plan for or explicitly predict these differences from the outset, you are simply banking on what I like to say might be a "historical accident", that you simply stumbled into these results. As such, it's deemed as proper for to test *all* contingencies.</span>
<span id="cb48-159"><a href="#cb48-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-160"><a href="#cb48-160" aria-hidden="true" tabindex="-1"></a>In the case above there are $(5!)/(2!)(5-2)!$ = 10 combinations. If we were to run a Bonferroni correction in this case or critical $p$ would need to be $.05/10=.005$ which is an extremely conservative value, and thus dramatically inflates the likelihood of Type II error. In cases like this, Tukey's HSD is the traditionally preferred method, as it takes into account the characteristics of your data (in particular the standard error of the distribution) when calculating the critical $p$ value. As such in cases where many post-hoc, pairwise comparisons are made, Tukey's HSD is less conservative than a Bonferroni adjustment.</span>
<span id="cb48-161"><a href="#cb48-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-162"><a href="#cb48-162" aria-hidden="true" tabindex="-1"></a>One final method that is becoming more *en vogue* is the Ryan, Einot, Gabriel, Welsch method (REGWQ). Whereas Tukey's method holds the critical $p$ constant for all comparisons (at the loss of power) the REGWQ allows for an adjustment for the number of comparisons. It is currently being promoted as the most desirable post-hoc method.</span>
<span id="cb48-163"><a href="#cb48-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-164"><a href="#cb48-164" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bonferonni-Dunn and Holm tests</span></span>
<span id="cb48-165"><a href="#cb48-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-166"><a href="#cb48-166" aria-hidden="true" tabindex="-1"></a>In <span class="in">`R`</span> there are several ways in which we can call post hoc corrections. For example we can call the Bonferonni and Holm adjustments using <span class="in">`pairwise.t.test()`</span> function from the <span class="in">`base`</span> package (already installed). The <span class="in">`pairwise.t.test()`</span> method asks you to input:</span>
<span id="cb48-167"><a href="#cb48-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-168"><a href="#cb48-168" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`x`</span> = your DV</span>
<span id="cb48-169"><a href="#cb48-169" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`g`</span> = your grouping factor</span>
<span id="cb48-170"><a href="#cb48-170" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`p.adjust.method`</span> = the name of your desired correction in string format</span>
<span id="cb48-171"><a href="#cb48-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-172"><a href="#cb48-172" aria-hidden="true" tabindex="-1"></a>First let's run the <span class="in">`pairwise.t.tests`</span> with no adjustment (akin to uncorrected $p$ values):</span>
<span id="cb48-173"><a href="#cb48-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-176"><a href="#cb48-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-177"><a href="#cb48-177" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x =</span> dataset<span class="sc">$</span>Time, <span class="at">g =</span> dataset<span class="sc">$</span>Group,<span class="at">p.adjust.method =</span> <span class="st">"none"</span>)</span>
<span id="cb48-178"><a href="#cb48-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-179"><a href="#cb48-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-180"><a href="#cb48-180" aria-hidden="true" tabindex="-1"></a>You see above that we get a cross-matrix containing the $p$ values for each cross pair (row × column). Remember this is something we would never do in a post hoc (no corrections) but I wanted to first run this to illustrate a point. Now let's run the the Bonferroni and Holm corrections:</span>
<span id="cb48-181"><a href="#cb48-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-182"><a href="#cb48-182" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bonferroni example (pairwise.t.test())</span></span>
<span id="cb48-183"><a href="#cb48-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-186"><a href="#cb48-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-187"><a href="#cb48-187" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x =</span> dataset<span class="sc">$</span>Time, <span class="at">g =</span> dataset<span class="sc">$</span>Group,<span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb48-188"><a href="#cb48-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-189"><a href="#cb48-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-190"><a href="#cb48-190" aria-hidden="true" tabindex="-1"></a>You'll note that the <span class="in">`p-values`</span> displayed here are 10x the p-values from the uncorrected matrix. To demonstrate this:</span>
<span id="cb48-191"><a href="#cb48-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-194"><a href="#cb48-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-195"><a href="#cb48-195" aria-hidden="true" tabindex="-1"></a>uncorrected <span class="ot">&lt;-</span> <span class="fu">pairwise.t.test</span>(<span class="at">x =</span> dataset<span class="sc">$</span>Time, <span class="at">g =</span> dataset<span class="sc">$</span>Group,<span class="at">p.adjust.method =</span> <span class="st">"none"</span>)</span>
<span id="cb48-196"><a href="#cb48-196" aria-hidden="true" tabindex="-1"></a>bonf_corrected <span class="ot">&lt;-</span> <span class="fu">pairwise.t.test</span>(<span class="at">x =</span> dataset<span class="sc">$</span>Time, <span class="at">g =</span> dataset<span class="sc">$</span>Group,<span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb48-197"><a href="#cb48-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-198"><a href="#cb48-198" aria-hidden="true" tabindex="-1"></a>bonf_corrected<span class="sc">$</span>p.value<span class="sc">/</span>uncorrected<span class="sc">$</span>p.value</span>
<span id="cb48-199"><a href="#cb48-199" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-200"><a href="#cb48-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-201"><a href="#cb48-201" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>note that the <span class="in">`1.378`</span> value is the result of p being capped at $p=1$ in the Bonferroni corrected comparison.</span>
<span id="cb48-202"><a href="#cb48-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-203"><a href="#cb48-203" aria-hidden="true" tabindex="-1"></a>Remember from a few paragraphs back that there are 10 possible combinations so the Bonferonni test would need to divide the critical alpha by 10. What this means is that anytime you perform a correction, <span class="in">`R`</span> actually adjusts the $p$ values for you; therefore you may interpret the output against your original (familywise) $\alpha$. So here, any values that are still less than .05 after the corrections are significant.</span>
<span id="cb48-204"><a href="#cb48-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-205"><a href="#cb48-205" aria-hidden="true" tabindex="-1"></a>Moving on...</span>
<span id="cb48-206"><a href="#cb48-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-207"><a href="#cb48-207" aria-hidden="true" tabindex="-1"></a><span class="fu">### Holm example (pairwise.t.test())</span></span>
<span id="cb48-208"><a href="#cb48-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-211"><a href="#cb48-211" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-212"><a href="#cb48-212" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x =</span> dataset<span class="sc">$</span>Time, <span class="at">g =</span> dataset<span class="sc">$</span>Group,<span class="at">p.adjust.method =</span> <span class="st">"holm"</span>)</span>
<span id="cb48-213"><a href="#cb48-213" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-214"><a href="#cb48-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-215"><a href="#cb48-215" aria-hidden="true" tabindex="-1"></a><span class="fu">## Tukey HSD and REGWQ tests</span></span>
<span id="cb48-216"><a href="#cb48-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-217"><a href="#cb48-217" aria-hidden="true" tabindex="-1"></a>In order to run Tukey's HSD and REGWQ methods we call upon the <span class="in">`agricolae`</span> package. In this case, we need to input our <span class="in">`lm() model`</span> into the function, as well as identify our "treatment" (in this case our "Group" factor). For example:</span>
<span id="cb48-218"><a href="#cb48-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-219"><a href="#cb48-219" aria-hidden="true" tabindex="-1"></a><span class="fu">### Tukey HSD example (agricolae)</span></span>
<span id="cb48-220"><a href="#cb48-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-223"><a href="#cb48-223" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-224"><a href="#cb48-224" aria-hidden="true" tabindex="-1"></a>morphine_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(Time<span class="sc">~</span>Group,<span class="at">data =</span> dataset) <span class="co"># from above</span></span>
<span id="cb48-225"><a href="#cb48-225" aria-hidden="true" tabindex="-1"></a>agricolae<span class="sc">::</span><span class="fu">HSD.test</span>(morphine_mdl,<span class="at">trt =</span> <span class="st">"Group"</span>,<span class="at">group =</span> T,<span class="at">console =</span> T) </span>
<span id="cb48-226"><a href="#cb48-226" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-227"><a href="#cb48-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-228"><a href="#cb48-228" aria-hidden="true" tabindex="-1"></a>Note that the <span class="in">`group`</span> and <span class="in">`console`</span> arguments pertain to the output. You typically will want to keep console set to <span class="in">`TRUE`</span> as that simply prints the output of your test. The <span class="in">`group`</span> argument controls how the output is presented. Above we set it to <span class="in">`TRUE.`</span> This results in an output that groups the treatment means into subsets where treatments with the same letter are not significantly different from one another, known as *compact letter displays*. For example, *a*s are not significantly different from each other, *b*s are not significantly different from each other, **but** *a*s are different from *b*s. Conversely if you wanted to see each comparison you can set this to <span class="in">`FALSE`</span>:</span>
<span id="cb48-229"><a href="#cb48-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-232"><a href="#cb48-232" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-233"><a href="#cb48-233" aria-hidden="true" tabindex="-1"></a>agricolae<span class="sc">::</span><span class="fu">HSD.test</span>(morphine_mdl,<span class="at">trt =</span> <span class="st">"Group"</span>,<span class="at">group =</span> <span class="cn">FALSE</span>,<span class="at">console =</span> <span class="cn">TRUE</span>) </span>
<span id="cb48-234"><a href="#cb48-234" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-235"><a href="#cb48-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-236"><a href="#cb48-236" aria-hidden="true" tabindex="-1"></a>Finally, if you do decide to group (<span class="in">`group=TRUE`</span>), you can take the outcome of this function and use it to generate a nice group plot. This is useful for quick visual inspection.</span>
<span id="cb48-237"><a href="#cb48-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-240"><a href="#cb48-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-241"><a href="#cb48-241" aria-hidden="true" tabindex="-1"></a>agricolae<span class="sc">::</span><span class="fu">HSD.test</span>(morphine_mdl,<span class="at">trt =</span> <span class="st">"Group"</span>,<span class="at">group =</span> T,<span class="at">console =</span> T) <span class="sc">%&gt;%</span> <span class="fu">plot</span>()</span>
<span id="cb48-242"><a href="#cb48-242" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-243"><a href="#cb48-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-244"><a href="#cb48-244" aria-hidden="true" tabindex="-1"></a><span class="fu">### REGWQ example (agricolae)</span></span>
<span id="cb48-245"><a href="#cb48-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-246"><a href="#cb48-246" aria-hidden="true" tabindex="-1"></a>The same applies to REGW, using the <span class="in">`REGW.test()`</span> function (with <span class="in">`group=F`</span>, I'm showing all of the comparisons):</span>
<span id="cb48-247"><a href="#cb48-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-250"><a href="#cb48-250" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-251"><a href="#cb48-251" aria-hidden="true" tabindex="-1"></a>agricolae<span class="sc">::</span><span class="fu">REGW.test</span>(morphine_mdl,<span class="at">trt =</span> <span class="st">"Group"</span>,<span class="at">group =</span> F,<span class="at">console =</span> T) </span>
<span id="cb48-252"><a href="#cb48-252" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-253"><a href="#cb48-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-254"><a href="#cb48-254" aria-hidden="true" tabindex="-1"></a>Compact letter displays are nice (SPSS generates them, too), but as seems to always be the case, there is some controversy as to whether we should use them. Taken from this vignette:</span>
<span id="cb48-255"><a href="#cb48-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-256"><a href="#cb48-256" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; CLD displays promote visually the idea that two means that are "not significantly different" are to be judged as being equal; and that is a very wrong interpretation. In addition, they draw an artificial "bright line" between P values on either side of alpha, even ones that are very close.</span></span>
<span id="cb48-257"><a href="#cb48-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-258"><a href="#cb48-258" aria-hidden="true" tabindex="-1"></a><span class="fu"># Using estimated marginal means, `emmeans()`</span></span>
<span id="cb48-259"><a href="#cb48-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-260"><a href="#cb48-260" aria-hidden="true" tabindex="-1"></a>In previous years I would have stopped here and left you with the impression that you may need to call different packages depending on what post-hoc (or later, contrast) you intend to run. While this is perfectly acceptable, more and more I am using the estimated marginal means (package) to perform just about all of my post hoc analyses and contrasts. From the <span class="in">`emmeans`</span> vignette <span class="co">[</span><span class="ot">(link)</span><span class="co">](https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html#EMMdef)</span>:</span>
<span id="cb48-261"><a href="#cb48-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-262"><a href="#cb48-262" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Estimated marginal means are based on a model -- not directly on data. The basis for them is what we call the reference grid for a given model. To obtain the reference grid, consider all the predictors in the model.</span></span>
<span id="cb48-263"><a href="#cb48-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-264"><a href="#cb48-264" aria-hidden="true" tabindex="-1"></a>(The notion of a reference grid will become more apparent when we more into factorial ANOVA For now, let's just focus on practical implementation).</span>
<span id="cb48-265"><a href="#cb48-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-266"><a href="#cb48-266" aria-hidden="true" tabindex="-1"></a>I typically use this framework as it allows for a higher level of flexibility in analyzing contrasts while still being unified. We'll see just how far we can go in the upcoming weeks. For now, let's use the <span class="in">`emmeans`</span> package to perform our post-hoc analyses from above.</span>
<span id="cb48-267"><a href="#cb48-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-268"><a href="#cb48-268" aria-hidden="true" tabindex="-1"></a>We start by throwing our model into the <span class="in">`emmeans()`</span> function, specifying our test as a function of our comparison. We also need to tell <span class="in">`R`</span> what adjustment (correction) we desire. To remind ourselves, our model is:</span>
<span id="cb48-269"><a href="#cb48-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-272"><a href="#cb48-272" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-273"><a href="#cb48-273" aria-hidden="true" tabindex="-1"></a>morphine_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Time<span class="sc">~</span>Group,<span class="at">data =</span> dataset)</span>
<span id="cb48-274"><a href="#cb48-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-275"><a href="#cb48-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-276"><a href="#cb48-276" aria-hidden="true" tabindex="-1"></a>For a <span class="in">`pairwise`</span> test with a <span class="in">`bonferroni`</span> correction we need to specify what factor (or predictor or IV) we are running our pairwise comparisons on (<span class="in">`spec =`</span>), and that we are <span class="in">`adjusting`</span> by using the bonferonni (<span class="in">`bonf`</span>). This takes the general form:</span>
<span id="cb48-277"><a href="#cb48-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-280"><a href="#cb48-280" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-281"><a href="#cb48-281" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(morphine_mdl, <span class="at">specs =</span> <span class="sc">~</span>Group) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"bonf"</span>)</span>
<span id="cb48-282"><a href="#cb48-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-283"><a href="#cb48-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-284"><a href="#cb48-284" aria-hidden="true" tabindex="-1"></a><span class="in">`emmeans`</span> also allows us to run a pairwise Tukey test:</span>
<span id="cb48-285"><a href="#cb48-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-288"><a href="#cb48-288" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-289"><a href="#cb48-289" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(morphine_mdl, <span class="at">specs =</span> <span class="sc">~</span>Group) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb48-290"><a href="#cb48-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-291"><a href="#cb48-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-292"><a href="#cb48-292" aria-hidden="true" tabindex="-1"></a><span class="fu">## Alternative to CLD()</span></span>
<span id="cb48-293"><a href="#cb48-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-294"><a href="#cb48-294" aria-hidden="true" tabindex="-1"></a>One thing to note, the curator of the <span class="in">`emmeans()`</span> package is not a fan of <span class="in">`cld`</span> (Compact Letter Displays) and instead has created <span class="in">`pwpp`</span> as a visualization tool.</span>
<span id="cb48-295"><a href="#cb48-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-298"><a href="#cb48-298" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-299"><a href="#cb48-299" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(morphine_mdl, <span class="at">specs =</span> <span class="sc">~</span>Group) <span class="sc">%&gt;%</span> <span class="fu">pwpp</span>()</span>
<span id="cb48-300"><a href="#cb48-300" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-301"><a href="#cb48-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-302"><a href="#cb48-302" aria-hidden="true" tabindex="-1"></a>You can visit <span class="co">[</span><span class="ot">this vignette</span><span class="co">](https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html)</span> to get a feel for what is at issue here.</span>
<span id="cb48-303"><a href="#cb48-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-304"><a href="#cb48-304" aria-hidden="true" tabindex="-1"></a><span class="fu">## Effect sizes</span></span>
<span id="cb48-305"><a href="#cb48-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-306"><a href="#cb48-306" aria-hidden="true" tabindex="-1"></a>Typically when reporting the effect size of the difference between two means we use Cohen's $d$. However, calculating Cohen's \$d\$ in a posthoc contrast is slightly more involved than the method used for a regular t-test. This is because with a regular t-test you only have 2 means from 2 samples that you have collected. In the case of pairwise contrasts in ANOVA, while you are only comparing two means, those means are nested within a larger group (e.g., when comparing MS and MM, we still need to account for the fact that we also collected samples from SS, SM, and McM). That is, you need to understand the difference between the two means **in the context of the entire model.**</span>
<span id="cb48-307"><a href="#cb48-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-308"><a href="#cb48-308" aria-hidden="true" tabindex="-1"></a>Simply put, in our calculations we need to account for the influence of all of our collected groups. This is done by placing the contrasted difference in the context of the Root Mean Square Error, or the square root of the Mean Square Error of the residuals in our ANOVA model. Recall that typically Cohen's $d$ is the **difference between the two means** divided by their **pooled standard deviation**. Here, $d$ is the **difference between the two means** divided by ***sigma, or the estimated standard deviation of the errors of the linear model.***</span>
<span id="cb48-309"><a href="#cb48-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-310"><a href="#cb48-310" aria-hidden="true" tabindex="-1"></a>To do this we're going to need two things from the original model. Let's take a look at the model summary:</span>
<span id="cb48-311"><a href="#cb48-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-314"><a href="#cb48-314" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-315"><a href="#cb48-315" aria-hidden="true" tabindex="-1"></a>morphine_mdl <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb48-316"><a href="#cb48-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-317"><a href="#cb48-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-318"><a href="#cb48-318" aria-hidden="true" tabindex="-1"></a>The values line that is important to us is the <span class="in">`Residual standard error ___ on __ degrees of freedom`</span>---in this case the values **5.657** and **35** respectively.</span>
<span id="cb48-319"><a href="#cb48-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-320"><a href="#cb48-320" aria-hidden="true" tabindex="-1"></a>Assuming you have run your comparisons using <span class="in">`emmeans()`</span> you can calculate your effect sizes for each comparison using <span class="in">`emmeans::eff_size()`</span>.</span>
<span id="cb48-321"><a href="#cb48-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-322"><a href="#cb48-322" aria-hidden="true" tabindex="-1"></a><span class="in">`eff_size()`</span> takes three arguments:</span>
<span id="cb48-323"><a href="#cb48-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-324"><a href="#cb48-324" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the emmeans object</span>
<span id="cb48-325"><a href="#cb48-325" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the estimated standard deviation of the errors of the linear model, <span class="in">`sigma`</span></span>
<span id="cb48-326"><a href="#cb48-326" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the residual degrees of freedom from the model, <span class="in">`df.residual`</span></span>
<span id="cb48-327"><a href="#cb48-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-328"><a href="#cb48-328" aria-hidden="true" tabindex="-1"></a>The functions <span class="in">`sigma()`</span> and <span class="in">`df.residual()`</span> allow us to get this information directly from the model. A typical call would look something like this</span>
<span id="cb48-329"><a href="#cb48-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-332"><a href="#cb48-332" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-333"><a href="#cb48-333" aria-hidden="true" tabindex="-1"></a><span class="co"># save your contrasts to an object</span></span>
<span id="cb48-334"><a href="#cb48-334" aria-hidden="true" tabindex="-1"></a>mdl_contrasts <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(morphine_mdl, <span class="at">specs =</span> <span class="sc">~</span>Group)</span>
<span id="cb48-335"><a href="#cb48-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-336"><a href="#cb48-336" aria-hidden="true" tabindex="-1"></a><span class="co"># use the saved object in the following function</span></span>
<span id="cb48-337"><a href="#cb48-337" aria-hidden="true" tabindex="-1"></a><span class="fu">eff_size</span>(mdl_contrasts,<span class="at">sigma =</span> <span class="fu">sigma</span>(morphine_mdl), <span class="fu">df.residual</span>(morphine_mdl))</span>
<span id="cb48-338"><a href="#cb48-338" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-339"><a href="#cb48-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-340"><a href="#cb48-340" aria-hidden="true" tabindex="-1"></a>That said, there is some debate as to whether this is the most appropriate way to calculate posthoc effect sizes, or whether posthoc effect sizes are in general a proper thing to calculate. I've personally never had a reviewer ask for one, **BUT** if I had to provide on I would use this method.</span>
<span id="cb48-341"><a href="#cb48-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-342"><a href="#cb48-342" aria-hidden="true" tabindex="-1"></a>FWIW, this won't be the last time that we need to call back to the original (omnibus) ANOVA when conducting posthoc tests. Things get a little messier next week!</span>
<span id="cb48-343"><a href="#cb48-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-344"><a href="#cb48-344" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reporting and ANOVA with post hoc analyses.</span></span>
<span id="cb48-345"><a href="#cb48-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-346"><a href="#cb48-346" aria-hidden="true" tabindex="-1"></a>In your report, you need to include information for the main ANOVA as well as information related to</span>
<span id="cb48-347"><a href="#cb48-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-348"><a href="#cb48-348" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the omnibus ANOVA</span>
<span id="cb48-349"><a href="#cb48-349" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>a statement on what multiple comparisons were run and how corrected</span>
<span id="cb48-350"><a href="#cb48-350" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>note which comparisons were significant.</span>
<span id="cb48-351"><a href="#cb48-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-352"><a href="#cb48-352" aria-hidden="true" tabindex="-1"></a>If we work off of our last example, you'll note that there are quite a few comparisons that we could discuss (10 in fact). In cases like these you could either put this information into a formatted table, or simply highlight a few that are especially relevant. For example, looking at the <span class="in">`emmeans()`</span> outcome as well as the <span class="in">`CLD`</span> plot from <span class="in">`agricolae::HSD.test`</span> we see that McM and SM (a's) in the CLD plot are both significantly greater than the remain conditions (b's). Based on this I would write something like:</span>
<span id="cb48-353"><a href="#cb48-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-354"><a href="#cb48-354" aria-hidden="true" tabindex="-1"></a>... Our ANOVA revealed a significant effect for Morphine treatment group, *F*(4, 35) = 27.325, *p* <span class="sc">\&lt;</span> .001. Tukey pairwise comparisons revealed that the mean tolerance times for the both the SM ($M±SD$: 24.00 ± 6.37) and McM (29.00 ± 6.16) groups were greater than the remaining three groups ($ps$ <span class="sc">\&lt;</span> .05), but not different from one another. The mean times for the remaining three conditions were not significantly different from one another, $ps &gt; .05$ (see Figure 1)</span>
<span id="cb48-355"><a href="#cb48-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-356"><a href="#cb48-356" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>assuming Figure 1 is a camera ready plot you've created in <span class="in">`ggplot()`</span>. Any of the barplots in this walkthrough will suffice.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Written by <a href="https://tehrandav.is">Tehran Davis</a> of PSYC 7014.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>