<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Tehran Davis">
<meta name="dcterms.date" content="2023-06-07">
<title>PSYC 7014: Graduate Statistics 1 - 35&nbsp; Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../week10/10_1-main_effects.html" rel="next">
<link href="../week09/9_1-posthocs.html" rel="prev">
<link href="../images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">PSYC 7014: Graduate Statistics 1</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Graduate Statistics Walkthroughs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part 1: INTRO to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_1-getting_started.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting started</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_2-resources.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Links to resources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_1-Rmarkdown_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Rmarkdown Basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_2-objects_assignment_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Objects, assignment, and functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_3-install_packages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Installing and loading an <code>R</code> package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_4-loading_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Loading in Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_5-leveling-up.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Leveling-up</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part 2: DESCRIBING &amp; VISUALIZING DATA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_1-structure_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The structure of your data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_2-central_tendency.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Measures of central tendency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_3-summary_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Creating summary tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_1-basic_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Basic ggplotting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_2-more_adv_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">More advanced ggPlots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_4-means_other_models.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Means and other models</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part 3: DISTRIBUTIONS and NHST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The normal distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_2-building_intuitions_about_probability_and_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Building intuitions about probability and NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Sampling distributions and seeing the logic of NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_4-more_examples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">More examples of distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_5-bias_variance.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Bias in sample variance estimates</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Part 4: MODELING w/ CONTINUOUS PREDICTORS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_2_correlations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_3_regressions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regression, pt.&nbsp;1: Running the model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_4_plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Plotting regression data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_5_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Regression model diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_6_example_report.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Example Report</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Part 5: T-TESTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_1_t-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing differences in means / t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_2_t-test-null-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Thinking about nothing (aka the null)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_3_t-test-lm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">t-test? It’s just a linear model</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Part 6: Power &amp; Effect Size</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_1-effect_size.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Effect Size</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_2-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_3-power_es_sig_tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Power, Effect sizes, and Significance testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_4-simulating_power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Simulating Power!!!</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Part 7: One-way ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_1-one-way-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">The One-way ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_2-anova-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">ANOVA and Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_1-posthocs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_2-planned_contrasts.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">Part 8: Factorial ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_1-main_effects.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Factorial ANOVA - The omnibus ANOVA and Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_2-factorial_w_post_hocs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Factorial ANOVA - Post hoc analysis of Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_3-advanced_example_and_apa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Template for Analysis &amp; APA Style</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Part 9: Repeated Measures ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_1-afex_ANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">afex is for ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_2-repeated_measures_anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Within Subjects / Repeated Measures ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_3-factorial_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Factorial RM-ANOVA and simple effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_4-sphericity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Sphericity: Variances and Co-Variances</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_5-spss_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Running a RM-ANOVA in SPSS</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#tldr-steps-for-running-an-a-priori-contrasts" id="toc-tldr-steps-for-running-an-a-priori-contrasts" class="nav-link active" data-scroll-target="#tldr-steps-for-running-an-a-priori-contrasts"><span class="toc-section-number">35.1</span>  TLDR; Steps for running an a-priori contrasts:</a></li>
  <li><a href="#a-few-considerations-regarding-planned-contrasts" id="toc-a-few-considerations-regarding-planned-contrasts" class="nav-link" data-scroll-target="#a-few-considerations-regarding-planned-contrasts"><span class="toc-section-number">35.2</span>  A few considerations regarding planned contrasts</a></li>
  <li><a href="#the-logic-of-planned-contrasts" id="toc-the-logic-of-planned-contrasts" class="nav-link" data-scroll-target="#the-logic-of-planned-contrasts"><span class="toc-section-number">35.3</span>  The logic of planned contrasts</a></li>
  <li>
<a href="#performing-planned-contrasts-in-r" id="toc-performing-planned-contrasts-in-r" class="nav-link" data-scroll-target="#performing-planned-contrasts-in-r"><span class="toc-section-number">35.4</span>  Performing planned contrasts in R</a>
  <ul class="collapse">
<li><a href="#making-the-contrasts-output-easier-to-read" id="toc-making-the-contrasts-output-easier-to-read" class="nav-link" data-scroll-target="#making-the-contrasts-output-easier-to-read"><span class="toc-section-number">35.4.1</span>  Making the contrasts output easier to read</a></li>
  <li><a href="#effect-size-for-planned-contrasts" id="toc-effect-size-for-planned-contrasts" class="nav-link" data-scroll-target="#effect-size-for-planned-contrasts"><span class="toc-section-number">35.4.2</span>  Effect size for planned contrasts</a></li>
  </ul>
</li>
  <li><a href="#reporting-your-results" id="toc-reporting-your-results" class="nav-link" data-scroll-target="#reporting-your-results"><span class="toc-section-number">35.5</span>  Reporting your results</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">
<span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tehran Davis </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 7, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header><section id="tldr-steps-for-running-an-a-priori-contrasts" class="level2" data-number="35.1"><h2 data-number="35.1" class="anchored" data-anchor-id="tldr-steps-for-running-an-a-priori-contrasts">
<span class="header-section-number">35.1</span> TLDR; Steps for running an a-priori contrasts:</h2>
<p>This walkthrough requires the following to be installed / loaded in <code>R</code></p>
<ol type="1">
<li>Be sure that the column that contains your IV is indeed being treated as a factor. If it is <code>levels(IV)</code> will list your levels, also the column containing the IV will contain <code>&lt;fct&gt;</code>. If not <code>mutate()</code> as column with your IV as a factor, ex: <code>newCol = factor(oldCol)</code>
</li>
<li>check the order of your IV using <code><a href="https://rdrr.io/r/base/levels.html">levels()</a></code>. If you need to reorder, use <code>fct_relevel()</code>
</li>
<li>create your contrast matrix according to the levels obtained in Step 1</li>
<li>build an ANOVA model using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>, or <code>afex()</code> (output to lm)</li>
<li>run your contrasts using <code>emmeans()</code>, inputting</li>
</ol>
<ul>
<li>your ANOVA model from Step 3</li>
<li>your contrasts from Step 2</li>
<li>your familywise correction (if any)</li>
</ul>
<p>Example (run line-by-line):</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Preliminaries</span></span>
<span><span class="co">## load in data</span></span>
<span><span class="va">dataset</span> <span class="op">&lt;-</span> <span class="fu">read_table2</span><span class="op">(</span><span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `read_table2()` was deprecated in readr 2.0.0.
ℹ Please use `read_table()` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  ID = col_character(),
  Group = col_double(),
  Time = col_double()
)</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## check data, identify columns</span></span>
<span><span class="va">dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 3
   ID    Group  Time
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 01        1     3
 2 02        1     5
 3 03        1     1
 4 04        1     8
 5 05        1     1
 6 06        1     1
 7 07        1     4
 8 08        1     9
 9 09        2     2
10 10        2    12
# ℹ 30 more rows</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Group is numerically coded. Fixing this and turning to a factor</span></span>
<span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span> <span class="op">&lt;-</span> <span class="fu">recode_factor</span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>, <span class="st">"1"</span><span class="op">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="op">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="op">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="op">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="op">=</span><span class="st">"McM"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Step 1: Check levels</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MS"  "MM"  "SS"  "SM"  "McM"</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Step 2: build contrasts</span></span>
<span><span class="co">## MS v. MM</span></span>
<span><span class="va">contrast1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="op">-</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span> </span>
<span></span>
<span><span class="co">## MS + MM v. SS + SM + McM</span></span>
<span><span class="va">contrast2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">/</span><span class="fl">2</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span><span class="op">)</span></span>
<span></span>
<span><span class="va">my_contrasts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"MS v. MM"</span> <span class="op">=</span> <span class="va">contrast1</span>,</span>
<span>                      <span class="st">"MS + MM v. SS + SM + McM"</span> <span class="op">=</span> <span class="va">contrast2</span></span>
<span>                     <span class="op">)</span></span>
<span></span>
<span><span class="co"># Step 3</span></span>
<span><span class="va">morphine_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Time</span><span class="op">~</span><span class="va">Group</span>, data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># Step 4</span></span>
<span><span class="fu">emmeans</span><span class="op">(</span>object <span class="op">=</span> <span class="va">morphine_mdl</span>,specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span>, adjust<span class="op">=</span><span class="st">"bonf"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">contrast</span><span class="op">(</span>method <span class="op">=</span> <span class="va">my_contrasts</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                 estimate   SE df t.ratio p.value
 MS v. MM                     -6.0 2.83 35  -2.121  0.0411
 MS + MM v. SS + SM + McM    -14.3 1.83 35  -7.851  &lt;.0001</code></pre>
</div>
</div>
</section><section id="a-few-considerations-regarding-planned-contrasts" class="level2" data-number="35.2"><h2 data-number="35.2" class="anchored" data-anchor-id="a-few-considerations-regarding-planned-contrasts">
<span class="header-section-number">35.2</span> A few considerations regarding planned contrasts</h2>
<p>If you have reasons to predict differences between particular sets of group means that are theory-driven, then you may perform <em>a priori</em> or planned contrasts. Logically, planned contrasts are similar to post-hoc tests in that we are comparing against two means, but there are some differences that make planned contrasts more powerful.</p>
<ul>
<li><p>Since your predictions are made prior to collecting data you, technically do not need to get a significant result on the omnibus ANOVA to run your contrasts. However, when doing post-hoc tests, if the omnibus ANOVA fails to reject the null, convention is that you are not permitted to run follow-up post hoc tests.</p></li>
<li><p>Since you are making predictions prior to seeing the outcome of your observed data, then you are safe to make a limited number of comparisons without the charge of cherry-picking. For example, if you have predicted-ahead that there would be differences between groups “MS” and “McM”, or groups “MM” and “MS” then you are free to run those comparisons and those comparisons-only. This is especially useful, since by limiting the number of comparisons you can keep the required corrections relatively minimal. This allows you to effectively reduce the problem of Type I error inflation while limiting the possibility of Type II error. For example, recall that using a Bonferonni correction on this data in the post-hoc case mandates that I use an adjusted <span class="math inline">\(\alpha\)</span> of .005 (.05/10 comparisons), even if I was only really interested in these two comparisons. Here, I am allowed to only perform these two, so my adjusted <span class="math inline">\(p\)</span> is .025.</p></li>
<li><p>Depending on the number of comparisons, you may be justified in not performing any <span class="math inline">\(p\)</span> correction at all. For example some recommend no need for correction if the number of contrasts is low or when the comparisons are complementary (e.g.&nbsp;orthogonal). See <a href="http://jrp.icaap.org/index.php/jrp/article/view/514/417">here</a>, <a href="https://www.graphpad.com/support/faqid/1390/">here</a>, and <a href="http://pirun.ku.ac.th/~faasatp/734462/data/06_contrasts2.pdf">here</a> for discussion of this issue.</p></li>
<li><p>We can easily perform a variety of comparisons using planned contrasts. For example, say we are interested in whether MS is different from the mean of the remaining groups (McM+MM+SM+SS), or that MM+MS is different from McM+SM+SS. We can test this using planned contrasts.</p></li>
</ul></section><section id="the-logic-of-planned-contrasts" class="level2" data-number="35.3"><h2 data-number="35.3" class="anchored" data-anchor-id="the-logic-of-planned-contrasts">
<span class="header-section-number">35.3</span> The logic of planned contrasts</h2>
</section><section id="performing-planned-contrasts-in-r" class="level2" data-number="35.4"><h2 data-number="35.4" class="anchored" data-anchor-id="performing-planned-contrasts-in-r">
<span class="header-section-number">35.4</span> Performing planned contrasts in R</h2>
<p>As outlined in both Winter and Field, planned contrasts begin by creating contrast weights. The idea with contrast weights is that the groups that are being compared should sum to equal -1 and +1 respectively, resulting in a null test against 0 (i.e.&nbsp;the two weighted means are equal). Any groups that are not being included in the comparison should be assigned weights of 0. You’ve already seen contrasts before, when looking at the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> ANOVA output. We remarked that this output allows you to make a comparison of each group against the control group.</p>
<p>First let’s load in the data and recode the factors:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## load in data</span></span>
<span><span class="va">dataset</span> <span class="op">&lt;-</span> <span class="fu">read_table2</span><span class="op">(</span><span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  ID = col_character(),
  Group = col_double(),
  Time = col_double()
)</code></pre>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Group is numerically coded. Fixing this and turning to a factor</span></span>
<span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span> <span class="op">&lt;-</span> <span class="fu">recode_factor</span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span>, <span class="st">"1"</span><span class="op">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="op">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="op">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="op">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="op">=</span><span class="st">"McM"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 3
   ID    Group  Time
   &lt;chr&gt; &lt;fct&gt; &lt;dbl&gt;
 1 01    MS        3
 2 02    MS        5
 3 03    MS        1
 4 04    MS        8
 5 05    MS        1
 6 06    MS        1
 7 07    MS        4
 8 08    MS        9
 9 09    MM        2
10 10    MM       12
# ℹ 30 more rows</code></pre>
</div>
</div>
<p>Looking at Siegel’s data we see that MS defaults as the control:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Step 1: Check levels</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MS"  "MM"  "SS"  "SM"  "McM"</code></pre>
</div>
</div>
<p>We can check which contrasts any model we run will default to, by invoking <code><a href="https://rdrr.io/r/stats/contrasts.html">contrasts()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    MM SS SM McM
MS   0  0  0   0
MM   1  0  0   0
SS   0  1  0   0
SM   0  0  1   0
McM  0  0  0   1</code></pre>
</div>
</div>
<p>These sorts of contrasts are known as treatment contrasts… measuring the effect of each treatment against a control. While there are several types of contrasts built into <code>R</code> we can create custom contrasts as well.</p>
<p>For example assume we are comparing “MS” to “MM” and were not concerned with the remaining groups. Then our contrast weights would be:</p>
<ul>
<li>MS = +1</li>
<li>MM = -1</li>
<li>McM = SM = SS = 0</li>
</ul>
<p>How about we want to compare McM + MM against the remaining three groups?</p>
<ul>
<li>MS + MM = 1</li>
<li>McM + SM + SS = -1</li>
</ul>
<p>From there we distribute the weight equally between the number of groups on each side of the contrast, so</p>
<ul>
<li>MS = +1/2; MM = +1/2</li>
<li>McM = -1/3; SM = -1/3; SS = -1/3</li>
</ul>
<p>in R we can construct each of these contrasts like so:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># checking the order of groups:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MS"  "MM"  "SS"  "SM"  "McM"</code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># building contrasts</span></span>
<span></span>
<span><span class="co"># MS v. MM</span></span>
<span><span class="va">contrast1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="op">-</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># MS + MM v. SS + SM + McM</span></span>
<span><span class="va">contrast2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">/</span><span class="fl">2</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When performing planned contrasts in <code>R</code> I recommend using the <code>emmeans</code> package rather than the <code>base</code> package examples in the Field text. For those that are interested as to why, in my experience the <code>base</code> method has a hard time dealing with non-orthogonal contrasts.</p>
<p><strong>To perform the contrast requires 3 steps:</strong></p>
<ul>
<li>run your omnibus ANOVA <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> model and save it as an object</li>
<li>input your <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> model into the <code>emmeans()</code> function, specifying the name of your IV and save it to an object</li>
<li>submit your <code>emmeans</code> object to the <code><a href="https://rdrr.io/r/stats/contrasts.html">contrasts()</a></code> function indicating what your contrasts are.</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">morphine_mdl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">Time</span><span class="op">~</span><span class="va">Group</span>,data <span class="op">=</span> <span class="va">dataset</span><span class="op">)</span></span>
<span><span class="va">emm_mdl</span> <span class="op">&lt;-</span> <span class="fu">emmeans</span><span class="op">(</span><span class="va">morphine_mdl</span>,specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span><span class="op">)</span></span>
<span><span class="fu">contrast</span><span class="op">(</span><span class="va">emm_mdl</span>, method <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">contrast1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast          estimate   SE df t.ratio p.value
 c(1, -1, 0, 0, 0)       -6 2.83 35  -2.121  0.0411</code></pre>
</div>
</div>
<p>The above result tells me:</p>
<ul>
<li>
<code>contrast</code>: the defined contrast</li>
<li>
<code>estimate</code>: the difference in means between my contrasted groups</li>
<li>
<code>SE</code>: a measure of variability</li>
<li>
<code>t.ratio</code>: obtained from the t-test between groups</li>
<li>
<code>p.value</code>: the resulting p-value</li>
</ul>
<p>Based upon these results I conclude that “MS” and “MM” are significantly different from one another. I make no claims about the other three conditions.</p>
<p>Recall that <code>contrast2</code> was testing [MS + MM] v. [SS + SM + McM]. If this was my only contrast I could run it independently as above. However, we can also test multiple contrasts simultaneously with a single test. We just add additional contrasts to the list in the method. So, for both <code>contrast1</code> and <code>contrast2</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">contrast</span><span class="op">(</span><span class="va">emm_mdl</span>, </span>
<span>         method <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">contrast1</span>,<span class="va">contrast2</span><span class="op">)</span>,</span>
<span>         <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                                              
 c(1, -1, 0, 0, 0)                                                     
 c(0.5, 0.5, -0.333333333333333, -0.333333333333333, -0.333333333333333
 estimate   SE df t.ratio p.value
     -6.0 2.83 35  -2.121  0.0411
    -14.3 1.83 35  -7.851  &lt;.0001</code></pre>
</div>
</div>
<section id="making-the-contrasts-output-easier-to-read" class="level3" data-number="35.4.1"><h3 data-number="35.4.1" class="anchored" data-anchor-id="making-the-contrasts-output-easier-to-read">
<span class="header-section-number">35.4.1</span> Making the contrasts output easier to read</h3>
<p>One thing you may have noticed above is that your contrasts aren’t labeled very transparently. Looking at the output you would have to remember what was being contrasted in <code>contrast1</code> and <code>contrast2</code>. You can save yourself a little headache if you label your contrasts while constructing the matrix. Let’s say I wanted to run these four contrasts based upon my levels:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dataset</span><span class="op">$</span><span class="va">Group</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MS"  "MM"  "SS"  "SM"  "McM"</code></pre>
</div>
</div>
<p>Now setting up my contrasts to match:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">contrast1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="op">-</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">contrast2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">contrast3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span>,<span class="op">-</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">contrast4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>,<span class="op">-</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>,<span class="fl">1</span><span class="op">/</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From here you can modify the previous code to assign names to the rows in your contrast matrix. For the sake of ease, I like to create an object, <code>my_contrasts</code> that includes the list of all contrasts. FWIW, on of the annoying things about the <code>contrast</code> function is that it requires the <code>method</code> argument of contrasts to be in a <code><a href="https://rdrr.io/r/base/list.html">list()</a></code>, even if its just one contrast.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">my_contrasts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"MM v. McM"</span> <span class="op">=</span> <span class="va">contrast1</span>,</span>
<span>                     <span class="st">"MS v. SS"</span> <span class="op">=</span> <span class="va">contrast2</span>,</span>
<span>                     <span class="st">"MM v. SS"</span> <span class="op">=</span> <span class="va">contrast3</span>,</span>
<span>                     <span class="st">"MS+MM+SS v. SM+McM"</span> <span class="op">=</span> <span class="va">contrast4</span></span>
<span>                     <span class="op">)</span></span>
<span></span>
<span><span class="va">my_contrasts</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`MM v. McM`
[1]  0 -1  0  0  1

$`MS v. SS`
[1] -1  0  1  0  0

$`MM v. SS`
[1]  0  1 -1  0  0

$`MS+MM+SS v. SM+McM`
[1] -0.3333333 -0.3333333 -0.3333333  0.5000000  0.5000000</code></pre>
</div>
</div>
<p>Now if I run my contrasts it includes my descriptions of what the contrasts are:</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">contrast</span><span class="op">(</span><span class="va">emm_mdl</span>, method <span class="op">=</span> <span class="va">my_contrasts</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE df t.ratio p.value
 MM v. McM              19.0 2.83 35   6.718  &lt;.0001
 MS v. SS                7.0 2.83 35   2.475  0.0183
 MM v. SS               -1.0 2.83 35  -0.354  0.7258
 MS+MM+SS v. SM+McM     18.2 1.83 35   9.950  &lt;.0001</code></pre>
</div>
</div>
<p>Note that this defaults to the <code>holm</code> correction. Can we think of anyway to run a “bonferroni” adjustment to the same comparisons?</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">contrast</span><span class="op">(</span><span class="va">emm_mdl</span>, </span>
<span>         method <span class="op">=</span> <span class="va">my_contrasts</span>,</span>
<span>         adjust <span class="op">=</span> <span class="st">"bonferroni"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE df t.ratio p.value
 MM v. McM              19.0 2.83 35   6.718  &lt;.0001
 MS v. SS                7.0 2.83 35   2.475  0.0733
 MM v. SS               -1.0 2.83 35  -0.354  1.0000
 MS+MM+SS v. SM+McM     18.2 1.83 35   9.950  &lt;.0001

P value adjustment: bonferroni method for 4 tests </code></pre>
</div>
</div>
</section><section id="effect-size-for-planned-contrasts" class="level3" data-number="35.4.2"><h3 data-number="35.4.2" class="anchored" data-anchor-id="effect-size-for-planned-contrasts">
<span class="header-section-number">35.4.2</span> Effect size for planned contrasts</h3>
<p>This is some text that’s recycled from the post-hoc test walkthrough. I’m going to shout again one more time with feeling. Typically when reporting the effect size off the difference between two means we use Cohen’s <span class="math inline">\(d\)</span>. However, calculating Cohen’s $d$ in a planned contrast is slightly more involved than the method used for a regular t-test. This is because with a regular t-test you only have 2 means from 2 samples that you have collected. In the case of Planned Contrasts in ANOVA, while you are only comparing two means, those means are nested within a larger group (e.g., comparing MS and MM, we still need to account for the fact that we also collected samples from SS, SM, and McM) or may be derived from multiple samples (e.g., contrasting the mean of MS + MM against the mean of SS + SM + McM). Simply put, in our calculations we need to account for the influence of all of our collected groups. This is done by placing the contrasted difference in the context of the Root Mean Square Error, or the square root of the Mean Square Error of the residuals in our ANOVA model.</p>
<p>Simply put, in our calculations we need to account for the influence of all of our collected groups. This is done by placing the contrasted difference in the context of the Root Mean Square Error, or the square root of the Mean Square Error of the residuals in our ANOVA model. Recall that typically Cohen’s <span class="math inline">\(d\)</span> is the <strong>difference between the two means</strong> divided by their <strong>pooled standard deviation</strong>. Here, <span class="math inline">\(d\)</span> is the <strong>difference between the two means</strong> divided by <strong><em>sigma, or the estimated standard deviation of the errors of the linear model.</em></strong></p>
<p>To do this we’re going to need two things from the original model. Let’s take a look at the model summary:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">morphine_mdl</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Time ~ Group, data = dataset)

Residuals:
   Min     1Q Median     3Q    Max 
 -9.00  -3.25   0.00   3.00  12.00 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    4.000      2.000   2.000   0.0533 .  
GroupMM        6.000      2.828   2.121   0.0411 *  
GroupSS        7.000      2.828   2.475   0.0183 *  
GroupSM       20.000      2.828   7.071 3.09e-08 ***
GroupMcM      25.000      2.828   8.839 1.93e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.657 on 35 degrees of freedom
Multiple R-squared:  0.7574,    Adjusted R-squared:  0.7297 
F-statistic: 27.32 on 4 and 35 DF,  p-value: 2.443e-10</code></pre>
</div>
</div>
<p>The values line that is important to us is the <code>Residual standard error ___ on __ degrees of freedom</code>—in this case the values <strong>5.657</strong> and <strong>35</strong> respectively.</p>
<p>Assuming you have run your comparisons using <code>emmeans()</code> you can calculate your effect sizes for each comparison using <code><a href="https://rdrr.io/pkg/emmeans/man/eff_size.html">emmeans::eff_size()</a></code>.</p>
<p><code>eff_size()</code> takes three arguments:</p>
<ul>
<li>the emmeans object</li>
<li>the estimated standard deviation of the errors of the linear model, <code>sigma</code>
</li>
<li>the residual degrees of freedom from the model, <code>df.residual</code>
</li>
<li>a vector containing our contrasts— e.g., <code>c(-1/2,-1/2,1/3,1/3,1/3)</code>
</li>
</ul>
<p>The functions <code><a href="https://rdrr.io/r/stats/sigma.html">sigma()</a></code> and <code><a href="https://rdrr.io/r/stats/df.residual.html">df.residual()</a></code> allow us to get the relevant information directly from the model. A typical call would look something like this</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># create and emmeans object specifying your factor</span></span>
<span><span class="va">emm_mdl</span> <span class="op">&lt;-</span> <span class="fu">emmeans</span><span class="op">(</span><span class="va">emm_mdl</span>, specs <span class="op">=</span> <span class="op">~</span><span class="va">Group</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># specify your contrasts, this goes in the method call</span></span>
<span><span class="va">my_contrasts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"MM v. McM"</span> <span class="op">=</span> <span class="va">contrast1</span>,</span>
<span>                     <span class="st">"MS v. SS"</span> <span class="op">=</span> <span class="va">contrast2</span>,</span>
<span>                     <span class="st">"MM v. SS"</span> <span class="op">=</span> <span class="va">contrast3</span>,</span>
<span>                     <span class="st">"MS+MM+SS v. SM+McM"</span> <span class="op">=</span> <span class="va">contrast4</span></span>
<span>                     <span class="op">)</span></span>
<span></span>
<span><span class="co"># run your contrasts</span></span>
<span><span class="va">planned_contrasts</span> <span class="op">&lt;-</span> <span class="fu">contrast</span><span class="op">(</span><span class="va">emm_mdl</span>, <span class="co"># emm_mdl from above</span></span>
<span>                              method <span class="op">=</span> <span class="va">my_contrasts</span>,</span>
<span>                              adjust <span class="op">=</span> <span class="st">"bonferroni"</span></span>
<span>                              <span class="op">)</span></span>
<span></span>
<span><span class="co"># use the saved object in the following function</span></span>
<span><span class="fu">eff_size</span><span class="op">(</span><span class="va">emm_mdl</span>,</span>
<span>         sigma <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sigma.html">sigma</a></span><span class="op">(</span><span class="va">morphine_mdl</span><span class="op">)</span>, </span>
<span>         <span class="fu"><a href="https://rdrr.io/r/stats/df.residual.html">df.residual</a></span><span class="op">(</span><span class="va">morphine_mdl</span><span class="op">)</span>,</span>
<span>         method<span class="op">=</span><span class="va">my_contrasts</span></span>
<span>         <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           effect.size    SE df lower.CL upper.CL
 MM v. McM                3.359 0.641 35    2.057    4.660
 MS v. SS                 1.237 0.521 35    0.179    2.296
 MM v. SS                -0.177 0.500 35   -1.193    0.839
 MS+MM+SS v. SM+McM       3.211 0.501 35    2.193    4.230

sigma used for effect sizes: 5.657 
Confidence level used: 0.95 </code></pre>
</div>
</div>
</section></section><section id="reporting-your-results" class="level2" data-number="35.5"><h2 data-number="35.5" class="anchored" data-anchor-id="reporting-your-results">
<span class="header-section-number">35.5</span> Reporting your results</h2>
<p>When reporting your results, we typically report:</p>
<ul>
<li>the omnibus ANOVA</li>
<li>a statement on what multiple comparisons were run and how corrected</li>
<li>note which comparisons were significant.</li>
</ul>
<p>Since our comparisons, if corrected, rely on adjusted p.values its kosher to simply state that <span class="math inline">\(p&lt;\alpha\)</span>. <em>If you elect to use the actual p values, then you need to note that they are corrected.</em></p>
<p>For planned comparisons, we might say:</p>
<blockquote class="blockquote">
<p>Our prevailing hypothesis predicted that response latency for groups SS, MM, and MS would be significantly less than groups SM and McM. To test this hypothesis we performed a planned contrast (no corrections). Our results revealed statistically significant difference between these groups, <span class="math inline">\(t\)</span>(35) = 9.95, <span class="math inline">\(p\)</span> &lt; .001, <span class="math inline">\(d\)</span> = 3.21, where the response latency in MS, MM, and SS was lower than SM and McM.</p>
</blockquote>
<p>Note that the <span class="math inline">\(df\)</span> in the t-test are the error <span class="math inline">\(df\)</span> from the omnibus model (35).</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../week09/9_1-posthocs.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../week10/10_1-main_effects.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Factorial ANOVA - The omnibus ANOVA and Main effects</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb38" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Multiple comparisons in One-way ANOVA, pt. 2: planned contrasts"</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Tehran Davis"</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "`r Sys.Date()`"</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## TLDR; Steps for running an a-priori contrasts:</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>This walkthrough requires the following to be installed / loaded in <span class="in">`R`</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r message=FALSE, warning=FALSE, include=FALSE}</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="co"># use pacman to check, install, and load necessary packages</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(agricolae,</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>               cowplot, </span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>               tidyverse, </span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>               emmeans,</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>               multcomp,</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>               psych,</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>               sjstats)</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Be sure that the column that contains your IV is indeed being treated as a factor. If it is <span class="in">`levels(IV)`</span> will list your levels, also the column containing the IV will contain <span class="in">`&lt;fct&gt;`</span>. If not <span class="in">`mutate()`</span> as column with your IV as a factor, ex: <span class="in">`newCol = factor(oldCol)`</span></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>check the order of your IV using <span class="in">`levels()`</span>. If you need to reorder, use <span class="in">`fct_relevel()`</span></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>create your contrast matrix according to the levels obtained in Step 1</span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>build an ANOVA model using <span class="in">`lm()`</span>, <span class="in">`aov()`</span>, or <span class="in">`afex()`</span> (output to lm)</span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>run your contrasts using <span class="in">`emmeans()`</span>, inputting</span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>your ANOVA model from Step 3</span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>your contrasts from Step 2</span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>your familywise correction (if any)</span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>Example (run line-by-line):</span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Preliminaries</span></span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a><span class="do">## load in data</span></span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_table2</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span>)</span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a><span class="do">## check data, identify columns</span></span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a>dataset</span>
<span id="cb38-43"><a href="#cb38-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-44"><a href="#cb38-44" aria-hidden="true" tabindex="-1"></a><span class="do">## Group is numerically coded. Fixing this and turning to a factor</span></span>
<span id="cb38-45"><a href="#cb38-45" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Group, <span class="st">"1"</span><span class="ot">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="ot">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="ot">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="ot">=</span><span class="st">"McM"</span>)</span>
<span id="cb38-46"><a href="#cb38-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-47"><a href="#cb38-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Check levels</span></span>
<span id="cb38-48"><a href="#cb38-48" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>Group)</span>
<span id="cb38-49"><a href="#cb38-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-50"><a href="#cb38-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: build contrasts</span></span>
<span id="cb38-51"><a href="#cb38-51" aria-hidden="true" tabindex="-1"></a><span class="do">## MS v. MM</span></span>
<span id="cb38-52"><a href="#cb38-52" aria-hidden="true" tabindex="-1"></a>contrast1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>) </span>
<span id="cb38-53"><a href="#cb38-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-54"><a href="#cb38-54" aria-hidden="true" tabindex="-1"></a><span class="do">## MS + MM v. SS + SM + McM</span></span>
<span id="cb38-55"><a href="#cb38-55" aria-hidden="true" tabindex="-1"></a>contrast2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)</span>
<span id="cb38-56"><a href="#cb38-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-57"><a href="#cb38-57" aria-hidden="true" tabindex="-1"></a>my_contrasts <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"MS v. MM"</span> <span class="ot">=</span> contrast1,</span>
<span id="cb38-58"><a href="#cb38-58" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"MS + MM v. SS + SM + McM"</span> <span class="ot">=</span> contrast2</span>
<span id="cb38-59"><a href="#cb38-59" aria-hidden="true" tabindex="-1"></a>                     )</span>
<span id="cb38-60"><a href="#cb38-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-61"><a href="#cb38-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3</span></span>
<span id="cb38-62"><a href="#cb38-62" aria-hidden="true" tabindex="-1"></a>morphine_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(Time<span class="sc">~</span>Group, <span class="at">data =</span> dataset) </span>
<span id="cb38-63"><a href="#cb38-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-64"><a href="#cb38-64" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4</span></span>
<span id="cb38-65"><a href="#cb38-65" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(<span class="at">object =</span> morphine_mdl,<span class="at">specs =</span> <span class="sc">~</span>Group, <span class="at">adjust=</span><span class="st">"bonf"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb38-66"><a href="#cb38-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">contrast</span>(<span class="at">method =</span> my_contrasts)</span>
<span id="cb38-67"><a href="#cb38-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-68"><a href="#cb38-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-69"><a href="#cb38-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## A few considerations regarding planned contrasts</span></span>
<span id="cb38-70"><a href="#cb38-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-71"><a href="#cb38-71" aria-hidden="true" tabindex="-1"></a>If you have reasons to predict differences between particular sets of group means that are theory-driven, then you may perform *a priori* or planned contrasts. Logically, planned contrasts are similar to post-hoc tests in that we are comparing against two means, but there are some differences that make planned contrasts more powerful.</span>
<span id="cb38-72"><a href="#cb38-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-73"><a href="#cb38-73" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Since your predictions are made prior to collecting data you, technically do not need to get a significant result on the omnibus ANOVA to run your contrasts. However, when doing post-hoc tests, if the omnibus ANOVA fails to reject the null, convention is that you are not permitted to run follow-up post hoc tests.</span>
<span id="cb38-74"><a href="#cb38-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-75"><a href="#cb38-75" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Since you are making predictions prior to seeing the outcome of your observed data, then you are safe to make a limited number of comparisons without the charge of cherry-picking. For example, if you have predicted-ahead that there would be differences between groups "MS" and "McM", or groups "MM" and "MS" then you are free to run those comparisons and those comparisons-only. This is especially useful, since by limiting the number of comparisons you can keep the required corrections relatively minimal. This allows you to effectively reduce the problem of Type I error inflation while limiting the possibility of Type II error. For example, recall that using a Bonferonni correction on this data in the post-hoc case mandates that I use an adjusted $\alpha$ of .005 (.05/10 comparisons), even if I was only really interested in these two comparisons. Here, I am allowed to only perform these two, so my adjusted $p$ is .025.</span>
<span id="cb38-76"><a href="#cb38-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-77"><a href="#cb38-77" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Depending on the number of comparisons, you may be justified in not performing any $p$ correction at all. For example some recommend no need for correction if the number of contrasts is low or when the comparisons are complementary (e.g. orthogonal). See <span class="co">[</span><span class="ot">here</span><span class="co">](http://jrp.icaap.org/index.php/jrp/article/view/514/417)</span>, <span class="co">[</span><span class="ot">here</span><span class="co">](https://www.graphpad.com/support/faqid/1390/)</span>, and <span class="co">[</span><span class="ot">here</span><span class="co">](http://pirun.ku.ac.th/~faasatp/734462/data/06_contrasts2.pdf)</span> for discussion of this issue.</span>
<span id="cb38-78"><a href="#cb38-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-79"><a href="#cb38-79" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>We can easily perform a variety of comparisons using planned contrasts. For example, say we are interested in whether MS is different from the mean of the remaining groups (McM+MM+SM+SS), or that MM+MS is different from McM+SM+SS. We can test this using planned contrasts.</span>
<span id="cb38-80"><a href="#cb38-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-81"><a href="#cb38-81" aria-hidden="true" tabindex="-1"></a><span class="fu">## The logic of planned contrasts</span></span>
<span id="cb38-82"><a href="#cb38-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-83"><a href="#cb38-83" aria-hidden="true" tabindex="-1"></a><span class="fu">## Performing planned contrasts in R</span></span>
<span id="cb38-84"><a href="#cb38-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-85"><a href="#cb38-85" aria-hidden="true" tabindex="-1"></a>As outlined in both Winter and Field, planned contrasts begin by creating contrast weights. The idea with contrast weights is that the groups that are being compared should sum to equal -1 and +1 respectively, resulting in a null test against 0 (i.e. the two weighted means are equal). Any groups that are not being included in the comparison should be assigned weights of 0. You've already seen contrasts before, when looking at the <span class="in">`lm()`</span> ANOVA output. We remarked that this output allows you to make a comparison of each group against the control group.</span>
<span id="cb38-86"><a href="#cb38-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-87"><a href="#cb38-87" aria-hidden="true" tabindex="-1"></a>First let's load in the data and recode the factors:</span>
<span id="cb38-88"><a href="#cb38-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-91"><a href="#cb38-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-92"><a href="#cb38-92" aria-hidden="true" tabindex="-1"></a><span class="do">## load in data</span></span>
<span id="cb38-93"><a href="#cb38-93" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_table2</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab12-1.dat"</span>)</span>
<span id="cb38-94"><a href="#cb38-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-95"><a href="#cb38-95" aria-hidden="true" tabindex="-1"></a><span class="do">## Group is numerically coded. Fixing this and turning to a factor</span></span>
<span id="cb38-96"><a href="#cb38-96" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(dataset<span class="sc">$</span>Group, <span class="st">"1"</span><span class="ot">=</span><span class="st">"MS"</span>,<span class="st">"2"</span><span class="ot">=</span><span class="st">"MM"</span>,<span class="st">"3"</span><span class="ot">=</span><span class="st">"SS"</span>,<span class="st">"4"</span><span class="ot">=</span><span class="st">"SM"</span>,<span class="st">"5"</span><span class="ot">=</span><span class="st">"McM"</span>)</span>
<span id="cb38-97"><a href="#cb38-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-98"><a href="#cb38-98" aria-hidden="true" tabindex="-1"></a>dataset</span>
<span id="cb38-99"><a href="#cb38-99" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-100"><a href="#cb38-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-101"><a href="#cb38-101" aria-hidden="true" tabindex="-1"></a>Looking at Siegel's data we see that MS defaults as the control:</span>
<span id="cb38-102"><a href="#cb38-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-105"><a href="#cb38-105" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-106"><a href="#cb38-106" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Check levels</span></span>
<span id="cb38-107"><a href="#cb38-107" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>Group)</span>
<span id="cb38-108"><a href="#cb38-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-109"><a href="#cb38-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-110"><a href="#cb38-110" aria-hidden="true" tabindex="-1"></a>We can check which contrasts any model we run will default to, by invoking <span class="in">`contrasts()`</span>:</span>
<span id="cb38-111"><a href="#cb38-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-114"><a href="#cb38-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-115"><a href="#cb38-115" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(dataset<span class="sc">$</span>Group)</span>
<span id="cb38-116"><a href="#cb38-116" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-117"><a href="#cb38-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-118"><a href="#cb38-118" aria-hidden="true" tabindex="-1"></a>These sorts of contrasts are known as treatment contrasts... measuring the effect of each treatment against a control. While there are several types of contrasts built into <span class="in">`R`</span> we can create custom contrasts as well.</span>
<span id="cb38-119"><a href="#cb38-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-120"><a href="#cb38-120" aria-hidden="true" tabindex="-1"></a>For example assume we are comparing "MS" to "MM" and were not concerned with the remaining groups. Then our contrast weights would be:</span>
<span id="cb38-121"><a href="#cb38-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-122"><a href="#cb38-122" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>MS = +1</span>
<span id="cb38-123"><a href="#cb38-123" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>MM = -1</span>
<span id="cb38-124"><a href="#cb38-124" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>McM = SM = SS = 0</span>
<span id="cb38-125"><a href="#cb38-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-126"><a href="#cb38-126" aria-hidden="true" tabindex="-1"></a>How about we want to compare McM + MM against the remaining three groups?</span>
<span id="cb38-127"><a href="#cb38-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-128"><a href="#cb38-128" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>MS + MM = 1</span>
<span id="cb38-129"><a href="#cb38-129" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>McM + SM + SS = -1</span>
<span id="cb38-130"><a href="#cb38-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-131"><a href="#cb38-131" aria-hidden="true" tabindex="-1"></a>From there we distribute the weight equally between the number of groups on each side of the contrast, so</span>
<span id="cb38-132"><a href="#cb38-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-133"><a href="#cb38-133" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>MS = +1/2; MM = +1/2</span>
<span id="cb38-134"><a href="#cb38-134" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>McM = -1/3; SM = -1/3; SS = -1/3</span>
<span id="cb38-135"><a href="#cb38-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-136"><a href="#cb38-136" aria-hidden="true" tabindex="-1"></a>in R we can construct each of these contrasts like so:</span>
<span id="cb38-137"><a href="#cb38-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-140"><a href="#cb38-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-141"><a href="#cb38-141" aria-hidden="true" tabindex="-1"></a><span class="co"># checking the order of groups:</span></span>
<span id="cb38-142"><a href="#cb38-142" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>Group)</span>
<span id="cb38-143"><a href="#cb38-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-144"><a href="#cb38-144" aria-hidden="true" tabindex="-1"></a><span class="co"># building contrasts</span></span>
<span id="cb38-145"><a href="#cb38-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-146"><a href="#cb38-146" aria-hidden="true" tabindex="-1"></a><span class="co"># MS v. MM</span></span>
<span id="cb38-147"><a href="#cb38-147" aria-hidden="true" tabindex="-1"></a>contrast1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>) </span>
<span id="cb38-148"><a href="#cb38-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-149"><a href="#cb38-149" aria-hidden="true" tabindex="-1"></a><span class="co"># MS + MM v. SS + SM + McM</span></span>
<span id="cb38-150"><a href="#cb38-150" aria-hidden="true" tabindex="-1"></a>contrast2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)</span>
<span id="cb38-151"><a href="#cb38-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-152"><a href="#cb38-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-153"><a href="#cb38-153" aria-hidden="true" tabindex="-1"></a>When performing planned contrasts in <span class="in">`R`</span> I recommend using the <span class="in">`emmeans`</span> package rather than the <span class="in">`base`</span> package examples in the Field text. For those that are interested as to why, in my experience the <span class="in">`base`</span> method has a hard time dealing with non-orthogonal contrasts.</span>
<span id="cb38-154"><a href="#cb38-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-155"><a href="#cb38-155" aria-hidden="true" tabindex="-1"></a>**To perform the contrast requires 3 steps:**</span>
<span id="cb38-156"><a href="#cb38-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-157"><a href="#cb38-157" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>run your omnibus ANOVA <span class="in">`lm()`</span> model and save it as an object</span>
<span id="cb38-158"><a href="#cb38-158" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>input your <span class="in">`lm()`</span> model into the <span class="in">`emmeans()`</span> function, specifying the name of your IV and save it to an object</span>
<span id="cb38-159"><a href="#cb38-159" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>submit your <span class="in">`emmeans`</span> object to the <span class="in">`contrasts()`</span> function indicating what your contrasts are.</span>
<span id="cb38-160"><a href="#cb38-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-163"><a href="#cb38-163" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-164"><a href="#cb38-164" aria-hidden="true" tabindex="-1"></a>morphine_mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Time<span class="sc">~</span>Group,<span class="at">data =</span> dataset)</span>
<span id="cb38-165"><a href="#cb38-165" aria-hidden="true" tabindex="-1"></a>emm_mdl <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(morphine_mdl,<span class="at">specs =</span> <span class="sc">~</span>Group)</span>
<span id="cb38-166"><a href="#cb38-166" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(emm_mdl, <span class="at">method =</span> <span class="fu">list</span>(contrast1))</span>
<span id="cb38-167"><a href="#cb38-167" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-168"><a href="#cb38-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-169"><a href="#cb38-169" aria-hidden="true" tabindex="-1"></a>The above result tells me:</span>
<span id="cb38-170"><a href="#cb38-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-171"><a href="#cb38-171" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`contrast`</span>: the defined contrast</span>
<span id="cb38-172"><a href="#cb38-172" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`estimate`</span>: the difference in means between my contrasted groups</span>
<span id="cb38-173"><a href="#cb38-173" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`SE`</span>: a measure of variability</span>
<span id="cb38-174"><a href="#cb38-174" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`t.ratio`</span>: obtained from the t-test between groups</span>
<span id="cb38-175"><a href="#cb38-175" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`p.value`</span>: the resulting p-value</span>
<span id="cb38-176"><a href="#cb38-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-177"><a href="#cb38-177" aria-hidden="true" tabindex="-1"></a>Based upon these results I conclude that "MS" and "MM" are significantly different from one another. I make no claims about the other three conditions.</span>
<span id="cb38-178"><a href="#cb38-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-179"><a href="#cb38-179" aria-hidden="true" tabindex="-1"></a>Recall that <span class="in">`contrast2`</span> was testing <span class="sc">\[</span>MS + MM<span class="sc">\]</span> v. <span class="sc">\[</span>SS + SM + McM<span class="sc">\]</span>. If this was my only contrast I could run it independently as above. However, we can also test multiple contrasts simultaneously with a single test. We just add additional contrasts to the list in the method. So, for both <span class="in">`contrast1`</span> and <span class="in">`contrast2`</span>:</span>
<span id="cb38-180"><a href="#cb38-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-183"><a href="#cb38-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-184"><a href="#cb38-184" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(emm_mdl, </span>
<span id="cb38-185"><a href="#cb38-185" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="fu">list</span>(contrast1,contrast2),</span>
<span id="cb38-186"><a href="#cb38-186" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb38-187"><a href="#cb38-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-188"><a href="#cb38-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-189"><a href="#cb38-189" aria-hidden="true" tabindex="-1"></a><span class="fu">### Making the contrasts output easier to read</span></span>
<span id="cb38-190"><a href="#cb38-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-191"><a href="#cb38-191" aria-hidden="true" tabindex="-1"></a>One thing you may have noticed above is that your contrasts aren't labeled very transparently. Looking at the output you would have to remember what was being contrasted in <span class="in">`contrast1`</span> and <span class="in">`contrast2`</span>. You can save yourself a little headache if you label your contrasts while constructing the matrix. Let's say I wanted to run these four contrasts based upon my levels:</span>
<span id="cb38-192"><a href="#cb38-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-195"><a href="#cb38-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-196"><a href="#cb38-196" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>Group)</span>
<span id="cb38-197"><a href="#cb38-197" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-198"><a href="#cb38-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-199"><a href="#cb38-199" aria-hidden="true" tabindex="-1"></a>Now setting up my contrasts to match:</span>
<span id="cb38-200"><a href="#cb38-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-203"><a href="#cb38-203" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-204"><a href="#cb38-204" aria-hidden="true" tabindex="-1"></a>contrast1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb38-205"><a href="#cb38-205" aria-hidden="true" tabindex="-1"></a>contrast2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb38-206"><a href="#cb38-206" aria-hidden="true" tabindex="-1"></a>contrast3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb38-207"><a href="#cb38-207" aria-hidden="true" tabindex="-1"></a>contrast4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb38-208"><a href="#cb38-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-209"><a href="#cb38-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-210"><a href="#cb38-210" aria-hidden="true" tabindex="-1"></a>From here you can modify the previous code to assign names to the rows in your contrast matrix. For the sake of ease, I like to create an object, <span class="in">`my_contrasts`</span> that includes the list of all contrasts. FWIW, on of the annoying things about the <span class="in">`contrast`</span> function is that it requires the <span class="in">`method`</span> argument of contrasts to be in a <span class="in">`list()`</span>, even if its just one contrast.</span>
<span id="cb38-211"><a href="#cb38-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-214"><a href="#cb38-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-215"><a href="#cb38-215" aria-hidden="true" tabindex="-1"></a>my_contrasts <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"MM v. McM"</span> <span class="ot">=</span> contrast1,</span>
<span id="cb38-216"><a href="#cb38-216" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"MS v. SS"</span> <span class="ot">=</span> contrast2,</span>
<span id="cb38-217"><a href="#cb38-217" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"MM v. SS"</span> <span class="ot">=</span> contrast3,</span>
<span id="cb38-218"><a href="#cb38-218" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"MS+MM+SS v. SM+McM"</span> <span class="ot">=</span> contrast4</span>
<span id="cb38-219"><a href="#cb38-219" aria-hidden="true" tabindex="-1"></a>                     )</span>
<span id="cb38-220"><a href="#cb38-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-221"><a href="#cb38-221" aria-hidden="true" tabindex="-1"></a>my_contrasts</span>
<span id="cb38-222"><a href="#cb38-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-223"><a href="#cb38-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-224"><a href="#cb38-224" aria-hidden="true" tabindex="-1"></a>Now if I run my contrasts it includes my descriptions of what the contrasts are:</span>
<span id="cb38-225"><a href="#cb38-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-228"><a href="#cb38-228" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-229"><a href="#cb38-229" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(emm_mdl, <span class="at">method =</span> my_contrasts)</span>
<span id="cb38-230"><a href="#cb38-230" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-231"><a href="#cb38-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-232"><a href="#cb38-232" aria-hidden="true" tabindex="-1"></a>Note that this defaults to the <span class="in">`holm`</span> correction. Can we think of anyway to run a "bonferroni" adjustment to the same comparisons?</span>
<span id="cb38-233"><a href="#cb38-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-236"><a href="#cb38-236" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-237"><a href="#cb38-237" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(emm_mdl, </span>
<span id="cb38-238"><a href="#cb38-238" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> my_contrasts,</span>
<span id="cb38-239"><a href="#cb38-239" aria-hidden="true" tabindex="-1"></a>         <span class="at">adjust =</span> <span class="st">"bonferroni"</span></span>
<span id="cb38-240"><a href="#cb38-240" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-241"><a href="#cb38-241" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-242"><a href="#cb38-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-243"><a href="#cb38-243" aria-hidden="true" tabindex="-1"></a><span class="fu">### Effect size for planned contrasts</span></span>
<span id="cb38-244"><a href="#cb38-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-245"><a href="#cb38-245" aria-hidden="true" tabindex="-1"></a>This is some text that's recycled from the post-hoc test walkthrough. I'm going to shout again one more time with feeling. Typically when reporting the effect size off the difference between two means we use Cohen's $d$. However, calculating Cohen's \$d\$ in a planned contrast is slightly more involved than the method used for a regular t-test. This is because with a regular t-test you only have 2 means from 2 samples that you have collected. In the case of Planned Contrasts in ANOVA, while you are only comparing two means, those means are nested within a larger group (e.g., comparing MS and MM, we still need to account for the fact that we also collected samples from SS, SM, and McM) or may be derived from multiple samples (e.g., contrasting the mean of MS + MM against the mean of SS + SM + McM). Simply put, in our calculations we need to account for the influence of all of our collected groups. This is done by placing the contrasted difference in the context of the Root Mean Square Error, or the square root of the Mean Square Error of the residuals in our ANOVA model.</span>
<span id="cb38-246"><a href="#cb38-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-247"><a href="#cb38-247" aria-hidden="true" tabindex="-1"></a>Simply put, in our calculations we need to account for the influence of all of our collected groups. This is done by placing the contrasted difference in the context of the Root Mean Square Error, or the square root of the Mean Square Error of the residuals in our ANOVA model. Recall that typically Cohen's $d$ is the **difference between the two means** divided by their **pooled standard deviation**. Here, $d$ is the **difference between the two means** divided by ***sigma, or the estimated standard deviation of the errors of the linear model.***</span>
<span id="cb38-248"><a href="#cb38-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-249"><a href="#cb38-249" aria-hidden="true" tabindex="-1"></a>To do this we're going to need two things from the original model. Let's take a look at the model summary:</span>
<span id="cb38-250"><a href="#cb38-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-253"><a href="#cb38-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-254"><a href="#cb38-254" aria-hidden="true" tabindex="-1"></a>morphine_mdl <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb38-255"><a href="#cb38-255" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-256"><a href="#cb38-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-257"><a href="#cb38-257" aria-hidden="true" tabindex="-1"></a>The values line that is important to us is the <span class="in">`Residual standard error ___ on __ degrees of freedom`</span>---in this case the values **5.657** and **35** respectively.</span>
<span id="cb38-258"><a href="#cb38-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-259"><a href="#cb38-259" aria-hidden="true" tabindex="-1"></a>Assuming you have run your comparisons using <span class="in">`emmeans()`</span> you can calculate your effect sizes for each comparison using <span class="in">`emmeans::eff_size()`</span>.</span>
<span id="cb38-260"><a href="#cb38-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-261"><a href="#cb38-261" aria-hidden="true" tabindex="-1"></a><span class="in">`eff_size()`</span> takes three arguments:</span>
<span id="cb38-262"><a href="#cb38-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-263"><a href="#cb38-263" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the emmeans object</span>
<span id="cb38-264"><a href="#cb38-264" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the estimated standard deviation of the errors of the linear model, <span class="in">`sigma`</span></span>
<span id="cb38-265"><a href="#cb38-265" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the residual degrees of freedom from the model, <span class="in">`df.residual`</span></span>
<span id="cb38-266"><a href="#cb38-266" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>a vector containing our contrasts--- e.g., <span class="in">`c(-1/2,-1/2,1/3,1/3,1/3)`</span></span>
<span id="cb38-267"><a href="#cb38-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-268"><a href="#cb38-268" aria-hidden="true" tabindex="-1"></a>The functions <span class="in">`sigma()`</span> and <span class="in">`df.residual()`</span> allow us to get the relevant information directly from the model. A typical call would look something like this</span>
<span id="cb38-269"><a href="#cb38-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-272"><a href="#cb38-272" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-273"><a href="#cb38-273" aria-hidden="true" tabindex="-1"></a><span class="co"># create and emmeans object specifying your factor</span></span>
<span id="cb38-274"><a href="#cb38-274" aria-hidden="true" tabindex="-1"></a>emm_mdl <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(emm_mdl, <span class="at">specs =</span> <span class="sc">~</span>Group)</span>
<span id="cb38-275"><a href="#cb38-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-276"><a href="#cb38-276" aria-hidden="true" tabindex="-1"></a><span class="co"># specify your contrasts, this goes in the method call</span></span>
<span id="cb38-277"><a href="#cb38-277" aria-hidden="true" tabindex="-1"></a>my_contrasts <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"MM v. McM"</span> <span class="ot">=</span> contrast1,</span>
<span id="cb38-278"><a href="#cb38-278" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"MS v. SS"</span> <span class="ot">=</span> contrast2,</span>
<span id="cb38-279"><a href="#cb38-279" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"MM v. SS"</span> <span class="ot">=</span> contrast3,</span>
<span id="cb38-280"><a href="#cb38-280" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"MS+MM+SS v. SM+McM"</span> <span class="ot">=</span> contrast4</span>
<span id="cb38-281"><a href="#cb38-281" aria-hidden="true" tabindex="-1"></a>                     )</span>
<span id="cb38-282"><a href="#cb38-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-283"><a href="#cb38-283" aria-hidden="true" tabindex="-1"></a><span class="co"># run your contrasts</span></span>
<span id="cb38-284"><a href="#cb38-284" aria-hidden="true" tabindex="-1"></a>planned_contrasts <span class="ot">&lt;-</span> <span class="fu">contrast</span>(emm_mdl, <span class="co"># emm_mdl from above</span></span>
<span id="cb38-285"><a href="#cb38-285" aria-hidden="true" tabindex="-1"></a>                              <span class="at">method =</span> my_contrasts,</span>
<span id="cb38-286"><a href="#cb38-286" aria-hidden="true" tabindex="-1"></a>                              <span class="at">adjust =</span> <span class="st">"bonferroni"</span></span>
<span id="cb38-287"><a href="#cb38-287" aria-hidden="true" tabindex="-1"></a>                              )</span>
<span id="cb38-288"><a href="#cb38-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-289"><a href="#cb38-289" aria-hidden="true" tabindex="-1"></a><span class="co"># use the saved object in the following function</span></span>
<span id="cb38-290"><a href="#cb38-290" aria-hidden="true" tabindex="-1"></a><span class="fu">eff_size</span>(emm_mdl,</span>
<span id="cb38-291"><a href="#cb38-291" aria-hidden="true" tabindex="-1"></a>         <span class="at">sigma =</span> <span class="fu">sigma</span>(morphine_mdl), </span>
<span id="cb38-292"><a href="#cb38-292" aria-hidden="true" tabindex="-1"></a>         <span class="fu">df.residual</span>(morphine_mdl),</span>
<span id="cb38-293"><a href="#cb38-293" aria-hidden="true" tabindex="-1"></a>         <span class="at">method=</span>my_contrasts</span>
<span id="cb38-294"><a href="#cb38-294" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb38-295"><a href="#cb38-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb38-296"><a href="#cb38-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-297"><a href="#cb38-297" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reporting your results</span></span>
<span id="cb38-298"><a href="#cb38-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-299"><a href="#cb38-299" aria-hidden="true" tabindex="-1"></a>When reporting your results, we typically report:</span>
<span id="cb38-300"><a href="#cb38-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-301"><a href="#cb38-301" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the omnibus ANOVA</span>
<span id="cb38-302"><a href="#cb38-302" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>a statement on what multiple comparisons were run and how corrected</span>
<span id="cb38-303"><a href="#cb38-303" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>note which comparisons were significant.</span>
<span id="cb38-304"><a href="#cb38-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-305"><a href="#cb38-305" aria-hidden="true" tabindex="-1"></a>Since our comparisons, if corrected, rely on adjusted p.values its kosher to simply state that $p&lt;\alpha$. *If you elect to use the actual p values, then you need to note that they are corrected.*</span>
<span id="cb38-306"><a href="#cb38-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-307"><a href="#cb38-307" aria-hidden="true" tabindex="-1"></a>For planned comparisons, we might say:</span>
<span id="cb38-308"><a href="#cb38-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-309"><a href="#cb38-309" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Our prevailing hypothesis predicted that response latency for groups SS, MM, and MS would be significantly less than groups SM and McM. To test this hypothesis we performed a planned contrast (no corrections). Our results revealed statistically significant difference between these groups, $t$(35) = 9.95, $p$ </span><span class="sc">\&lt;</span><span class="at"> .001, $d$ = 3.21, where the response latency in MS, MM, and SS was lower than SM and McM.</span></span>
<span id="cb38-310"><a href="#cb38-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-311"><a href="#cb38-311" aria-hidden="true" tabindex="-1"></a>Note that the $df$ in the t-test are the error $df$ from the omnibus model (35).</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Written by <a href="https://tehrandav.is">Tehran Davis</a> of PSYC 7014.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>