<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Tehran Davis">
<title>PSYC 7014: Graduate Statistics 1 - 25&nbsp; Testing differences in means / t-test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../week06/6_2_t-test-null-model.html" rel="next">
<link href="../week05/5_6_example_report.html" rel="prev">
<link href="../images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing differences in means / t-test</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">PSYC 7014: Graduate Statistics 1</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Graduate Statistics Walkthroughs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part 1: INTRO to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_1-getting_started.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting started</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week00/0_2-resources.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Links to resources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_1-Rmarkdown_basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Rmarkdown Basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_2-objects_assignment_functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Objects, assignment, and functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_3-install_packages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Installing and loading an <code>R</code> package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_4-loading_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Loading in Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_5-leveling-up.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Leveling-up</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part 2: DESCRIBING &amp; VISUALIZING DATA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_1-structure_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The structure of your data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_2-central_tendency.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Measures of central tendency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_3-summary_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Creating summary tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_1-basic_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Basic ggplotting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_2-more_adv_ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">More advanced ggPlots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_4-means_other_models.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Means and other models</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part 3: DISTRIBUTIONS and NHST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The normal distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_2-building_intuitions_about_probability_and_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Building intuitions about probability and NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Sampling distributions and seeing the logic of NHST</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_4-more_examples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">More examples of distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_5-bias_variance.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Bias in sample variance estimates</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Part 4: MODELING w/ CONTINUOUS PREDICTORS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_2_correlations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_3_regressions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regression, pt.&nbsp;1: Running the model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_4_plotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Plotting regression data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_5_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Regression model diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_6_example_report.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Example Report</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Part 5: T-TESTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_1_t-test.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing differences in means / t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_2_t-test-null-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Thinking about nothing (aka the null)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_3_t-test-lm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">t-test? It’s just a linear model</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Part 6: Power &amp; Effect Size</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_1-effect_size.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Effect Size</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_2-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_3-power_es_sig_tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Power, Effect sizes, and Significance testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_4-simulating_power.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Simulating Power!!!</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Part 7: One-way ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_1-one-way-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">The One-way ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_2-anova-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">ANOVA and Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_1-posthocs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_2-planned_contrasts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">Part 8: Factorial ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_1-main_effects.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Factorial ANOVA - The omnibus ANOVA and Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_2-factorial_w_post_hocs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Factorial ANOVA - Post hoc analysis of Main effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_3-advanced_example_and_apa.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Template for Analysis &amp; APA Style</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">Part 9: Repeated Measures ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_1-afex_ANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">afex is for ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_2-repeated_measures_anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Within Subjects / Repeated Measures ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_3-factorial_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Factorial RM-ANOVA and simple effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_4-sphericity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Sphericity: Variances and Co-Variances</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_5-spss_rma.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Running a RM-ANOVA in SPSS</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#things-to-consider-before-running-the-t-test" id="toc-things-to-consider-before-running-the-t-test" class="nav-link active" data-scroll-target="#things-to-consider-before-running-the-t-test"><span class="toc-section-number">25.1</span>  Things to consider before running the t-test</a>
  <ul class="collapse">
<li><a href="#what-is-the-nature-of-your-sample-data" id="toc-what-is-the-nature-of-your-sample-data" class="nav-link" data-scroll-target="#what-is-the-nature-of-your-sample-data"><span class="toc-section-number">25.1.1</span>  What is the nature of your sample data?</a></li>
  <li><a href="#what-is-the-structure-of-your-data-file" id="toc-what-is-the-structure-of-your-data-file" class="nav-link" data-scroll-target="#what-is-the-structure-of-your-data-file"><span class="toc-section-number">25.1.2</span>  What is the structure of your data file?</a></li>
  <li><a href="#testing-assumptions" id="toc-testing-assumptions" class="nav-link" data-scroll-target="#testing-assumptions"><span class="toc-section-number">25.1.3</span>  Testing assumptions</a></li>
  <li><a href="#getting-the-descriptive-stats-and-plotting-the-means." id="toc-getting-the-descriptive-stats-and-plotting-the-means." class="nav-link" data-scroll-target="#getting-the-descriptive-stats-and-plotting-the-means."><span class="toc-section-number">25.1.4</span>  Getting the descriptive stats and plotting the means.</a></li>
  </ul>
</li>
  <li><a href="#performing-the-t-test-paired-sample-t-test" id="toc-performing-the-t-test-paired-sample-t-test" class="nav-link" data-scroll-target="#performing-the-t-test-paired-sample-t-test"><span class="toc-section-number">25.2</span>  Performing the t-test (Paired sample t-test)</a></li>
  <li>
<a href="#other-t-tests" id="toc-other-t-tests" class="nav-link" data-scroll-target="#other-t-tests"><span class="toc-section-number">25.3</span>  Other <span class="math inline">\(t\)</span> tests:</a>
  <ul class="collapse">
<li><a href="#one-sample" id="toc-one-sample" class="nav-link" data-scroll-target="#one-sample"><span class="toc-section-number">25.3.1</span>  One sample:</a></li>
  <li><a href="#independent-samples-example" id="toc-independent-samples-example" class="nav-link" data-scroll-target="#independent-samples-example"><span class="toc-section-number">25.3.2</span>  Independent samples example</a></li>
  </ul>
</li>
  <li><a href="#independent-or-paired-sample" id="toc-independent-or-paired-sample" class="nav-link" data-scroll-target="#independent-or-paired-sample"><span class="toc-section-number">25.4</span>  Independent or Paired Sample?</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">
<span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing differences in means / t-test</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>This week we cover when and how to conduct a <span class="math inline">\(t-test\)</span>. We use a t-test to assess whether the observed difference between sample means is greater than would be predicted be chance. Both the Navarro text and Poldrack text do a wonderful job of explaining t-tests conceptually so I will defer to those experts on matters of the underlying their statistical basis. Instead my goal this week is to walk through some examples on performing, interpreting, and reporting t-tests using <code>R</code>.</p>
<p>This walkthough assumes that the following packages are installed and loaded on your computer:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>, <span class="va">car</span>, <span class="va">cowplot</span>, <span class="va">lsr</span>, <span class="va">DescTools</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="things-to-consider-before-running-the-t-test" class="level2" data-number="25.1"><h2 data-number="25.1" class="anchored" data-anchor-id="things-to-consider-before-running-the-t-test">
<span class="header-section-number">25.1</span> Things to consider before running the t-test</h2>
<p>Before running a <code>t.test</code> there are a few practical and statistical considerations that must be taken. In fact, these considerations extend to every type of analysis that we will encounter for the remainder of the semester (and indeed the rest of your career) so it would be good to get in the habit of running through your checks. In what proceeds here I will walk step by step with how I condunct a <code>t.test</code> (while also highlighting certain decision points as they come up).</p>
<section id="what-is-the-nature-of-your-sample-data" class="level3" data-number="25.1.1"><h3 data-number="25.1.1" class="anchored" data-anchor-id="what-is-the-nature-of-your-sample-data">
<span class="header-section-number">25.1.1</span> What is the nature of your sample data?</h3>
<p>In other words where is the data coming from? Is it coming from a single sample of participants? Is it coming from multiple samples of the SAME participants? Is it coming from multiple groups of participants. This will not only determine what analysis you choose to run, but in also how you go about the business of preparing to run this analysis. Of course, truth be told this information should already be known before you even start collecting your data, which reinforces an important point, your central analyses should already be selected BEFORE you start collecting data! As you design your experiments you should do so in a way in which the statistics that you run are built into the design, not settled upon afterwards. This enables you to give the tests you perform the most power, as you are making predictions about the outcomes of your test <em>a priori</em>. This will become a major theme on the back half of the class, but best to introduce it now.</p>
<p>For this week, it will determine what test we will elect to perform. Let’s grab some sample data from an experiment by Hand, et al.&nbsp;(1994)</p>
<blockquote class="blockquote">
<p>Hand, et al., 1994, reported on family therapy as a treatment for anorexia. There were 17 girls in this experiment, and they were weighed before and after treatment. The weights of the girls, in pounds, is provided in the data below:</p>
</blockquote>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">anorexia_data</span> <span class="op">&lt;-</span> <span class="fu">read_delim</span><span class="op">(</span><span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab7-3.dat"</span>, </span>
<span>                     <span class="st">"\t"</span>, escape_double <span class="op">=</span> <span class="cn">FALSE</span>, trim_ws <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 17 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): ID
dbl (2): Before, After

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>So what is known: we have 17 total participants from (hypothetically) the same population that are measured twice (once <code>Before</code> treatment, and once <code>After</code> treatment). Based upon the experimental question we need to run a paired-sample (matched-sample) test. (Although I’ll use this data to provide an example of a one-sample test later on).</p>
</section><section id="what-is-the-structure-of-your-data-file" class="level3" data-number="25.1.2"><h3 data-number="25.1.2" class="anchored" data-anchor-id="what-is-the-structure-of-your-data-file">
<span class="header-section-number">25.1.2</span> What is the structure of your data file?</h3>
<p>Before doing anything you should always take a look at your data:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">show</span><span class="op">(</span><span class="va">anorexia_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 3
   ID    Before After
   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 01      83.8  95.2
 2 02      83.3  94.3
 3 03      86    91.5
 4 04      82.5  91.9
 5 05      86.7 100. 
 6 06      79.6  76.7
 7 07      76.9  76.7
 8 08      94.2 102. 
 9 09      73.4  94.9
10 10      80.5  75.2
11 11      81.6  77.8
12 12      82.1  95.5
13 13      77.6  90.7
14 14      83.5  92.6
15 15      89.9  93.8
16 16      86    91.7
17 17      87.3  98  </code></pre>
</div>
</div>
<p>So what do we have here, three columns:</p>
<ul>
<li>
<code>ID</code>: the participant number</li>
<li>
<code>Before</code>: participants’ weights before treatment</li>
<li>
<code>After</code>: participants’ weights after treatment</li>
</ul>
<p>Most important for present purposes this data is in <code>WIDE</code> format—each line represents a participant. While this might be intuitive for tabluar visualization, many statistical softwares prefer when <code>LONG</code> format, where each line represents a single <em>observation</em> (or some mixed of WIDE and LONG like SPSS).</p>
<p>I spoke a little bit about this issue in Week 2, Walkthrough 0.</p>
<section id="getting-data-from-wide-to-long" class="level4" data-number="25.1.2.1"><h4 data-number="25.1.2.1" class="anchored" data-anchor-id="getting-data-from-wide-to-long">
<span class="header-section-number">25.1.2.1</span> Getting data from WIDE to LONG</h4>
<p>So the data are in WIDE format, each line has multiple observations of data that are being compared. Here both <code>Before</code> scores and <code>After</code> scores are on the same line. In order to make life easier for analysis and plotting in <code>ggplot</code>, we need to get the data into LONG format (<code>Before</code> scores and <code>After</code> scores are on different lines). This can be done using the <code>pivot_longer()</code> function from the <code>tidyr</code> package.</p>
<p>Before gathering, one thing to consider is whether or not you have a column that defines each subject. In this case we have <code>ID</code>. This tells <code>R</code> that these data are coming from the same subject and will allow <code>R</code> to connect these data when performing analysis. That said, for <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> this is not crucially important—<code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> assumes that the order of lines represents the order of subjects, e.g., the first <code>Before</code> line is matched to the first <code>After</code> line. Later on when we are doing ANOVA, however, this participant column will be important an we will need to add if it is missing.</p>
<p><strong>Using <code>pivot_longer()</code>:</strong> This function takes a number of arguments, but for us right now, the most important are <code>data</code>: your dataframe; <code>cols</code>: which columns to gather; <code>names_to</code>: what do you want the header of the collaped nonminal variables to be? Here, we might ask what title would encapsulate both <code>Before</code> and <code>After</code>. I’ll choose <code>treatment</code> ; <code>values_to</code>: what do the values represent, here I choose <code>weight</code>. I’m just going to overwrite the original data frame:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">anorexia_data</span> <span class="op">&lt;-</span> <span class="fu">pivot_longer</span><span class="op">(</span><span class="va">anorexia_data</span>,cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Before"</span>,<span class="st">"After"</span><span class="op">)</span>,names_to <span class="op">=</span> <span class="st">"treatment"</span>, values_to <span class="op">=</span> <span class="st">"weight"</span><span class="op">)</span></span>
<span><span class="va">anorexia_data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 34 × 3
   ID    treatment weight
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
 1 01    Before      83.8
 2 01    After       95.2
 3 02    Before      83.3
 4 02    After       94.3
 5 03    Before      86  
 6 03    After       91.5
 7 04    Before      82.5
 8 04    After       91.9
 9 05    Before      86.7
10 05    After      100. 
# ℹ 24 more rows</code></pre>
</div>
</div>
<p>Ok data is structured correctly, on to the next step.</p>
</section></section><section id="testing-assumptions" class="level3" data-number="25.1.3"><h3 data-number="25.1.3" class="anchored" data-anchor-id="testing-assumptions">
<span class="header-section-number">25.1.3</span> Testing assumptions</h3>
<p>Remember that you should always test to see if the data fit the assumptions of the test you intend to perform. In this case, we need to assess two things:</p>
<section id="is-the-data-normally-distributed" class="level4" data-number="25.1.3.1"><h4 data-number="25.1.3.1" class="anchored" data-anchor-id="is-the-data-normally-distributed">
<span class="header-section-number">25.1.3.1</span> Is the data normally distributed?</h4>
<p>Knowing the design of your experiment also has implications for testing your assumptions. For example, whether you have a paired (matched) sample design (e.g., two samples from the same participants) or an independent sample design (e.g., two groups) determines how you go about the business of testing the normality assumption. If you have an independent samples test, you test each sample separately, noting measures of skew, kurtosis, inspecting the qqPlot, and Shapiro-Wilkes test (though acknowledging that SW is very sensitive). However, if you are running a paired (matched) samples test, you need to be concerned with the distribution of the difference scores. In the present example we are comparing participants’ weights <code>Before</code> treatment to their weight <code>After</code>. This is a paired design, so I need to test the differences between each participant’s <code>Before</code> and <code>After</code> for normality.</p>
<p>First, let me <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> my data accordingly for <code>Before</code> and <code>After</code> (essentially creating separate vectors for each condition):</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">beforeTreatment</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">anorexia_data</span>, <span class="va">treatment</span><span class="op">==</span><span class="st">"Before"</span><span class="op">)</span> </span>
<span><span class="va">afterTreatment</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">anorexia_data</span>, <span class="va">treatment</span><span class="op">==</span><span class="st">"After"</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now compute the difference scores, and run my assumption tests:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">diffWeights</span> <span class="op">&lt;-</span> <span class="va">beforeTreatment</span><span class="op">$</span><span class="va">weight</span> <span class="op">-</span> <span class="va">afterTreatment</span><span class="op">$</span><span class="va">weight</span></span>
<span></span>
<span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">diffWeights</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars  n  mean   sd median trimmed  mad   min max range skew kurtosis   se
X1    1 17 -7.26 7.17   -9.1   -7.15 5.93 -21.5 5.3  26.8 0.18    -0.77 1.74</code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/qqPlot.html">qqPlot</a></span><span class="op">(</span><span class="va">diffWeights</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  9 10</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">diffWeights</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  diffWeights
W = 0.9528, p-value = 0.5023</code></pre>
</div>
</div>
<p>What conclusions might we draw about normality?</p>
</section></section><section id="getting-the-descriptive-stats-and-plotting-the-means." class="level3" data-number="25.1.4"><h3 data-number="25.1.4" class="anchored" data-anchor-id="getting-the-descriptive-stats-and-plotting-the-means.">
<span class="header-section-number">25.1.4</span> Getting the descriptive stats and plotting the means.</h3>
<p>Finally, as we will be performing a test of difference in means, it would be a good idea to get descriptive measures of means and variability for each group. Indeed, these data were already obatined when we used <code><a href="https://rdrr.io/pkg/psych/man/describe.html">psych::describe()</a></code> to assess the normality of each sample. Here I’ll just do it again to get these values:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.by.html">describeBy</a></span><span class="op">(</span><span class="va">anorexia_data</span><span class="op">$</span><span class="va">weight</span>,group <span class="op">=</span> <span class="va">anorexia_data</span><span class="op">$</span><span class="va">treatment</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Descriptive statistics by group 
group: After
   vars  n  mean   sd median trimmed  mad  min   max range  skew kurtosis   se
X1    1 17 90.49 8.49   92.6   90.77 3.85 75.2 101.6  26.4 -0.74    -0.93 2.06
------------------------------------------------------------ 
group: Before
   vars  n  mean   sd median trimmed  mad  min  max range skew kurtosis   se
X1    1 17 83.23 5.02   83.3   83.15 4.15 73.4 94.2  20.8 0.15    -0.29 1.22</code></pre>
</div>
</div>
<p>Typically along with the mean, you need to report a measure of variability of your sample. This can be either the SD, SEM, or if you choose the 95% CI, although this is more rare in the actual report. See the supplied HW example and APA examples for conventions on how to report these in your results section.</p>
<section id="plotting-in-ggplot" class="level4" data-number="25.1.4.1"><h4 data-number="25.1.4.1" class="anchored" data-anchor-id="plotting-in-ggplot">
<span class="header-section-number">25.1.4.1</span> Plotting in ggplot</h4>
<p>I’ve mentioned the limits and issues with plotting bar plots, but they remain a standard, so we will simply proceed using these plots. But I’ll note that boxplots, violin plots, bean plots, and pirate plots are all modern alternatives to bar plots and are easy to execute in <code>ggplot()</code>. Try a Google search.</p>
<p>In the meantime, to produce a bar plot in <code>R</code> we simply modify a few of the arguments that we are familiar width.</p>
<p>Here is the code for plotting these two groups:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">anorexia_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">treatment</span>, y<span class="op">=</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"col"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Breaking this down line-by-line:</p>
<ul>
<li><p><code>ggplot(data = anorexia_data, aes(x=treatment, y=weight))</code>: standard fare for starting a <code>ggplot</code>.</p></li>
<li><p><code>stat_summary(fun = "mean", geom = "col")</code>: <code>stat_summary()</code> gets summary statistics and projects them onto the geom of your choice. In this case we are getting the mean values, <code>fun = "mean"</code> and using them to create a column plot <code>geom = "col"</code> .</p></li>
<li><p><code>stat_summary(fun.data = "mean_se", geom = "errorbar", width = .1)</code> : here we are creating error bars, <code>geom = "errorbar"</code>. Important to note here is that error bars require knowing three values: mean, upper limit, and lower limit. Whenever you are asking for a single value, like a mean, you use <code>fun</code>. When multiple values are needed you use <code>fun.data</code>. Here <code>fun.data = "mean_se"</code> requests Standard error bars. Other alternatives include 95% CI <code>"mean_cl_normal"</code> and Standard deviation <code>"mean_sdl"</code>. The <code>width</code> argument adjusts the width of the error bars.</p></li>
<li><p><code>scale_y_continuous(expand = c(0,0))</code>: Typically <code>R</code> will do this strange thing where it places a gap bewteen the data and the <code>x-axis</code>. This line is a hack to remove this default. It says along the y-axis add <code>0</code> expansion (or gap).</p></li>
<li><p><code>theme_cowplot()</code>: quick APA aesthetics.</p></li>
</ul>
<p>You may also feel that the zooming factor is off. This may especially be true in cases where there is little visual discrepency between the bars. To “zoom in” on the data you can use <code>coord_cartesian()</code>. For example, you might want to only show the range between 70 lbs and 100 lbs. When doing this, be careful not to truncate the upper limits of your bars and importantly your error bars.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">anorexia_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">treatment</span>, y<span class="op">=</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"col"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_cartesian</span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">70</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Additionally, to get this into true APA format I would need to adjust my axis labels. Here capitalization is needed. Also, because the weight has a unit measure, I need to be specific about that:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">anorexia_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">treatment</span>, y<span class="op">=</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"col"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_cartesian</span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">70</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Treatment"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Weight (lbs)"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Finally, you may have notice that the order of Treatment on the plot is opposite of what we might like to logically present. In this case the “After” data comes prior to the “Before” data on the x-axis. This is because <code>R</code> defaults to alphabetical order when loading in data. To correct this I can use <code>scale_x_discrete()</code> and specify the order that I want in <code>limits</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">anorexia_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">treatment</span>, y<span class="op">=</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"col"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_cartesian</span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">70</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Treatment"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Weight (lbs)"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">scale_x_discrete</span><span class="op">(</span>limits<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Before"</span>,<span class="st">"After"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Alternatively I can correct the order of the levels of a factor within the dataframe itself using <code>fct_relevel()</code> (this gets loaded with <code>tidyverse</code>). Note that here I am overwriting the original <code>treatment</code> column. If you do this proceed at your own risk! You could also just <code>mutate</code> a new column if you would rather not overwrite.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">anorexia_data</span><span class="op">$</span><span class="va">treatment</span> <span class="op">&lt;-</span> <span class="fu">fct_relevel</span><span class="op">(</span><span class="va">anorexia_data</span><span class="op">$</span><span class="va">treatment</span>, <span class="st">"Before"</span>, <span class="st">"After"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">anorexia_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">treatment</span>, y<span class="op">=</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"col"</span>, </span>
<span>               fill <span class="op">=</span> <span class="st">"lightgray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># adding some color mods here.</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_cartesian</span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">70</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Treatment"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Weight (lbs)"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># note that I don't have to do the `scale_x_discrete(limits=c("Before","After"))` correction</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>All good (well maybe check with Sierra first)! One other thing to consider (although please do not worry about it here) is the recent argument that when dealing with repeated measures data you need to adjust you error bars. See <a href="http://www.tqmp.org/Content/vol04-2/p061/p061.pdf">this pdf</a> by Richard Morey (2005) for more information on this issue. We’ll revisit this issue when running Repeated Measures ANOVA.</p>
</section><section id="an-aside-other-types-of-plots" class="level4" data-number="25.1.4.2"><h4 data-number="25.1.4.2" class="anchored" data-anchor-id="an-aside-other-types-of-plots">
<span class="header-section-number">25.1.4.2</span> An aside… other types of plots</h4>
<p>As I mentioned barplots (especially those that use standard error bars) have more recently come under criticism for “hiding” the true name of the data. There is currently a movement to make data more transparent using other kinds of plots that convey more information about your sample. For example let’s contrast out barplot from above with a combination “pointrange” and violin plot. The <code>pointrange</code> simply provides the mean as a point with error bars extending as specified (here I choose standard error). The violin plot is essentially a histogram of the data turned on its side, centered on the mean, and then mirrored… it gives us info about the TRUE distribution of scores.</p>
<p>Let’s take a look side by side</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">barplot</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">anorexia_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">treatment</span>, y<span class="op">=</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"col"</span>, </span>
<span>               fill <span class="op">=</span> <span class="st">"lightgray"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># adding some color mods here.</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_cartesian</span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">70</span>,<span class="fl">110</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Treatment"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Weight (lbs)"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># note that order matters. I need to do the violin before the pointrange or else the violin will "paint over" the pointrange.</span></span>
<span></span>
<span><span class="va">point_violin_plot</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">anorexia_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">treatment</span>, y<span class="op">=</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_violin</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"pointrange"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># adding some color mods here.</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_cowplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_cartesian</span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">70</span>,<span class="fl">110</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Treatment"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Weight (lbs)"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">cowplot</span><span class="fu">::</span><span class="fu"><a href="https://wilkelab.org/cowplot/reference/plot_grid.html">plot_grid</a></span><span class="op">(</span><span class="va">barplot</span>, <span class="va">point_violin_plot</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As you can see the second plot gives me more information about what’s truly going on with my data.</p>
</section></section></section><section id="performing-the-t-test-paired-sample-t-test" class="level2" data-number="25.2"><h2 data-number="25.2" class="anchored" data-anchor-id="performing-the-t-test-paired-sample-t-test">
<span class="header-section-number">25.2</span> Performing the t-test (Paired sample t-test)</h2>
<p>Okay, now that we’ve done all of our preparation, we’re now ready to perform the test. We can do so using the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function. In this case, the experimental question warrants a <code>paired</code> samples t-test. Given that our Levene’s test failed to reject the null, we will assume that our variances are equal.</p>
<p>Since we’ve got long-format data we will use the formula syntax. This reads “predicting changes in <code>weight</code> as a function of <code>treatment</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">weight</span><span class="op">~</span><span class="va">treatment</span>,data<span class="op">=</span><span class="va">anorexia_data</span>,paired<span class="op">=</span><span class="cn">T</span>, var.equal<span class="op">=</span><span class="cn">T</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  weight by treatment
t = -4.1802, df = 16, p-value = 0.0007072
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -10.948840  -3.580571
sample estimates:
mean difference 
      -7.264706 </code></pre>
</div>
</div>
<p>The output provides us with our <span class="math inline">\(t\)</span> value, the <span class="math inline">\(df\)</span> and the <span class="math inline">\(p\)</span> value. It also includes a measure of the 95% CI, and the mean difference. Remember that the null hypothesis is that there is no difference between our two samples. In the case of repeated measures especially, it makes sense to think of this in terms of a difference score of change, where the null is 0. The resulting interpretation is that on average participants’ weight increased 7.26 pounds due to the treatment, with a 95% likelihood that the true mean change is between 3.58 lbs and 10.95 lbs. Important for us is that 0 is not in the 95% CI, reinforcing that there was indeed a non-zero change (rejecting the null).</p>
</section><section id="other-t-tests" class="level2" data-number="25.3"><h2 data-number="25.3" class="anchored" data-anchor-id="other-t-tests">
<span class="header-section-number">25.3</span> Other <span class="math inline">\(t\)</span> tests:</h2>
<section id="one-sample" class="level3" data-number="25.3.1"><h3 data-number="25.3.1" class="anchored" data-anchor-id="one-sample">
<span class="header-section-number">25.3.1</span> One sample:</h3>
<p>The data in our example warranted running a paired t-test. However, as noted we can run a <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> to compare a single sample to a single value. For example it might be reasonable to ask whether or not the 17 adolescent girls that Hand, et al., 1994 treated were different from what would be considered the average weight of a teenaged girl. A quick Google search suggests that the average weight of girls 12-17 in 2002 was 130 lbs. How does this compare to Hand et al.’s participants <code>Before</code> treatment? We can run a one sample t-test to answer this question:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">beforeTreatment</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">anorexia_data</span>,<span class="va">treatment</span><span class="op">==</span><span class="st">"Before"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">beforeTreatment</span><span class="op">$</span><span class="va">weight</span>, mu <span class="op">=</span> <span class="fl">130</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  beforeTreatment$weight
t = -38.44, df = 16, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 130
95 percent confidence interval:
 80.65007 85.80876
sample estimates:
mean of x 
 83.22941 </code></pre>
</div>
</div>
<p>Yes, this group of girls was significantly underweight compared to the national average.</p>
</section><section id="independent-samples-example" class="level3" data-number="25.3.2"><h3 data-number="25.3.2" class="anchored" data-anchor-id="independent-samples-example">
<span class="header-section-number">25.3.2</span> Independent samples example</h3>
<p>We run an independent samples t-test when we have reason to believe that the data in the two samples is <strong>NOT</strong> meaningfully related in any fashion. Consider this example regarding Joshua Aronson’s work on stereotype threat:</p>
<blockquote class="blockquote">
<p>Joshua Aronson has done extensive work on what he refers to as “stereotype threat,” which refers to the fact that “members of stereotyped groups often feel extra pressure in situations where their behavior can confirm the negative reputation that their group lacks a valued ability” (Aronson, Lustina, Good, Keough, Steele, &amp; Brown, 1998). This feeling of stereo- type threat is then hypothesized to affect performance, generally by lowering it from what it would have been had the individual not felt threatened. Considerable work has been done with ethnic groups who are stereotypically reputed to do poorly in some area, but Aronson et al.&nbsp;went a step further to ask if stereotype threat could actually lower the performance of white males—a group that is not normally associated with stereotype threat.</p>
</blockquote>
<blockquote class="blockquote">
<p>Aronson et al.&nbsp;(1998) used two independent groups of college students who were known to excel in mathematics, and for whom doing well in math was considered important. They assigned 11 students to a control group that was simply asked to complete a difficult mathematics exam. They assigned 12 students to a threat condition, in which they were told that Asian students typically did better than other students in math tests, and that the purpose of the exam was to help the experimenter to understand why this difference exists. Aronson reasoned that simply telling white students that Asians did better on math tests would arousal feelings of stereotype threat and diminish the students’ performance.</p>
</blockquote>
<p>Here we have two mutually exclusive groups of white men, those that are controls and those under induced threat. Importantly we have no reason to believe that any one control man’s score is more closely tied to any individual experimental group counterpart than any others (we’ll return to this idea in a bit).</p>
<p>Here is the data:</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stereotype_data</span> <span class="op">&lt;-</span> <span class="fu">read_delim</span><span class="op">(</span><span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab7-7.dat"</span>, delim <span class="op">=</span> <span class="st">"\t"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 23 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): ID
dbl (2): Score, Group

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>As before, let’s take a look at the file structure:</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">show</span><span class="op">(</span><span class="va">stereotype_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 3
   ID    Score Group
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 01        4     1
 2 02        9     1
 3 03       12     1
 4 04        8     1
 5 05        9     1
 6 06       13     1
 7 07       12     1
 8 08       13     1
 9 09       13     1
10 10        7     1
# ℹ 13 more rows</code></pre>
</div>
</div>
<p>I want to look at this example as it give is an opportunity to deal with another common issue in data cleaning. If you take a look at <code>Group</code> you see it’s either <code>1</code> or <code>2</code>. In this case <code>Group 1</code> are the control subjects and <code>Group 2</code> are the threat subjects. Using numbers instead of names to identify levels of a factor is a convention from older methods and software. In more modern software you don’t need to do this sort of number coding (the software works this out in the background).</p>
<p>If you want to change this, you can use the <code>recode_factor()</code> function from <code>dplyr</code> package in the <code>tidyverse</code> (https://dplyr.tidyverse.org/reference/recode.html). For what it’s worth there are several other ways to do this including a <code>recode()</code> function in car. See http://rprogramming.net/recode-data-in-r/ for examples.</p>
<p>Here I’m just going to mutate a new column, <code>namedGroup</code> column with the recoded names:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stereotype_data</span> <span class="op">&lt;-</span> <span class="va">stereotype_data</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="st">"namedGroup"</span> <span class="op">=</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode_factor</a></span><span class="op">(</span><span class="va">Group</span>,</span>
<span>                                            <span class="st">"1"</span><span class="op">=</span><span class="st">"Control"</span>, </span>
<span>                                            <span class="st">"2"</span><span class="op">=</span><span class="st">"Threat"</span><span class="op">)</span></span>
<span>                            <span class="op">)</span></span>
<span><span class="va">stereotype_data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 4
   ID    Score Group namedGroup
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     
 1 01        4     1 Control   
 2 02        9     1 Control   
 3 03       12     1 Control   
 4 04        8     1 Control   
 5 05        9     1 Control   
 6 06       13     1 Control   
 7 07       12     1 Control   
 8 08       13     1 Control   
 9 09       13     1 Control   
10 10        7     1 Control   
# ℹ 13 more rows</code></pre>
</div>
</div>
<p>An now to run the requisite assumption tests. Note that in this case I am running an Indepednent samples test, so I need to test the assumptions on each sample separately. Here I’m going be a little more critical about how I test for normality.</p>
<p>Using <code><a href="https://rdrr.io/pkg/psych/man/describe.by.html">psych::describeBy</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.by.html">describeBy</a></span><span class="op">(</span><span class="va">stereotype_data</span>,group <span class="op">=</span> <span class="va">stereotype_data</span><span class="op">$</span><span class="va">namedGroup</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Descriptive statistics by group 
group: Control
            vars  n mean   sd median trimmed  mad min max range  skew kurtosis
ID*            1 11 6.00 3.32      6    6.00 4.45   1  11    10  0.00    -1.53
Score          2 11 9.64 3.17      9    9.89 4.45   4  13     9 -0.31    -1.48
Group          3 11 1.00 0.00      1    1.00 0.00   1   1     0   NaN      NaN
namedGroup*    4 11 1.00 0.00      1    1.00 0.00   1   1     0   NaN      NaN
              se
ID*         1.00
Score       0.96
Group       0.00
namedGroup* 0.00
------------------------------------------------------------ 
group: Threat
            vars  n mean   sd median trimmed  mad min max range  skew kurtosis
ID*            1 12 6.50 3.61    6.5     6.5 4.45   1  12    11  0.00    -1.50
Score          2 12 6.58 3.03    7.0     6.9 2.22   0  10    10 -0.86    -0.39
Group          3 12 2.00 0.00    2.0     2.0 0.00   2   2     0   NaN      NaN
namedGroup*    4 12 2.00 0.00    2.0     2.0 0.00   2   2     0   NaN      NaN
              se
ID*         1.04
Score       0.87
Group       0.00
namedGroup* 0.00</code></pre>
</div>
</div>
<p>Using <code>DescTools</code>:</p>
<p><strong>control group</strong></p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">control_group</span> <span class="op">&lt;-</span> <span class="va">stereotype_data</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">namedGroup</span><span class="op">==</span><span class="st">"Control"</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">control_skew</span> <span class="op">&lt;-</span> <span class="fu">DescTools</span><span class="fu">::</span><span class="fu"><a href="https://andrisignorell.github.io/DescTools/reference/Skew.html">Skew</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">control_group</span><span class="op">$</span><span class="va">Score</span>,method <span class="op">=</span> <span class="fl">2</span>,conf.level <span class="op">=</span> <span class="fl">.95</span>,ci.type <span class="op">=</span> <span class="st">"bca"</span>,R <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span>
<span><span class="va">control_skew_ses</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">control_skew</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">-</span> <span class="va">control_skew</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="fl">3.92</span></span>
<span><span class="va">control_skew</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">/</span><span class="va">control_skew_ses</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      skew 
-0.6529139 </code></pre>
</div>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">control_kurt</span> <span class="op">&lt;-</span> <span class="fu">DescTools</span><span class="fu">::</span><span class="fu"><a href="https://andrisignorell.github.io/DescTools/reference/Skew.html">Kurt</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">control_group</span><span class="op">$</span><span class="va">Score</span>,method <span class="op">=</span> <span class="fl">2</span>,conf.level <span class="op">=</span> <span class="fl">.95</span>,ci.type <span class="op">=</span> <span class="st">"bca"</span>,R <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span>
<span><span class="va">control_kurt_ses</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">control_kurt</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">-</span> <span class="va">control_kurt</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="fl">3.92</span></span>
<span><span class="va">control_kurt</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">/</span><span class="va">control_kurt_ses</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     kurt 
-1.105614 </code></pre>
</div>
</div>
<p><strong>threat group</strong></p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">threat_group</span> <span class="op">&lt;-</span> <span class="va">stereotype_data</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">namedGroup</span><span class="op">==</span><span class="st">"Threat"</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">threat_skew</span> <span class="op">&lt;-</span> <span class="fu">DescTools</span><span class="fu">::</span><span class="fu"><a href="https://andrisignorell.github.io/DescTools/reference/Skew.html">Skew</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">threat_group</span><span class="op">$</span><span class="va">Score</span>,method <span class="op">=</span> <span class="fl">2</span>,conf.level <span class="op">=</span> <span class="fl">.95</span>,ci.type <span class="op">=</span> <span class="st">"bca"</span>,R <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span>
<span><span class="va">threat_skew_ses</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">threat_skew</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">-</span> <span class="va">threat_skew</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="fl">3.92</span></span>
<span><span class="va">threat_skew</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">/</span><span class="va">threat_skew_ses</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     skew 
-1.746705 </code></pre>
</div>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">threat_kurt</span> <span class="op">&lt;-</span> <span class="fu">DescTools</span><span class="fu">::</span><span class="fu"><a href="https://andrisignorell.github.io/DescTools/reference/Skew.html">Kurt</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">threat_group</span><span class="op">$</span><span class="va">Score</span>,method <span class="op">=</span> <span class="fl">2</span>,conf.level <span class="op">=</span> <span class="fl">.95</span>,ci.type <span class="op">=</span> <span class="st">"bca"</span>,R <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span>
<span><span class="va">threat_kurt_ses</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">threat_kurt</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">-</span> <span class="va">threat_kurt</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="fl">3.92</span></span>
<span><span class="va">threat_kurt</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">/</span><span class="va">threat_kurt_ses</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     kurt 
0.4284613 </code></pre>
</div>
</div>
<p>This is a pain… can we make a function for this!!!!</p>
<p><strong>QQ-Plot</strong></p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">qqplotr</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">stereotype_data</span>, <span class="fu">aes</span><span class="op">(</span>sample<span class="op">=</span><span class="va">Score</span>, group<span class="op">=</span><span class="va">namedGroup</span>, color<span class="op">=</span><span class="va">namedGroup</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_qq</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu">geom_qq_line</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="6_1_t-test_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Homogeniety of Variance:</em></p>
<p>While the paired samples test doesn’t make this assumption, the Independence samples test assumes the variability of scores for the two groups is roughly homogeneous.</p>
<p>For a t-test this can be tested by using the <code>leveneTest()</code> from the <code>car</code> package:</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># using long-format enter as a formula:</span></span>
<span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/leveneTest.html">leveneTest</a></span><span class="op">(</span><span class="va">Score</span><span class="op">~</span><span class="va">namedGroup</span>, data<span class="op">=</span><span class="va">stereotype_data</span>, center<span class="op">=</span><span class="st">"mean"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = "mean")
      Df F value Pr(&gt;F)
group  1  0.4306 0.5188
      21               </code></pre>
</div>
</div>
<p>You’ll note above I elected to mean center my samples. This is consistent with typical practice although “median” centering may be more robust.</p>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/leveneTest.html">leveneTest</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">stereotype_data</span>, <span class="va">Score</span><span class="op">~</span><span class="va">namedGroup</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  0.4639 0.5033
      21               </code></pre>
</div>
</div>
<p><em>T-test</em> Given that my obtained <code>Pr(&gt;F)</code>, or p-value of Levene’s F-test, is greater than .05, I may elect to assume that my variances are equal. However, if you remained skeptical, there are adjustments that you may make. This includes adjusting the degrees of freedom according to Welch-Satterthwaite recommendation (see below). Recall later on that we are looking at our obtained <span class="math inline">\(t\)</span> value with respect to the number of <span class="math inline">\(df\)</span>. This adjustment effectively reduces the <span class="math inline">\(df\)</span> in turn making your test more conservative.</p>
<p>The Levene’s test failed to reject the null so I may proceed with my <code>t.test</code> assuming variances are equal. Note that <code>paired=FALSE</code> for independent sample tests:</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">stereotype_data</span>, <span class="va">Score</span><span class="op">~</span><span class="va">namedGroup</span>, paired<span class="op">=</span><span class="cn">FALSE</span>, var.equal<span class="op">=</span><span class="cn">T</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Score by namedGroup
t = 2.3614, df = 21, p-value = 0.02795
alternative hypothesis: true difference in means between group Control and group Threat is not equal to 0
95 percent confidence interval:
 0.3643033 5.7417573
sample estimates:
mean in group Control  mean in group Threat 
             9.636364              6.583333 </code></pre>
</div>
</div>
<p>This output gives us the <span class="math inline">\(t\)</span>-value, <span class="math inline">\(df\)</span> and <span class="math inline">\(p\)</span>-value. Based on this output I may conclude that the mean score in the Control group is significantly greater than the Threat group.</p>
<p>Just as an example, let’s set <code>var.equal</code> to <code>FALSE</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">stereotype_data</span>, <span class="va">Score</span><span class="op">~</span><span class="va">namedGroup</span>, paired<span class="op">=</span><span class="cn">FALSE</span>, var.equal<span class="op">=</span><span class="cn">F</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Score by namedGroup
t = 2.3565, df = 20.614, p-value = 0.02843
alternative hypothesis: true difference in means between group Control and group Threat is not equal to 0
95 percent confidence interval:
 0.3556143 5.7504463
sample estimates:
mean in group Control  mean in group Threat 
             9.636364              6.583333 </code></pre>
</div>
</div>
<p>Comparing the outputs you see that in this case <code>R</code> has indicated that it has run the test with the Welsh correction. Note that this changes the <span class="math inline">\(df\)</span> and consequently the resulting <span class="math inline">\(p\)</span> value. That this change was negligible reinforces that the variances were very similar to one another. However in cases where they are not close to one another you may see dramatic changes in <span class="math inline">\(df\)</span>.</p>
<p>In <code>R</code>, the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function sets <code>var.equal=FALSE</code> by default. Why you ask? Well, you can make the argument that the variances are ALWAYS unequal, its only a matter of degree. Assuming variances are unequal makes your test more conservative, meaning that if the test suggests that you should reject the null, you can be slightly more confident that you are not committing Type I error. At the same time, it could be argued that setting your <code>var.equal=TRUE</code> in this case (where the Levene test failed to reject the null) makes your test more powerful, and you should take advantage of that power to avoid Type II error.</p>
</section></section><section id="independent-or-paired-sample" class="level2" data-number="25.4"><h2 data-number="25.4" class="anchored" data-anchor-id="independent-or-paired-sample">
<span class="header-section-number">25.4</span> Independent or Paired Sample?</h2>
<p>It is safe to assume that anytime that you are collecting data samples from the same person at two different points in time that you need to run a paired-samples test. However, it would not be safe to assume that if the samples are coming from different groups of people that you always run an independent samples test. Remember the important qualifier mentioned above: That there no reason to believe that any one participant in the first group is is more closely related to any single counterpart in the second group than the remaining of others. In our Independent test example we have no reason to assume this is the case, we assume that members of the Control and Threat groups were randomly selected. But what if we instead recruited brothers or twins? In this case, it may make sense to treat members of the two groups as paired; brothers have a shared history (education, socio-economic level, family dynamic, etc) that would make their scores more likely to be related to one another than by random chance.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../week05/5_6_example_report.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Example Report</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../week06/6_2_t-test-null-model.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Thinking about nothing (aka the null)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb53" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Testing differences in means / t-test"</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>This week we cover when and how to conduct a $t-test$. We use a t-test to assess whether the observed difference between sample means is greater than would be predicted be chance. Both the Navarro text and Poldrack text do a wonderful job of explaining t-tests conceptually so I will defer to those experts on matters of the underlying their statistical basis. Instead my goal this week is to walk through some examples on performing, interpreting, and reporting t-tests using <span class="in">`R`</span>.</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>This walkthough assumes that the following packages are installed and loaded on your computer:</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, car, cowplot, lsr, DescTools)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## Things to consider before running the t-test</span></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>Before running a <span class="in">`t.test`</span> there are a few practical and statistical considerations that must be taken. In fact, these considerations extend to every type of analysis that we will encounter for the remainder of the semester (and indeed the rest of your career) so it would be good to get in the habit of running through your checks. In what proceeds here I will walk step by step with how I condunct a <span class="in">`t.test`</span> (while also highlighting certain decision points as they come up).</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a><span class="fu">### What is the nature of your sample data?</span></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>In other words where is the data coming from? Is it coming from a single sample of participants? Is it coming from multiple samples of the SAME participants? Is it coming from multiple groups of participants. This will not only determine what analysis you choose to run, but in also how you go about the business of preparing to run this analysis. Of course, truth be told this information should already be known before you even start collecting your data, which reinforces an important point, your central analyses should already be selected BEFORE you start collecting data! As you design your experiments you should do so in a way in which the statistics that you run are built into the design, not settled upon afterwards. This enables you to give the tests you perform the most power, as you are making predictions about the outcomes of your test *a priori*. This will become a major theme on the back half of the class, but best to introduce it now.</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>For this week, it will determine what test we will elect to perform. Let's grab some sample data from an experiment by Hand, et al. (1994)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Hand, et al., 1994, reported on family therapy as a treatment for anorexia. There were 17 girls in this experiment, and they were weighed before and after treatment. The weights of the girls, in pounds, is provided in the data below:</span></span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a>anorexia_data <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab7-3.dat"</span>, </span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">escape_double =</span> <span class="cn">FALSE</span>, <span class="at">trim_ws =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a>So what is known: we have 17 total participants from (hypothetically) the same population that are measured twice (once <span class="in">`Before`</span> treatment, and once <span class="in">`After`</span> treatment). Based upon the experimental question we need to run a paired-sample (matched-sample) test. (Although I'll use this data to provide an example of a one-sample test later on).</span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a><span class="fu">### What is the structure of your data file?</span></span>
<span id="cb53-37"><a href="#cb53-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-38"><a href="#cb53-38" aria-hidden="true" tabindex="-1"></a>Before doing anything you should always take a look at your data:</span>
<span id="cb53-39"><a href="#cb53-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-42"><a href="#cb53-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-43"><a href="#cb53-43" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(anorexia_data)</span>
<span id="cb53-44"><a href="#cb53-44" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-45"><a href="#cb53-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-46"><a href="#cb53-46" aria-hidden="true" tabindex="-1"></a>So what do we have here, three columns:</span>
<span id="cb53-47"><a href="#cb53-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-48"><a href="#cb53-48" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`ID`</span>: the participant number</span>
<span id="cb53-49"><a href="#cb53-49" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`Before`</span>: participants' weights before treatment</span>
<span id="cb53-50"><a href="#cb53-50" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`After`</span>: participants' weights after treatment</span>
<span id="cb53-51"><a href="#cb53-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-52"><a href="#cb53-52" aria-hidden="true" tabindex="-1"></a>Most important for present purposes this data is in <span class="in">`WIDE`</span> format---each line represents a participant. While this might be intuitive for tabluar visualization, many statistical softwares prefer when <span class="in">`LONG`</span> format, where each line represents a single *observation* (or some mixed of WIDE and LONG like SPSS).</span>
<span id="cb53-53"><a href="#cb53-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-54"><a href="#cb53-54" aria-hidden="true" tabindex="-1"></a>I spoke a little bit about this issue in Week 2, Walkthrough 0.</span>
<span id="cb53-55"><a href="#cb53-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-56"><a href="#cb53-56" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Getting data from WIDE to LONG</span></span>
<span id="cb53-57"><a href="#cb53-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-58"><a href="#cb53-58" aria-hidden="true" tabindex="-1"></a>So the data are in WIDE format, each line has multiple observations of data that are being compared. Here both <span class="in">`Before`</span> scores and <span class="in">`After`</span> scores are on the same line. In order to make life easier for analysis and plotting in <span class="in">`ggplot`</span>, we need to get the data into LONG format (<span class="in">`Before`</span> scores and <span class="in">`After`</span> scores are on different lines). This can be done using the <span class="in">`pivot_longer()`</span> function from the <span class="in">`tidyr`</span> package.</span>
<span id="cb53-59"><a href="#cb53-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-60"><a href="#cb53-60" aria-hidden="true" tabindex="-1"></a>Before gathering, one thing to consider is whether or not you have a column that defines each subject. In this case we have <span class="in">`ID`</span>. This tells <span class="in">`R`</span> that these data are coming from the same subject and will allow <span class="in">`R`</span> to connect these data when performing analysis. That said, for <span class="in">`t.test()`</span> this is not crucially important---<span class="in">`t.test()`</span> assumes that the order of lines represents the order of subjects, e.g., the first <span class="in">`Before`</span> line is matched to the first <span class="in">`After`</span> line. Later on when we are doing ANOVA, however, this participant column will be important an we will need to add if it is missing.</span>
<span id="cb53-61"><a href="#cb53-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-62"><a href="#cb53-62" aria-hidden="true" tabindex="-1"></a>**Using `pivot_longer()`:** This function takes a number of arguments, but for us right now, the most important are <span class="in">`data`</span>: your dataframe; <span class="in">`cols`</span>: which columns to gather; <span class="in">`names_to`</span>: what do you want the header of the collaped nonminal variables to be? Here, we might ask what title would encapsulate both <span class="in">`Before`</span> and <span class="in">`After`</span>. I'll choose <span class="in">`treatment`</span> ; <span class="in">`values_to`</span>: what do the values represent, here I choose <span class="in">`weight`</span>. I'm just going to overwrite the original data frame:</span>
<span id="cb53-63"><a href="#cb53-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-66"><a href="#cb53-66" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-67"><a href="#cb53-67" aria-hidden="true" tabindex="-1"></a>anorexia_data <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(anorexia_data,<span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"Before"</span>,<span class="st">"After"</span>),<span class="at">names_to =</span> <span class="st">"treatment"</span>, <span class="at">values_to =</span> <span class="st">"weight"</span>)</span>
<span id="cb53-68"><a href="#cb53-68" aria-hidden="true" tabindex="-1"></a>anorexia_data</span>
<span id="cb53-69"><a href="#cb53-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-70"><a href="#cb53-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-71"><a href="#cb53-71" aria-hidden="true" tabindex="-1"></a>Ok data is structured correctly, on to the next step.</span>
<span id="cb53-72"><a href="#cb53-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-73"><a href="#cb53-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Testing assumptions</span></span>
<span id="cb53-74"><a href="#cb53-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-75"><a href="#cb53-75" aria-hidden="true" tabindex="-1"></a>Remember that you should always test to see if the data fit the assumptions of the test you intend to perform. In this case, we need to assess two things:</span>
<span id="cb53-76"><a href="#cb53-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-77"><a href="#cb53-77" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Is the data normally distributed?</span></span>
<span id="cb53-78"><a href="#cb53-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-79"><a href="#cb53-79" aria-hidden="true" tabindex="-1"></a>Knowing the design of your experiment also has implications for testing your assumptions. For example, whether you have a paired (matched) sample design (e.g., two samples from the same participants) or an independent sample design (e.g., two groups) determines how you go about the business of testing the normality assumption. If you have an independent samples test, you test each sample separately, noting measures of skew, kurtosis, inspecting the qqPlot, and Shapiro-Wilkes test (though acknowledging that SW is very sensitive). However, if you are running a paired (matched) samples test, you need to be concerned with the distribution of the difference scores. In the present example we are comparing participants' weights <span class="in">`Before`</span> treatment to their weight <span class="in">`After`</span>. This is a paired design, so I need to test the differences between each participant's <span class="in">`Before`</span> and <span class="in">`After`</span> for normality.</span>
<span id="cb53-80"><a href="#cb53-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-81"><a href="#cb53-81" aria-hidden="true" tabindex="-1"></a>First, let me <span class="in">`filter()`</span> my data accordingly for <span class="in">`Before`</span> and <span class="in">`After`</span> (essentially creating separate vectors for each condition):</span>
<span id="cb53-82"><a href="#cb53-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-85"><a href="#cb53-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-86"><a href="#cb53-86" aria-hidden="true" tabindex="-1"></a>beforeTreatment <span class="ot">&lt;-</span> <span class="fu">filter</span>(anorexia_data, treatment<span class="sc">==</span><span class="st">"Before"</span>) </span>
<span id="cb53-87"><a href="#cb53-87" aria-hidden="true" tabindex="-1"></a>afterTreatment <span class="ot">&lt;-</span> <span class="fu">filter</span>(anorexia_data, treatment<span class="sc">==</span><span class="st">"After"</span>) </span>
<span id="cb53-88"><a href="#cb53-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-89"><a href="#cb53-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-90"><a href="#cb53-90" aria-hidden="true" tabindex="-1"></a>And now compute the difference scores, and run my assumption tests:</span>
<span id="cb53-91"><a href="#cb53-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-94"><a href="#cb53-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-95"><a href="#cb53-95" aria-hidden="true" tabindex="-1"></a>diffWeights <span class="ot">&lt;-</span> beforeTreatment<span class="sc">$</span>weight <span class="sc">-</span> afterTreatment<span class="sc">$</span>weight</span>
<span id="cb53-96"><a href="#cb53-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-97"><a href="#cb53-97" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(diffWeights)</span>
<span id="cb53-98"><a href="#cb53-98" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(diffWeights)</span>
<span id="cb53-99"><a href="#cb53-99" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(diffWeights)</span>
<span id="cb53-100"><a href="#cb53-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-101"><a href="#cb53-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-102"><a href="#cb53-102" aria-hidden="true" tabindex="-1"></a>What conclusions might we draw about normality?</span>
<span id="cb53-103"><a href="#cb53-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-104"><a href="#cb53-104" aria-hidden="true" tabindex="-1"></a><span class="fu">### Getting the descriptive stats and plotting the means.</span></span>
<span id="cb53-105"><a href="#cb53-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-106"><a href="#cb53-106" aria-hidden="true" tabindex="-1"></a>Finally, as we will be performing a test of difference in means, it would be a good idea to get descriptive measures of means and variability for each group. Indeed, these data were already obatined when we used <span class="in">`psych::describe()`</span> to assess the normality of each sample. Here I'll just do it again to get these values:</span>
<span id="cb53-107"><a href="#cb53-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-110"><a href="#cb53-110" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-111"><a href="#cb53-111" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describeBy</span>(anorexia_data<span class="sc">$</span>weight,<span class="at">group =</span> anorexia_data<span class="sc">$</span>treatment)</span>
<span id="cb53-112"><a href="#cb53-112" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-113"><a href="#cb53-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-114"><a href="#cb53-114" aria-hidden="true" tabindex="-1"></a>Typically along with the mean, you need to report a measure of variability of your sample. This can be either the SD, SEM, or if you choose the 95% CI, although this is more rare in the actual report. See the supplied HW example and APA examples for conventions on how to report these in your results section.</span>
<span id="cb53-115"><a href="#cb53-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-116"><a href="#cb53-116" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Plotting in ggplot</span></span>
<span id="cb53-117"><a href="#cb53-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-118"><a href="#cb53-118" aria-hidden="true" tabindex="-1"></a>I've mentioned the limits and issues with plotting bar plots, but they remain a standard, so we will simply proceed using these plots. But I'll note that boxplots, violin plots, bean plots, and pirate plots are all modern alternatives to bar plots and are easy to execute in <span class="in">`ggplot()`</span>. Try a Google search.</span>
<span id="cb53-119"><a href="#cb53-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-120"><a href="#cb53-120" aria-hidden="true" tabindex="-1"></a>In the meantime, to produce a bar plot in <span class="in">`R`</span> we simply modify a few of the arguments that we are familiar width.</span>
<span id="cb53-121"><a href="#cb53-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-122"><a href="#cb53-122" aria-hidden="true" tabindex="-1"></a>Here is the code for plotting these two groups:</span>
<span id="cb53-123"><a href="#cb53-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-126"><a href="#cb53-126" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-127"><a href="#cb53-127" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> anorexia_data, <span class="fu">aes</span>(<span class="at">x=</span>treatment, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb53-128"><a href="#cb53-128" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"col"</span>) <span class="sc">+</span> </span>
<span id="cb53-129"><a href="#cb53-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-130"><a href="#cb53-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb53-131"><a href="#cb53-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()</span>
<span id="cb53-132"><a href="#cb53-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-133"><a href="#cb53-133" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-134"><a href="#cb53-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-135"><a href="#cb53-135" aria-hidden="true" tabindex="-1"></a>Breaking this down line-by-line:</span>
<span id="cb53-136"><a href="#cb53-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-137"><a href="#cb53-137" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`ggplot(data = anorexia_data, aes(x=treatment, y=weight))`</span>: standard fare for starting a <span class="in">`ggplot`</span>.</span>
<span id="cb53-138"><a href="#cb53-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-139"><a href="#cb53-139" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`stat_summary(fun = "mean", geom = "col")`</span>: <span class="in">`stat_summary()`</span> gets summary statistics and projects them onto the geom of your choice. In this case we are getting the mean values, <span class="in">`fun = "mean"`</span> and using them to create a column plot <span class="in">`geom = "col"`</span> .</span>
<span id="cb53-140"><a href="#cb53-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-141"><a href="#cb53-141" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`stat_summary(fun.data = "mean_se", geom = "errorbar", width = .1)`</span> : here we are creating error bars, <span class="in">`geom = "errorbar"`</span>. Important to note here is that error bars require knowing three values: mean, upper limit, and lower limit. Whenever you are asking for a single value, like a mean, you use <span class="in">`fun`</span>. When multiple values are needed you use <span class="in">`fun.data`</span>. Here <span class="in">`fun.data = "mean_se"`</span> requests Standard error bars. Other alternatives include 95% CI <span class="in">`"mean_cl_normal"`</span> and Standard deviation <span class="in">`"mean_sdl"`</span>. The <span class="in">`width`</span> argument adjusts the width of the error bars.</span>
<span id="cb53-142"><a href="#cb53-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-143"><a href="#cb53-143" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`scale_y_continuous(expand = c(0,0))`</span>: Typically <span class="in">`R`</span> will do this strange thing where it places a gap bewteen the data and the <span class="in">`x-axis`</span>. This line is a hack to remove this default. It says along the y-axis add <span class="in">`0`</span> expansion (or gap).</span>
<span id="cb53-144"><a href="#cb53-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-145"><a href="#cb53-145" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`theme_cowplot()`</span>: quick APA aesthetics.</span>
<span id="cb53-146"><a href="#cb53-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-147"><a href="#cb53-147" aria-hidden="true" tabindex="-1"></a>You may also feel that the zooming factor is off. This may especially be true in cases where there is little visual discrepency between the bars. To "zoom in" on the data you can use <span class="in">`coord_cartesian()`</span>. For example, you might want to only show the range between 70 lbs and 100 lbs. When doing this, be careful not to truncate the upper limits of your bars and importantly your error bars.</span>
<span id="cb53-148"><a href="#cb53-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-151"><a href="#cb53-151" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-152"><a href="#cb53-152" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> anorexia_data, <span class="fu">aes</span>(<span class="at">x=</span>treatment, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb53-153"><a href="#cb53-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"col"</span>) <span class="sc">+</span> </span>
<span id="cb53-154"><a href="#cb53-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-155"><a href="#cb53-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb53-156"><a href="#cb53-156" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb53-157"><a href="#cb53-157" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">70</span>,<span class="dv">100</span>))</span>
<span id="cb53-158"><a href="#cb53-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-159"><a href="#cb53-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-160"><a href="#cb53-160" aria-hidden="true" tabindex="-1"></a>Additionally, to get this into true APA format I would need to adjust my axis labels. Here capitalization is needed. Also, because the weight has a unit measure, I need to be specific about that:</span>
<span id="cb53-161"><a href="#cb53-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-164"><a href="#cb53-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-165"><a href="#cb53-165" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> anorexia_data, <span class="fu">aes</span>(<span class="at">x=</span>treatment, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb53-166"><a href="#cb53-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"col"</span>) <span class="sc">+</span> </span>
<span id="cb53-167"><a href="#cb53-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-168"><a href="#cb53-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb53-169"><a href="#cb53-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb53-170"><a href="#cb53-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">70</span>,<span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb53-171"><a href="#cb53-171" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Treatment"</span>) <span class="sc">+</span> </span>
<span id="cb53-172"><a href="#cb53-172" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Weight (lbs)"</span>)</span>
<span id="cb53-173"><a href="#cb53-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-174"><a href="#cb53-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-175"><a href="#cb53-175" aria-hidden="true" tabindex="-1"></a>Finally, you may have notice that the order of Treatment on the plot is opposite of what we might like to logically present. In this case the "After" data comes prior to the "Before" data on the x-axis. This is because <span class="in">`R`</span> defaults to alphabetical order when loading in data. To correct this I can use <span class="in">`scale_x_discrete()`</span> and specify the order that I want in <span class="in">`limits`</span>:</span>
<span id="cb53-176"><a href="#cb53-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-179"><a href="#cb53-179" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-180"><a href="#cb53-180" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> anorexia_data, <span class="fu">aes</span>(<span class="at">x=</span>treatment, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb53-181"><a href="#cb53-181" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"col"</span>) <span class="sc">+</span> </span>
<span id="cb53-182"><a href="#cb53-182" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-183"><a href="#cb53-183" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb53-184"><a href="#cb53-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb53-185"><a href="#cb53-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">70</span>,<span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb53-186"><a href="#cb53-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Treatment"</span>) <span class="sc">+</span> </span>
<span id="cb53-187"><a href="#cb53-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Weight (lbs)"</span>) <span class="sc">+</span> </span>
<span id="cb53-188"><a href="#cb53-188" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="st">"Before"</span>,<span class="st">"After"</span>))</span>
<span id="cb53-189"><a href="#cb53-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-190"><a href="#cb53-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-191"><a href="#cb53-191" aria-hidden="true" tabindex="-1"></a>Alternatively I can correct the order of the levels of a factor within the dataframe itself using <span class="in">`fct_relevel()`</span> (this gets loaded with <span class="in">`tidyverse`</span>). Note that here I am overwriting the original <span class="in">`treatment`</span> column. If you do this proceed at your own risk! You could also just <span class="in">`mutate`</span> a new column if you would rather not overwrite.</span>
<span id="cb53-192"><a href="#cb53-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-195"><a href="#cb53-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-196"><a href="#cb53-196" aria-hidden="true" tabindex="-1"></a>anorexia_data<span class="sc">$</span>treatment <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(anorexia_data<span class="sc">$</span>treatment, <span class="st">"Before"</span>, <span class="st">"After"</span>)</span>
<span id="cb53-197"><a href="#cb53-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-198"><a href="#cb53-198" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> anorexia_data, <span class="fu">aes</span>(<span class="at">x=</span>treatment, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb53-199"><a href="#cb53-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"col"</span>, </span>
<span id="cb53-200"><a href="#cb53-200" aria-hidden="true" tabindex="-1"></a>               <span class="at">fill =</span> <span class="st">"lightgray"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="co"># adding some color mods here.</span></span>
<span id="cb53-201"><a href="#cb53-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-202"><a href="#cb53-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb53-203"><a href="#cb53-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb53-204"><a href="#cb53-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">70</span>,<span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb53-205"><a href="#cb53-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Treatment"</span>) <span class="sc">+</span> </span>
<span id="cb53-206"><a href="#cb53-206" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Weight (lbs)"</span>)</span>
<span id="cb53-207"><a href="#cb53-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-208"><a href="#cb53-208" aria-hidden="true" tabindex="-1"></a><span class="co"># note that I don't have to do the `scale_x_discrete(limits=c("Before","After"))` correction</span></span>
<span id="cb53-209"><a href="#cb53-209" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-210"><a href="#cb53-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-211"><a href="#cb53-211" aria-hidden="true" tabindex="-1"></a>All good (well maybe check with Sierra first)! One other thing to consider (although please do not worry about it here) is the recent argument that when dealing with repeated measures data you need to adjust you error bars. See <span class="co">[</span><span class="ot">this pdf</span><span class="co">](http://www.tqmp.org/Content/vol04-2/p061/p061.pdf)</span> by Richard Morey (2005) for more information on this issue. We'll revisit this issue when running Repeated Measures ANOVA.</span>
<span id="cb53-212"><a href="#cb53-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-213"><a href="#cb53-213" aria-hidden="true" tabindex="-1"></a><span class="fu">#### An aside... other types of plots</span></span>
<span id="cb53-214"><a href="#cb53-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-215"><a href="#cb53-215" aria-hidden="true" tabindex="-1"></a>As I mentioned barplots (especially those that use standard error bars) have more recently come under criticism for "hiding" the true name of the data. There is currently a movement to make data more transparent using other kinds of plots that convey more information about your sample. For example let's contrast out barplot from above with a combination "pointrange" and violin plot. The <span class="in">`pointrange`</span> simply provides the mean as a point with error bars extending as specified (here I choose standard error). The violin plot is essentially a histogram of the data turned on its side, centered on the mean, and then mirrored... it gives us info about the TRUE distribution of scores.</span>
<span id="cb53-216"><a href="#cb53-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-217"><a href="#cb53-217" aria-hidden="true" tabindex="-1"></a>Let's take a look side by side</span>
<span id="cb53-218"><a href="#cb53-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-221"><a href="#cb53-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-222"><a href="#cb53-222" aria-hidden="true" tabindex="-1"></a>barplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> anorexia_data, <span class="fu">aes</span>(<span class="at">x=</span>treatment, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb53-223"><a href="#cb53-223" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"col"</span>, </span>
<span id="cb53-224"><a href="#cb53-224" aria-hidden="true" tabindex="-1"></a>               <span class="at">fill =</span> <span class="st">"lightgray"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="co"># adding some color mods here.</span></span>
<span id="cb53-225"><a href="#cb53-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-226"><a href="#cb53-226" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb53-227"><a href="#cb53-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb53-228"><a href="#cb53-228" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">70</span>,<span class="dv">110</span>)) <span class="sc">+</span></span>
<span id="cb53-229"><a href="#cb53-229" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Treatment"</span>) <span class="sc">+</span> </span>
<span id="cb53-230"><a href="#cb53-230" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Weight (lbs)"</span>)</span>
<span id="cb53-231"><a href="#cb53-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-232"><a href="#cb53-232" aria-hidden="true" tabindex="-1"></a><span class="co"># note that order matters. I need to do the violin before the pointrange or else the violin will "paint over" the pointrange.</span></span>
<span id="cb53-233"><a href="#cb53-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-234"><a href="#cb53-234" aria-hidden="true" tabindex="-1"></a>point_violin_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> anorexia_data, <span class="fu">aes</span>(<span class="at">x=</span>treatment, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb53-235"><a href="#cb53-235" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb53-236"><a href="#cb53-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_se"</span>, <span class="at">geom =</span> <span class="st">"pointrange"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="co"># adding some color mods here.</span></span>
<span id="cb53-237"><a href="#cb53-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb53-238"><a href="#cb53-238" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb53-239"><a href="#cb53-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">70</span>,<span class="dv">110</span>)) <span class="sc">+</span></span>
<span id="cb53-240"><a href="#cb53-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Treatment"</span>) <span class="sc">+</span> </span>
<span id="cb53-241"><a href="#cb53-241" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Weight (lbs)"</span>)</span>
<span id="cb53-242"><a href="#cb53-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-243"><a href="#cb53-243" aria-hidden="true" tabindex="-1"></a>cowplot<span class="sc">::</span><span class="fu">plot_grid</span>(barplot, point_violin_plot)</span>
<span id="cb53-244"><a href="#cb53-244" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-245"><a href="#cb53-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-246"><a href="#cb53-246" aria-hidden="true" tabindex="-1"></a>As you can see the second plot gives me more information about what's truly going on with my data.</span>
<span id="cb53-247"><a href="#cb53-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-248"><a href="#cb53-248" aria-hidden="true" tabindex="-1"></a><span class="fu">## Performing the t-test (Paired sample t-test)</span></span>
<span id="cb53-249"><a href="#cb53-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-250"><a href="#cb53-250" aria-hidden="true" tabindex="-1"></a>Okay, now that we've done all of our preparation, we're now ready to perform the test. We can do so using the <span class="in">`t.test()`</span> function. In this case, the experimental question warrants a <span class="in">`paired`</span> samples t-test. Given that our Levene's test failed to reject the null, we will assume that our variances are equal.</span>
<span id="cb53-251"><a href="#cb53-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-252"><a href="#cb53-252" aria-hidden="true" tabindex="-1"></a>Since we've got long-format data we will use the formula syntax. This reads "predicting changes in <span class="in">`weight`</span> as a function of <span class="in">`treatment`</span>.</span>
<span id="cb53-253"><a href="#cb53-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-256"><a href="#cb53-256" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-257"><a href="#cb53-257" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(weight<span class="sc">~</span>treatment,<span class="at">data=</span>anorexia_data,<span class="at">paired=</span>T, <span class="at">var.equal=</span>T)</span>
<span id="cb53-258"><a href="#cb53-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-259"><a href="#cb53-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-260"><a href="#cb53-260" aria-hidden="true" tabindex="-1"></a>The output provides us with our $t$ value, the $df$ and the $p$ value. It also includes a measure of the 95% CI, and the mean difference. Remember that the null hypothesis is that there is no difference between our two samples. In the case of repeated measures especially, it makes sense to think of this in terms of a difference score of change, where the null is 0. The resulting interpretation is that on average participants' weight increased 7.26 pounds due to the treatment, with a 95% likelihood that the true mean change is between 3.58 lbs and 10.95 lbs. Important for us is that 0 is not in the 95% CI, reinforcing that there was indeed a non-zero change (rejecting the null).</span>
<span id="cb53-261"><a href="#cb53-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-262"><a href="#cb53-262" aria-hidden="true" tabindex="-1"></a><span class="fu">## Other $t$ tests:</span></span>
<span id="cb53-263"><a href="#cb53-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-264"><a href="#cb53-264" aria-hidden="true" tabindex="-1"></a><span class="fu">### One sample:</span></span>
<span id="cb53-265"><a href="#cb53-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-266"><a href="#cb53-266" aria-hidden="true" tabindex="-1"></a>The data in our example warranted running a paired t-test. However, as noted we can run a <span class="in">`t.test()`</span> to compare a single sample to a single value. For example it might be reasonable to ask whether or not the 17 adolescent girls that Hand, et al., 1994 treated were different from what would be considered the average weight of a teenaged girl. A quick Google search suggests that the average weight of girls 12-17 in 2002 was 130 lbs. How does this compare to Hand et al.'s participants <span class="in">`Before`</span> treatment? We can run a one sample t-test to answer this question:</span>
<span id="cb53-267"><a href="#cb53-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-270"><a href="#cb53-270" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-271"><a href="#cb53-271" aria-hidden="true" tabindex="-1"></a>beforeTreatment <span class="ot">&lt;-</span> <span class="fu">filter</span>(anorexia_data,treatment<span class="sc">==</span><span class="st">"Before"</span>)</span>
<span id="cb53-272"><a href="#cb53-272" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(beforeTreatment<span class="sc">$</span>weight, <span class="at">mu =</span> <span class="dv">130</span>)</span>
<span id="cb53-273"><a href="#cb53-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-274"><a href="#cb53-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-275"><a href="#cb53-275" aria-hidden="true" tabindex="-1"></a>Yes, this group of girls was significantly underweight compared to the national average.</span>
<span id="cb53-276"><a href="#cb53-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-277"><a href="#cb53-277" aria-hidden="true" tabindex="-1"></a><span class="fu">### Independent samples example</span></span>
<span id="cb53-278"><a href="#cb53-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-279"><a href="#cb53-279" aria-hidden="true" tabindex="-1"></a>We run an independent samples t-test when we have reason to believe that the data in the two samples is **NOT** meaningfully related in any fashion. Consider this example regarding Joshua Aronson's work on stereotype threat:</span>
<span id="cb53-280"><a href="#cb53-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-281"><a href="#cb53-281" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Joshua Aronson has done extensive work on what he refers to as "stereotype threat," which refers to the fact that "members of stereotyped groups often feel extra pressure in situations where their behavior can confirm the negative reputation that their group lacks a valued ability" (Aronson, Lustina, Good, Keough, Steele, &amp; Brown, 1998). This feeling of stereo- type threat is then hypothesized to affect performance, generally by lowering it from what it would have been had the individual not felt threatened. Considerable work has been done with ethnic groups who are stereotypically reputed to do poorly in some area, but Aronson et al. went a step further to ask if stereotype threat could actually lower the performance of white males---a group that is not normally associated with stereotype threat.</span></span>
<span id="cb53-282"><a href="#cb53-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-283"><a href="#cb53-283" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Aronson et al. (1998) used two independent groups of college students who were known to excel in mathematics, and for whom doing well in math was considered important. They assigned 11 students to a control group that was simply asked to complete a difficult mathematics exam. They assigned 12 students to a threat condition, in which they were told that Asian students typically did better than other students in math tests, and that the purpose of the exam was to help the experimenter to understand why this difference exists. Aronson reasoned that simply telling white students that Asians did better on math tests would arousal feelings of stereotype threat and diminish the students' performance.</span></span>
<span id="cb53-284"><a href="#cb53-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-285"><a href="#cb53-285" aria-hidden="true" tabindex="-1"></a>Here we have two mutually exclusive groups of white men, those that are controls and those under induced threat. Importantly we have no reason to believe that any one control man's score is more closely tied to any individual experimental group counterpart than any others (we'll return to this idea in a bit).</span>
<span id="cb53-286"><a href="#cb53-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-287"><a href="#cb53-287" aria-hidden="true" tabindex="-1"></a>Here is the data:</span>
<span id="cb53-288"><a href="#cb53-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-291"><a href="#cb53-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-292"><a href="#cb53-292" aria-hidden="true" tabindex="-1"></a>stereotype_data <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab7-7.dat"</span>, <span class="at">delim =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb53-293"><a href="#cb53-293" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-294"><a href="#cb53-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-295"><a href="#cb53-295" aria-hidden="true" tabindex="-1"></a>As before, let's take a look at the file structure:</span>
<span id="cb53-296"><a href="#cb53-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-299"><a href="#cb53-299" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-300"><a href="#cb53-300" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(stereotype_data)</span>
<span id="cb53-301"><a href="#cb53-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-302"><a href="#cb53-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-303"><a href="#cb53-303" aria-hidden="true" tabindex="-1"></a>I want to look at this example as it give is an opportunity to deal with another common issue in data cleaning. If you take a look at <span class="in">`Group`</span> you see it's either <span class="in">`1`</span> or <span class="in">`2`</span>. In this case <span class="in">`Group 1`</span> are the control subjects and <span class="in">`Group 2`</span> are the threat subjects. Using numbers instead of names to identify levels of a factor is a convention from older methods and software. In more modern software you don't need to do this sort of number coding (the software works this out in the background).</span>
<span id="cb53-304"><a href="#cb53-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-305"><a href="#cb53-305" aria-hidden="true" tabindex="-1"></a>If you want to change this, you can use the <span class="in">`recode_factor()`</span> function from <span class="in">`dplyr`</span> package in the <span class="in">`tidyverse`</span> (https://dplyr.tidyverse.org/reference/recode.html). For what it's worth there are several other ways to do this including a <span class="in">`recode()`</span> function in car. See http://rprogramming.net/recode-data-in-r/ for examples.</span>
<span id="cb53-306"><a href="#cb53-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-307"><a href="#cb53-307" aria-hidden="true" tabindex="-1"></a>Here I'm just going to mutate a new column, <span class="in">`namedGroup`</span> column with the recoded names:</span>
<span id="cb53-308"><a href="#cb53-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-311"><a href="#cb53-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-312"><a href="#cb53-312" aria-hidden="true" tabindex="-1"></a>stereotype_data <span class="ot">&lt;-</span> stereotype_data <span class="sc">%&gt;%</span> </span>
<span id="cb53-313"><a href="#cb53-313" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"namedGroup"</span> <span class="ot">=</span> dplyr<span class="sc">::</span><span class="fu">recode_factor</span>(Group,</span>
<span id="cb53-314"><a href="#cb53-314" aria-hidden="true" tabindex="-1"></a>                                            <span class="st">"1"</span><span class="ot">=</span><span class="st">"Control"</span>, </span>
<span id="cb53-315"><a href="#cb53-315" aria-hidden="true" tabindex="-1"></a>                                            <span class="st">"2"</span><span class="ot">=</span><span class="st">"Threat"</span>)</span>
<span id="cb53-316"><a href="#cb53-316" aria-hidden="true" tabindex="-1"></a>                            )</span>
<span id="cb53-317"><a href="#cb53-317" aria-hidden="true" tabindex="-1"></a>stereotype_data</span>
<span id="cb53-318"><a href="#cb53-318" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-319"><a href="#cb53-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-320"><a href="#cb53-320" aria-hidden="true" tabindex="-1"></a>An now to run the requisite assumption tests. Note that in this case I am running an Indepednent samples test, so I need to test the assumptions on each sample separately. Here I'm going be a little more critical about how I test for normality.</span>
<span id="cb53-321"><a href="#cb53-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-322"><a href="#cb53-322" aria-hidden="true" tabindex="-1"></a>Using <span class="in">`psych::describeBy`</span>:</span>
<span id="cb53-323"><a href="#cb53-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-326"><a href="#cb53-326" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-327"><a href="#cb53-327" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describeBy</span>(stereotype_data,<span class="at">group =</span> stereotype_data<span class="sc">$</span>namedGroup)</span>
<span id="cb53-328"><a href="#cb53-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-329"><a href="#cb53-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-330"><a href="#cb53-330" aria-hidden="true" tabindex="-1"></a>Using <span class="in">`DescTools`</span>:</span>
<span id="cb53-331"><a href="#cb53-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-332"><a href="#cb53-332" aria-hidden="true" tabindex="-1"></a>**control group**</span>
<span id="cb53-333"><a href="#cb53-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-336"><a href="#cb53-336" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-337"><a href="#cb53-337" aria-hidden="true" tabindex="-1"></a>control_group <span class="ot">&lt;-</span> stereotype_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(namedGroup<span class="sc">==</span><span class="st">"Control"</span>) </span>
<span id="cb53-338"><a href="#cb53-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-339"><a href="#cb53-339" aria-hidden="true" tabindex="-1"></a>control_skew <span class="ot">&lt;-</span> DescTools<span class="sc">::</span><span class="fu">Skew</span>(<span class="at">x=</span>control_group<span class="sc">$</span>Score,<span class="at">method =</span> <span class="dv">2</span>,<span class="at">conf.level =</span> .<span class="dv">95</span>,<span class="at">ci.type =</span> <span class="st">"bca"</span>,<span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb53-340"><a href="#cb53-340" aria-hidden="true" tabindex="-1"></a>control_skew_ses <span class="ot">&lt;-</span> (control_skew[<span class="dv">3</span>] <span class="sc">-</span> control_skew[<span class="dv">2</span>])<span class="sc">/</span><span class="fl">3.92</span></span>
<span id="cb53-341"><a href="#cb53-341" aria-hidden="true" tabindex="-1"></a>control_skew[<span class="dv">1</span>]<span class="sc">/</span>control_skew_ses</span>
<span id="cb53-342"><a href="#cb53-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-343"><a href="#cb53-343" aria-hidden="true" tabindex="-1"></a>control_kurt <span class="ot">&lt;-</span> DescTools<span class="sc">::</span><span class="fu">Kurt</span>(<span class="at">x=</span>control_group<span class="sc">$</span>Score,<span class="at">method =</span> <span class="dv">2</span>,<span class="at">conf.level =</span> .<span class="dv">95</span>,<span class="at">ci.type =</span> <span class="st">"bca"</span>,<span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb53-344"><a href="#cb53-344" aria-hidden="true" tabindex="-1"></a>control_kurt_ses <span class="ot">&lt;-</span> (control_kurt[<span class="dv">3</span>] <span class="sc">-</span> control_kurt[<span class="dv">2</span>])<span class="sc">/</span><span class="fl">3.92</span></span>
<span id="cb53-345"><a href="#cb53-345" aria-hidden="true" tabindex="-1"></a>control_kurt[<span class="dv">1</span>]<span class="sc">/</span>control_kurt_ses</span>
<span id="cb53-346"><a href="#cb53-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-347"><a href="#cb53-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-348"><a href="#cb53-348" aria-hidden="true" tabindex="-1"></a>**threat group**</span>
<span id="cb53-349"><a href="#cb53-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-352"><a href="#cb53-352" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-353"><a href="#cb53-353" aria-hidden="true" tabindex="-1"></a>threat_group <span class="ot">&lt;-</span> stereotype_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(namedGroup<span class="sc">==</span><span class="st">"Threat"</span>) </span>
<span id="cb53-354"><a href="#cb53-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-355"><a href="#cb53-355" aria-hidden="true" tabindex="-1"></a>threat_skew <span class="ot">&lt;-</span> DescTools<span class="sc">::</span><span class="fu">Skew</span>(<span class="at">x=</span>threat_group<span class="sc">$</span>Score,<span class="at">method =</span> <span class="dv">2</span>,<span class="at">conf.level =</span> .<span class="dv">95</span>,<span class="at">ci.type =</span> <span class="st">"bca"</span>,<span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb53-356"><a href="#cb53-356" aria-hidden="true" tabindex="-1"></a>threat_skew_ses <span class="ot">&lt;-</span> (threat_skew[<span class="dv">3</span>] <span class="sc">-</span> threat_skew[<span class="dv">2</span>])<span class="sc">/</span><span class="fl">3.92</span></span>
<span id="cb53-357"><a href="#cb53-357" aria-hidden="true" tabindex="-1"></a>threat_skew[<span class="dv">1</span>]<span class="sc">/</span>threat_skew_ses</span>
<span id="cb53-358"><a href="#cb53-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-359"><a href="#cb53-359" aria-hidden="true" tabindex="-1"></a>threat_kurt <span class="ot">&lt;-</span> DescTools<span class="sc">::</span><span class="fu">Kurt</span>(<span class="at">x=</span>threat_group<span class="sc">$</span>Score,<span class="at">method =</span> <span class="dv">2</span>,<span class="at">conf.level =</span> .<span class="dv">95</span>,<span class="at">ci.type =</span> <span class="st">"bca"</span>,<span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb53-360"><a href="#cb53-360" aria-hidden="true" tabindex="-1"></a>threat_kurt_ses <span class="ot">&lt;-</span> (threat_kurt[<span class="dv">3</span>] <span class="sc">-</span> threat_kurt[<span class="dv">2</span>])<span class="sc">/</span><span class="fl">3.92</span></span>
<span id="cb53-361"><a href="#cb53-361" aria-hidden="true" tabindex="-1"></a>threat_kurt[<span class="dv">1</span>]<span class="sc">/</span>threat_kurt_ses</span>
<span id="cb53-362"><a href="#cb53-362" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-363"><a href="#cb53-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-364"><a href="#cb53-364" aria-hidden="true" tabindex="-1"></a>This is a pain... can we make a function for this!!!!</span>
<span id="cb53-365"><a href="#cb53-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-366"><a href="#cb53-366" aria-hidden="true" tabindex="-1"></a>**QQ-Plot**</span>
<span id="cb53-367"><a href="#cb53-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-370"><a href="#cb53-370" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-371"><a href="#cb53-371" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(qqplotr)</span>
<span id="cb53-372"><a href="#cb53-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-373"><a href="#cb53-373" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stereotype_data, <span class="fu">aes</span>(<span class="at">sample=</span>Score, <span class="at">group=</span>namedGroup, <span class="at">color=</span>namedGroup)) <span class="sc">+</span> </span>
<span id="cb53-374"><a href="#cb53-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>()</span>
<span id="cb53-375"><a href="#cb53-375" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-376"><a href="#cb53-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-377"><a href="#cb53-377" aria-hidden="true" tabindex="-1"></a>*Homogeniety of Variance:*</span>
<span id="cb53-378"><a href="#cb53-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-379"><a href="#cb53-379" aria-hidden="true" tabindex="-1"></a>While the paired samples test doesn't make this assumption, the Independence samples test assumes the variability of scores for the two groups is roughly homogeneous.</span>
<span id="cb53-380"><a href="#cb53-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-381"><a href="#cb53-381" aria-hidden="true" tabindex="-1"></a>For a t-test this can be tested by using the <span class="in">`leveneTest()`</span> from the <span class="in">`car`</span> package:</span>
<span id="cb53-382"><a href="#cb53-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-385"><a href="#cb53-385" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-386"><a href="#cb53-386" aria-hidden="true" tabindex="-1"></a><span class="co"># using long-format enter as a formula:</span></span>
<span id="cb53-387"><a href="#cb53-387" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(Score<span class="sc">~</span>namedGroup, <span class="at">data=</span>stereotype_data, <span class="at">center=</span><span class="st">"mean"</span>)</span>
<span id="cb53-388"><a href="#cb53-388" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-389"><a href="#cb53-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-390"><a href="#cb53-390" aria-hidden="true" tabindex="-1"></a>You'll note above I elected to mean center my samples. This is consistent with typical practice although "median" centering may be more robust.</span>
<span id="cb53-391"><a href="#cb53-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-394"><a href="#cb53-394" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-395"><a href="#cb53-395" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(<span class="at">data=</span>stereotype_data, Score<span class="sc">~</span>namedGroup)</span>
<span id="cb53-396"><a href="#cb53-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-397"><a href="#cb53-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-398"><a href="#cb53-398" aria-hidden="true" tabindex="-1"></a>*T-test* Given that my obtained <span class="in">`Pr(&gt;F)`</span>, or p-value of Levene's F-test, is greater than .05, I may elect to assume that my variances are equal. However, if you remained skeptical, there are adjustments that you may make. This includes adjusting the degrees of freedom according to Welch-Satterthwaite recommendation (see below). Recall later on that we are looking at our obtained $t$ value with respect to the number of $df$. This adjustment effectively reduces the $df$ in turn making your test more conservative.</span>
<span id="cb53-399"><a href="#cb53-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-400"><a href="#cb53-400" aria-hidden="true" tabindex="-1"></a>The Levene's test failed to reject the null so I may proceed with my <span class="in">`t.test`</span> assuming variances are equal. Note that <span class="in">`paired=FALSE`</span> for independent sample tests:</span>
<span id="cb53-401"><a href="#cb53-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-404"><a href="#cb53-404" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-405"><a href="#cb53-405" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">data=</span>stereotype_data, Score<span class="sc">~</span>namedGroup, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal=</span>T)</span>
<span id="cb53-406"><a href="#cb53-406" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-407"><a href="#cb53-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-408"><a href="#cb53-408" aria-hidden="true" tabindex="-1"></a>This output gives us the $t$-value, $df$ and $p$-value. Based on this output I may conclude that the mean score in the Control group is significantly greater than the Threat group.</span>
<span id="cb53-409"><a href="#cb53-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-410"><a href="#cb53-410" aria-hidden="true" tabindex="-1"></a>Just as an example, let's set <span class="in">`var.equal`</span> to <span class="in">`FALSE`</span>:</span>
<span id="cb53-411"><a href="#cb53-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-414"><a href="#cb53-414" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-415"><a href="#cb53-415" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">data=</span>stereotype_data, Score<span class="sc">~</span>namedGroup, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal=</span>F)</span>
<span id="cb53-416"><a href="#cb53-416" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-417"><a href="#cb53-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-418"><a href="#cb53-418" aria-hidden="true" tabindex="-1"></a>Comparing the outputs you see that in this case <span class="in">`R`</span> has indicated that it has run the test with the Welsh correction. Note that this changes the $df$ and consequently the resulting $p$ value. That this change was negligible reinforces that the variances were very similar to one another. However in cases where they are not close to one another you may see dramatic changes in $df$.</span>
<span id="cb53-419"><a href="#cb53-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-420"><a href="#cb53-420" aria-hidden="true" tabindex="-1"></a>In <span class="in">`R`</span>, the <span class="in">`t.test()`</span> function sets <span class="in">`var.equal=FALSE`</span> by default. Why you ask? Well, you can make the argument that the variances are ALWAYS unequal, its only a matter of degree. Assuming variances are unequal makes your test more conservative, meaning that if the test suggests that you should reject the null, you can be slightly more confident that you are not committing Type I error. At the same time, it could be argued that setting your <span class="in">`var.equal=TRUE`</span> in this case (where the Levene test failed to reject the null) makes your test more powerful, and you should take advantage of that power to avoid Type II error.</span>
<span id="cb53-421"><a href="#cb53-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-422"><a href="#cb53-422" aria-hidden="true" tabindex="-1"></a><span class="fu">## Independent or Paired Sample?</span></span>
<span id="cb53-423"><a href="#cb53-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-424"><a href="#cb53-424" aria-hidden="true" tabindex="-1"></a>It is safe to assume that anytime that you are collecting data samples from the same person at two different points in time that you need to run a paired-samples test. However, it would not be safe to assume that if the samples are coming from different groups of people that you always run an independent samples test. Remember the important qualifier mentioned above: That there no reason to believe that any one participant in the first group is is more closely related to any single counterpart in the second group than the remaining of others. In our Independent test example we have no reason to assume this is the case, we assume that members of the Control and Threat groups were randomly selected. But what if we instead recruited brothers or twins? In this case, it may make sense to treat members of the two groups as paired; brothers have a shared history (education, socio-economic level, family dynamic, etc) that would make their scores more likely to be related to one another than by random chance.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Written by <a href="https://tehrandav.is">Tehran Davis</a> of PSYC 7014.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>