<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>tehrandav.is - The One-way ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating nav-fixed">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">tehrandav.is</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="https://tehrandav.is">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">The One-way ANOVA</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../walkthroughs.html" class="sidebar-item-text sidebar-link">PSYC 7014</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">TOPIC 1 INTRO to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_1-Rmarkdown_basics.html" class="sidebar-item-text sidebar-link">Rmarkdown Basics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_2-objects_assignment_functions.html" class="sidebar-item-text sidebar-link">Objects, assignment, and functions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_3-install_packages.html" class="sidebar-item-text sidebar-link">Installing and loading an <code>R</code> package</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_4-loading_data.html" class="sidebar-item-text sidebar-link">Loading in Data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week01/1_5-leveling-up.html" class="sidebar-item-text sidebar-link">Leveling-up</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">TOPIC 2: DESCRIPTIVE STATS and CENTRAL TENDENCY</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_1-structure_data.html" class="sidebar-item-text sidebar-link">The structure of your data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_2-central_tendency.html" class="sidebar-item-text sidebar-link">Measures of central tendency</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_3-summary_tables.html" class="sidebar-item-text sidebar-link">Creating summary tables</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week02/2_4-means_other_models.html" class="sidebar-item-text sidebar-link">Means and other models</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">TOPIC 3: DATA VISUALIZATION</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_1-basic_ggplot.html" class="sidebar-item-text sidebar-link">Basic ggplotting</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week03/3_2-more_adv_ggplot.html" class="sidebar-item-text sidebar-link">More advanced ggPlots</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">TOPIC 4: DISTRIBUTIONS and NHST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link">The normal distribution</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_2-building_intuitions_about_probability_and_nhst.html" class="sidebar-item-text sidebar-link">Building intuitions about probability and NHST</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_3-sampling_distributions_and_seeing_the_logic_of_nhst.html" class="sidebar-item-text sidebar-link">Sampling distributions and seeing the logic of NHST</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_4-more_examples.html" class="sidebar-item-text sidebar-link">More examples of distributions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week04/4_5-bias_variance.html" class="sidebar-item-text sidebar-link">Bias in sample variance estimates</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">TOPIC 5: CORRELATION AND REGRESSION</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_1-the_normal_distribution.html" class="sidebar-item-text sidebar-link">The normal distribution</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_2_correlations.html" class="sidebar-item-text sidebar-link">Correlations</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_3_regressions.html" class="sidebar-item-text sidebar-link">Regression, pt.&nbsp;1: Running the model</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_4_plotting.html" class="sidebar-item-text sidebar-link">Plotting regression data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_5_diagnostics.html" class="sidebar-item-text sidebar-link">Regression model diagnostics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week05/5_6_example_report.html" class="sidebar-item-text sidebar-link">Example Report</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">TOPIC 6: T-TESTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_1_t-test.html" class="sidebar-item-text sidebar-link">Testing differences in means / t-test</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_2_t-test-null-model.html" class="sidebar-item-text sidebar-link">Thinking about nothing (aka the null)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week06/6_3_t-test-lm.html" class="sidebar-item-text sidebar-link">t-test? It’s just a linear model</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">TOPIC 7: POWER &amp; EFFECT SIZES</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_1-effect_size.html" class="sidebar-item-text sidebar-link">Effect Size</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_2-power.html" class="sidebar-item-text sidebar-link">Power</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_3-power_es_sig_tests.html" class="sidebar-item-text sidebar-link">Power, Effect sizes, and Significance testing</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week07/7_4-simulating_power.html" class="sidebar-item-text sidebar-link">Simulating Power!!!</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">TOPIC 8: INTRO to ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_1-one-way-anova.html" class="sidebar-item-text sidebar-link active">The One-way ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week08/8_2-anova-regression.html" class="sidebar-item-text sidebar-link">ANOVA and Regression</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">TOPIC 9: ANOVA: CONTRASTS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_1-posthocs.html" class="sidebar-item-text sidebar-link">Multiple comparisons in One-way ANOVA, pt.&nbsp;1: post hoc tests</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week09/9_2-planned_contrasts.html" class="sidebar-item-text sidebar-link">Multiple comparisons in One-way ANOVA, pt.&nbsp;2: planned contrasts</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">TOPIC 10: ANOVA: FACTORIAL ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_1-main_effects.html" class="sidebar-item-text sidebar-link">Factorial ANOVA - The omnibus ANOVA and Main effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_2-factorial_w_post_hocs.html" class="sidebar-item-text sidebar-link">Factorial ANOVA - Post hoc analysis of Main effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week10/10_3-advanced_example_and_apa.html" class="sidebar-item-text sidebar-link">Template for Analysis &amp; APA Style</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">TOPIC 11: ANOVA + INTERACTIONS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week11/11_1-interactions.html" class="sidebar-item-text sidebar-link">Analysis of Variance: the Factorial ANOVA - Interactions &amp; Simple Effects ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week11/11_2-higher_order_anova.html" class="sidebar-item-text sidebar-link">Dealing with Higher Order Factorial ANOVA</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">TOPIC 12: WITHIN SUBJECTS / REPEATED MEASURES ANOVA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_1-afex_ANOVA.html" class="sidebar-item-text sidebar-link">afex is for ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_2-repeated_measures_anova.html" class="sidebar-item-text sidebar-link">Within Subjects / Repeated Measures ANOVA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_3-factorial_rma.html" class="sidebar-item-text sidebar-link">Factorial RM-ANOVA and simple effects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_4-sphericity.html" class="sidebar-item-text sidebar-link">Sphericity: Variances and Co-Variances</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week12/12_5-spss_rma.html" class="sidebar-item-text sidebar-link">Running a RM-ANOVA in SPSS</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">TOPIC 13: MIXED ANOVA (BS + WS)</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week13/13_1-mixed_effects_anova.html" class="sidebar-item-text sidebar-link">Mixed-effects ANOVA (BS + WS)</a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#anovas-for-comparing-means" id="toc-anovas-for-comparing-means" class="nav-link active" data-scroll-target="#anovas-for-comparing-means">ANOVAs for comparing means</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The data</a></li>
  <li>
<a href="#getting-the-data-in-order" id="toc-getting-the-data-in-order" class="nav-link" data-scroll-target="#getting-the-data-in-order">Getting the data in order</a>
  <ul class="collapse">
<li><a href="#the-importance-of-a-participant-id-column" id="toc-the-importance-of-a-participant-id-column" class="nav-link" data-scroll-target="#the-importance-of-a-participant-id-column">The importance of a participant ID column</a></li>
  <li><a href="#recoding-the-factors-if-number-coded" id="toc-recoding-the-factors-if-number-coded" class="nav-link" data-scroll-target="#recoding-the-factors-if-number-coded">Recoding the factors (if number coded)</a></li>
  <li><a href="#renaming-column-headers-optional" id="toc-renaming-column-headers-optional" class="nav-link" data-scroll-target="#renaming-column-headers-optional">Renaming column headers (optional)</a></li>
  <li><a href="#reordering-your-levels" id="toc-reordering-your-levels" class="nav-link" data-scroll-target="#reordering-your-levels">Reordering your levels</a></li>
  </ul>
</li>
  <li>
<a href="#assumptions-for-anova" id="toc-assumptions-for-anova" class="nav-link" data-scroll-target="#assumptions-for-anova">Assumptions for ANOVA</a>
  <ul class="collapse">
<li><a href="#checking-the-normality-assumption-option-1-raw-data-by-group" id="toc-checking-the-normality-assumption-option-1-raw-data-by-group" class="nav-link" data-scroll-target="#checking-the-normality-assumption-option-1-raw-data-by-group">Checking the normality assumption, OPTION 1 raw data by group</a></li>
  <li><a href="#checking-the-normality-assumption-option-2-the-better-way-look-at-the-residuals." id="toc-checking-the-normality-assumption-option-2-the-better-way-look-at-the-residuals." class="nav-link" data-scroll-target="#checking-the-normality-assumption-option-2-the-better-way-look-at-the-residuals.">Checking the normality assumption, OPTION 2, the better way: Look at the residuals.</a></li>
  <li><a href="#homogeneity-of-variance" id="toc-homogeneity-of-variance" class="nav-link" data-scroll-target="#homogeneity-of-variance">Homogeneity of Variance</a></li>
  <li><a href="#what-to-do-if-the-assumptions-are-violated" id="toc-what-to-do-if-the-assumptions-are-violated" class="nav-link" data-scroll-target="#what-to-do-if-the-assumptions-are-violated">What to do if the assumptions are violated?</a></li>
  </ul>
</li>
  <li><a href="#running-the-anova-in-r-using-aov-or-lm" id="toc-running-the-anova-in-r-using-aov-or-lm" class="nav-link" data-scroll-target="#running-the-anova-in-r-using-aov-or-lm">Running the ANOVA in R using <code>aov()</code> or <code>lm()</code></a></li>
  <li><a href="#plotting-your-data" id="toc-plotting-your-data" class="nav-link" data-scroll-target="#plotting-your-data">Plotting your data</a></li>
  <li><a href="#reporting-your-data-the-write-up" id="toc-reporting-your-data-the-write-up" class="nav-link" data-scroll-target="#reporting-your-data-the-write-up">Reporting your data / the write up</a></li>
  <li><a href="#what-the-omnibus-anova-tells-you" id="toc-what-the-omnibus-anova-tells-you" class="nav-link" data-scroll-target="#what-the-omnibus-anova-tells-you">What the omnibus ANOVA tells you</a></li>
  <li><a href="#running-an-anova-using-lm-its-a-regression-afterall" id="toc-running-an-anova-using-lm-its-a-regression-afterall" class="nav-link" data-scroll-target="#running-an-anova-using-lm-its-a-regression-afterall">Running an ANOVA using <code>lm()</code> (it’s a regression afterall)</a></li>
  <li>
<a href="#reporting-your-results." id="toc-reporting-your-results." class="nav-link" data-scroll-target="#reporting-your-results.">Reporting your results.</a>
  <ul class="collapse">
<li><a href="#reporting-just-the-anova" id="toc-reporting-just-the-anova" class="nav-link" data-scroll-target="#reporting-just-the-anova">Reporting just the ANOVA</a></li>
  <li><a href="#reporting-the-anova-lm-output" id="toc-reporting-the-anova-lm-output" class="nav-link" data-scroll-target="#reporting-the-anova-lm-output">Reporting the ANOVA, lm() output</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">The One-way ANOVA</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="anovas-for-comparing-means" class="level2"><h2 class="anchored" data-anchor-id="anovas-for-comparing-means">ANOVAs for comparing means</h2>
<p>This week we covered <strong>ANOVA</strong>. A major emphasis in the material (especially Winter’s optional text) is that ANOVA (much like many of the other tests that we cover in this course) is an extension of the general linear model. In many respects, ANOVA and regression are conceptually identical—whereas in linear regression our predictor variables are typically continuous (or, in some cases ordinal) we usually reserve the term ANOVA for instances when our predictors are discrete or nominal (although it really need not be). This would be the difference say in predicting weight as a function of height (linear regression) in contrast to weight as function of hometown (Dayton, Youngstown, Cleveland, Cincinnati). Given that the assigned readings (and the optional Winter text) do a wonderful job of explaining the underlying principles of ANOVA, I won’t spend too much time here rehashing what is already available there. Both the Flora text and the Winter text, especially does an excellent job of demonstrating how even though regression and ANOVA are often treated differently in terms of research focus (e.g., observation v. experimentation) and data focus (correlation/goodness of fit v. comparing means) they are indeed one and the same. Here, my goal is to reinforce this idea using examples in <code>R</code>, as well as providing a practical tutorial that will serve as our entry point into ANOVA.</p>
<p>We typically understand ANOVA as a method for allowing us to compare means from more than two samples. To see how this connects with what we have learned from regression lets use an example dataset. Before proceeding, this walk-through assumes that you have the following packages installed and loaded in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(car,</span>
<span id="cb1-2"><a href="#cb1-2"></a>               cowplot, </span>
<span id="cb1-3"><a href="#cb1-3"></a>               tidyverse,</span>
<span id="cb1-4"><a href="#cb1-4"></a>               psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="the-data" class="level2"><h2 class="anchored" data-anchor-id="the-data">The data</h2>
<p>To start, lets download Eysenck’s (1974) study on verbal recall and levels of processing. As described in Howell (2012):</p>
<blockquote class="blockquote">
<p>Craik and Lockhart (1972) proposed as a model of memory that the degree to which verbal material is remembered by the subject is a function of the degree to which it was processed when it was initially presented. Thus, for example, if you were trying to memorize a list of words, repeating a word to yourself (a low level of processing) would not lead to as good recall as thinking about the word and trying to form associations between that word and some other word. Eysenck (1974) was interested in testing this model and, more important, in looking to see whether it could help to explain reported differences between young and old subjects in their ability to recall verbal material…</p>
<p>Eysenck randomly assigned 50 subjects between the ages of 55 and 65 years to one of five groups—four incidental-learning groups and one intentional-learning group. (Incidental learning is learning in the absence of the expectation that the material will later need to be recalled.) The Counting group was asked to read through a list of words and simply count the number of letters in each word. This involved the lowest level of processing, because subjects did not need to deal with each word as anything more than a collection of letters. The Rhyming group was asked to read each word and think of a word that rhymed with it. This task involved considering the sound of each word, but not its meaning. The Adjective group had to process the words to the extent of giving an adjective that could reasonably be used to modify each word on the list. The Imagery group was instructed to try to form vivid images of each word. This was assumed to require the deepest level of processing of the four incidental conditions. None of these four groups were told that they would later be asked for recall of the items. Finally, the Intentional group was told to read through the list and to memorize the words for later recall. After subjects had gone through the list of 27 items three times, they were given a sheet of paper and asked to write down all of the words they could remember. If learning involves nothing more than being exposed to the material (the way most of us read a newspaper or, heaven forbid, a class assignment), then the five groups should have shown equal recall—after all, they all saw all of the words. If the level of processing of the material is important, then there should have been noticeable differences among the group means.</p>
</blockquote>
<p>We can download this <code>dataset</code> using the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Ex11-1.dat"</span>, </span>
<span id="cb2-2"><a href="#cb2-2"></a>                      <span class="at">delim =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 50 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
dbl (2): GROUP, RECALL

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">show</span>(dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 2
   GROUP RECALL
   &lt;dbl&gt;  &lt;dbl&gt;
 1     1      9
 2     1      8
 3     1      6
 4     1      8
 5     1     10
 6     1      4
 7     1      6
 8     1      5
 9     1      7
10     1      7
# ℹ 40 more rows</code></pre>
</div>
</div>
</section><section id="getting-the-data-in-order" class="level2"><h2 class="anchored" data-anchor-id="getting-the-data-in-order">Getting the data in order</h2>
<p>Although the focus for this course is conceptual and applied knowledge of statistics, I again want to be mindful of the practice of data analysis. That is, in the real world, you’ll be asked to do some <strong>data wrangling,</strong> or getting your data in the right format and containing the right information to properly proceed with analysis. When looking at this data, two important things jump out that we might want to address: (1) there is no column indicating participant ID. and (2) the data is numerically coded. A little bit about each of these points.</p>
<section id="the-importance-of-a-participant-id-column" class="level3"><h3 class="anchored" data-anchor-id="the-importance-of-a-participant-id-column">The importance of a participant ID column</h3>
<p>Depending on what statistical software you use, including a Participant ID column varies in its importance. For building statistical models in <code>R</code> that involve categorical data, including designs that that test within and across subjects making sure that you have Participant IDs coded is vitally important. Ideally this will already be done before you import your data, but on the case that it’s not you need to add a column specifying participant ID. How you do this will depend on what format your data is in (Wide v. Long) and whether you have a repeated-measures design (multiple measures from each participant).</p>
<p>** I grant that it might be useful to use you Excel ninja skills here and get everything in its right place before importing, but will assume that you want to stay in an <code>R</code> environment.</p>
<p>In this case, our data is in long format and we have a between subjects design. That is every line represents a single measure of a participant and every participant is represented only once. In this case we can just assign a unique number to each participant / row. In most cases this is a simple as assigning participant numbers {1,2,3…n}. An easy way to do this is to use the <code><a href="https://rdrr.io/r/base/seq.html">seq_along()</a></code> function. The <code><a href="https://rdrr.io/r/base/seq.html">seq_along()</a></code> function simply says to create numbers in sequence that match along a vector. In this case we can <code>seq_along</code> the <code>GROUP</code> column (vector).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">PartID =</span> <span class="fu">seq_along</span>(dataset<span class="sc">$</span>GROUP))</span>
<span id="cb6-2"><a href="#cb6-2"></a>dataset</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 3
   GROUP RECALL PartID
   &lt;dbl&gt;  &lt;dbl&gt;  &lt;int&gt;
 1     1      9      1
 2     1      8      2
 3     1      6      3
 4     1      8      4
 5     1     10      5
 6     1      4      6
 7     1      6      7
 8     1      5      8
 9     1      7      9
10     1      7     10
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>FWIW, if you have the same compulsion that I do and insist that your <code>PartID</code> column is first in your dataset this can be solved using <code>select</code>. Here, I’m saying put <code>PartID</code> first and then follow it with <code>everything()</code> else.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">select</span>(PartID, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>OK. That’s addressed. Now onto issue #2.</p>
</section><section id="recoding-the-factors-if-number-coded" class="level3"><h3 class="anchored" data-anchor-id="recoding-the-factors-if-number-coded">Recoding the factors (if number coded)</h3>
<p>As we can see the data is number coded. In this case,</p>
<ul>
<li><p>1 = ‘Counting’,</p></li>
<li><p>2 = ‘Rhyming’,</p></li>
<li><p>3 = ‘Adjective’,</p></li>
<li><p>4 = ‘Imagery’ and</p></li>
<li><p>5 = ‘Intentional’</p></li>
</ul>
<p>My advice for what to do if you get dummy coded data is to create a corresponding column in your data set that contains the factors in nominal (name) format.</p>
<p>Recall from previous weeks that we can use the <code>recode()</code> and <code>recode_factor()</code>functions to reassign the number variables. Here, we are recoding the levels of a factor, so the preferred function is <code>recode_factor()</code>. When we <code>recode_factor()</code> we have the added benefit of automatically <em>factorizing</em>, telling <code>R</code> to treat the IV as a factor. Let’s create a new column <code>dataset$GROUP_FACTOR</code> that contains this data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># assigning the appropriate names for the dummy codes</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">mutate</span>(<span class="at">GROUP_FACTOR =</span> dplyr<span class="sc">::</span><span class="fu">recode_factor</span>(GROUP, </span>
<span id="cb9-4"><a href="#cb9-4"></a>                                             <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Counting"</span>,</span>
<span id="cb9-5"><a href="#cb9-5"></a>                                             <span class="st">"2"</span><span class="ot">=</span><span class="st">"Rhyming"</span>,</span>
<span id="cb9-6"><a href="#cb9-6"></a>                                             <span class="st">"3"</span><span class="ot">=</span><span class="st">"Adjective"</span>,</span>
<span id="cb9-7"><a href="#cb9-7"></a>                                             <span class="st">"4"</span><span class="ot">=</span><span class="st">"Imagery"</span>,</span>
<span id="cb9-8"><a href="#cb9-8"></a>                                             <span class="st">"5"</span><span class="ot">=</span><span class="st">"Intentional"</span></span>
<span id="cb9-9"><a href="#cb9-9"></a>                                             )</span>
<span id="cb9-10"><a href="#cb9-10"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="renaming-column-headers-optional" class="level3"><h3 class="anchored" data-anchor-id="renaming-column-headers-optional">Renaming column headers (optional)</h3>
<p>And now, just to be clear, let’s rename the original <code>GROUP</code> to <code>GROUP_NUM</code>. This can be accomplished by using the <code><a href="https://dplyr.tidyverse.org/reference/rename.html">dplyr::rename()</a></code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># The template is rename(NEW_NAME = OLD_NAME)</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">GROUP_NUM =</span> GROUP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="https://www.datanovia.com/en/lessons/rename-data-frame-columns-in-r/#renaming-columns-with-dplyrrename">Check out this link</a> for info on how to rename multiple columns at once using <code><a href="https://rdrr.io/r/base/names.html">names()</a></code> or <code><a href="https://dplyr.tidyverse.org/reference/rename.html">dplyr::rename()</a></code> from the <code>tidyverse</code>.</p>
</section><section id="reordering-your-levels" class="level3"><h3 class="anchored" data-anchor-id="reordering-your-levels">Reordering your levels</h3>
<p>One important question you should ask before you look at your data is “what is your <strong>control</strong> (group, condition)”. Proper experimentation requires a proper control in order to properly isolate the influence of the manipulation (that’s a lot of propers). Here, the best candidates for our control group might either be “Counting” or “Intentional”, depending on how the original problem was approached. If the larger comparison involved “Intentional v. incidental” learning for recall, then the “Intentional” group serves best as your control. If the original question involved levels of processing, then “Counting”” (theoretically the lowest level of incidental processing) is best. Here I am assuming the latter (although I believe theoretically Eysenck originally was interested in the former).</p>
<p>I bring this up, as its typically best to ensure that your control is entered first into the ANOVA model. To check the order of your levels, you may simply:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>GROUP_FACTOR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Counting"    "Rhyming"     "Adjective"   "Imagery"     "Intentional"</code></pre>
</div>
</div>
<p>Here we see that “Counting” is first and will therefore be entered first into the model.</p>
<p>Assuming that we wanted to reorder the sequence, say to have <code>Intentional</code> as the control, then we might simply use <code>fct_relevel()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">mutate</span>(<span class="at">GROUP_FACTOR =</span> <span class="fu">fct_relevel</span>(GROUP_FACTOR, <span class="st">"Intentional"</span>))</span>
<span id="cb13-3"><a href="#cb13-3"></a>                              </span>
<span id="cb13-4"><a href="#cb13-4"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>GROUP_FACTOR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intentional" "Counting"    "Rhyming"     "Adjective"   "Imagery"    </code></pre>
</div>
</div>
<p>Note that with <code>fct_relevel()</code> whatever level(s) I list get moved to the front of the line. In this case I just bumped <code>Intentional</code> up while keeping the remaining levels ordered the same.</p>
<p>However, I liked the original order, so let’s change it back:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2"></a>  <span class="fu">mutate</span>(<span class="at">GROUP_FACTOR =</span> <span class="fu">fct_relevel</span>(GROUP_FACTOR, </span>
<span id="cb15-3"><a href="#cb15-3"></a>                                    <span class="st">"Counting"</span>, </span>
<span id="cb15-4"><a href="#cb15-4"></a>                                    <span class="st">"Rhyming"</span>, </span>
<span id="cb15-5"><a href="#cb15-5"></a>                                    <span class="st">"Adjective"</span>, </span>
<span id="cb15-6"><a href="#cb15-6"></a>                                    <span class="st">"Imagery"</span>, </span>
<span id="cb15-7"><a href="#cb15-7"></a>                                    <span class="st">"Intentional"</span>))</span>
<span id="cb15-8"><a href="#cb15-8"></a></span>
<span id="cb15-9"><a href="#cb15-9"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>GROUP_FACTOR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Counting"    "Rhyming"     "Adjective"   "Imagery"     "Intentional"</code></pre>
</div>
</div>
<p>That’s better. Why the order is important will be made clear later in this write up. For now, think back to our example in class of running a t-test using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. You may recall that the group level that was first entered into the model served as the <strong>model intercept</strong> where the second group level was expressed in terms of the slope of the line (beta). A similar output will be happening here.</p>
<p>So the data structure looks good.</p>
<p>One last little bit of ninja-ing. If you wanted to save a particular <code>R</code> object to be used later on you can use the <code>write_rds()</code> function (from <code>tidyverse</code>). I’m going to save <code>dataset</code> as I’ve cleaned it up so that I can use it in the next walkthrough.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">write_rds</span>(dataset,<span class="st">'clean_dataset.rds'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Onward to the analysis!!!!</p>
</section></section><section id="assumptions-for-anova" class="level2"><h2 class="anchored" data-anchor-id="assumptions-for-anova">Assumptions for ANOVA</h2>
<section id="checking-the-normality-assumption-option-1-raw-data-by-group" class="level3"><h3 class="anchored" data-anchor-id="checking-the-normality-assumption-option-1-raw-data-by-group">Checking the normality assumption, OPTION 1 raw data by group</h3>
<p>To check the distribution of outcomes in ANOVA, you have two options. The first would be to check the distribution of outcomes for EACH group/condition independently. In the case of the example <code>dataset</code> we could get info related to the skew and kurtosis of RECALL for each GROUP_FACTOR using <code>describeBy()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>psych<span class="sc">::</span><span class="fu">describeBy</span>(dataset,<span class="at">group =</span> <span class="st">"GROUP_FACTOR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Descriptive statistics by group 
GROUP_FACTOR: Counting
              vars  n mean   sd median trimmed  mad min max range skew kurtosis
PartID           1 10  5.5 3.03    5.5     5.5 3.71   1  10     9    0    -1.56
GROUP_NUM        2 10  1.0 0.00    1.0     1.0 0.00   1   1     0  NaN      NaN
RECALL           3 10  7.0 1.83    7.0     7.0 1.48   4  10     6    0    -1.22
GROUP_FACTOR*    4 10  1.0 0.00    1.0     1.0 0.00   1   1     0  NaN      NaN
                se
PartID        0.96
GROUP_NUM     0.00
RECALL        0.58
GROUP_FACTOR* 0.00
------------------------------------------------------------ 
GROUP_FACTOR: Rhyming
              vars  n mean   sd median trimmed  mad min max range skew kurtosis
PartID           1 10 15.5 3.03   15.5   15.50 3.71  11  20     9 0.00    -1.56
GROUP_NUM        2 10  2.0 0.00    2.0    2.00 0.00   2   2     0  NaN      NaN
RECALL           3 10  6.9 2.13    6.5    6.88 0.74   3  11     8 0.18    -0.40
GROUP_FACTOR*    4 10  2.0 0.00    2.0    2.00 0.00   2   2     0  NaN      NaN
                se
PartID        0.96
GROUP_NUM     0.00
RECALL        0.67
GROUP_FACTOR* 0.00
------------------------------------------------------------ 
GROUP_FACTOR: Adjective
              vars  n mean   sd median trimmed  mad min max range  skew
PartID           1 10 25.5 3.03   25.5   25.50 3.71  21  30     9  0.00
GROUP_NUM        2 10  3.0 0.00    3.0    3.00 0.00   3   3     0   NaN
RECALL           3 10 11.0 2.49   11.0   11.25 2.97   6  14     8 -0.66
GROUP_FACTOR*    4 10  3.0 0.00    3.0    3.00 0.00   3   3     0   NaN
              kurtosis   se
PartID           -1.56 0.96
GROUP_NUM          NaN 0.00
RECALL           -0.84 0.79
GROUP_FACTOR*      NaN 0.00
------------------------------------------------------------ 
GROUP_FACTOR: Imagery
              vars  n mean   sd median trimmed  mad min max range skew kurtosis
PartID           1 10 35.5 3.03   35.5   35.50 3.71  31  40     9 0.00    -1.56
GROUP_NUM        2 10  4.0 0.00    4.0    4.00 0.00   4   4     0  NaN      NaN
RECALL           3 10 13.4 4.50   11.5   12.75 1.48   9  23    14 0.99    -0.53
GROUP_FACTOR*    4 10  4.0 0.00    4.0    4.00 0.00   4   4     0  NaN      NaN
                se
PartID        0.96
GROUP_NUM     0.00
RECALL        1.42
GROUP_FACTOR* 0.00
------------------------------------------------------------ 
GROUP_FACTOR: Intentional
              vars  n mean   sd median trimmed  mad min max range skew kurtosis
PartID           1 10 45.5 3.03   45.5    45.5 3.71  41  50     9 0.00    -1.56
GROUP_NUM        2 10  5.0 0.00    5.0     5.0 0.00   5   5     0  NaN      NaN
RECALL           3 10 12.0 3.74   11.0    12.0 2.97   5  19    14 0.05    -0.47
GROUP_FACTOR*    4 10  5.0 0.00    5.0     5.0 0.00   5   5     0  NaN      NaN
                se
PartID        0.96
GROUP_NUM     0.00
RECALL        1.18
GROUP_FACTOR* 0.00</code></pre>
</div>
</div>
<p>If we wanted to perform for extensive methods like <code><a href="https://rdrr.io/r/graphics/hist.html">hist()</a></code>, <code>qqPlot()</code>, and <code><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test()</a></code>, in the past I had you filter be each level (group) and proceed. So for example for <code>Counting</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>countingGroup <span class="ot">&lt;-</span> <span class="fu">filter</span>(dataset,GROUP_FACTOR<span class="sc">==</span><span class="st">"Counting"</span>)</span>
<span id="cb20-2"><a href="#cb20-2"></a></span>
<span id="cb20-3"><a href="#cb20-3"></a><span class="fu">hist</span>(countingGroup<span class="sc">$</span>RECALL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">qqPlot</span>(countingGroup<span class="sc">$</span>RECALL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">shapiro.test</span>(countingGroup<span class="sc">$</span>RECALL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  countingGroup$RECALL
W = 0.98372, p-value = 0.9819</code></pre>
</div>
</div>
<p>In the past you would have to repeat this for each other level. An alternative to generate an output by each level of a factor is to use the <code><a href="https://rdrr.io/r/base/by.html">by()</a></code> function. For example to generate a sequence of <code>qqPlot</code>s (for the sake of space I’m not going to execute this code here, but try on your computer)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># by(dependent variable, grouping factor, name of function)</span></span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="fu">by</span>(dataset<span class="sc">$</span>RECALL,<span class="at">INDICES =</span> dataset<span class="sc">$</span>GROUP_FACTOR,qqPlot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can do the same with <code><a href="https://rdrr.io/r/graphics/hist.html">hist()</a></code> and <code><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test()</a></code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">by</span>(dataset<span class="sc">$</span>RECALL,<span class="at">INDICES =</span> dataset<span class="sc">$</span>GROUP_FACTOR,hist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-10-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-10-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>dataset$GROUP_FACTOR: Counting
$breaks
[1]  4  5  6  7  8  9 10

$counts
[1] 2 2 2 2 1 1

$density
[1] 0.2 0.2 0.2 0.2 0.1 0.1

$mids
[1] 4.5 5.5 6.5 7.5 8.5 9.5

$xname
[1] "dd[x, ]"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"
------------------------------------------------------------ 
dataset$GROUP_FACTOR: Rhyming
$breaks
[1]  2  4  6  8 10 12

$counts
[1] 1 4 3 1 1

$density
[1] 0.05 0.20 0.15 0.05 0.05

$mids
[1]  3  5  7  9 11

$xname
[1] "dd[x, ]"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"
------------------------------------------------------------ 
dataset$GROUP_FACTOR: Adjective
$breaks
[1]  6  8 10 12 14

$counts
[1] 2 1 3 4

$density
[1] 0.10 0.05 0.15 0.20

$mids
[1]  7  9 11 13

$xname
[1] "dd[x, ]"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"
------------------------------------------------------------ 
dataset$GROUP_FACTOR: Imagery
$breaks
[1]  8 10 12 14 16 18 20 22 24

$counts
[1] 2 5 0 1 0 1 0 1

$density
[1] 0.10 0.25 0.00 0.05 0.00 0.05 0.00 0.05

$mids
[1]  9 11 13 15 17 19 21 23

$xname
[1] "dd[x, ]"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"
------------------------------------------------------------ 
dataset$GROUP_FACTOR: Intentional
$breaks
[1]  4  6  8 10 12 14 16 18 20

$counts
[1] 1 0 2 3 2 1 0 1

$density
[1] 0.05 0.00 0.10 0.15 0.10 0.05 0.00 0.05

$mids
[1]  5  7  9 11 13 15 17 19

$xname
[1] "dd[x, ]"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">by</span>(dataset<span class="sc">$</span>RECALL,<span class="at">INDICES =</span> dataset<span class="sc">$</span>GROUP_FACTOR,shapiro.test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>dataset$GROUP_FACTOR: Counting

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.98372, p-value = 0.9819

------------------------------------------------------------ 
dataset$GROUP_FACTOR: Rhyming

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.93024, p-value = 0.4502

------------------------------------------------------------ 
dataset$GROUP_FACTOR: Adjective

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.90607, p-value = 0.2551

------------------------------------------------------------ 
dataset$GROUP_FACTOR: Imagery

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.81967, p-value = 0.02511

------------------------------------------------------------ 
dataset$GROUP_FACTOR: Intentional

    Shapiro-Wilk normality test

data:  dd[x, ]
W = 0.94339, p-value = 0.5913</code></pre>
</div>
</div>
<p>and even our custom standardized skew and kurtosis functions.</p>
</section><section id="checking-the-normality-assumption-option-2-the-better-way-look-at-the-residuals." class="level3"><h3 class="anchored" data-anchor-id="checking-the-normality-assumption-option-2-the-better-way-look-at-the-residuals.">Checking the normality assumption, OPTION 2, the better way: Look at the residuals.</h3>
<p>Although <code><a href="https://rdrr.io/r/base/by.html">by()</a></code> may or may not make life easier for you in this test case, things rapidly become more complicated when attempting to check normality by condition. For example if you’re running a 2×3×3 mixed effect ANOVA, you would need to run through 18 conditions!!! So what to do?!?!?!</p>
<p>A simpler alternative is to run you model and analyze your residuals. <a href="https://www.theanalysisfactor.com/checking-normality-anova-model/">This web link</a> does a nice and quick job of explaining the logic.</p>
<p>In this case we would run our ANOVA model using <code>lm</code> (see told you its all the same)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>dataset_aov <span class="ot">&lt;-</span> <span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Congrats, you’ve just run an ANOVA, but for now we aren’t interested in the results from the model. Remember from a few weeks back that many outputs have <code>attributes</code> that may be accessed. In this case, we want the models residuals. These can be accessed by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">resid</span>(dataset_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            1             2             3             4             5 
 2.000000e+00  1.000000e+00 -1.000000e+00  1.000000e+00  3.000000e+00 
            6             7             8             9            10 
-3.000000e+00 -1.000000e+00 -2.000000e+00  5.551115e-17  5.551115e-17 
           11            12            13            14            15 
 1.000000e-01  2.100000e+00 -9.000000e-01 -9.000000e-01 -9.000000e-01 
           16            17            18            19            20 
 4.100000e+00 -9.000000e-01 -3.900000e+00  1.100000e+00  1.000000e-01 
           21            22            23            24            25 
 5.551115e-17  2.000000e+00 -3.000000e+00 -5.000000e+00  3.000000e+00 
           26            27            28            29            30 
 5.551115e-17  2.000000e+00  2.000000e+00 -1.000000e+00  5.551115e-17 
           31            32            33            34            35 
-1.400000e+00 -2.400000e+00  2.600000e+00 -2.400000e+00 -4.400000e+00 
           36            37            38            39            40 
 9.600000e+00 -1.400000e+00 -3.400000e+00  5.600000e+00 -2.400000e+00 
           41            42            43            44            45 
-2.000000e+00  7.000000e+00  2.000000e+00 -7.000000e+00 -2.000000e+00 
           46            47            48            49            50 
-1.000000e+00  2.000000e+00  3.000000e+00 -1.000000e+00 -1.000000e+00 </code></pre>
</div>
</div>
<p>From here, we can simply take the residuals (as we did with regression) and submit them to our standard tests for normality. For example, testing skew, and kurtosis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">resid</span>(dataset_aov) <span class="sc">%&gt;%</span> <span class="fu">skew</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6388343</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="fu">resid</span>(dataset_aov) <span class="sc">%&gt;%</span> <span class="fu">kurtosi</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.221947</code></pre>
</div>
</div>
<p>or submit the entire model diagnostic plots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(performance)</span>
<span id="cb37-2"><a href="#cb37-2"></a></span>
<span id="cb37-3"><a href="#cb37-3"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(dataset_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>So, between OPTION 1 and OPTION 2, I’d recommend typically going with OPTION 2. Especially as your ANOVA designs become more complex.</strong></p>
<section id="walkthrough-problem-run-the-requisite-tests-for-normality-using-the-residuals-from-dataset_aov" class="level4"><h4 class="anchored" data-anchor-id="walkthrough-problem-run-the-requisite-tests-for-normality-using-the-residuals-from-dataset_aov">WALKTHROUGH PROBLEM: Run the requisite tests for normality using the <code>residuals</code> from <code>dataset_aov</code>
</h4>
</section></section><section id="homogeneity-of-variance" class="level3"><h3 class="anchored" data-anchor-id="homogeneity-of-variance">Homogeneity of Variance</h3>
<p>Another assumption of ANOVA is the homogeneity of variance between groups. An easy-way to get an eyeball test of this assumption is two perform a box plot of the data. Here I am performing this plot using <code>ggplot2</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span>dataset, <span class="fu">aes</span>(<span class="at">x=</span>GROUP_FACTOR,<span class="at">y=</span>RECALL)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Huge differences in the IQR regions may be a clue that the homogeneity assumption is violated. We can run more specific tests in <code>R</code> including the Levene Test and Fligner-Killeen Test of Homogeneity of Variances. You are familiar with the Levene Test from a few weeks ago. The Figner-Killeen Test is offered as an alternative if you are concerned with violations of the normality assumption.</p>
<p>As is typically the case <span class="math inline">\(p&lt;.05\)</span> indicates a violation of this assumption:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># Levene Test of Homogeneity of Variances</span></span>
<span id="cb39-2"><a href="#cb39-2"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  4  0.8932 0.4759
      45               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="co"># Fligner-Killeen Test of Homogeneity of Variances</span></span>
<span id="cb41-2"><a href="#cb41-2"></a><span class="fu">fligner.test</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fligner-Killeen test of homogeneity of variances

data:  RECALL by GROUP_FACTOR
Fligner-Killeen:med chi-squared = 1.9733, df = 4, p-value = 0.7407</code></pre>
</div>
</div>
</section><section id="what-to-do-if-the-assumptions-are-violated" class="level3"><h3 class="anchored" data-anchor-id="what-to-do-if-the-assumptions-are-violated">What to do if the assumptions are violated?</h3>
<p>If either assumption is violated, one option that you have is to transform you data. We’ve talked several times in class about the pros and cons of doing this, and there are several resources that provide examples of how this is done. Another option is to use a non-parametric test such as the Kruskal-Wallis Test if the data is not normal, or Welch’s ANOVA is the variances are not homogeneous. That said, one of reasons that ANOVA is so popular is that it has been demonstrated to be robust in the face of violated assumptions (as long as the sample sizes are equal). For example, in <em>Design and Analysis of Experiments</em> (1999, p.&nbsp;112) Dean &amp; Voss argue that the maximum group variance may be as high as 3× the minimum group variance without any issue. With this in mind, a question (gray area) before us is <em>how much</em> of a violation is there in the data? And if not so much, you may be fine just running an ANOVA regardless.</p>
</section></section><section id="running-the-anova-in-r-using-aov-or-lm" class="level2"><h2 class="anchored" data-anchor-id="running-the-anova-in-r-using-aov-or-lm">Running the ANOVA in R using <code>aov()</code> or <code>lm()</code>
</h2>
<p>There are many, many ways to build an ANOVA model in <code>R</code>. Throughout the semester we will be highlighting three: <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>, and using the <code>afex</code> package. This week we will concentrate on <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> which is the standard method, as well as the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> method that you have used before, just to reinforce that ANOVA and regression are one in the same. In fact, SPOILER ALERT, <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> is just a fancy wrapper for <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, AND FWIW I don’t really like using <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>. I only mention it here as if you go looking for how to run ANOVA in <code>R</code> online, many sites will say use <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>.</p>
<p>Like <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> from weeks past, <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> asks us to enter our dependent and independent variables into the model in the formula format <strong>DV ~ IVs</strong>. In this case, we only have a single IV, <code>GROUP_FACTOR</code>. Thus our model is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>aov.model <span class="ot">&lt;-</span> <span class="fu">aov</span>(RECALL<span class="sc">~</span>GROUP_FACTOR,<span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From here, an <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> of the model gives us our ANOVA table. Note that <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code> accomplished the same thing, though gives us a different format. The added benefit is that if we so choose, we can change how our Sums of Squares are calculated. This isn’t important for simple One-way ANOVA, but see the Field text, Jane Superbrain 11.1 for an explanation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="fu">anova</span>(aov.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: RECALL
             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
GROUP_FACTOR  4 351.52  87.880  9.0848 1.815e-05 ***
Residuals    45 435.30   9.673                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(aov.model, <span class="at">type=</span><span class="st">"3"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: RECALL
             Sum Sq Df F value    Pr(&gt;F)    
(Intercept)  490.00  1 50.6547 6.831e-09 ***
GROUP_FACTOR 351.52  4  9.0848 1.815e-05 ***
Residuals    435.30 45                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Also note that we can get <code>residuals</code> from the <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> output as well. In fact take a look at the object’s <code>$class</code>… see I told you, <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>!!!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="fu">resid</span>(aov.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            1             2             3             4             5 
 2.000000e+00  1.000000e+00 -1.000000e+00  1.000000e+00  3.000000e+00 
            6             7             8             9            10 
-3.000000e+00 -1.000000e+00 -2.000000e+00  5.551115e-17  5.551115e-17 
           11            12            13            14            15 
 1.000000e-01  2.100000e+00 -9.000000e-01 -9.000000e-01 -9.000000e-01 
           16            17            18            19            20 
 4.100000e+00 -9.000000e-01 -3.900000e+00  1.100000e+00  1.000000e-01 
           21            22            23            24            25 
 5.551115e-17  2.000000e+00 -3.000000e+00 -5.000000e+00  3.000000e+00 
           26            27            28            29            30 
 5.551115e-17  2.000000e+00  2.000000e+00 -1.000000e+00  5.551115e-17 
           31            32            33            34            35 
-1.400000e+00 -2.400000e+00  2.600000e+00 -2.400000e+00 -4.400000e+00 
           36            37            38            39            40 
 9.600000e+00 -1.400000e+00 -3.400000e+00  5.600000e+00 -2.400000e+00 
           41            42            43            44            45 
-2.000000e+00  7.000000e+00  2.000000e+00 -7.000000e+00 -2.000000e+00 
           46            47            48            49            50 
-1.000000e+00  2.000000e+00  3.000000e+00 -1.000000e+00 -1.000000e+00 </code></pre>
</div>
</div>
<p>Even better, a more comprehensive anova table can be obtained by submitting our <code>aov.model</code> to <code><a href="https://strengejacke.github.io/sjstats/reference/anova_stats.html">sjstats::anova_stats()</a></code>, which gives us our effect sizes as well! This function calculates eta-squared (<span class="math inline">\(\eta^2\)</span>), partial-eta-squared (<span class="math inline">\(\eta_p^2\)</span>), omega squared (<span class="math inline">\(\omega^2\)</span>) and partial omega-squared (<span class="math inline">\(\omega_p^2\)</span>) as well as Cohen’s <em>f</em>. Typically for One-Way ANOVA psychologists report eta-squared (<span class="math inline">\(\eta^2\)</span>), though there are arguments that omega squared (<span class="math inline">\(\omega^2\)</span>) may be the more preferred measure. Note that pander is for web formatting this page.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(pander)</span>
<span id="cb50-2"><a href="#cb50-2"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjstats)</span>
<span id="cb50-3"><a href="#cb50-3"></a>sjstats<span class="sc">::</span><span class="fu">anova_stats</span>(aov.model) <span class="sc">%&gt;%</span> <span class="fu">pander</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p>Quitting from lines 323-326 (8_1-one-way-anova.rmarkdown) Error: Package <code>pwr</code> needed for this function to work. Please install it.</p>
</div>
</div>
</section><section id="plotting-your-data" class="level2"><h2 class="anchored" data-anchor-id="plotting-your-data">Plotting your data</h2>
<p>For publication quality ANOVA plots, there are typically three acceptable plots used to convey your results, box plots, bar plots, and line plots. As the ANOVA become more complex, we tend towards using line plots (box plots and bar plots may become very busy in complex designs). Unless there are other compelling reasons we tend to plot the means (although note that box plots usually give you medians). Since you have already produced box plots and barplots, I’ll show examples of how to do a line plot.</p>
<p>To create a <strong>line plot</strong> with points at the means and error lines representing the 95% CI (known as a point range), we can use call that you are familiar with and a new geom <code>pointrange</code>. Whats nice about point range is that it allows you to create your points and the error bars all in a single line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a>ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span>dataset,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> GROUP_FACTOR, <span class="at">y =</span> RECALL)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, </span>
<span id="cb51-3"><a href="#cb51-3"></a>               <span class="at">size=</span><span class="dv">1</span>, </span>
<span id="cb51-4"><a href="#cb51-4"></a>               <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb51-5"><a href="#cb51-5"></a>               <span class="at">geom=</span><span class="st">"pointrange"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now to add the lines to this plot. For this you will need another <code>stat_summary()</code> line specifying that the vertices of the lines should be the means, <code>fun = mean</code> and a parameter that specifies how the lines should be grouped. Since we have a One-way ANOVA, <code>group=1</code>. When we built to more complex designs you may elect to <code>group=FACTOR_NAME</code>. Something like this is useful to say make some lines dashed and some lines solid according to levels on a factor. More on this in two weeks when we get to factorial ANOVA.</p>
<p>While we’re at it let’s fix those axes titles. We can use the functions <code>xlab()</code> and <code>ylab()</code> to do so.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="co"># this is from before, saving as object "p"</span></span>
<span id="cb52-2"><a href="#cb52-2"></a>p <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span>dataset,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> GROUP_FACTOR, <span class="at">y =</span> RECALL)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, </span>
<span id="cb52-4"><a href="#cb52-4"></a>               <span class="at">size=</span><span class="dv">1</span>, </span>
<span id="cb52-5"><a href="#cb52-5"></a>               <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb52-6"><a href="#cb52-6"></a>               <span class="at">geom=</span><span class="st">"pointrange"</span>) <span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7"></a>  <span class="co"># adding lines</span></span>
<span id="cb52-8"><a href="#cb52-8"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, </span>
<span id="cb52-9"><a href="#cb52-9"></a>               <span class="at">size =</span> <span class="dv">1</span>, </span>
<span id="cb52-10"><a href="#cb52-10"></a>               <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb52-11"><a href="#cb52-11"></a>               <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">group=</span><span class="dv">1</span>), </span>
<span id="cb52-12"><a href="#cb52-12"></a>               <span class="at">geom=</span><span class="st">"line"</span>) <span class="sc">+</span></span>
<span id="cb52-13"><a href="#cb52-13"></a>  <span class="co"># and fixing the axis titles:</span></span>
<span id="cb52-14"><a href="#cb52-14"></a>  <span class="fu">xlab</span>(<span class="st">"Group"</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">"Words recalled"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="fu">show</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Finally, for aesthetic reasons you may elect to expand the y-axis. For example to make the range of y-axis values (0,20):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a>p <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="8_1-one-way-anova_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That being said, this data probably lends itself to a bar plot. This is similar to how you built your bar plots from as when doing a t-test. As a matter of fact:</p>
<section id="walkthrough-problem-create-a-bar-plot-with-error-bars-for-our-dataset." class="level4"><h4 class="anchored" data-anchor-id="walkthrough-problem-create-a-bar-plot-with-error-bars-for-our-dataset.">WALKTHROUGH PROBLEM: Create a bar plot with error bars for our <code>dataset</code>.</h4>
</section></section><section id="reporting-your-data-the-write-up" class="level2"><h2 class="anchored" data-anchor-id="reporting-your-data-the-write-up">Reporting your data / the write up</h2>
<p>There are two components to reporting your omnibus ANOVA. First, You need to report your output as related to the test:</p>
<ul>
<li>
<strong>the F value</strong>,</li>
<li>
<strong>the degrees of freedom (between and within)</strong>,</li>
<li><strong>the p-value</strong></li>
<li>
<strong>effect size</strong>: typically with between-effects ANOVA we report eta squared, although note that Howell advocates for omega squared. Recall that submitting the model to <code><a href="https://strengejacke.github.io/sjstats/reference/anova_stats.html">sjstats::anova_stats()</a></code> gives you both.</li>
</ul>
<p>Second, as we typically focus on means with ANOVA, it is typically a good idea to report means and some report of of the distribution of each group (typically either standard deviation or standard error; although 95% CI may be useful in certain scenarios).</p>
<p>So for example reporting the <code>Rhyming</code> group:</p>
<ul>
<li>
<strong>M ± SD:</strong> 6.90 ± 2.13</li>
<li>
<strong>M ± SE:</strong> 6.90 ± 0.67</li>
</ul></section><section id="what-the-omnibus-anova-tells-you" class="level2"><h2 class="anchored" data-anchor-id="what-the-omnibus-anova-tells-you">What the omnibus ANOVA tells you</h2>
<p>While it may be useful to report the means, you need to be mindful of what the omnibus ANOVA tells you. Remember, that the the null hypothesis of the omnibus ANOVA is that “there are no differences between observed means”. Our significant result tells us that there <em>are</em> differences between our means, <strong>but does not tell us what those specific differences are</strong>. So while it may be useful to report general relationships, e.g., “Recall for people in the Intentional group tended to be greater than for the Counting group” you <strong>cannot</strong> say definitively “Recall was significantly greater for the Intentional Group”. Typically when you only have tested the omnibus ANOVA, you only speak in generalities (e.g., “Recall tended to increase with level of processing.”)</p>
<p><strong>Always be mindful that you don’t over interpret your data.</strong></p>
</section><section id="running-an-anova-using-lm-its-a-regression-afterall" class="level2"><h2 class="anchored" data-anchor-id="running-an-anova-using-lm-its-a-regression-afterall">Running an ANOVA using <code>lm()</code> (it’s a regression afterall)</h2>
<p>Now that we’ve got practical matters out of the way, I want to take some time to dig a little deeper into the connections between ANOVA this week and our work on correlations and regressions in the past.</p>
<p>As we’ve already mentioned (and spent time discussing in class) ANOVA is just an extension of the simple linear model that we covered last week, where ANOVA is used when our predictors are discrete. In fact <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> is simply a wrapper for the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function that we used last week. For example, let’s run our model using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and then pipe it into <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> or <code><a href="https://strengejacke.github.io/sjstats/reference/anova_stats.html">sjstats::anova_stats()</a></code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a>lm.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span>
<span id="cb56-2"><a href="#cb56-2"></a><span class="fu">anova</span>(lm.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: RECALL
             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
GROUP_FACTOR  4 351.52  87.880  9.0848 1.815e-05 ***
Residuals    45 435.30   9.673                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a>sjstats<span class="sc">::</span><span class="fu">anova_stats</span>(lm.model) <span class="sc">%&gt;%</span> <span class="fu">pander</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p>Quitting from lines 411-414 (8_1-one-way-anova.rmarkdown) Error: Package <code>pwr</code> needed for this function to work. Please install it.</p>
</div>
</div>
<p>All <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> does is take an <code>lm</code> object and produce an ANOVA table from the results. If we were simply to look at the <code>lm() model</code> we see that it gives us the info in our ANOVA table at the end of the summary, including the <code>F-statistic</code> (9.085), the <code>degrees of freedom</code> (4 and 45) and the <code>p-value</code> (1.815e-05):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = RECALL ~ GROUP_FACTOR, data = dataset)

Residuals:
   Min     1Q Median     3Q    Max 
 -7.00  -1.85  -0.45   2.00   9.60 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               7.0000     0.9835   7.117 6.83e-09 ***
GROUP_FACTORRhyming      -0.1000     1.3909  -0.072 0.943004    
GROUP_FACTORAdjective     4.0000     1.3909   2.876 0.006138 ** 
GROUP_FACTORImagery       6.4000     1.3909   4.601 3.43e-05 ***
GROUP_FACTORIntentional   5.0000     1.3909   3.595 0.000802 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.11 on 45 degrees of freedom
Multiple R-squared:  0.4468,    Adjusted R-squared:  0.3976 
F-statistic: 9.085 on 4 and 45 DF,  p-value: 1.815e-05</code></pre>
</div>
</div>
<p>Taking a look at this output, we see that the <code>lm() model</code> also gives us a lot of other additional useful info. For example the <span class="math inline">\(R^2\)</span> of the model may be understood as the effect size of the ANOVA. However, when we report it for One-Way ANOVA we express it as… dun, dun, dunnnn… <em>eta-squared</em>!!, or <span class="math inline">\(\eta^2\)</span>.</p>
<p>One more time with feeling, <strong>for simple oneway ANOVA,</strong> <span class="math inline">\(R^2\)</span> <strong>and</strong> <span class="math inline">\(\eta^2\)</span> <strong>are the same damn thing!!</strong></p>
<p>Zooming in on the coefficients:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                        Estimate Std. Error     t value     Pr(&gt;|t|)
(Intercept)                  7.0  0.9835311  7.11721300 6.830993e-09
GROUP_FACTORRhyming         -0.1  1.3909230 -0.07189471 9.430043e-01
GROUP_FACTORAdjective        4.0  1.3909230  2.87578833 6.137702e-03
GROUP_FACTORImagery          6.4  1.3909230  4.60126133 3.425167e-05
GROUP_FACTORIntentional      5.0  1.3909230  3.59473541 8.019114e-04</code></pre>
</div>
</div>
<p>We see information about the means of each group relative to the <code>(Intercept)</code>. <em>This is why I stressed earlier that it may be useful to rearrange the order of your levels such that <code>R</code> enters your control group into the model first</em>. In this case, the first predictor entered is assigned to the <code>(Intercept)</code>. The remaining predictors in the model are then presented relative to the first. Since we entered “Counting” first, the estimate of the <code>(Intercept)</code> represents its mean. The means for each remaining group are the sum of its estimate coefficient and the <code>(Intercept)</code>. So for example the mean of the Rhyming group is <span class="math inline">\((-0.1)+(7.0)=6.9\)</span>.</p>
<p>The coefficients section also gives us one other useful bit of information, the <span class="math inline">\(t\)</span>-values of the estimate. As we learned a few weeks ago, for a simple regression the beta coefficient gives us information about the slope of the regression line and the corresponding <span class="math inline">\(t\)</span>-value is a test of the null <span class="math inline">\(beta=0\)</span>. So for a simple regression this tells us if our slope is significantly different from 0.</p>
<p>A similar logic applies to the ANOVA model. As I mentioned above, deriving the means of each level of our IV is a matter of summing the (Intercept) and the beta estimate for that level. It should be apparent, then, that the beta estimates here represent the slope of a line that between the intercept and the mean of the level (where the distance between the predictor and coefficient is treated as a unit 1). Therefore, a significant <span class="math inline">\(t\)</span>-value for beta tells us that the slope between the two means is significant, or that those two means are significantly different from one another.</p>
<p>Keep in mind the only comparisons that are being made here are between the individual levels of our IV and the control (Intercept). So while this output allows us to make a claim about the difference between the means of the Counting (Intercept) group compared to each of the other groups, it <strong>does not</strong> allow us to make a claim about differences between our other levels. For example no information about a statistical test of differences between the Rhyming and Imagery groups is conveyed here. However, assuming you are interested in deviations from your control, you can get info here quickly. There is a caveat here, in that our alpha criterion will need to be adjusted to be more conservative than <code>.05.</code> More on this next week.</p>
</section><section id="reporting-your-results." class="level2"><h2 class="anchored" data-anchor-id="reporting-your-results.">Reporting your results.</h2>
<section id="reporting-just-the-anova" class="level3"><h3 class="anchored" data-anchor-id="reporting-just-the-anova">Reporting just the ANOVA</h3>
<p>For this week’s assignment, you are going to be asked to simply report the ANOVA. In future weeks you will see that simply reporting the ANOVA is not the end of your analysis, but only the beginning of additional, necessary follow-ups. But that is for next week, for now let’s take a look at what one might expect to be reported in an ANOVA write-up.</p>
<p>Given our example:</p>
<ul>
<li>words RECALL is our dependent measure</li>
<li>GROUP_FACTOR is our independent variable, with five levels (or groups).</li>
</ul>
<p>Using sjstats to generate an ANOVA table (pander makes it pretty for this web page:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>sjstats<span class="sc">::</span><span class="fu">anova_stats</span>(aov.model) <span class="sc">%&gt;%</span> <span class="fu">pander</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p>Quitting from lines 461-462 (8_1-one-way-anova.rmarkdown) Error: Package <code>pwr</code> needed for this function to work. Please install it.</p>
</div>
</div>
<p>From this table, we need our:</p>
<ul>
<li>
<strong>df</strong>: 4 and 45</li>
<li>
<strong>F-statistic</strong>: 9.085</li>
<li>
<strong>p.value</strong>: even though it says zero, its “&lt;.001”</li>
<li>
<strong>etasq</strong>: .447; the symbol for etasq is <span class="math inline">\(\eta^2\)</span>
</li>
</ul>
<p>Taking all of this info, and plugging into a write-up template (inserted points in bold):</p>
<p>“We hypothesized that different types of memorization strategies would result in different levels of memorization between our <strong>five groups</strong>, as measured by the <strong>number of words recalled</strong>. To test this hypothesis we conducted a One-way Analysis of Variance. Our analysis revealed a significant effect for <strong>Groups</strong>, <em>F</em>(4, 45) = 9.08, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .45; see Figure 1.”</p>
<p>For now, this is all you can say with only running a One-way ANOVA using this method, and that’s all I would want for the homework for this week.</p>
</section><section id="reporting-the-anova-lm-output" class="level3"><h3 class="anchored" data-anchor-id="reporting-the-anova-lm-output">Reporting the ANOVA, lm() output</h3>
<p>Let’s revisit the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> output. Recall that the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> method gives us the added benefit of comparing each level of the <code>GROUP_FACTOR</code> to the control level. This is what’s known as treatment contrasts (see Winter, Chapter 7). In this case, our control level is <code>Counting</code> and every other level (group) is compared against <code>Counting</code> and captured in the resulting beta coefficients:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a>aov_model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data =</span> dataset)</span>
<span id="cb63-2"><a href="#cb63-2"></a><span class="fu">summary</span>(aov_model_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = RECALL ~ GROUP_FACTOR, data = dataset)

Residuals:
   Min     1Q Median     3Q    Max 
 -7.00  -1.85  -0.45   2.00   9.60 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               7.0000     0.9835   7.117 6.83e-09 ***
GROUP_FACTORRhyming      -0.1000     1.3909  -0.072 0.943004    
GROUP_FACTORAdjective     4.0000     1.3909   2.876 0.006138 ** 
GROUP_FACTORImagery       6.4000     1.3909   4.601 3.43e-05 ***
GROUP_FACTORIntentional   5.0000     1.3909   3.595 0.000802 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.11 on 45 degrees of freedom
Multiple R-squared:  0.4468,    Adjusted R-squared:  0.3976 
F-statistic: 9.085 on 4 and 45 DF,  p-value: 1.815e-05</code></pre>
</div>
</div>
<p>From this summary output we would not only extract our <code>F-statistic</code>, <code>df</code>, <code>p-value</code> and <code>R-squared</code> (remember that <span class="math inline">\(R^2\)</span> is <span class="math inline">\(\eta^2\)</span>) as we do for the previous write-up, but now we can talk about differences between the other levels and <code>Counting</code> as expressed as a <code>t</code> value (we are running t-tests). We then combine this info with info related to the means and standard errors (note that I got the means and ses by creating a summary <code>tibble():</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1"></a>dataset <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2"></a>  <span class="fu">group_by</span>(GROUP_FACTOR) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(RECALL) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">2</span>),</span>
<span id="cb65-4"><a href="#cb65-4"></a>            <span class="at">se =</span> <span class="fu">sd</span>(RECALL)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()) <span class="co"># ses = sd / sqrt number of participants</span></span>
<span id="cb65-5"><a href="#cb65-5"></a>            ) <span class="sc">%&gt;%</span> </span>
<span id="cb65-6"><a href="#cb65-6"></a>  <span class="co"># this bit of code does some rounding (optional)</span></span>
<span id="cb65-7"><a href="#cb65-7"></a>  <span class="fu">mutate_if</span>(is.numeric,</span>
<span id="cb65-8"><a href="#cb65-8"></a>            round,</span>
<span id="cb65-9"><a href="#cb65-9"></a>            <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  GROUP_FACTOR  mean    se
  &lt;fct&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Counting       7    0.58
2 Rhyming        6.9  0.67
3 Adjective     11    0.79
4 Imagery       13.4  1.42
5 Intentional   12    1.18</code></pre>
</div>
</div>
<p>Putting all of this info together, we might say:</p>
<blockquote class="blockquote">
<p>“We hypothesized that different types of memorization strategies would result in different levels of memorization between our <strong>five groups</strong>, as measured by the <strong>number of words recalled</strong>. To test this hypothesis we conducted a One-way Analysis of Variance. Our analysis revealed a significant effect for <strong>Groups</strong>, <em>F</em>(4, 45) = 9.08, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .45. As can be seen in Figure 1, we found that the average number of words recalled for the Adjective (<span class="math inline">\(M\)</span> = 11.0, SE = 0.79; <span class="math inline">\(t\)</span>(45) = 2.88), Imagery (<span class="math inline">\(M\)</span> = 13.4, SE = 1.42; <span class="math inline">\(t\)</span>(45) = 4.60), and Intentional (<span class="math inline">\(M\)</span> = 12.0, SE = 1.18; <span class="math inline">\(t\)</span>(45) = 3.60) memorization groups were all greater than the Counting group (<span class="math inline">\(M\)</span> = 7.0, SE = 0.58); <em>ps</em> &lt; .01”.</p>
</blockquote>
<ul>
<li>note that I find it acceptable to lump the p-values together in this manner when doing multiple comparisons, as we are doing here.</li>
</ul>
<p>In both cases BE SURE TO PRODUCE A CAMERA READY FIGURE and REFER TO IT IN THE TEXT!!!</p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb67" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb67-1"><a href="#cb67-1"></a><span class="co">---</span></span>
<span id="cb67-2"><a href="#cb67-2"></a><span class="an">title:</span><span class="co"> "The One-way ANOVA"</span></span>
<span id="cb67-3"><a href="#cb67-3"></a><span class="co">---</span></span>
<span id="cb67-4"><a href="#cb67-4"></a></span>
<span id="cb67-5"><a href="#cb67-5"></a><span class="fu">## ANOVAs for comparing means</span></span>
<span id="cb67-6"><a href="#cb67-6"></a></span>
<span id="cb67-7"><a href="#cb67-7"></a>This week we covered **ANOVA**. A major emphasis in the material (especially Winter's optional text) is that ANOVA (much like many of the other tests that we cover in this course) is an extension of the general linear model. In many respects, ANOVA and regression are conceptually identical---whereas in linear regression our predictor variables are typically continuous (or, in some cases ordinal) we usually reserve the term ANOVA for instances when our predictors are discrete or nominal (although it really need not be). This would be the difference say in predicting weight as a function of height (linear regression) in contrast to weight as function of hometown (Dayton, Youngstown, Cleveland, Cincinnati). Given that the assigned readings (and the optional Winter text) do a wonderful job of explaining the underlying principles of ANOVA, I won't spend too much time here rehashing what is already available there. Both the Flora text and the Winter text, especially does an excellent job of demonstrating how even though regression and ANOVA are often treated differently in terms of research focus (e.g., observation v. experimentation) and data focus (correlation/goodness of fit v. comparing means) they are indeed one and the same. Here, my goal is to reinforce this idea using examples in <span class="in">`R`</span>, as well as providing a practical tutorial that will serve as our entry point into ANOVA.</span>
<span id="cb67-8"><a href="#cb67-8"></a></span>
<span id="cb67-9"><a href="#cb67-9"></a>We typically understand ANOVA as a method for allowing us to compare means from more than two samples. To see how this connects with what we have learned from regression lets use an example dataset. Before proceeding, this walk-through assumes that you have the following packages installed and loaded in R:</span>
<span id="cb67-10"><a href="#cb67-10"></a></span>
<span id="cb67-11"><a href="#cb67-11"></a><span class="in">```{r installing packages, warning = FALSE, message=FALSE}</span></span>
<span id="cb67-12"><a href="#cb67-12"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(car,</span>
<span id="cb67-13"><a href="#cb67-13"></a>               cowplot, </span>
<span id="cb67-14"><a href="#cb67-14"></a>               tidyverse,</span>
<span id="cb67-15"><a href="#cb67-15"></a>               psych)</span>
<span id="cb67-16"><a href="#cb67-16"></a><span class="in">```</span></span>
<span id="cb67-17"><a href="#cb67-17"></a></span>
<span id="cb67-18"><a href="#cb67-18"></a><span class="fu">## The data</span></span>
<span id="cb67-19"><a href="#cb67-19"></a></span>
<span id="cb67-20"><a href="#cb67-20"></a>To start, lets download Eysenck's (1974) study on verbal recall and levels of processing. As described in Howell (2012):</span>
<span id="cb67-21"><a href="#cb67-21"></a></span>
<span id="cb67-22"><a href="#cb67-22"></a><span class="at">&gt; Craik and Lockhart (1972) proposed as a model of memory that the degree to which verbal material is remembered by the subject is a function of the degree to which it was processed when it was initially presented. Thus, for example, if you were trying to memorize a list of words, repeating a word to yourself (a low level of processing) would not lead to as good recall as thinking about the word and trying to form associations between that word and some other word. Eysenck (1974) was interested in testing this model and, more important, in looking to see whether it could help to explain reported differences between young and old subjects in their ability to recall verbal material...</span></span>
<span id="cb67-23"><a href="#cb67-23"></a><span class="at">&gt;</span></span>
<span id="cb67-24"><a href="#cb67-24"></a><span class="at">&gt; Eysenck randomly assigned 50 subjects between the ages of 55 and 65 years to one of five groups---four incidental-learning groups and one intentional-learning group. (Incidental learning is learning in the absence of the expectation that the material will later need to be recalled.) The Counting group was asked to read through a list of words and simply count the number of letters in each word. This involved the lowest level of processing, because subjects did not need to deal with each word as anything more than a collection of letters. The Rhyming group was asked to read each word and think of a word that rhymed with it. This task involved considering the sound of each word, but not its meaning. The Adjective group had to process the words to the extent of giving an adjective that could reasonably be used to modify each word on the list. The Imagery group was instructed to try to form vivid images of each word. This was assumed to require the deepest level of processing of the four incidental conditions. None of these four groups were told that they would later be asked for recall of the items. Finally, the Intentional group was told to read through the list and to memorize the words for later recall. After subjects had gone through the list of 27 items three times, they were given a sheet of paper and asked to write down all of the words they could remember. If learning involves nothing more than being exposed to the material (the way most of us read a newspaper or, heaven forbid, a class assignment), then the five groups should have shown equal recall---after all, they all saw all of the words. If the level of processing of the material is important, then there should have been noticeable differences among the group means.</span></span>
<span id="cb67-25"><a href="#cb67-25"></a></span>
<span id="cb67-26"><a href="#cb67-26"></a>We can download this <span class="in">`dataset`</span> using the following code:</span>
<span id="cb67-27"><a href="#cb67-27"></a></span>
<span id="cb67-28"><a href="#cb67-28"></a><span class="in">```{r downloading dataset}</span></span>
<span id="cb67-29"><a href="#cb67-29"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"https://www.uvm.edu/~statdhtx/methods8/DataFiles/Ex11-1.dat"</span>, </span>
<span id="cb67-30"><a href="#cb67-30"></a>                      <span class="at">delim =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb67-31"><a href="#cb67-31"></a></span>
<span id="cb67-32"><a href="#cb67-32"></a><span class="fu">show</span>(dataset)</span>
<span id="cb67-33"><a href="#cb67-33"></a><span class="in">```</span></span>
<span id="cb67-34"><a href="#cb67-34"></a></span>
<span id="cb67-35"><a href="#cb67-35"></a><span class="fu">## Getting the data in order</span></span>
<span id="cb67-36"><a href="#cb67-36"></a></span>
<span id="cb67-37"><a href="#cb67-37"></a>Although the focus for this course is conceptual and applied knowledge of statistics, I again want to be mindful of the practice of data analysis. That is, in the real world, you'll be asked to do some **data wrangling,** or getting your data in the right format and containing the right information to properly proceed with analysis. When looking at this data, two important things jump out that we might want to address: (1) there is no column indicating participant ID. and (2) the data is numerically coded. A little bit about each of these points.</span>
<span id="cb67-38"><a href="#cb67-38"></a></span>
<span id="cb67-39"><a href="#cb67-39"></a><span class="fu">### The importance of a participant ID column</span></span>
<span id="cb67-40"><a href="#cb67-40"></a></span>
<span id="cb67-41"><a href="#cb67-41"></a>Depending on what statistical software you use, including a Participant ID column varies in its importance. For building statistical models in <span class="in">`R`</span> that involve categorical data, including designs that that test within and across subjects making sure that you have Participant IDs coded is vitally important. Ideally this will already be done before you import your data, but on the case that it's not you need to add a column specifying participant ID. How you do this will depend on what format your data is in (Wide v. Long) and whether you have a repeated-measures design (multiple measures from each participant).</span>
<span id="cb67-42"><a href="#cb67-42"></a></span>
<span id="cb67-43"><a href="#cb67-43"></a><span class="sc">\*\*</span> I grant that it might be useful to use you Excel ninja skills here and get everything in its right place before importing, but will assume that you want to stay in an <span class="in">`R`</span> environment.</span>
<span id="cb67-44"><a href="#cb67-44"></a></span>
<span id="cb67-45"><a href="#cb67-45"></a>In this case, our data is in long format and we have a between subjects design. That is every line represents a single measure of a participant and every participant is represented only once. In this case we can just assign a unique number to each participant / row. In most cases this is a simple as assigning participant numbers {1,2,3...n}. An easy way to do this is to use the <span class="in">`seq_along()`</span> function. The <span class="in">`seq_along()`</span> function simply says to create numbers in sequence that match along a vector. In this case we can <span class="in">`seq_along`</span> the <span class="in">`GROUP`</span> column (vector).</span>
<span id="cb67-46"><a href="#cb67-46"></a></span>
<span id="cb67-49"><a href="#cb67-49"></a><span class="in">```{r}</span></span>
<span id="cb67-50"><a href="#cb67-50"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">PartID =</span> <span class="fu">seq_along</span>(dataset<span class="sc">$</span>GROUP))</span>
<span id="cb67-51"><a href="#cb67-51"></a>dataset</span>
<span id="cb67-52"><a href="#cb67-52"></a><span class="in">```</span></span>
<span id="cb67-53"><a href="#cb67-53"></a></span>
<span id="cb67-54"><a href="#cb67-54"></a>FWIW, if you have the same compulsion that I do and insist that your <span class="in">`PartID`</span> column is first in your dataset this can be solved using <span class="in">`select`</span>. Here, I'm saying put <span class="in">`PartID`</span> first and then follow it with <span class="in">`everything()`</span> else.</span>
<span id="cb67-55"><a href="#cb67-55"></a></span>
<span id="cb67-58"><a href="#cb67-58"></a><span class="in">```{r}</span></span>
<span id="cb67-59"><a href="#cb67-59"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">select</span>(PartID, <span class="fu">everything</span>())</span>
<span id="cb67-60"><a href="#cb67-60"></a><span class="in">```</span></span>
<span id="cb67-61"><a href="#cb67-61"></a></span>
<span id="cb67-62"><a href="#cb67-62"></a>OK. That's addressed. Now onto issue #2.</span>
<span id="cb67-63"><a href="#cb67-63"></a></span>
<span id="cb67-64"><a href="#cb67-64"></a><span class="fu">### Recoding the factors (if number coded)</span></span>
<span id="cb67-65"><a href="#cb67-65"></a></span>
<span id="cb67-66"><a href="#cb67-66"></a>As we can see the data is number coded. In this case,</span>
<span id="cb67-67"><a href="#cb67-67"></a></span>
<span id="cb67-68"><a href="#cb67-68"></a><span class="ss">-   </span>1 = 'Counting',</span>
<span id="cb67-69"><a href="#cb67-69"></a></span>
<span id="cb67-70"><a href="#cb67-70"></a><span class="ss">-   </span>2 = 'Rhyming',</span>
<span id="cb67-71"><a href="#cb67-71"></a></span>
<span id="cb67-72"><a href="#cb67-72"></a><span class="ss">-   </span>3 = 'Adjective',</span>
<span id="cb67-73"><a href="#cb67-73"></a></span>
<span id="cb67-74"><a href="#cb67-74"></a><span class="ss">-   </span>4 = 'Imagery' and</span>
<span id="cb67-75"><a href="#cb67-75"></a></span>
<span id="cb67-76"><a href="#cb67-76"></a><span class="ss">-   </span>5 = 'Intentional'</span>
<span id="cb67-77"><a href="#cb67-77"></a></span>
<span id="cb67-78"><a href="#cb67-78"></a>My advice for what to do if you get dummy coded data is to create a corresponding column in your data set that contains the factors in nominal (name) format.</span>
<span id="cb67-79"><a href="#cb67-79"></a></span>
<span id="cb67-80"><a href="#cb67-80"></a>Recall from previous weeks that we can use the <span class="in">`recode()`</span> and <span class="in">`recode_factor()`</span>functions to reassign the number variables. Here, we are recoding the levels of a factor, so the preferred function is <span class="in">`recode_factor()`</span>. When we <span class="in">`recode_factor()`</span> we have the added benefit of automatically *factorizing*, telling <span class="in">`R`</span> to treat the IV as a factor. Let's create a new column <span class="in">`dataset$GROUP_FACTOR`</span> that contains this data:</span>
<span id="cb67-81"><a href="#cb67-81"></a></span>
<span id="cb67-82"><a href="#cb67-82"></a><span class="in">```{r renaming dummy codes}</span></span>
<span id="cb67-83"><a href="#cb67-83"></a><span class="co"># assigning the appropriate names for the dummy codes</span></span>
<span id="cb67-84"><a href="#cb67-84"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> </span>
<span id="cb67-85"><a href="#cb67-85"></a>  <span class="fu">mutate</span>(<span class="at">GROUP_FACTOR =</span> dplyr<span class="sc">::</span><span class="fu">recode_factor</span>(GROUP, </span>
<span id="cb67-86"><a href="#cb67-86"></a>                                             <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Counting"</span>,</span>
<span id="cb67-87"><a href="#cb67-87"></a>                                             <span class="st">"2"</span><span class="ot">=</span><span class="st">"Rhyming"</span>,</span>
<span id="cb67-88"><a href="#cb67-88"></a>                                             <span class="st">"3"</span><span class="ot">=</span><span class="st">"Adjective"</span>,</span>
<span id="cb67-89"><a href="#cb67-89"></a>                                             <span class="st">"4"</span><span class="ot">=</span><span class="st">"Imagery"</span>,</span>
<span id="cb67-90"><a href="#cb67-90"></a>                                             <span class="st">"5"</span><span class="ot">=</span><span class="st">"Intentional"</span></span>
<span id="cb67-91"><a href="#cb67-91"></a>                                             )</span>
<span id="cb67-92"><a href="#cb67-92"></a>  )</span>
<span id="cb67-93"><a href="#cb67-93"></a><span class="in">```</span></span>
<span id="cb67-94"><a href="#cb67-94"></a></span>
<span id="cb67-95"><a href="#cb67-95"></a><span class="fu">### Renaming column headers (optional)</span></span>
<span id="cb67-96"><a href="#cb67-96"></a></span>
<span id="cb67-97"><a href="#cb67-97"></a>And now, just to be clear, let's rename the original <span class="in">`GROUP`</span> to <span class="in">`GROUP_NUM`</span>. This can be accomplished by using the <span class="in">`dplyr::rename()`</span> function.</span>
<span id="cb67-98"><a href="#cb67-98"></a></span>
<span id="cb67-101"><a href="#cb67-101"></a><span class="in">```{r}</span></span>
<span id="cb67-102"><a href="#cb67-102"></a><span class="co"># The template is rename(NEW_NAME = OLD_NAME)</span></span>
<span id="cb67-103"><a href="#cb67-103"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">GROUP_NUM =</span> GROUP)</span>
<span id="cb67-104"><a href="#cb67-104"></a><span class="in">```</span></span>
<span id="cb67-105"><a href="#cb67-105"></a></span>
<span id="cb67-106"><a href="#cb67-106"></a><span class="co">[</span><span class="ot">Check out this link</span><span class="co">](https://www.datanovia.com/en/lessons/rename-data-frame-columns-in-r/#renaming-columns-with-dplyrrename)</span> for info on how to rename multiple columns at once using <span class="in">`names()`</span> or <span class="in">`dplyr::rename()`</span> from the <span class="in">`tidyverse`</span>.</span>
<span id="cb67-107"><a href="#cb67-107"></a></span>
<span id="cb67-108"><a href="#cb67-108"></a><span class="fu">### Reordering your levels</span></span>
<span id="cb67-109"><a href="#cb67-109"></a></span>
<span id="cb67-110"><a href="#cb67-110"></a>One important question you should ask before you look at your data is "what is your **control** (group, condition)". Proper experimentation requires a proper control in order to properly isolate the influence of the manipulation (that's a lot of propers). Here, the best candidates for our control group might either be "Counting" or "Intentional", depending on how the original problem was approached. If the larger comparison involved "Intentional v. incidental" learning for recall, then the "Intentional" group serves best as your control. If the original question involved levels of processing, then "Counting"" (theoretically the lowest level of incidental processing) is best. Here I am assuming the latter (although I believe theoretically Eysenck originally was interested in the former).</span>
<span id="cb67-111"><a href="#cb67-111"></a></span>
<span id="cb67-112"><a href="#cb67-112"></a>I bring this up, as its typically best to ensure that your control is entered first into the ANOVA model. To check the order of your levels, you may simply:</span>
<span id="cb67-113"><a href="#cb67-113"></a></span>
<span id="cb67-116"><a href="#cb67-116"></a><span class="in">```{r}</span></span>
<span id="cb67-117"><a href="#cb67-117"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>GROUP_FACTOR)</span>
<span id="cb67-118"><a href="#cb67-118"></a><span class="in">```</span></span>
<span id="cb67-119"><a href="#cb67-119"></a></span>
<span id="cb67-120"><a href="#cb67-120"></a>Here we see that "Counting" is first and will therefore be entered first into the model.</span>
<span id="cb67-121"><a href="#cb67-121"></a></span>
<span id="cb67-122"><a href="#cb67-122"></a>Assuming that we wanted to reorder the sequence, say to have <span class="in">`Intentional`</span> as the control, then we might simply use <span class="in">`fct_relevel()`</span>:</span>
<span id="cb67-123"><a href="#cb67-123"></a></span>
<span id="cb67-124"><a href="#cb67-124"></a><span class="in">```{r re-levling}</span></span>
<span id="cb67-125"><a href="#cb67-125"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> </span>
<span id="cb67-126"><a href="#cb67-126"></a>  <span class="fu">mutate</span>(<span class="at">GROUP_FACTOR =</span> <span class="fu">fct_relevel</span>(GROUP_FACTOR, <span class="st">"Intentional"</span>))</span>
<span id="cb67-127"><a href="#cb67-127"></a>                              </span>
<span id="cb67-128"><a href="#cb67-128"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>GROUP_FACTOR)</span>
<span id="cb67-129"><a href="#cb67-129"></a><span class="in">```</span></span>
<span id="cb67-130"><a href="#cb67-130"></a></span>
<span id="cb67-131"><a href="#cb67-131"></a>Note that with <span class="in">`fct_relevel()`</span> whatever level(s) I list get moved to the front of the line. In this case I just bumped <span class="in">`Intentional`</span> up while keeping the remaining levels ordered the same.</span>
<span id="cb67-132"><a href="#cb67-132"></a></span>
<span id="cb67-133"><a href="#cb67-133"></a>However, I liked the original order, so let's change it back:</span>
<span id="cb67-134"><a href="#cb67-134"></a></span>
<span id="cb67-137"><a href="#cb67-137"></a><span class="in">```{r}</span></span>
<span id="cb67-138"><a href="#cb67-138"></a>dataset <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> </span>
<span id="cb67-139"><a href="#cb67-139"></a>  <span class="fu">mutate</span>(<span class="at">GROUP_FACTOR =</span> <span class="fu">fct_relevel</span>(GROUP_FACTOR, </span>
<span id="cb67-140"><a href="#cb67-140"></a>                                    <span class="st">"Counting"</span>, </span>
<span id="cb67-141"><a href="#cb67-141"></a>                                    <span class="st">"Rhyming"</span>, </span>
<span id="cb67-142"><a href="#cb67-142"></a>                                    <span class="st">"Adjective"</span>, </span>
<span id="cb67-143"><a href="#cb67-143"></a>                                    <span class="st">"Imagery"</span>, </span>
<span id="cb67-144"><a href="#cb67-144"></a>                                    <span class="st">"Intentional"</span>))</span>
<span id="cb67-145"><a href="#cb67-145"></a></span>
<span id="cb67-146"><a href="#cb67-146"></a><span class="fu">levels</span>(dataset<span class="sc">$</span>GROUP_FACTOR)</span>
<span id="cb67-147"><a href="#cb67-147"></a><span class="in">```</span></span>
<span id="cb67-148"><a href="#cb67-148"></a></span>
<span id="cb67-149"><a href="#cb67-149"></a>That's better. Why the order is important will be made clear later in this write up. For now, think back to our example in class of running a t-test using <span class="in">`lm()`</span>. You may recall that the group level that was first entered into the model served as the **model intercept** where the second group level was expressed in terms of the slope of the line (beta). A similar output will be happening here.</span>
<span id="cb67-150"><a href="#cb67-150"></a></span>
<span id="cb67-151"><a href="#cb67-151"></a>So the data structure looks good.</span>
<span id="cb67-152"><a href="#cb67-152"></a></span>
<span id="cb67-153"><a href="#cb67-153"></a>One last little bit of ninja-ing. If you wanted to save a particular <span class="in">`R`</span> object to be used later on you can use the <span class="in">`write_rds()`</span> function (from <span class="in">`tidyverse`</span>). I'm going to save <span class="in">`dataset`</span> as I've cleaned it up so that I can use it in the next walkthrough.</span>
<span id="cb67-154"><a href="#cb67-154"></a></span>
<span id="cb67-157"><a href="#cb67-157"></a><span class="in">```{r}</span></span>
<span id="cb67-158"><a href="#cb67-158"></a><span class="fu">write_rds</span>(dataset,<span class="st">'clean_dataset.rds'</span>)</span>
<span id="cb67-159"><a href="#cb67-159"></a><span class="in">```</span></span>
<span id="cb67-160"><a href="#cb67-160"></a></span>
<span id="cb67-161"><a href="#cb67-161"></a>Onward to the analysis!!!!</span>
<span id="cb67-162"><a href="#cb67-162"></a></span>
<span id="cb67-163"><a href="#cb67-163"></a><span class="fu">## Assumptions for ANOVA</span></span>
<span id="cb67-164"><a href="#cb67-164"></a></span>
<span id="cb67-165"><a href="#cb67-165"></a><span class="fu">### Checking the normality assumption, OPTION 1 raw data by group</span></span>
<span id="cb67-166"><a href="#cb67-166"></a></span>
<span id="cb67-167"><a href="#cb67-167"></a>To check the distribution of outcomes in ANOVA, you have two options. The first would be to check the distribution of outcomes for EACH group/condition independently. In the case of the example <span class="in">`dataset`</span> we could get info related to the skew and kurtosis of RECALL for each GROUP_FACTOR using <span class="in">`describeBy()`</span>:</span>
<span id="cb67-168"><a href="#cb67-168"></a></span>
<span id="cb67-171"><a href="#cb67-171"></a><span class="in">```{r}</span></span>
<span id="cb67-172"><a href="#cb67-172"></a>psych<span class="sc">::</span><span class="fu">describeBy</span>(dataset,<span class="at">group =</span> <span class="st">"GROUP_FACTOR"</span>)</span>
<span id="cb67-173"><a href="#cb67-173"></a><span class="in">```</span></span>
<span id="cb67-174"><a href="#cb67-174"></a></span>
<span id="cb67-175"><a href="#cb67-175"></a>If we wanted to perform for extensive methods like <span class="in">`hist()`</span>, <span class="in">`qqPlot()`</span>, and <span class="in">`shapiro.test()`</span>, in the past I had you filter be each level (group) and proceed. So for example for <span class="in">`Counting`</span>:</span>
<span id="cb67-176"><a href="#cb67-176"></a></span>
<span id="cb67-179"><a href="#cb67-179"></a><span class="in">```{r}</span></span>
<span id="cb67-180"><a href="#cb67-180"></a>countingGroup <span class="ot">&lt;-</span> <span class="fu">filter</span>(dataset,GROUP_FACTOR<span class="sc">==</span><span class="st">"Counting"</span>)</span>
<span id="cb67-181"><a href="#cb67-181"></a></span>
<span id="cb67-182"><a href="#cb67-182"></a><span class="fu">hist</span>(countingGroup<span class="sc">$</span>RECALL)</span>
<span id="cb67-183"><a href="#cb67-183"></a><span class="fu">qqPlot</span>(countingGroup<span class="sc">$</span>RECALL)</span>
<span id="cb67-184"><a href="#cb67-184"></a><span class="fu">shapiro.test</span>(countingGroup<span class="sc">$</span>RECALL)</span>
<span id="cb67-185"><a href="#cb67-185"></a><span class="in">```</span></span>
<span id="cb67-186"><a href="#cb67-186"></a></span>
<span id="cb67-187"><a href="#cb67-187"></a>In the past you would have to repeat this for each other level. An alternative to generate an output by each level of a factor is to use the <span class="in">`by()`</span> function. For example to generate a sequence of <span class="in">`qqPlot`</span>s (for the sake of space I'm not going to execute this code here, but try on your computer)</span>
<span id="cb67-188"><a href="#cb67-188"></a></span>
<span id="cb67-189"><a href="#cb67-189"></a><span class="in">```{r eval=FALSE}</span></span>
<span id="cb67-190"><a href="#cb67-190"></a><span class="co"># by(dependent variable, grouping factor, name of function)</span></span>
<span id="cb67-191"><a href="#cb67-191"></a><span class="fu">by</span>(dataset<span class="sc">$</span>RECALL,<span class="at">INDICES =</span> dataset<span class="sc">$</span>GROUP_FACTOR,qqPlot)</span>
<span id="cb67-192"><a href="#cb67-192"></a><span class="in">```</span></span>
<span id="cb67-193"><a href="#cb67-193"></a></span>
<span id="cb67-194"><a href="#cb67-194"></a>You can do the same with <span class="in">`hist()`</span> and <span class="in">`shapiro.test()`</span></span>
<span id="cb67-195"><a href="#cb67-195"></a></span>
<span id="cb67-198"><a href="#cb67-198"></a><span class="in">```{r}</span></span>
<span id="cb67-199"><a href="#cb67-199"></a><span class="fu">by</span>(dataset<span class="sc">$</span>RECALL,<span class="at">INDICES =</span> dataset<span class="sc">$</span>GROUP_FACTOR,hist)</span>
<span id="cb67-200"><a href="#cb67-200"></a><span class="fu">by</span>(dataset<span class="sc">$</span>RECALL,<span class="at">INDICES =</span> dataset<span class="sc">$</span>GROUP_FACTOR,shapiro.test)</span>
<span id="cb67-201"><a href="#cb67-201"></a><span class="in">```</span></span>
<span id="cb67-202"><a href="#cb67-202"></a></span>
<span id="cb67-203"><a href="#cb67-203"></a>and even our custom standardized skew and kurtosis functions.</span>
<span id="cb67-204"><a href="#cb67-204"></a></span>
<span id="cb67-205"><a href="#cb67-205"></a><span class="fu">### Checking the normality assumption, OPTION 2, the better way: Look at the residuals.</span></span>
<span id="cb67-206"><a href="#cb67-206"></a></span>
<span id="cb67-207"><a href="#cb67-207"></a>Although <span class="in">`by()`</span> may or may not make life easier for you in this test case, things rapidly become more complicated when attempting to check normality by condition. For example if you're running a 2×3×3 mixed effect ANOVA, you would need to run through 18 conditions!!! So what to do?!?!?!</span>
<span id="cb67-208"><a href="#cb67-208"></a></span>
<span id="cb67-209"><a href="#cb67-209"></a>A simpler alternative is to run you model and analyze your residuals. <span class="co">[</span><span class="ot">This web link</span><span class="co">](https://www.theanalysisfactor.com/checking-normality-anova-model/)</span> does a nice and quick job of explaining the logic.</span>
<span id="cb67-210"><a href="#cb67-210"></a></span>
<span id="cb67-211"><a href="#cb67-211"></a>In this case we would run our ANOVA model using <span class="in">`lm`</span> (see told you its all the same)</span>
<span id="cb67-212"><a href="#cb67-212"></a></span>
<span id="cb67-215"><a href="#cb67-215"></a><span class="in">```{r}</span></span>
<span id="cb67-216"><a href="#cb67-216"></a>dataset_aov <span class="ot">&lt;-</span> <span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span>
<span id="cb67-217"><a href="#cb67-217"></a><span class="in">```</span></span>
<span id="cb67-218"><a href="#cb67-218"></a></span>
<span id="cb67-219"><a href="#cb67-219"></a>Congrats, you've just run an ANOVA, but for now we aren't interested in the results from the model. Remember from a few weeks back that many outputs have <span class="in">`attributes`</span> that may be accessed. In this case, we want the models residuals. These can be accessed by</span>
<span id="cb67-220"><a href="#cb67-220"></a></span>
<span id="cb67-223"><a href="#cb67-223"></a><span class="in">```{r}</span></span>
<span id="cb67-224"><a href="#cb67-224"></a><span class="fu">resid</span>(dataset_aov)</span>
<span id="cb67-225"><a href="#cb67-225"></a><span class="in">```</span></span>
<span id="cb67-226"><a href="#cb67-226"></a></span>
<span id="cb67-227"><a href="#cb67-227"></a>From here, we can simply take the residuals (as we did with regression) and submit them to our standard tests for normality. For example, testing skew, and kurtosis:</span>
<span id="cb67-228"><a href="#cb67-228"></a></span>
<span id="cb67-231"><a href="#cb67-231"></a><span class="in">```{r}</span></span>
<span id="cb67-232"><a href="#cb67-232"></a><span class="fu">resid</span>(dataset_aov) <span class="sc">%&gt;%</span> <span class="fu">skew</span>()</span>
<span id="cb67-233"><a href="#cb67-233"></a><span class="fu">resid</span>(dataset_aov) <span class="sc">%&gt;%</span> <span class="fu">kurtosi</span>()</span>
<span id="cb67-234"><a href="#cb67-234"></a><span class="in">```</span></span>
<span id="cb67-235"><a href="#cb67-235"></a></span>
<span id="cb67-236"><a href="#cb67-236"></a>or submit the entire model diagnostic plots:</span>
<span id="cb67-237"><a href="#cb67-237"></a></span>
<span id="cb67-240"><a href="#cb67-240"></a><span class="in">```{r}</span></span>
<span id="cb67-241"><a href="#cb67-241"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(performance)</span>
<span id="cb67-242"><a href="#cb67-242"></a></span>
<span id="cb67-243"><a href="#cb67-243"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(dataset_aov)</span>
<span id="cb67-244"><a href="#cb67-244"></a><span class="in">```</span></span>
<span id="cb67-245"><a href="#cb67-245"></a></span>
<span id="cb67-246"><a href="#cb67-246"></a>**So, between OPTION 1 and OPTION 2, I'd recommend typically going with OPTION 2. Especially as your ANOVA designs become more complex.**</span>
<span id="cb67-247"><a href="#cb67-247"></a></span>
<span id="cb67-248"><a href="#cb67-248"></a><span class="fu">#### WALKTHROUGH PROBLEM: Run the requisite tests for normality using the `residuals` from `dataset_aov`</span></span>
<span id="cb67-249"><a href="#cb67-249"></a></span>
<span id="cb67-250"><a href="#cb67-250"></a><span class="fu">### Homogeneity of Variance</span></span>
<span id="cb67-251"><a href="#cb67-251"></a></span>
<span id="cb67-252"><a href="#cb67-252"></a>Another assumption of ANOVA is the homogeneity of variance between groups. An easy-way to get an eyeball test of this assumption is two perform a box plot of the data. Here I am performing this plot using <span class="in">`ggplot2`</span>:</span>
<span id="cb67-253"><a href="#cb67-253"></a></span>
<span id="cb67-256"><a href="#cb67-256"></a><span class="in">```{r}</span></span>
<span id="cb67-257"><a href="#cb67-257"></a><span class="fu">ggplot</span>(<span class="at">data =</span>dataset, <span class="fu">aes</span>(<span class="at">x=</span>GROUP_FACTOR,<span class="at">y=</span>RECALL)) <span class="sc">+</span></span>
<span id="cb67-258"><a href="#cb67-258"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb67-259"><a href="#cb67-259"></a><span class="in">```</span></span>
<span id="cb67-260"><a href="#cb67-260"></a></span>
<span id="cb67-261"><a href="#cb67-261"></a>Huge differences in the IQR regions may be a clue that the homogeneity assumption is violated. We can run more specific tests in <span class="in">`R`</span> including the Levene Test and Fligner-Killeen Test of Homogeneity of Variances. You are familiar with the Levene Test from a few weeks ago. The Figner-Killeen Test is offered as an alternative if you are concerned with violations of the normality assumption.</span>
<span id="cb67-262"><a href="#cb67-262"></a></span>
<span id="cb67-263"><a href="#cb67-263"></a>As is typically the case $p&lt;.05$ indicates a violation of this assumption:</span>
<span id="cb67-264"><a href="#cb67-264"></a></span>
<span id="cb67-267"><a href="#cb67-267"></a><span class="in">```{r}</span></span>
<span id="cb67-268"><a href="#cb67-268"></a><span class="co"># Levene Test of Homogeneity of Variances</span></span>
<span id="cb67-269"><a href="#cb67-269"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span>
<span id="cb67-270"><a href="#cb67-270"></a></span>
<span id="cb67-271"><a href="#cb67-271"></a><span class="co"># Fligner-Killeen Test of Homogeneity of Variances</span></span>
<span id="cb67-272"><a href="#cb67-272"></a><span class="fu">fligner.test</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span>
<span id="cb67-273"><a href="#cb67-273"></a><span class="in">```</span></span>
<span id="cb67-274"><a href="#cb67-274"></a></span>
<span id="cb67-275"><a href="#cb67-275"></a><span class="fu">### What to do if the assumptions are violated?</span></span>
<span id="cb67-276"><a href="#cb67-276"></a></span>
<span id="cb67-277"><a href="#cb67-277"></a>If either assumption is violated, one option that you have is to transform you data. We've talked several times in class about the pros and cons of doing this, and there are several resources that provide examples of how this is done. Another option is to use a non-parametric test such as the Kruskal-Wallis Test if the data is not normal, or Welch's ANOVA is the variances are not homogeneous. That said, one of reasons that ANOVA is so popular is that it has been demonstrated to be robust in the face of violated assumptions (as long as the sample sizes are equal). For example, in *Design and Analysis of Experiments* (1999, p. 112) Dean &amp; Voss argue that the maximum group variance may be as high as 3× the minimum group variance without any issue. With this in mind, a question (gray area) before us is *how much* of a violation is there in the data? And if not so much, you may be fine just running an ANOVA regardless.</span>
<span id="cb67-278"><a href="#cb67-278"></a></span>
<span id="cb67-279"><a href="#cb67-279"></a><span class="fu">## Running the ANOVA in R using `aov()` or `lm()`</span></span>
<span id="cb67-280"><a href="#cb67-280"></a></span>
<span id="cb67-281"><a href="#cb67-281"></a>There are many, many ways to build an ANOVA model in <span class="in">`R`</span>. Throughout the semester we will be highlighting three: <span class="in">`lm()`</span>, <span class="in">`aov()`</span>, and using the <span class="in">`afex`</span> package. This week we will concentrate on <span class="in">`aov()`</span> which is the standard method, as well as the <span class="in">`lm()`</span> method that you have used before, just to reinforce that ANOVA and regression are one in the same. In fact, SPOILER ALERT, <span class="in">`aov()`</span> is just a fancy wrapper for <span class="in">`lm()`</span>, AND FWIW I don't really like using <span class="in">`aov()`</span>. I only mention it here as if you go looking for how to run ANOVA in <span class="in">`R`</span> online, many sites will say use <span class="in">`aov()`</span>.</span>
<span id="cb67-282"><a href="#cb67-282"></a></span>
<span id="cb67-283"><a href="#cb67-283"></a>Like <span class="in">`lm()`</span> from weeks past, <span class="in">`aov()`</span> asks us to enter our dependent and independent variables into the model in the formula format **DV \~ IVs**. In this case, we only have a single IV, <span class="in">`GROUP_FACTOR`</span>. Thus our model is:</span>
<span id="cb67-284"><a href="#cb67-284"></a></span>
<span id="cb67-287"><a href="#cb67-287"></a><span class="in">```{r}</span></span>
<span id="cb67-288"><a href="#cb67-288"></a>aov.model <span class="ot">&lt;-</span> <span class="fu">aov</span>(RECALL<span class="sc">~</span>GROUP_FACTOR,<span class="at">data =</span> dataset)</span>
<span id="cb67-289"><a href="#cb67-289"></a><span class="in">```</span></span>
<span id="cb67-290"><a href="#cb67-290"></a></span>
<span id="cb67-291"><a href="#cb67-291"></a>From here, an <span class="in">`anova()`</span> of the model gives us our ANOVA table. Note that <span class="in">`car::Anova()`</span> accomplished the same thing, though gives us a different format. The added benefit is that if we so choose, we can change how our Sums of Squares are calculated. This isn't important for simple One-way ANOVA, but see the Field text, Jane Superbrain 11.1 for an explanation.</span>
<span id="cb67-292"><a href="#cb67-292"></a></span>
<span id="cb67-295"><a href="#cb67-295"></a><span class="in">```{r}</span></span>
<span id="cb67-296"><a href="#cb67-296"></a><span class="fu">anova</span>(aov.model)</span>
<span id="cb67-297"><a href="#cb67-297"></a>car<span class="sc">::</span><span class="fu">Anova</span>(aov.model, <span class="at">type=</span><span class="st">"3"</span>)</span>
<span id="cb67-298"><a href="#cb67-298"></a><span class="in">```</span></span>
<span id="cb67-299"><a href="#cb67-299"></a></span>
<span id="cb67-300"><a href="#cb67-300"></a>Also note that we can get <span class="in">`residuals`</span> from the <span class="in">`aov()`</span> output as well. In fact take a look at the object's <span class="in">`$class`</span>... see I told you, <span class="in">`lm()`</span>!!!</span>
<span id="cb67-301"><a href="#cb67-301"></a></span>
<span id="cb67-304"><a href="#cb67-304"></a><span class="in">```{r}</span></span>
<span id="cb67-305"><a href="#cb67-305"></a><span class="fu">resid</span>(aov.model)</span>
<span id="cb67-306"><a href="#cb67-306"></a><span class="in">```</span></span>
<span id="cb67-307"><a href="#cb67-307"></a></span>
<span id="cb67-308"><a href="#cb67-308"></a>Even better, a more comprehensive anova table can be obtained by submitting our <span class="in">`aov.model`</span> to <span class="in">`sjstats::anova_stats()`</span>, which gives us our effect sizes as well! This function calculates eta-squared ($\eta^2$), partial-eta-squared ($\eta_p^2$), omega squared ($\omega^2$) and partial omega-squared ($\omega_p^2$) as well as Cohen's *f*. Typically for One-Way ANOVA psychologists report eta-squared ($\eta^2$), though there are arguments that omega squared ($\omega^2$) may be the more preferred measure. Note that pander is for web formatting this page.</span>
<span id="cb67-309"><a href="#cb67-309"></a></span>
<span id="cb67-312"><a href="#cb67-312"></a><span class="in">```{r}</span></span>
<span id="cb67-313"><a href="#cb67-313"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(pander)</span>
<span id="cb67-314"><a href="#cb67-314"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjstats)</span>
<span id="cb67-315"><a href="#cb67-315"></a>sjstats<span class="sc">::</span><span class="fu">anova_stats</span>(aov.model) <span class="sc">%&gt;%</span> <span class="fu">pander</span>()</span>
<span id="cb67-316"><a href="#cb67-316"></a><span class="in">```</span></span>
<span id="cb67-317"><a href="#cb67-317"></a></span>
<span id="cb67-318"><a href="#cb67-318"></a><span class="fu">## Plotting your data</span></span>
<span id="cb67-319"><a href="#cb67-319"></a></span>
<span id="cb67-320"><a href="#cb67-320"></a>For publication quality ANOVA plots, there are typically three acceptable plots used to convey your results, box plots, bar plots, and line plots. As the ANOVA become more complex, we tend towards using line plots (box plots and bar plots may become very busy in complex designs). Unless there are other compelling reasons we tend to plot the means (although note that box plots usually give you medians). Since you have already produced box plots and barplots, I'll show examples of how to do a line plot.</span>
<span id="cb67-321"><a href="#cb67-321"></a></span>
<span id="cb67-322"><a href="#cb67-322"></a>To create a **line plot** with points at the means and error lines representing the 95% CI (known as a point range), we can use call that you are familiar with and a new geom <span class="in">`pointrange`</span>. Whats nice about point range is that it allows you to create your points and the error bars all in a single line.</span>
<span id="cb67-323"><a href="#cb67-323"></a></span>
<span id="cb67-326"><a href="#cb67-326"></a><span class="in">```{r}</span></span>
<span id="cb67-327"><a href="#cb67-327"></a>ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span>dataset,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> GROUP_FACTOR, <span class="at">y =</span> RECALL)) <span class="sc">+</span></span>
<span id="cb67-328"><a href="#cb67-328"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, </span>
<span id="cb67-329"><a href="#cb67-329"></a>               <span class="at">size=</span><span class="dv">1</span>, </span>
<span id="cb67-330"><a href="#cb67-330"></a>               <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb67-331"><a href="#cb67-331"></a>               <span class="at">geom=</span><span class="st">"pointrange"</span>)</span>
<span id="cb67-332"><a href="#cb67-332"></a><span class="in">```</span></span>
<span id="cb67-333"><a href="#cb67-333"></a></span>
<span id="cb67-334"><a href="#cb67-334"></a>Now to add the lines to this plot. For this you will need another <span class="in">`stat_summary()`</span> line specifying that the vertices of the lines should be the means, <span class="in">`fun = mean`</span> and a parameter that specifies how the lines should be grouped. Since we have a One-way ANOVA, <span class="in">`group=1`</span>. When we built to more complex designs you may elect to <span class="in">`group=FACTOR_NAME`</span>. Something like this is useful to say make some lines dashed and some lines solid according to levels on a factor. More on this in two weeks when we get to factorial ANOVA.</span>
<span id="cb67-335"><a href="#cb67-335"></a></span>
<span id="cb67-336"><a href="#cb67-336"></a>While we're at it let's fix those axes titles. We can use the functions <span class="in">`xlab()`</span> and <span class="in">`ylab()`</span> to do so.</span>
<span id="cb67-337"><a href="#cb67-337"></a></span>
<span id="cb67-340"><a href="#cb67-340"></a><span class="in">```{r}</span></span>
<span id="cb67-341"><a href="#cb67-341"></a><span class="co"># this is from before, saving as object "p"</span></span>
<span id="cb67-342"><a href="#cb67-342"></a>p <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span>dataset,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> GROUP_FACTOR, <span class="at">y =</span> RECALL)) <span class="sc">+</span></span>
<span id="cb67-343"><a href="#cb67-343"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, </span>
<span id="cb67-344"><a href="#cb67-344"></a>               <span class="at">size=</span><span class="dv">1</span>, </span>
<span id="cb67-345"><a href="#cb67-345"></a>               <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb67-346"><a href="#cb67-346"></a>               <span class="at">geom=</span><span class="st">"pointrange"</span>) <span class="sc">+</span></span>
<span id="cb67-347"><a href="#cb67-347"></a>  <span class="co"># adding lines</span></span>
<span id="cb67-348"><a href="#cb67-348"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, </span>
<span id="cb67-349"><a href="#cb67-349"></a>               <span class="at">size =</span> <span class="dv">1</span>, </span>
<span id="cb67-350"><a href="#cb67-350"></a>               <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb67-351"><a href="#cb67-351"></a>               <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">group=</span><span class="dv">1</span>), </span>
<span id="cb67-352"><a href="#cb67-352"></a>               <span class="at">geom=</span><span class="st">"line"</span>) <span class="sc">+</span></span>
<span id="cb67-353"><a href="#cb67-353"></a>  <span class="co"># and fixing the axis titles:</span></span>
<span id="cb67-354"><a href="#cb67-354"></a>  <span class="fu">xlab</span>(<span class="st">"Group"</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">"Words recalled"</span>)</span>
<span id="cb67-355"><a href="#cb67-355"></a><span class="fu">show</span>(p)</span>
<span id="cb67-356"><a href="#cb67-356"></a><span class="in">```</span></span>
<span id="cb67-357"><a href="#cb67-357"></a></span>
<span id="cb67-358"><a href="#cb67-358"></a>Finally, for aesthetic reasons you may elect to expand the y-axis. For example to make the range of y-axis values (0,20):</span>
<span id="cb67-359"><a href="#cb67-359"></a></span>
<span id="cb67-362"><a href="#cb67-362"></a><span class="in">```{r}</span></span>
<span id="cb67-363"><a href="#cb67-363"></a>p <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>))</span>
<span id="cb67-364"><a href="#cb67-364"></a><span class="in">```</span></span>
<span id="cb67-365"><a href="#cb67-365"></a></span>
<span id="cb67-366"><a href="#cb67-366"></a>That being said, this data probably lends itself to a bar plot. This is similar to how you built your bar plots from as when doing a t-test. As a matter of fact:</span>
<span id="cb67-367"><a href="#cb67-367"></a></span>
<span id="cb67-368"><a href="#cb67-368"></a><span class="fu">#### WALKTHROUGH PROBLEM: Create a bar plot with error bars for our `dataset`.</span></span>
<span id="cb67-369"><a href="#cb67-369"></a></span>
<span id="cb67-370"><a href="#cb67-370"></a><span class="fu">## Reporting your data / the write up</span></span>
<span id="cb67-371"><a href="#cb67-371"></a></span>
<span id="cb67-372"><a href="#cb67-372"></a>There are two components to reporting your omnibus ANOVA. First, You need to report your output as related to the test:</span>
<span id="cb67-373"><a href="#cb67-373"></a></span>
<span id="cb67-374"><a href="#cb67-374"></a><span class="ss">-   </span>**the F value**,</span>
<span id="cb67-375"><a href="#cb67-375"></a><span class="ss">-   </span>**the degrees of freedom (between and within)**,</span>
<span id="cb67-376"><a href="#cb67-376"></a><span class="ss">-   </span>**the p-value**</span>
<span id="cb67-377"><a href="#cb67-377"></a><span class="ss">-   </span>**effect size**: typically with between-effects ANOVA we report eta squared, although note that Howell advocates for omega squared. Recall that submitting the model to <span class="in">`sjstats::anova_stats()`</span> gives you both.</span>
<span id="cb67-378"><a href="#cb67-378"></a></span>
<span id="cb67-379"><a href="#cb67-379"></a>Second, as we typically focus on means with ANOVA, it is typically a good idea to report means and some report of of the distribution of each group (typically either standard deviation or standard error; although 95% CI may be useful in certain scenarios).</span>
<span id="cb67-380"><a href="#cb67-380"></a></span>
<span id="cb67-381"><a href="#cb67-381"></a>So for example reporting the <span class="in">`Rhyming`</span> group:</span>
<span id="cb67-382"><a href="#cb67-382"></a></span>
<span id="cb67-383"><a href="#cb67-383"></a><span class="ss">-   </span>**M ± SD:** 6.90 ± 2.13</span>
<span id="cb67-384"><a href="#cb67-384"></a><span class="ss">-   </span>**M ± SE:** 6.90 ± 0.67</span>
<span id="cb67-385"><a href="#cb67-385"></a></span>
<span id="cb67-386"><a href="#cb67-386"></a><span class="fu">## What the omnibus ANOVA tells you</span></span>
<span id="cb67-387"><a href="#cb67-387"></a></span>
<span id="cb67-388"><a href="#cb67-388"></a>While it may be useful to report the means, you need to be mindful of what the omnibus ANOVA tells you. Remember, that the the null hypothesis of the omnibus ANOVA is that "there are no differences between observed means". Our significant result tells us that there *are* differences between our means, **but does not tell us what those specific differences are**. So while it may be useful to report general relationships, e.g., "Recall for people in the Intentional group tended to be greater than for the Counting group" you **cannot** say definitively "Recall was significantly greater for the Intentional Group". Typically when you only have tested the omnibus ANOVA, you only speak in generalities (e.g., "Recall tended to increase with level of processing.")</span>
<span id="cb67-389"><a href="#cb67-389"></a></span>
<span id="cb67-390"><a href="#cb67-390"></a>**Always be mindful that you don't over interpret your data.**</span>
<span id="cb67-391"><a href="#cb67-391"></a></span>
<span id="cb67-392"><a href="#cb67-392"></a><span class="fu">## Running an ANOVA using `lm()` (it's a regression afterall)</span></span>
<span id="cb67-393"><a href="#cb67-393"></a></span>
<span id="cb67-394"><a href="#cb67-394"></a>Now that we've got practical matters out of the way, I want to take some time to dig a little deeper into the connections between ANOVA this week and our work on correlations and regressions in the past.</span>
<span id="cb67-395"><a href="#cb67-395"></a></span>
<span id="cb67-396"><a href="#cb67-396"></a>As we've already mentioned (and spent time discussing in class) ANOVA is just an extension of the simple linear model that we covered last week, where ANOVA is used when our predictors are discrete. In fact <span class="in">`aov()`</span> is simply a wrapper for the <span class="in">`lm()`</span> function that we used last week. For example, let's run our model using <span class="in">`lm()`</span> and then pipe it into <span class="in">`anova()`</span> or <span class="in">`sjstats::anova_stats()`</span>.</span>
<span id="cb67-397"><a href="#cb67-397"></a></span>
<span id="cb67-400"><a href="#cb67-400"></a><span class="in">```{r}</span></span>
<span id="cb67-401"><a href="#cb67-401"></a>lm.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset)</span>
<span id="cb67-402"><a href="#cb67-402"></a><span class="fu">anova</span>(lm.model)</span>
<span id="cb67-403"><a href="#cb67-403"></a>sjstats<span class="sc">::</span><span class="fu">anova_stats</span>(lm.model) <span class="sc">%&gt;%</span> <span class="fu">pander</span>()</span>
<span id="cb67-404"><a href="#cb67-404"></a><span class="in">```</span></span>
<span id="cb67-405"><a href="#cb67-405"></a></span>
<span id="cb67-406"><a href="#cb67-406"></a>All <span class="in">`aov()`</span> does is take an <span class="in">`lm`</span> object and produce an ANOVA table from the results. If we were simply to look at the <span class="in">`lm() model`</span> we see that it gives us the info in our ANOVA table at the end of the summary, including the <span class="in">`F-statistic`</span> (9.085), the <span class="in">`degrees of freedom`</span> (4 and 45) and the <span class="in">`p-value`</span> (1.815e-05):</span>
<span id="cb67-407"><a href="#cb67-407"></a></span>
<span id="cb67-410"><a href="#cb67-410"></a><span class="in">```{r}</span></span>
<span id="cb67-411"><a href="#cb67-411"></a><span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb67-412"><a href="#cb67-412"></a><span class="in">```</span></span>
<span id="cb67-413"><a href="#cb67-413"></a></span>
<span id="cb67-414"><a href="#cb67-414"></a>Taking a look at this output, we see that the <span class="in">`lm() model`</span> also gives us a lot of other additional useful info. For example the $R^2$ of the model may be understood as the effect size of the ANOVA. However, when we report it for One-Way ANOVA we express it as... dun, dun, dunnnn... *eta-squared*!!, or $\eta^2$.</span>
<span id="cb67-415"><a href="#cb67-415"></a></span>
<span id="cb67-416"><a href="#cb67-416"></a>One more time with feeling, **for simple oneway ANOVA,** $R^2$ **and** $\eta^2$ **are the same damn thing!!**</span>
<span id="cb67-417"><a href="#cb67-417"></a></span>
<span id="cb67-418"><a href="#cb67-418"></a>Zooming in on the coefficients:</span>
<span id="cb67-419"><a href="#cb67-419"></a></span>
<span id="cb67-420"><a href="#cb67-420"></a><span class="in">```{r echo=FALSE}</span></span>
<span id="cb67-421"><a href="#cb67-421"></a>lm.summary <span class="ot">&lt;-</span> <span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data=</span>dataset) <span class="sc">%&gt;%</span> <span class="fu">summary</span>() <span class="co"># save above to object</span></span>
<span id="cb67-422"><a href="#cb67-422"></a>lm.summary<span class="sc">$</span>coefficients</span>
<span id="cb67-423"><a href="#cb67-423"></a><span class="in">```</span></span>
<span id="cb67-424"><a href="#cb67-424"></a></span>
<span id="cb67-425"><a href="#cb67-425"></a>We see information about the means of each group relative to the <span class="in">`(Intercept)`</span>. *This is why I stressed earlier that it may be useful to rearrange the order of your levels such that `R` enters your control group into the model first*. In this case, the first predictor entered is assigned to the <span class="in">`(Intercept)`</span>. The remaining predictors in the model are then presented relative to the first. Since we entered "Counting" first, the estimate of the <span class="in">`(Intercept)`</span> represents its mean. The means for each remaining group are the sum of its estimate coefficient and the <span class="in">`(Intercept)`</span>. So for example the mean of the Rhyming group is $(-0.1)+(7.0)=6.9$.</span>
<span id="cb67-426"><a href="#cb67-426"></a></span>
<span id="cb67-427"><a href="#cb67-427"></a>The coefficients section also gives us one other useful bit of information, the $t$-values of the estimate. As we learned a few weeks ago, for a simple regression the beta coefficient gives us information about the slope of the regression line and the corresponding $t$-value is a test of the null $beta=0$. So for a simple regression this tells us if our slope is significantly different from 0.</span>
<span id="cb67-428"><a href="#cb67-428"></a></span>
<span id="cb67-429"><a href="#cb67-429"></a>A similar logic applies to the ANOVA model. As I mentioned above, deriving the means of each level of our IV is a matter of summing the (Intercept) and the beta estimate for that level. It should be apparent, then, that the beta estimates here represent the slope of a line that between the intercept and the mean of the level (where the distance between the predictor and coefficient is treated as a unit 1). Therefore, a significant $t$-value for beta tells us that the slope between the two means is significant, or that those two means are significantly different from one another.</span>
<span id="cb67-430"><a href="#cb67-430"></a></span>
<span id="cb67-431"><a href="#cb67-431"></a>Keep in mind the only comparisons that are being made here are between the individual levels of our IV and the control (Intercept). So while this output allows us to make a claim about the difference between the means of the Counting (Intercept) group compared to each of the other groups, it **does not** allow us to make a claim about differences between our other levels. For example no information about a statistical test of differences between the Rhyming and Imagery groups is conveyed here. However, assuming you are interested in deviations from your control, you can get info here quickly. There is a caveat here, in that our alpha criterion will need to be adjusted to be more conservative than <span class="in">`.05.`</span> More on this next week.</span>
<span id="cb67-432"><a href="#cb67-432"></a></span>
<span id="cb67-433"><a href="#cb67-433"></a><span class="fu">## Reporting your results.</span></span>
<span id="cb67-434"><a href="#cb67-434"></a></span>
<span id="cb67-435"><a href="#cb67-435"></a><span class="fu">### Reporting just the ANOVA</span></span>
<span id="cb67-436"><a href="#cb67-436"></a></span>
<span id="cb67-437"><a href="#cb67-437"></a>For this week's assignment, you are going to be asked to simply report the ANOVA. In future weeks you will see that simply reporting the ANOVA is not the end of your analysis, but only the beginning of additional, necessary follow-ups. But that is for next week, for now let's take a look at what one might expect to be reported in an ANOVA write-up.</span>
<span id="cb67-438"><a href="#cb67-438"></a></span>
<span id="cb67-439"><a href="#cb67-439"></a>Given our example:</span>
<span id="cb67-440"><a href="#cb67-440"></a></span>
<span id="cb67-441"><a href="#cb67-441"></a><span class="ss">-   </span>words RECALL is our dependent measure</span>
<span id="cb67-442"><a href="#cb67-442"></a><span class="ss">-   </span>GROUP_FACTOR is our independent variable, with five levels (or groups).</span>
<span id="cb67-443"><a href="#cb67-443"></a></span>
<span id="cb67-444"><a href="#cb67-444"></a>Using sjstats to generate an ANOVA table (pander makes it pretty for this web page:</span>
<span id="cb67-445"><a href="#cb67-445"></a></span>
<span id="cb67-448"><a href="#cb67-448"></a><span class="in">```{r}</span></span>
<span id="cb67-449"><a href="#cb67-449"></a>sjstats<span class="sc">::</span><span class="fu">anova_stats</span>(aov.model) <span class="sc">%&gt;%</span> <span class="fu">pander</span>()</span>
<span id="cb67-450"><a href="#cb67-450"></a><span class="in">```</span></span>
<span id="cb67-451"><a href="#cb67-451"></a></span>
<span id="cb67-452"><a href="#cb67-452"></a>From this table, we need our:</span>
<span id="cb67-453"><a href="#cb67-453"></a></span>
<span id="cb67-454"><a href="#cb67-454"></a><span class="ss">-   </span>**df**: 4 and 45</span>
<span id="cb67-455"><a href="#cb67-455"></a><span class="ss">-   </span>**F-statistic**: 9.085</span>
<span id="cb67-456"><a href="#cb67-456"></a><span class="ss">-   </span>**p.value**: even though it says zero, its "<span class="sc">\&lt;</span>.001"</span>
<span id="cb67-457"><a href="#cb67-457"></a><span class="ss">-   </span>**etasq**: .447; the symbol for etasq is $\eta^2$</span>
<span id="cb67-458"><a href="#cb67-458"></a></span>
<span id="cb67-459"><a href="#cb67-459"></a>Taking all of this info, and plugging into a write-up template (inserted points in bold):</span>
<span id="cb67-460"><a href="#cb67-460"></a></span>
<span id="cb67-461"><a href="#cb67-461"></a>"We hypothesized that different types of memorization strategies would result in different levels of memorization between our **five groups**, as measured by the **number of words recalled**. To test this hypothesis we conducted a One-way Analysis of Variance. Our analysis revealed a significant effect for **Groups**, *F*(4, 45) = 9.08, *p* <span class="sc">\&lt;</span> .001, $\eta^2$ = .45; see Figure 1."</span>
<span id="cb67-462"><a href="#cb67-462"></a></span>
<span id="cb67-463"><a href="#cb67-463"></a>For now, this is all you can say with only running a One-way ANOVA using this method, and that's all I would want for the homework for this week.</span>
<span id="cb67-464"><a href="#cb67-464"></a></span>
<span id="cb67-465"><a href="#cb67-465"></a><span class="fu">### Reporting the ANOVA, lm() output</span></span>
<span id="cb67-466"><a href="#cb67-466"></a></span>
<span id="cb67-467"><a href="#cb67-467"></a>Let's revisit the <span class="in">`lm()`</span> output. Recall that the <span class="in">`lm()`</span> method gives us the added benefit of comparing each level of the <span class="in">`GROUP_FACTOR`</span> to the control level. This is what's known as treatment contrasts (see Winter, Chapter 7). In this case, our control level is <span class="in">`Counting`</span> and every other level (group) is compared against <span class="in">`Counting`</span> and captured in the resulting beta coefficients:</span>
<span id="cb67-468"><a href="#cb67-468"></a></span>
<span id="cb67-471"><a href="#cb67-471"></a><span class="in">```{r}</span></span>
<span id="cb67-472"><a href="#cb67-472"></a>aov_model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(RECALL<span class="sc">~</span>GROUP_FACTOR, <span class="at">data =</span> dataset)</span>
<span id="cb67-473"><a href="#cb67-473"></a><span class="fu">summary</span>(aov_model_lm)</span>
<span id="cb67-474"><a href="#cb67-474"></a><span class="in">```</span></span>
<span id="cb67-475"><a href="#cb67-475"></a></span>
<span id="cb67-476"><a href="#cb67-476"></a>From this summary output we would not only extract our <span class="in">`F-statistic`</span>, <span class="in">`df`</span>, <span class="in">`p-value`</span> and <span class="in">`R-squared`</span> (remember that $R^2$ is $\eta^2$) as we do for the previous write-up, but now we can talk about differences between the other levels and <span class="in">`Counting`</span> as expressed as a <span class="in">`t`</span> value (we are running t-tests). We then combine this info with info related to the means and standard errors (note that I got the means and ses by creating a summary <span class="in">`tibble():`</span></span>
<span id="cb67-477"><a href="#cb67-477"></a></span>
<span id="cb67-480"><a href="#cb67-480"></a><span class="in">```{r}</span></span>
<span id="cb67-481"><a href="#cb67-481"></a>dataset <span class="sc">%&gt;%</span> </span>
<span id="cb67-482"><a href="#cb67-482"></a>  <span class="fu">group_by</span>(GROUP_FACTOR) <span class="sc">%&gt;%</span></span>
<span id="cb67-483"><a href="#cb67-483"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(RECALL) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">2</span>),</span>
<span id="cb67-484"><a href="#cb67-484"></a>            <span class="at">se =</span> <span class="fu">sd</span>(RECALL)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()) <span class="co"># ses = sd / sqrt number of participants</span></span>
<span id="cb67-485"><a href="#cb67-485"></a>            ) <span class="sc">%&gt;%</span> </span>
<span id="cb67-486"><a href="#cb67-486"></a>  <span class="co"># this bit of code does some rounding (optional)</span></span>
<span id="cb67-487"><a href="#cb67-487"></a>  <span class="fu">mutate_if</span>(is.numeric,</span>
<span id="cb67-488"><a href="#cb67-488"></a>            round,</span>
<span id="cb67-489"><a href="#cb67-489"></a>            <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb67-490"><a href="#cb67-490"></a>  </span>
<span id="cb67-491"><a href="#cb67-491"></a></span>
<span id="cb67-492"><a href="#cb67-492"></a><span class="in">```</span></span>
<span id="cb67-493"><a href="#cb67-493"></a></span>
<span id="cb67-494"><a href="#cb67-494"></a>Putting all of this info together, we might say:</span>
<span id="cb67-495"><a href="#cb67-495"></a></span>
<span id="cb67-496"><a href="#cb67-496"></a><span class="at">&gt; "We hypothesized that different types of memorization strategies would result in different levels of memorization between our **five groups**, as measured by the **number of words recalled**. To test this hypothesis we conducted a One-way Analysis of Variance. Our analysis revealed a significant effect for **Groups**, *F*(4, 45) = 9.08, *p* \&lt; .001, $\eta^2$ = .45. As can be seen in Figure 1, we found that the average number of words recalled for the Adjective ($M$ = 11.0, SE = 0.79; $t$(45) = 2.88), Imagery ($M$ = 13.4, SE = 1.42; $t$(45) = 4.60), and Intentional ($M$ = 12.0, SE = 1.18; $t$(45) = 3.60) memorization groups were all greater than the Counting group ($M$ = 7.0, SE = 0.58); *ps* </span><span class="sc">\&lt;</span><span class="at"> .01".</span></span>
<span id="cb67-497"><a href="#cb67-497"></a></span>
<span id="cb67-498"><a href="#cb67-498"></a><span class="ss">-   </span>note that I find it acceptable to lump the p-values together in this manner when doing multiple comparisons, as we are doing here.</span>
<span id="cb67-499"><a href="#cb67-499"></a></span>
<span id="cb67-500"><a href="#cb67-500"></a>In both cases BE SURE TO PRODUCE A CAMERA READY FIGURE and REFER TO IT IN THE TEXT!!!</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>